<!--
title: Trova spartiti per chitarra, accordi, testi e tablature di Marco Masini. Discografia Marco Masini.
description: Trova tutti gli spartiti, accordi, testi e tablature di Marco Masini. Discografia Marco Masini.
keywords: Discografia, Marco Masini, spartiti, accordi, testi, tablature
template: tablature
-->
<h1>Trova spartiti per chitarra, accordi, testi e tablature di Marco Masini</h1><h2>Leggere gli spartiti per chitarra, gli accordi e le tablature:</h2>
<?php require("tabdescription.php"); ?>

<h2>Discografia Marco Masini:</h2>
<h2>Tozzi Masini (2006) </h2>
<b>1</b>. Come Si Fa - <a target="_blank" href="http://www.google.com/search?q=spartiti+Come+Si+Fa+Marco+Masini" title="Spartiti di Come Si Fa">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Come+Si+Fa+Marco+Masini" title="Accordi di Come Si Fa">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Come+Si+Fa+Marco+Masini" title="Testi di Come Si Fa">testi</a><br>
<b>2</b>. Anima Italiana - <a target="_blank" href="http://www.google.com/search?q=spartiti+Anima+Italiana+Marco+Masini" title="Spartiti di Anima Italiana">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Anima+Italiana+Marco+Masini" title="Accordi di Anima Italiana">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Anima+Italiana+Marco+Masini" title="Testi di Anima Italiana">testi</a><br>
<b>3</b>. Arrivederci Per Lei - <a target="_blank" href="http://www.google.com/search?q=spartiti+Arrivederci+Per+Lei+Marco+Masini" title="Spartiti di Arrivederci Per Lei">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Arrivederci+Per+Lei+Marco+Masini" title="Accordi di Arrivederci Per Lei">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Arrivederci+Per+Lei+Marco+Masini" title="Testi di Arrivederci Per Lei">testi</a><br>
<b>4</b>. T'innamorerai - <a target="_blank" href="http://www.google.com/search?q=spartiti+T%27innamorerai+Marco+Masini" title="Spartiti di T'innamorerai">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+T%27innamorerai+Marco+Masini" title="Accordi di T'innamorerai">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+T%27innamorerai+Marco+Masini" title="Testi di T'innamorerai">testi</a><br>
<b>5</b>. Perché Lo Fai - <a target="_blank" href="http://www.google.com/search?q=spartiti+Perch%E9+Lo+Fai+Marco+Masini" title="Spartiti di Perché Lo Fai">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Perch%E9+Lo+Fai+Marco+Masini" title="Accordi di Perché Lo Fai">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Perch%E9+Lo+Fai+Marco+Masini" title="Testi di Perché Lo Fai">testi</a><br>
<b>6</b>. Ti Vorrei - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ti+Vorrei+Marco+Masini" title="Spartiti di Ti Vorrei">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ti+Vorrei+Marco+Masini" title="Accordi di Ti Vorrei">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ti+Vorrei+Marco+Masini" title="Testi di Ti Vorrei">testi</a><br>
<b>7</b>. Tu - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tu+Marco+Masini" title="Spartiti di Tu">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tu+Marco+Masini" title="Accordi di Tu">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tu+Marco+Masini" title="Testi di Tu">testi</a><br>
<b>8</b>. Gli Altri Siamo Noi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Gli+Altri+Siamo+Noi+Marco+Masini" title="Spartiti di Gli Altri Siamo Noi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Gli+Altri+Siamo+Noi+Marco+Masini" title="Accordi di Gli Altri Siamo Noi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Gli+Altri+Siamo+Noi+Marco+Masini" title="Testi di Gli Altri Siamo Noi">testi</a><br>
<b>9</b>. Disperato - <a target="_blank" href="http://www.google.com/search?q=spartiti+Disperato+Marco+Masini" title="Spartiti di Disperato">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Disperato+Marco+Masini" title="Accordi di Disperato">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Disperato+Marco+Masini" title="Testi di Disperato">testi</a><br>
<b>10</b>. Cenerentola Innamorata - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cenerentola+Innamorata+Marco+Masini" title="Spartiti di Cenerentola Innamorata">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cenerentola+Innamorata+Marco+Masini" title="Accordi di Cenerentola Innamorata">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cenerentola+Innamorata+Marco+Masini" title="Testi di Cenerentola Innamorata">testi</a><br>
<b>11</b>. Ti Amo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ti+Amo+Marco+Masini" title="Spartiti di Ti Amo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ti+Amo+Marco+Masini" title="Accordi di Ti Amo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ti+Amo+Marco+Masini" title="Testi di Ti Amo">testi</a><br>
<b>12</b>. Gloria - <a target="_blank" href="http://www.google.com/search?q=spartiti+Gloria+Marco+Masini" title="Spartiti di Gloria">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Gloria+Marco+Masini" title="Accordi di Gloria">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Gloria+Marco+Masini" title="Testi di Gloria">testi</a><br>
<b>13</b>. Ci Vorrebbe Il Mare - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ci+Vorrebbe+Il+Mare+Marco+Masini" title="Spartiti di Ci Vorrebbe Il Mare">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ci+Vorrebbe+Il+Mare+Marco+Masini" title="Accordi di Ci Vorrebbe Il Mare">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ci+Vorrebbe+Il+Mare+Marco+Masini" title="Testi di Ci Vorrebbe Il Mare">testi</a><br>
<b>14</b>. L'uomo Volante - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%27uomo+Volante+Marco+Masini" title="Spartiti di L'uomo Volante">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%27uomo+Volante+Marco+Masini" title="Accordi di L'uomo Volante">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%27uomo+Volante+Marco+Masini" title="Testi di L'uomo Volante">testi</a><br>
<b>15</b>. Io Camminero' - <a target="_blank" href="http://www.google.com/search?q=spartiti+Io+Camminero%27+Marco+Masini" title="Spartiti di Io Camminero'">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Io+Camminero%27+Marco+Masini" title="Accordi di Io Camminero'">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Io+Camminero%27+Marco+Masini" title="Testi di Io Camminero'">testi</a><br>
<b>16</b>. Qualcosa Qualcuno - <a target="_blank" href="http://www.google.com/search?q=spartiti+Qualcosa+Qualcuno+Marco+Masini" title="Spartiti di Qualcosa Qualcuno">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Qualcosa+Qualcuno+Marco+Masini" title="Accordi di Qualcosa Qualcuno">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Qualcosa+Qualcuno+Marco+Masini" title="Testi di Qualcosa Qualcuno">testi</a><br>
<h2>Il Giardino Delle Api (2005) </h2>
<b>1</b>. Tutto Quello Che Ho Di Te - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tutto+Quello+Che+Ho+Di+Te+Marco+Masini" title="Spartiti di Tutto Quello Che Ho Di Te">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tutto+Quello+Che+Ho+Di+Te+Marco+Masini" title="Accordi di Tutto Quello Che Ho Di Te">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tutto+Quello+Che+Ho+Di+Te+Marco+Masini" title="Testi di Tutto Quello Che Ho Di Te">testi</a><br>
<b>2</b>. Libera - <a target="_blank" href="http://www.google.com/search?q=spartiti+Libera+Marco+Masini" title="Spartiti di Libera">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Libera+Marco+Masini" title="Accordi di Libera">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Libera+Marco+Masini" title="Testi di Libera">testi</a><br>
<b>3</b>. Rimani Così - <a target="_blank" href="http://www.google.com/search?q=spartiti+Rimani+Cos%EC+Marco+Masini" title="Spartiti di Rimani Così">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Rimani+Cos%EC+Marco+Masini" title="Accordi di Rimani Così">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Rimani+Cos%EC+Marco+Masini" title="Testi di Rimani Così">testi</a><br>
<b>4</b>. Nel Mondo Dei Sogni (Con Jessica Morlacchi) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Nel+Mondo+Dei+Sogni+%28Con+Jessica+Morlacchi%29+Marco+Masini" title="Spartiti di Nel Mondo Dei Sogni (Con Jessica Morlacchi)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Nel+Mondo+Dei+Sogni+%28Con+Jessica+Morlacchi%29+Marco+Masini" title="Accordi di Nel Mondo Dei Sogni (Con Jessica Morlacchi)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Nel+Mondo+Dei+Sogni+%28Con+Jessica+Morlacchi%29+Marco+Masini" title="Testi di Nel Mondo Dei Sogni (Con Jessica Morlacchi)">testi</a><br>
<b>5</b>. La Mia Preghiera - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Mia+Preghiera+Marco+Masini" title="Spartiti di La Mia Preghiera">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Mia+Preghiera+Marco+Masini" title="Accordi di La Mia Preghiera">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Mia+Preghiera+Marco+Masini" title="Testi di La Mia Preghiera">testi</a><br>
<b>6</b>. Briciole - <a target="_blank" href="http://www.google.com/search?q=spartiti+Briciole+Marco+Masini" title="Spartiti di Briciole">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Briciole+Marco+Masini" title="Accordi di Briciole">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Briciole+Marco+Masini" title="Testi di Briciole">testi</a><br>
<b>7</b>. Il Nostro Ritorno - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Nostro+Ritorno+Marco+Masini" title="Spartiti di Il Nostro Ritorno">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Nostro+Ritorno+Marco+Masini" title="Accordi di Il Nostro Ritorno">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Nostro+Ritorno+Marco+Masini" title="Testi di Il Nostro Ritorno">testi</a><br>
<b>8</b>. Gli Occhi Dell'arno - <a target="_blank" href="http://www.google.com/search?q=spartiti+Gli+Occhi+Dell%27arno+Marco+Masini" title="Spartiti di Gli Occhi Dell'arno">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Gli+Occhi+Dell%27arno+Marco+Masini" title="Accordi di Gli Occhi Dell'arno">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Gli+Occhi+Dell%27arno+Marco+Masini" title="Testi di Gli Occhi Dell'arno">testi</a><br>
<b>9</b>. Brava - <a target="_blank" href="http://www.google.com/search?q=spartiti+Brava+Marco+Masini" title="Spartiti di Brava">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Brava+Marco+Masini" title="Accordi di Brava">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Brava+Marco+Masini" title="Testi di Brava">testi</a><br>
<b>10</b>. Maledetta Amica Mia - <a target="_blank" href="http://www.google.com/search?q=spartiti+Maledetta+Amica+Mia+Marco+Masini" title="Spartiti di Maledetta Amica Mia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Maledetta+Amica+Mia+Marco+Masini" title="Accordi di Maledetta Amica Mia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Maledetta+Amica+Mia+Marco+Masini" title="Testi di Maledetta Amica Mia">testi</a><br>
<b>11</b>. Nel Mondo Dei Sogni - <a target="_blank" href="http://www.google.com/search?q=spartiti+Nel+Mondo+Dei+Sogni+Marco+Masini" title="Spartiti di Nel Mondo Dei Sogni">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Nel+Mondo+Dei+Sogni+Marco+Masini" title="Accordi di Nel Mondo Dei Sogni">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Nel+Mondo+Dei+Sogni+Marco+Masini" title="Testi di Nel Mondo Dei Sogni">testi</a><br>
<b>12</b>. Il Giardino Delle Api - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Giardino+Delle+Api+Marco+Masini" title="Spartiti di Il Giardino Delle Api">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Giardino+Delle+Api+Marco+Masini" title="Accordi di Il Giardino Delle Api">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Giardino+Delle+Api+Marco+Masini" title="Testi di Il Giardino Delle Api">testi</a><br>
<h2>Masini (2004) </h2>
<b>1</b>. L'Uomo Volante - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%27Uomo+Volante+Marco+Masini" title="Spartiti di L'Uomo Volante">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%27Uomo+Volante+Marco+Masini" title="Accordi di L'Uomo Volante">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%27Uomo+Volante+Marco+Masini" title="Testi di L'Uomo Volante">testi</a><br>
<b>2</b>. E Ti Amo - <a target="_blank" href="http://www.google.com/search?q=spartiti+E+Ti+Amo+Marco+Masini" title="Spartiti di E Ti Amo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+E+Ti+Amo+Marco+Masini" title="Accordi di E Ti Amo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+E+Ti+Amo+Marco+Masini" title="Testi di E Ti Amo">testi</a><br>
<b>3</b>. Generation - <a target="_blank" href="http://www.google.com/search?q=spartiti+Generation+Marco+Masini" title="Spartiti di Generation">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Generation+Marco+Masini" title="Accordi di Generation">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Generation+Marco+Masini" title="Testi di Generation">testi</a><br>
<b>4</b>. Io Non Ti Sposerò - <a target="_blank" href="http://www.google.com/search?q=spartiti+Io+Non+Ti+Sposer%F2+Marco+Masini" title="Spartiti di Io Non Ti Sposerò">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Io+Non+Ti+Sposer%F2+Marco+Masini" title="Accordi di Io Non Ti Sposerò">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Io+Non+Ti+Sposer%F2+Marco+Masini" title="Testi di Io Non Ti Sposerò">testi</a><br>
<b>5</b>. Benvenuta - <a target="_blank" href="http://www.google.com/search?q=spartiti+Benvenuta+Marco+Masini" title="Spartiti di Benvenuta">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Benvenuta+Marco+Masini" title="Accordi di Benvenuta">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Benvenuta+Marco+Masini" title="Testi di Benvenuta">testi</a><br>
<b>6</b>. Disperato - <a target="_blank" href="http://www.google.com/search?q=spartiti+Disperato+Marco+Masini" title="Spartiti di Disperato">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Disperato+Marco+Masini" title="Accordi di Disperato">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Disperato+Marco+Masini" title="Testi di Disperato">testi</a><br>
<b>7</b>. Le Ragazze Serie - <a target="_blank" href="http://www.google.com/search?q=spartiti+Le+Ragazze+Serie+Marco+Masini" title="Spartiti di Le Ragazze Serie">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Le+Ragazze+Serie+Marco+Masini" title="Accordi di Le Ragazze Serie">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Le+Ragazze+Serie+Marco+Masini" title="Testi di Le Ragazze Serie">testi</a><br>
<b>8</b>. Cenerentola Innamorata - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cenerentola+Innamorata+Marco+Masini" title="Spartiti di Cenerentola Innamorata">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cenerentola+Innamorata+Marco+Masini" title="Accordi di Cenerentola Innamorata">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cenerentola+Innamorata+Marco+Masini" title="Testi di Cenerentola Innamorata">testi</a><br>
<b>9</b>. Ti Vorrei - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ti+Vorrei+Marco+Masini" title="Spartiti di Ti Vorrei">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ti+Vorrei+Marco+Masini" title="Accordi di Ti Vorrei">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ti+Vorrei+Marco+Masini" title="Testi di Ti Vorrei">testi</a><br>
<b>10</b>. T'Innamorerai - <a target="_blank" href="http://www.google.com/search?q=spartiti+T%27Innamorerai+Marco+Masini" title="Spartiti di T'Innamorerai">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+T%27Innamorerai+Marco+Masini" title="Accordi di T'Innamorerai">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+T%27Innamorerai+Marco+Masini" title="Testi di T'Innamorerai">testi</a><br>
<b>11</b>. Caro Babbo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Caro+Babbo+Marco+Masini" title="Spartiti di Caro Babbo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Caro+Babbo+Marco+Masini" title="Accordi di Caro Babbo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Caro+Babbo+Marco+Masini" title="Testi di Caro Babbo">testi</a><br>
<b>12</b>. Dal Buio - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dal+Buio+Marco+Masini" title="Spartiti di Dal Buio">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dal+Buio+Marco+Masini" title="Accordi di Dal Buio">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dal+Buio+Marco+Masini" title="Testi di Dal Buio">testi</a><br>
<b>13</b>. Dentro Di Te - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dentro+Di+Te+Marco+Masini" title="Spartiti di Dentro Di Te">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dentro+Di+Te+Marco+Masini" title="Accordi di Dentro Di Te">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dentro+Di+Te+Marco+Masini" title="Testi di Dentro Di Te">testi</a><br>
<b>14</b>. Ci Vorrebbe Il Mare - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ci+Vorrebbe+Il+Mare+Marco+Masini" title="Spartiti di Ci Vorrebbe Il Mare">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ci+Vorrebbe+Il+Mare+Marco+Masini" title="Accordi di Ci Vorrebbe Il Mare">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ci+Vorrebbe+Il+Mare+Marco+Masini" title="Testi di Ci Vorrebbe Il Mare">testi</a><br>
<h2>Il Mio Cammino (2003) </h2>
<b>1</b>. Generation - <a target="_blank" href="http://www.google.com/search?q=spartiti+Generation+Marco+Masini" title="Spartiti di Generation">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Generation+Marco+Masini" title="Accordi di Generation">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Generation+Marco+Masini" title="Testi di Generation">testi</a><br>
<b>2</b>. Io Non Ti Sposerò - <a target="_blank" href="http://www.google.com/search?q=spartiti+Io+Non+Ti+Sposer%F2+Marco+Masini" title="Spartiti di Io Non Ti Sposerò">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Io+Non+Ti+Sposer%F2+Marco+Masini" title="Accordi di Io Non Ti Sposerò">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Io+Non+Ti+Sposer%F2+Marco+Masini" title="Testi di Io Non Ti Sposerò">testi</a><br>
<b>3</b>. Benvenuta - <a target="_blank" href="http://www.google.com/search?q=spartiti+Benvenuta+Marco+Masini" title="Spartiti di Benvenuta">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Benvenuta+Marco+Masini" title="Accordi di Benvenuta">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Benvenuta+Marco+Masini" title="Testi di Benvenuta">testi</a><br>
<b>4</b>. Disperato - <a target="_blank" href="http://www.google.com/search?q=spartiti+Disperato+Marco+Masini" title="Spartiti di Disperato">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Disperato+Marco+Masini" title="Accordi di Disperato">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Disperato+Marco+Masini" title="Testi di Disperato">testi</a><br>
<b>5</b>. Le Ragazze Serie - <a target="_blank" href="http://www.google.com/search?q=spartiti+Le+Ragazze+Serie+Marco+Masini" title="Spartiti di Le Ragazze Serie">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Le+Ragazze+Serie+Marco+Masini" title="Accordi di Le Ragazze Serie">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Le+Ragazze+Serie+Marco+Masini" title="Testi di Le Ragazze Serie">testi</a><br>
<b>6</b>. Cenerentola Innamorata - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cenerentola+Innamorata+Marco+Masini" title="Spartiti di Cenerentola Innamorata">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cenerentola+Innamorata+Marco+Masini" title="Accordi di Cenerentola Innamorata">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cenerentola+Innamorata+Marco+Masini" title="Testi di Cenerentola Innamorata">testi</a><br>
<b>7</b>. Ti Vorrei - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ti+Vorrei+Marco+Masini" title="Spartiti di Ti Vorrei">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ti+Vorrei+Marco+Masini" title="Accordi di Ti Vorrei">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ti+Vorrei+Marco+Masini" title="Testi di Ti Vorrei">testi</a><br>
<b>8</b>. T'Innamorerai - <a target="_blank" href="http://www.google.com/search?q=spartiti+T%27Innamorerai+Marco+Masini" title="Spartiti di T'Innamorerai">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+T%27Innamorerai+Marco+Masini" title="Accordi di T'Innamorerai">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+T%27Innamorerai+Marco+Masini" title="Testi di T'Innamorerai">testi</a><br>
<b>9</b>. Caro Babbo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Caro+Babbo+Marco+Masini" title="Spartiti di Caro Babbo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Caro+Babbo+Marco+Masini" title="Accordi di Caro Babbo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Caro+Babbo+Marco+Masini" title="Testi di Caro Babbo">testi</a><br>
<b>10</b>. Dal Buio - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dal+Buio+Marco+Masini" title="Spartiti di Dal Buio">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dal+Buio+Marco+Masini" title="Accordi di Dal Buio">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dal+Buio+Marco+Masini" title="Testi di Dal Buio">testi</a><br>
<b>11</b>. Dentro Di Te Fuori Dal Mondo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dentro+Di+Te+Fuori+Dal+Mondo+Marco+Masini" title="Spartiti di Dentro Di Te Fuori Dal Mondo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dentro+Di+Te+Fuori+Dal+Mondo+Marco+Masini" title="Accordi di Dentro Di Te Fuori Dal Mondo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dentro+Di+Te+Fuori+Dal+Mondo+Marco+Masini" title="Testi di Dentro Di Te Fuori Dal Mondo">testi</a><br>
<b>12</b>. Ci Vorrebbe Il Mare - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ci+Vorrebbe+Il+Mare+Marco+Masini" title="Spartiti di Ci Vorrebbe Il Mare">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ci+Vorrebbe+Il+Mare+Marco+Masini" title="Accordi di Ci Vorrebbe Il Mare">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ci+Vorrebbe+Il+Mare+Marco+Masini" title="Testi di Ci Vorrebbe Il Mare">testi</a><br>
<h2>Uscita Di Sicurezza (2001) </h2>
<b>1</b>. La Danza Della Ragione - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Danza+Della+Ragione+Marco+Masini" title="Spartiti di La Danza Della Ragione">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Danza+Della+Ragione+Marco+Masini" title="Accordi di La Danza Della Ragione">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Danza+Della+Ragione+Marco+Masini" title="Testi di La Danza Della Ragione">testi</a><br>
<b>2</b>. Errori - <a target="_blank" href="http://www.google.com/search?q=spartiti+Errori+Marco+Masini" title="Spartiti di Errori">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Errori+Marco+Masini" title="Accordi di Errori">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Errori+Marco+Masini" title="Testi di Errori">testi</a><br>
<b>3</b>. Lasciaminonmilasciare - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lasciaminonmilasciare+Marco+Masini" title="Spartiti di Lasciaminonmilasciare">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lasciaminonmilasciare+Marco+Masini" title="Accordi di Lasciaminonmilasciare">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lasciaminonmilasciare+Marco+Masini" title="Testi di Lasciaminonmilasciare">testi</a><br>
<b>4</b>. Il Bellissimo Mestiere (Sono Incazzato Con L'Amore) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Bellissimo+Mestiere+%28Sono+Incazzato+Con+L%27Amore%29+Marco+Masini" title="Spartiti di Il Bellissimo Mestiere (Sono Incazzato Con L'Amore)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Bellissimo+Mestiere+%28Sono+Incazzato+Con+L%27Amore%29+Marco+Masini" title="Accordi di Il Bellissimo Mestiere (Sono Incazzato Con L'Amore)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Bellissimo+Mestiere+%28Sono+Incazzato+Con+L%27Amore%29+Marco+Masini" title="Testi di Il Bellissimo Mestiere (Sono Incazzato Con L'Amore)">testi</a><br>
<b>5</b>. Vai Male A Scuola - <a target="_blank" href="http://www.google.com/search?q=spartiti+Vai+Male+A+Scuola+Marco+Masini" title="Spartiti di Vai Male A Scuola">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Vai+Male+A+Scuola+Marco+Masini" title="Accordi di Vai Male A Scuola">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Vai+Male+A+Scuola+Marco+Masini" title="Testi di Vai Male A Scuola">testi</a><br>
<b>6</b>. E Chi Se Ne Frega (Nothing Else Matters) - <a target="_blank" href="http://www.google.com/search?q=spartiti+E+Chi+Se+Ne+Frega+%28Nothing+Else+Matters%29+Marco+Masini" title="Spartiti di E Chi Se Ne Frega (Nothing Else Matters)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+E+Chi+Se+Ne+Frega+%28Nothing+Else+Matters%29+Marco+Masini" title="Accordi di E Chi Se Ne Frega (Nothing Else Matters)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+E+Chi+Se+Ne+Frega+%28Nothing+Else+Matters%29+Marco+Masini" title="Testi di E Chi Se Ne Frega (Nothing Else Matters)">testi</a><br>
<b>7</b>. La Clessidra - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Clessidra+Marco+Masini" title="Spartiti di La Clessidra">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Clessidra+Marco+Masini" title="Accordi di La Clessidra">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Clessidra+Marco+Masini" title="Testi di La Clessidra">testi</a><br>
<b>8</b>. Trappole - <a target="_blank" href="http://www.google.com/search?q=spartiti+Trappole+Marco+Masini" title="Spartiti di Trappole">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Trappole+Marco+Masini" title="Accordi di Trappole">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Trappole+Marco+Masini" title="Testi di Trappole">testi</a><br>
<b>9</b>. Vivere Liberamente - <a target="_blank" href="http://www.google.com/search?q=spartiti+Vivere+Liberamente+Marco+Masini" title="Spartiti di Vivere Liberamente">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Vivere+Liberamente+Marco+Masini" title="Accordi di Vivere Liberamente">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Vivere+Liberamente+Marco+Masini" title="Testi di Vivere Liberamente">testi</a><br>
<b>10</b>. Figlio Della Polvere - <a target="_blank" href="http://www.google.com/search?q=spartiti+Figlio+Della+Polvere+Marco+Masini" title="Spartiti di Figlio Della Polvere">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Figlio+Della+Polvere+Marco+Masini" title="Accordi di Figlio Della Polvere">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Figlio+Della+Polvere+Marco+Masini" title="Testi di Figlio Della Polvere">testi</a><br>
<b>11</b>. Ci Vediamo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ci+Vediamo+Marco+Masini" title="Spartiti di Ci Vediamo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ci+Vediamo+Marco+Masini" title="Accordi di Ci Vediamo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ci+Vediamo+Marco+Masini" title="Testi di Ci Vediamo">testi</a><br>
<b>12</b>. Sant'Elena - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sant%27Elena+Marco+Masini" title="Spartiti di Sant'Elena">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sant%27Elena+Marco+Masini" title="Accordi di Sant'Elena">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sant%27Elena+Marco+Masini" title="Testi di Sant'Elena">testi</a><br>
<b>13</b>. L'Ultima Birra - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%27Ultima+Birra+Marco+Masini" title="Spartiti di L'Ultima Birra">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%27Ultima+Birra+Marco+Masini" title="Accordi di L'Ultima Birra">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%27Ultima+Birra+Marco+Masini" title="Testi di L'Ultima Birra">testi</a><br>
<b>14</b>. Il Gusto di Esistere - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Gusto+di+Esistere+Marco+Masini" title="Spartiti di Il Gusto di Esistere">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Gusto+di+Esistere+Marco+Masini" title="Accordi di Il Gusto di Esistere">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Gusto+di+Esistere+Marco+Masini" title="Testi di Il Gusto di Esistere">testi</a><br>
<h2>Raccontami Di Te (2000) </h2>
<b>1</b>. Raccontami Di Te - <a target="_blank" href="http://www.google.com/search?q=spartiti+Raccontami+Di+Te+Marco+Masini" title="Spartiti di Raccontami Di Te">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Raccontami+Di+Te+Marco+Masini" title="Accordi di Raccontami Di Te">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Raccontami+Di+Te+Marco+Masini" title="Testi di Raccontami Di Te">testi</a><br>
<b>2</b>. Protagonista - <a target="_blank" href="http://www.google.com/search?q=spartiti+Protagonista+Marco+Masini" title="Spartiti di Protagonista">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Protagonista+Marco+Masini" title="Accordi di Protagonista">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Protagonista+Marco+Masini" title="Testi di Protagonista">testi</a><br>
<b>3</b>. Parlo Di Noi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Parlo+Di+Noi+Marco+Masini" title="Spartiti di Parlo Di Noi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Parlo+Di+Noi+Marco+Masini" title="Accordi di Parlo Di Noi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Parlo+Di+Noi+Marco+Masini" title="Testi di Parlo Di Noi">testi</a><br>
<b>4</b>. Abbracciami - <a target="_blank" href="http://www.google.com/search?q=spartiti+Abbracciami+Marco+Masini" title="Spartiti di Abbracciami">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Abbracciami+Marco+Masini" title="Accordi di Abbracciami">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Abbracciami+Marco+Masini" title="Testi di Abbracciami">testi</a><br>
<b>5</b>. C'è Qualcosa Di Più - <a target="_blank" href="http://www.google.com/search?q=spartiti+C%27%E8+Qualcosa+Di+Pi%F9+Marco+Masini" title="Spartiti di C'è Qualcosa Di Più">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+C%27%E8+Qualcosa+Di+Pi%F9+Marco+Masini" title="Accordi di C'è Qualcosa Di Più">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+C%27%E8+Qualcosa+Di+Pi%F9+Marco+Masini" title="Testi di C'è Qualcosa Di Più">testi</a><br>
<b>6</b>. A 200 All'Ora - <a target="_blank" href="http://www.google.com/search?q=spartiti+A+200+All%27Ora+Marco+Masini" title="Spartiti di A 200 All'Ora">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+A+200+All%27Ora+Marco+Masini" title="Accordi di A 200 All'Ora">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+A+200+All%27Ora+Marco+Masini" title="Testi di A 200 All'Ora">testi</a><br>
<b>7</b>. Ancora Vita E' - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ancora+Vita+E%27+Marco+Masini" title="Spartiti di Ancora Vita E'">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ancora+Vita+E%27+Marco+Masini" title="Accordi di Ancora Vita E'">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ancora+Vita+E%27+Marco+Masini" title="Testi di Ancora Vita E'">testi</a><br>
<b>8</b>. Il Giorno di Natale (Il Giorno Più Banale) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Giorno+di+Natale+%28Il+Giorno+Pi%F9+Banale%29+Marco+Masini" title="Spartiti di Il Giorno di Natale (Il Giorno Più Banale)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Giorno+di+Natale+%28Il+Giorno+Pi%F9+Banale%29+Marco+Masini" title="Accordi di Il Giorno di Natale (Il Giorno Più Banale)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Giorno+di+Natale+%28Il+Giorno+Pi%F9+Banale%29+Marco+Masini" title="Testi di Il Giorno di Natale (Il Giorno Più Banale)">testi</a><br>
<b>9</b>. Non Ti Fidare Di Me - <a target="_blank" href="http://www.google.com/search?q=spartiti+Non+Ti+Fidare+Di+Me+Marco+Masini" title="Spartiti di Non Ti Fidare Di Me">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Non+Ti+Fidare+Di+Me+Marco+Masini" title="Accordi di Non Ti Fidare Di Me">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Non+Ti+Fidare+Di+Me+Marco+Masini" title="Testi di Non Ti Fidare Di Me">testi</a><br>
<b>10</b>. Se Potessi Rinascere - <a target="_blank" href="http://www.google.com/search?q=spartiti+Se+Potessi+Rinascere+Marco+Masini" title="Spartiti di Se Potessi Rinascere">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Se+Potessi+Rinascere+Marco+Masini" title="Accordi di Se Potessi Rinascere">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Se+Potessi+Rinascere+Marco+Masini" title="Testi di Se Potessi Rinascere">testi</a><br>
<b>11</b>. 10 Anni - <a target="_blank" href="http://www.google.com/search?q=spartiti+10+Anni+Marco+Masini" title="Spartiti di 10 Anni">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+10+Anni+Marco+Masini" title="Accordi di 10 Anni">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+10+Anni+Marco+Masini" title="Testi di 10 Anni">testi</a><br>
<h2>Scimmie (1998) </h2>
<b>1</b>. Scimmie - <a target="_blank" href="http://www.google.com/search?q=spartiti+Scimmie+Marco+Masini" title="Spartiti di Scimmie">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Scimmie+Marco+Masini" title="Accordi di Scimmie">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Scimmie+Marco+Masini" title="Testi di Scimmie">testi</a><br>
<b>2</b>. Falso - <a target="_blank" href="http://www.google.com/search?q=spartiti+Falso+Marco+Masini" title="Spartiti di Falso">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Falso+Marco+Masini" title="Accordi di Falso">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Falso+Marco+Masini" title="Testi di Falso">testi</a><br>
<b>3</b>. Profondo Porpora - <a target="_blank" href="http://www.google.com/search?q=spartiti+Profondo+Porpora+Marco+Masini" title="Spartiti di Profondo Porpora">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Profondo+Porpora+Marco+Masini" title="Accordi di Profondo Porpora">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Profondo+Porpora+Marco+Masini" title="Testi di Profondo Porpora">testi</a><br>
<b>4</b>. Il Posto Delle Fragole - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Posto+Delle+Fragole+Marco+Masini" title="Spartiti di Il Posto Delle Fragole">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Posto+Delle+Fragole+Marco+Masini" title="Accordi di Il Posto Delle Fragole">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Posto+Delle+Fragole+Marco+Masini" title="Testi di Il Posto Delle Fragole">testi</a><br>
<b>5</b>. Lungomare - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lungomare+Marco+Masini" title="Spartiti di Lungomare">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lungomare+Marco+Masini" title="Accordi di Lungomare">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lungomare+Marco+Masini" title="Testi di Lungomare">testi</a><br>
<b>6</b>. Ali Di Cera - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ali+Di+Cera+Marco+Masini" title="Spartiti di Ali Di Cera">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ali+Di+Cera+Marco+Masini" title="Accordi di Ali Di Cera">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ali+Di+Cera+Marco+Masini" title="Testi di Ali Di Cera">testi</a><br>
<b>7</b>. Togliti La Voglia - <a target="_blank" href="http://www.google.com/search?q=spartiti+Togliti+La+Voglia+Marco+Masini" title="Spartiti di Togliti La Voglia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Togliti+La+Voglia+Marco+Masini" title="Accordi di Togliti La Voglia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Togliti+La+Voglia+Marco+Masini" title="Testi di Togliti La Voglia">testi</a><br>
<b>8</b>. Il Fiore - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Fiore+Marco+Masini" title="Spartiti di Il Fiore">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Fiore+Marco+Masini" title="Accordi di Il Fiore">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Fiore+Marco+Masini" title="Testi di Il Fiore">testi</a><br>
<b>9</b>. Fino A Tutta La Vita Che C'è - <a target="_blank" href="http://www.google.com/search?q=spartiti+Fino+A+Tutta+La+Vita+Che+C%27%E8+Marco+Masini" title="Spartiti di Fino A Tutta La Vita Che C'è">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Fino+A+Tutta+La+Vita+Che+C%27%E8+Marco+Masini" title="Accordi di Fino A Tutta La Vita Che C'è">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Fino+A+Tutta+La+Vita+Che+C%27%E8+Marco+Masini" title="Testi di Fino A Tutta La Vita Che C'è">testi</a><br>
<b>10</b>. Fuorigioco - <a target="_blank" href="http://www.google.com/search?q=spartiti+Fuorigioco+Marco+Masini" title="Spartiti di Fuorigioco">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Fuorigioco+Marco+Masini" title="Accordi di Fuorigioco">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Fuorigioco+Marco+Masini" title="Testi di Fuorigioco">testi</a><br>
<h2>Mi Amor Allí Estará (1996) </h2>
<b>1</b>. Mi Amor Allí Estará - <a target="_blank" href="http://www.google.com/search?q=spartiti+Mi+Amor+All%ED+Estar%E1+Marco+Masini" title="Spartiti di Mi Amor Allí Estará">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Mi+Amor+All%ED+Estar%E1+Marco+Masini" title="Accordi di Mi Amor Allí Estará">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Mi+Amor+All%ED+Estar%E1+Marco+Masini" title="Testi di Mi Amor Allí Estará">testi</a><br>
<b>2</b>. Desesperado - <a target="_blank" href="http://www.google.com/search?q=spartiti+Desesperado+Marco+Masini" title="Spartiti di Desesperado">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Desesperado+Marco+Masini" title="Accordi di Desesperado">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Desesperado+Marco+Masini" title="Testi di Desesperado">testi</a><br>
<b>3</b>. Porqué Lo Harás - <a target="_blank" href="http://www.google.com/search?q=spartiti+Porqu%E9+Lo+Har%E1s+Marco+Masini" title="Spartiti di Porqué Lo Harás">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Porqu%E9+Lo+Har%E1s+Marco+Masini" title="Accordi di Porqué Lo Harás">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Porqu%E9+Lo+Har%E1s+Marco+Masini" title="Testi di Porqué Lo Harás">testi</a><br>
<b>4</b>. Te Enamorarás - <a target="_blank" href="http://www.google.com/search?q=spartiti+Te+Enamorar%E1s+Marco+Masini" title="Spartiti di Te Enamorarás">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Te+Enamorar%E1s+Marco+Masini" title="Accordi di Te Enamorarás">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Te+Enamorar%E1s+Marco+Masini" title="Testi di Te Enamorarás">testi</a><br>
<b>5</b>. Bella Idiota - <a target="_blank" href="http://www.google.com/search?q=spartiti+Bella+Idiota+Marco+Masini" title="Spartiti di Bella Idiota">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Bella+Idiota+Marco+Masini" title="Accordi di Bella Idiota">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Bella+Idiota+Marco+Masini" title="Testi di Bella Idiota">testi</a><br>
<b>6</b>. Ve Con él - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ve+Con+%E9l+Marco+Masini" title="Spartiti di Ve Con él">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ve+Con+%E9l+Marco+Masini" title="Accordi di Ve Con él">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ve+Con+%E9l+Marco+Masini" title="Testi di Ve Con él">testi</a><br>
<b>7</b>. Cenicienta Desconsolada - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cenicienta+Desconsolada+Marco+Masini" title="Spartiti di Cenicienta Desconsolada">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cenicienta+Desconsolada+Marco+Masini" title="Accordi di Cenicienta Desconsolada">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cenicienta+Desconsolada+Marco+Masini" title="Testi di Cenicienta Desconsolada">testi</a><br>
<b>8</b>. Vaffanculo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Vaffanculo+Marco+Masini" title="Spartiti di Vaffanculo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Vaffanculo+Marco+Masini" title="Accordi di Vaffanculo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Vaffanculo+Marco+Masini" title="Testi di Vaffanculo">testi</a><br>
<b>9</b>. Princesa - <a target="_blank" href="http://www.google.com/search?q=spartiti+Princesa+Marco+Masini" title="Spartiti di Princesa">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Princesa+Marco+Masini" title="Accordi di Princesa">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Princesa+Marco+Masini" title="Testi di Princesa">testi</a><br>
<b>10</b>. Necesito El Mar - <a target="_blank" href="http://www.google.com/search?q=spartiti+Necesito+El+Mar+Marco+Masini" title="Spartiti di Necesito El Mar">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Necesito+El+Mar+Marco+Masini" title="Accordi di Necesito El Mar">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Necesito+El+Mar+Marco+Masini" title="Testi di Necesito El Mar">testi</a><br>
<b>11</b>. Te Querré - <a target="_blank" href="http://www.google.com/search?q=spartiti+Te+Querr%E9+Marco+Masini" title="Spartiti di Te Querré">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Te+Querr%E9+Marco+Masini" title="Accordi di Te Querré">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Te+Querr%E9+Marco+Masini" title="Testi di Te Querré">testi</a><br>
<b>12</b>. La Libertad - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Libertad+Marco+Masini" title="Spartiti di La Libertad">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Libertad+Marco+Masini" title="Accordi di La Libertad">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Libertad+Marco+Masini" title="Testi di La Libertad">testi</a><br>
<b>13</b>. Fuera De Aquí - <a target="_blank" href="http://www.google.com/search?q=spartiti+Fuera+De+Aqu%ED+Marco+Masini" title="Spartiti di Fuera De Aquí">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Fuera+De+Aqu%ED+Marco+Masini" title="Accordi di Fuera De Aquí">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Fuera+De+Aqu%ED+Marco+Masini" title="Testi di Fuera De Aquí">testi</a><br>
<b>14</b>. Ando Solo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ando+Solo+Marco+Masini" title="Spartiti di Ando Solo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ando+Solo+Marco+Masini" title="Accordi di Ando Solo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ando+Solo+Marco+Masini" title="Testi di Ando Solo">testi</a><br>
<h2>L'Amore Sia Con Te (1996) </h2>
<b>1</b>. L'Amore Sia Con Te - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%27Amore+Sia+Con+Te+Marco+Masini" title="Spartiti di L'Amore Sia Con Te">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%27Amore+Sia+Con+Te+Marco+Masini" title="Accordi di L'Amore Sia Con Te">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%27Amore+Sia+Con+Te+Marco+Masini" title="Testi di L'Amore Sia Con Te">testi</a><br>
<b>2</b>. Disperato - <a target="_blank" href="http://www.google.com/search?q=spartiti+Disperato+Marco+Masini" title="Spartiti di Disperato">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Disperato+Marco+Masini" title="Accordi di Disperato">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Disperato+Marco+Masini" title="Testi di Disperato">testi</a><br>
<b>3</b>. Perché Lo Fai - <a target="_blank" href="http://www.google.com/search?q=spartiti+Perch%E9+Lo+Fai+Marco+Masini" title="Spartiti di Perché Lo Fai">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Perch%E9+Lo+Fai+Marco+Masini" title="Accordi di Perché Lo Fai">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Perch%E9+Lo+Fai+Marco+Masini" title="Testi di Perché Lo Fai">testi</a><br>
<b>4</b>. T'Innamorerai - <a target="_blank" href="http://www.google.com/search?q=spartiti+T%27Innamorerai+Marco+Masini" title="Spartiti di T'Innamorerai">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+T%27Innamorerai+Marco+Masini" title="Accordi di T'Innamorerai">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+T%27Innamorerai+Marco+Masini" title="Testi di T'Innamorerai">testi</a><br>
<b>5</b>. Bella Stronza - <a target="_blank" href="http://www.google.com/search?q=spartiti+Bella+Stronza+Marco+Masini" title="Spartiti di Bella Stronza">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Bella+Stronza+Marco+Masini" title="Accordi di Bella Stronza">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Bella+Stronza+Marco+Masini" title="Testi di Bella Stronza">testi</a><br>
<b>6</b>. Vai Con Lui - <a target="_blank" href="http://www.google.com/search?q=spartiti+Vai+Con+Lui+Marco+Masini" title="Spartiti di Vai Con Lui">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Vai+Con+Lui+Marco+Masini" title="Accordi di Vai Con Lui">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Vai+Con+Lui+Marco+Masini" title="Testi di Vai Con Lui">testi</a><br>
<b>7</b>. Cenerentola Innamorata - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cenerentola+Innamorata+Marco+Masini" title="Spartiti di Cenerentola Innamorata">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cenerentola+Innamorata+Marco+Masini" title="Accordi di Cenerentola Innamorata">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cenerentola+Innamorata+Marco+Masini" title="Testi di Cenerentola Innamorata">testi</a><br>
<b>8</b>. Vaffanculo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Vaffanculo+Marco+Masini" title="Spartiti di Vaffanculo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Vaffanculo+Marco+Masini" title="Accordi di Vaffanculo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Vaffanculo+Marco+Masini" title="Testi di Vaffanculo">testi</a><br>
<b>9</b>. Principessa - <a target="_blank" href="http://www.google.com/search?q=spartiti+Principessa+Marco+Masini" title="Spartiti di Principessa">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Principessa+Marco+Masini" title="Accordi di Principessa">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Principessa+Marco+Masini" title="Testi di Principessa">testi</a><br>
<b>10</b>. Ci Vorrebbe Il Mare - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ci+Vorrebbe+Il+Mare+Marco+Masini" title="Spartiti di Ci Vorrebbe Il Mare">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ci+Vorrebbe+Il+Mare+Marco+Masini" title="Accordi di Ci Vorrebbe Il Mare">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ci+Vorrebbe+Il+Mare+Marco+Masini" title="Testi di Ci Vorrebbe Il Mare">testi</a><br>
<b>11</b>. Ti Vorrei - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ti+Vorrei+Marco+Masini" title="Spartiti di Ti Vorrei">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ti+Vorrei+Marco+Masini" title="Accordi di Ti Vorrei">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ti+Vorrei+Marco+Masini" title="Testi di Ti Vorrei">testi</a><br>
<b>12</b>. Caro Babbo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Caro+Babbo+Marco+Masini" title="Spartiti di Caro Babbo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Caro+Babbo+Marco+Masini" title="Accordi di Caro Babbo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Caro+Babbo+Marco+Masini" title="Testi di Caro Babbo">testi</a><br>
<b>13</b>. Le Ragazze Serie - <a target="_blank" href="http://www.google.com/search?q=spartiti+Le+Ragazze+Serie+Marco+Masini" title="Spartiti di Le Ragazze Serie">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Le+Ragazze+Serie+Marco+Masini" title="Accordi di Le Ragazze Serie">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Le+Ragazze+Serie+Marco+Masini" title="Testi di Le Ragazze Serie">testi</a><br>
<b>14</b>. Meglio Solo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Meglio+Solo+Marco+Masini" title="Spartiti di Meglio Solo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Meglio+Solo+Marco+Masini" title="Accordi di Meglio Solo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Meglio+Solo+Marco+Masini" title="Testi di Meglio Solo">testi</a><br>
<h2>El Cielo De Virgo (1995) </h2>
<b>1</b>. Bella Idiota - <a target="_blank" href="http://www.google.com/search?q=spartiti+Bella+Idiota+Marco+Masini" title="Spartiti di Bella Idiota">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Bella+Idiota+Marco+Masini" title="Accordi di Bella Idiota">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Bella+Idiota+Marco+Masini" title="Testi di Bella Idiota">testi</a><br>
<b>2</b>. El Cielo De Virgo - <a target="_blank" href="http://www.google.com/search?q=spartiti+El+Cielo+De+Virgo+Marco+Masini" title="Spartiti di El Cielo De Virgo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+El+Cielo+De+Virgo+Marco+Masini" title="Accordi di El Cielo De Virgo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+El+Cielo+De+Virgo+Marco+Masini" title="Testi di El Cielo De Virgo">testi</a><br>
<b>3</b>. Frankenstein - <a target="_blank" href="http://www.google.com/search?q=spartiti+Frankenstein+Marco+Masini" title="Spartiti di Frankenstein">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Frankenstein+Marco+Masini" title="Accordi di Frankenstein">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Frankenstein+Marco+Masini" title="Testi di Frankenstein">testi</a><br>
<b>4</b>. El Morbo De Beautiful - <a target="_blank" href="http://www.google.com/search?q=spartiti+El+Morbo+De+Beautiful+Marco+Masini" title="Spartiti di El Morbo De Beautiful">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+El+Morbo+De+Beautiful+Marco+Masini" title="Accordi di El Morbo De Beautiful">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+El+Morbo+De+Beautiful+Marco+Masini" title="Testi di El Morbo De Beautiful">testi</a><br>
<b>5</b>. Cachorro - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cachorro+Marco+Masini" title="Spartiti di Cachorro">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cachorro+Marco+Masini" title="Accordi di Cachorro">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cachorro+Marco+Masini" title="Testi di Cachorro">testi</a><br>
<b>6</b>. Princesa - <a target="_blank" href="http://www.google.com/search?q=spartiti+Princesa+Marco+Masini" title="Spartiti di Princesa">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Princesa+Marco+Masini" title="Accordi di Princesa">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Princesa+Marco+Masini" title="Testi di Princesa">testi</a><br>
<b>7</b>. Quererse Mal - <a target="_blank" href="http://www.google.com/search?q=spartiti+Quererse+Mal+Marco+Masini" title="Spartiti di Quererse Mal">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Quererse+Mal+Marco+Masini" title="Accordi di Quererse Mal">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Quererse+Mal+Marco+Masini" title="Testi di Quererse Mal">testi</a><br>
<b>8</b>. Hazte Duro - <a target="_blank" href="http://www.google.com/search?q=spartiti+Hazte+Duro+Marco+Masini" title="Spartiti di Hazte Duro">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Hazte+Duro+Marco+Masini" title="Accordi di Hazte Duro">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Hazte+Duro+Marco+Masini" title="Testi di Hazte Duro">testi</a><br>
<b>9</b>. Cero - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cero+Marco+Masini" title="Spartiti di Cero">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cero+Marco+Masini" title="Accordi di Cero">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cero+Marco+Masini" title="Testi di Cero">testi</a><br>
<b>10</b>. Tiempo Perdido - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tiempo+Perdido+Marco+Masini" title="Spartiti di Tiempo Perdido">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tiempo+Perdido+Marco+Masini" title="Accordi di Tiempo Perdido">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tiempo+Perdido+Marco+Masini" title="Testi di Tiempo Perdido">testi</a><br>
<h2>Il Cielo Della Vergine (1995) </h2>
<b>1</b>. Bella Stronza - <a target="_blank" href="http://www.google.com/search?q=spartiti+Bella+Stronza+Marco+Masini" title="Spartiti di Bella Stronza">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Bella+Stronza+Marco+Masini" title="Accordi di Bella Stronza">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Bella+Stronza+Marco+Masini" title="Testi di Bella Stronza">testi</a><br>
<b>2</b>. Il Cielo Della Vergine - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Cielo+Della+Vergine+Marco+Masini" title="Spartiti di Il Cielo Della Vergine">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Cielo+Della+Vergine+Marco+Masini" title="Accordi di Il Cielo Della Vergine">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Cielo+Della+Vergine+Marco+Masini" title="Testi di Il Cielo Della Vergine">testi</a><br>
<b>3</b>. Frankenstein - <a target="_blank" href="http://www.google.com/search?q=spartiti+Frankenstein+Marco+Masini" title="Spartiti di Frankenstein">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Frankenstein+Marco+Masini" title="Accordi di Frankenstein">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Frankenstein+Marco+Masini" title="Testi di Frankenstein">testi</a><br>
<b>4</b>. Il Morbo di Beautiful - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Morbo+di+Beautiful+Marco+Masini" title="Spartiti di Il Morbo di Beautiful">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Morbo+di+Beautiful+Marco+Masini" title="Accordi di Il Morbo di Beautiful">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Morbo+di+Beautiful+Marco+Masini" title="Testi di Il Morbo di Beautiful">testi</a><br>
<b>5</b>. Cuccioli - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cuccioli+Marco+Masini" title="Spartiti di Cuccioli">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cuccioli+Marco+Masini" title="Accordi di Cuccioli">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cuccioli+Marco+Masini" title="Testi di Cuccioli">testi</a><br>
<b>6</b>. Principessa - <a target="_blank" href="http://www.google.com/search?q=spartiti+Principessa+Marco+Masini" title="Spartiti di Principessa">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Principessa+Marco+Masini" title="Accordi di Principessa">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Principessa+Marco+Masini" title="Testi di Principessa">testi</a><br>
<b>7</b>. Volersi Male - <a target="_blank" href="http://www.google.com/search?q=spartiti+Volersi+Male+Marco+Masini" title="Spartiti di Volersi Male">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Volersi+Male+Marco+Masini" title="Accordi di Volersi Male">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Volersi+Male+Marco+Masini" title="Testi di Volersi Male">testi</a><br>
<b>8</b>. Fatti Furbo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Fatti+Furbo+Marco+Masini" title="Spartiti di Fatti Furbo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Fatti+Furbo+Marco+Masini" title="Accordi di Fatti Furbo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Fatti+Furbo+Marco+Masini" title="Testi di Fatti Furbo">testi</a><br>
<b>9</b>. Zero - <a target="_blank" href="http://www.google.com/search?q=spartiti+Zero+Marco+Masini" title="Spartiti di Zero">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Zero+Marco+Masini" title="Accordi di Zero">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Zero+Marco+Masini" title="Testi di Zero">testi</a><br>
<b>10</b>. Tempo Buttato Via - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tempo+Buttato+Via+Marco+Masini" title="Spartiti di Tempo Buttato Via">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tempo+Buttato+Via+Marco+Masini" title="Accordi di Tempo Buttato Via">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tempo+Buttato+Via+Marco+Masini" title="Testi di Tempo Buttato Via">testi</a><br>
<h2>Te Enamorarás (1993) </h2>
<b>1</b>. Vaffanculo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Vaffanculo+Marco+Masini" title="Spartiti di Vaffanculo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Vaffanculo+Marco+Masini" title="Accordi di Vaffanculo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Vaffanculo+Marco+Masini" title="Testi di Vaffanculo">testi</a><br>
<b>2</b>. Te Enamorarás - <a target="_blank" href="http://www.google.com/search?q=spartiti+Te+Enamorar%E1s+Marco+Masini" title="Spartiti di Te Enamorarás">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Te+Enamorar%E1s+Marco+Masini" title="Accordi di Te Enamorarás">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Te+Enamorar%E1s+Marco+Masini" title="Testi di Te Enamorarás">testi</a><br>
<b>3</b>. Cantan Los Niños - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cantan+Los+Ni%F1os+Marco+Masini" title="Spartiti di Cantan Los Niños">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cantan+Los+Ni%F1os+Marco+Masini" title="Accordi di Cantan Los Niños">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cantan+Los+Ni%F1os+Marco+Masini" title="Testi di Cantan Los Niños">testi</a><br>
<b>4</b>. Miedo De Amarse - <a target="_blank" href="http://www.google.com/search?q=spartiti+Miedo+De+Amarse+Marco+Masini" title="Spartiti di Miedo De Amarse">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Miedo+De+Amarse+Marco+Masini" title="Accordi di Miedo De Amarse">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Miedo+De+Amarse+Marco+Masini" title="Testi di Miedo De Amarse">testi</a><br>
<b>5</b>. Dios Se Fue - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dios+Se+Fue+Marco+Masini" title="Spartiti di Dios Se Fue">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dios+Se+Fue+Marco+Masini" title="Accordi di Dios Se Fue">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dios+Se+Fue+Marco+Masini" title="Testi di Dios Se Fue">testi</a><br>
<b>6</b>. La Libertad - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Libertad+Marco+Masini" title="Spartiti di La Libertad">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Libertad+Marco+Masini" title="Accordi di La Libertad">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Libertad+Marco+Masini" title="Testi di La Libertad">testi</a><br>
<b>7</b>. Quiero Volar - <a target="_blank" href="http://www.google.com/search?q=spartiti+Quiero+Volar+Marco+Masini" title="Spartiti di Quiero Volar">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Quiero+Volar+Marco+Masini" title="Accordi di Quiero Volar">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Quiero+Volar+Marco+Masini" title="Testi di Quiero Volar">testi</a><br>
<b>8</b>. Ana, Vivamos - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ana%2C+Vivamos+Marco+Masini" title="Spartiti di Ana, Vivamos">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ana%2C+Vivamos+Marco+Masini" title="Accordi di Ana, Vivamos">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ana%2C+Vivamos+Marco+Masini" title="Testi di Ana, Vivamos">testi</a><br>
<b>9</b>. Pequeño Gran Chopin - <a target="_blank" href="http://www.google.com/search?q=spartiti+Peque%F1o+Gran+Chopin+Marco+Masini" title="Spartiti di Pequeño Gran Chopin">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Peque%F1o+Gran+Chopin+Marco+Masini" title="Accordi di Pequeño Gran Chopin">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Peque%F1o+Gran+Chopin+Marco+Masini" title="Testi di Pequeño Gran Chopin">testi</a><br>
<h2>T'Innamorerai (1993) </h2>
<b>1</b>. Vaffanculo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Vaffanculo+Marco+Masini" title="Spartiti di Vaffanculo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Vaffanculo+Marco+Masini" title="Accordi di Vaffanculo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Vaffanculo+Marco+Masini" title="Testi di Vaffanculo">testi</a><br>
<b>2</b>. T'Innamorerai - <a target="_blank" href="http://www.google.com/search?q=spartiti+T%27Innamorerai+Marco+Masini" title="Spartiti di T'Innamorerai">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+T%27Innamorerai+Marco+Masini" title="Accordi di T'Innamorerai">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+T%27Innamorerai+Marco+Masini" title="Testi di T'Innamorerai">testi</a><br>
<b>3</b>. Cantano I Ragazzi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cantano+I+Ragazzi+Marco+Masini" title="Spartiti di Cantano I Ragazzi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cantano+I+Ragazzi+Marco+Masini" title="Accordi di Cantano I Ragazzi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cantano+I+Ragazzi+Marco+Masini" title="Testi di Cantano I Ragazzi">testi</a><br>
<b>4</b>. Paura D'Amare - <a target="_blank" href="http://www.google.com/search?q=spartiti+Paura+D%27Amare+Marco+Masini" title="Spartiti di Paura D'Amare">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Paura+D%27Amare+Marco+Masini" title="Accordi di Paura D'Amare">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Paura+D%27Amare+Marco+Masini" title="Testi di Paura D'Amare">testi</a><br>
<b>5</b>. Dio Non C'è - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dio+Non+C%27%E8+Marco+Masini" title="Spartiti di Dio Non C'è">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dio+Non+C%27%E8+Marco+Masini" title="Accordi di Dio Non C'è">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dio+Non+C%27%E8+Marco+Masini" title="Testi di Dio Non C'è">testi</a><br>
<b>6</b>. La Libertà - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Libert%E0+Marco+Masini" title="Spartiti di La Libertà">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Libert%E0+Marco+Masini" title="Accordi di La Libertà">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Libert%E0+Marco+Masini" title="Testi di La Libertà">testi</a><br>
<b>7</b>. Voglio Volare - <a target="_blank" href="http://www.google.com/search?q=spartiti+Voglio+Volare+Marco+Masini" title="Spartiti di Voglio Volare">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Voglio+Volare+Marco+Masini" title="Accordi di Voglio Volare">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Voglio+Volare+Marco+Masini" title="Testi di Voglio Volare">testi</a><br>
<b>8</b>. Anna Viviamo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Anna+Viviamo+Marco+Masini" title="Spartiti di Anna Viviamo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Anna+Viviamo+Marco+Masini" title="Accordi di Anna Viviamo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Anna+Viviamo+Marco+Masini" title="Testi di Anna Viviamo">testi</a><br>
<b>9</b>. Un Piccolo Chopin - <a target="_blank" href="http://www.google.com/search?q=spartiti+Un+Piccolo+Chopin+Marco+Masini" title="Spartiti di Un Piccolo Chopin">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Un+Piccolo+Chopin+Marco+Masini" title="Accordi di Un Piccolo Chopin">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Un+Piccolo+Chopin+Marco+Masini" title="Testi di Un Piccolo Chopin">testi</a><br>
<h2>Marco Masini (Español) (1992) </h2>
<b>1</b>. Dentro De Ti, Fuera Del Mundo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dentro+De+Ti%2C+Fuera+Del+Mundo+Marco+Masini" title="Spartiti di Dentro De Ti, Fuera Del Mundo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dentro+De+Ti%2C+Fuera+Del+Mundo+Marco+Masini" title="Accordi di Dentro De Ti, Fuera Del Mundo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dentro+De+Ti%2C+Fuera+Del+Mundo+Marco+Masini" title="Testi di Dentro De Ti, Fuera Del Mundo">testi</a><br>
<b>2</b>. Ve Con él - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ve+Con+%E9l+Marco+Masini" title="Spartiti di Ve Con él">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ve+Con+%E9l+Marco+Masini" title="Accordi di Ve Con él">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ve+Con+%E9l+Marco+Masini" title="Testi di Ve Con él">testi</a><br>
<b>3</b>. Desesperado - <a target="_blank" href="http://www.google.com/search?q=spartiti+Desesperado+Marco+Masini" title="Spartiti di Desesperado">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Desesperado+Marco+Masini" title="Accordi di Desesperado">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Desesperado+Marco+Masini" title="Testi di Desesperado">testi</a><br>
<b>4</b>. Las Muchachas Serias - <a target="_blank" href="http://www.google.com/search?q=spartiti+Las+Muchachas+Serias+Marco+Masini" title="Spartiti di Las Muchachas Serias">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Las+Muchachas+Serias+Marco+Masini" title="Accordi di Las Muchachas Serias">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Las+Muchachas+Serias+Marco+Masini" title="Testi di Las Muchachas Serias">testi</a><br>
<b>5</b>. Necesito El Mar - <a target="_blank" href="http://www.google.com/search?q=spartiti+Necesito+El+Mar+Marco+Masini" title="Spartiti di Necesito El Mar">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Necesito+El+Mar+Marco+Masini" title="Accordi di Necesito El Mar">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Necesito+El+Mar+Marco+Masini" title="Testi di Necesito El Mar">testi</a><br>
<b>6</b>. Porqué Lo Harás - <a target="_blank" href="http://www.google.com/search?q=spartiti+Porqu%E9+Lo+Har%E1s+Marco+Masini" title="Spartiti di Porqué Lo Harás">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Porqu%E9+Lo+Har%E1s+Marco+Masini" title="Accordi di Porqué Lo Harás">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Porqu%E9+Lo+Har%E1s+Marco+Masini" title="Testi di Porqué Lo Harás">testi</a><br>
<b>7</b>. Cenicienta Desconsolada - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cenicienta+Desconsolada+Marco+Masini" title="Spartiti di Cenicienta Desconsolada">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cenicienta+Desconsolada+Marco+Masini" title="Accordi di Cenicienta Desconsolada">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cenicienta+Desconsolada+Marco+Masini" title="Testi di Cenicienta Desconsolada">testi</a><br>
<b>8</b>. Te Querré - <a target="_blank" href="http://www.google.com/search?q=spartiti+Te+Querr%E9+Marco+Masini" title="Spartiti di Te Querré">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Te+Querr%E9+Marco+Masini" title="Accordi di Te Querré">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Te+Querr%E9+Marco+Masini" title="Testi di Te Querré">testi</a><br>
<b>9</b>. Querido Papá - <a target="_blank" href="http://www.google.com/search?q=spartiti+Querido+Pap%E1+Marco+Masini" title="Spartiti di Querido Papá">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Querido+Pap%E1+Marco+Masini" title="Accordi di Querido Papá">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Querido+Pap%E1+Marco+Masini" title="Testi di Querido Papá">testi</a><br>
<h2>Malinconoia (1991) </h2>
<b>1</b>. Perché Lo Fai - <a target="_blank" href="http://www.google.com/search?q=spartiti+Perch%E9+Lo+Fai+Marco+Masini" title="Spartiti di Perché Lo Fai">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Perch%E9+Lo+Fai+Marco+Masini" title="Accordi di Perché Lo Fai">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Perch%E9+Lo+Fai+Marco+Masini" title="Testi di Perché Lo Fai">testi</a><br>
<b>2</b>. Il Niente - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Niente+Marco+Masini" title="Spartiti di Il Niente">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Niente+Marco+Masini" title="Accordi di Il Niente">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Niente+Marco+Masini" title="Testi di Il Niente">testi</a><br>
<b>3</b>. Cenerentola Innamorata - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cenerentola+Innamorata+Marco+Masini" title="Spartiti di Cenerentola Innamorata">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cenerentola+Innamorata+Marco+Masini" title="Accordi di Cenerentola Innamorata">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cenerentola+Innamorata+Marco+Masini" title="Testi di Cenerentola Innamorata">testi</a><br>
<b>4</b>. Chi Fa Da Sé - <a target="_blank" href="http://www.google.com/search?q=spartiti+Chi+Fa+Da+S%E9+Marco+Masini" title="Spartiti di Chi Fa Da Sé">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Chi+Fa+Da+S%E9+Marco+Masini" title="Accordi di Chi Fa Da Sé">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Chi+Fa+Da+S%E9+Marco+Masini" title="Testi di Chi Fa Da Sé">testi</a><br>
<b>5</b>. Malinconoia - <a target="_blank" href="http://www.google.com/search?q=spartiti+Malinconoia+Marco+Masini" title="Spartiti di Malinconoia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Malinconoia+Marco+Masini" title="Accordi di Malinconoia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Malinconoia+Marco+Masini" title="Testi di Malinconoia">testi</a><br>
<b>6</b>. Fuori Di Qui - <a target="_blank" href="http://www.google.com/search?q=spartiti+Fuori+Di+Qui+Marco+Masini" title="Spartiti di Fuori Di Qui">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Fuori+Di+Qui+Marco+Masini" title="Accordi di Fuori Di Qui">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Fuori+Di+Qui+Marco+Masini" title="Testi di Fuori Di Qui">testi</a><br>
<b>7</b>. Ti Vorrei - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ti+Vorrei+Marco+Masini" title="Spartiti di Ti Vorrei">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ti+Vorrei+Marco+Masini" title="Accordi di Ti Vorrei">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ti+Vorrei+Marco+Masini" title="Testi di Ti Vorrei">testi</a><br>
<b>8</b>. Il Giorno Dei Perdenti - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Giorno+Dei+Perdenti+Marco+Masini" title="Spartiti di Il Giorno Dei Perdenti">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Giorno+Dei+Perdenti+Marco+Masini" title="Accordi di Il Giorno Dei Perdenti">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Giorno+Dei+Perdenti+Marco+Masini" title="Testi di Il Giorno Dei Perdenti">testi</a><br>
<b>9</b>. La Voglia di Morire - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Voglia+di+Morire+Marco+Masini" title="Spartiti di La Voglia di Morire">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Voglia+di+Morire+Marco+Masini" title="Accordi di La Voglia di Morire">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Voglia+di+Morire+Marco+Masini" title="Testi di La Voglia di Morire">testi</a><br>
<h2>Marco Masini (1990) </h2>
<b>1</b>. Vai Con Lui - <a target="_blank" href="http://www.google.com/search?q=spartiti+Vai+Con+Lui+Marco+Masini" title="Spartiti di Vai Con Lui">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Vai+Con+Lui+Marco+Masini" title="Accordi di Vai Con Lui">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Vai+Con+Lui+Marco+Masini" title="Testi di Vai Con Lui">testi</a><br>
<b>2</b>. Dentro di Te Fuori Dal Mondo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dentro+di+Te+Fuori+Dal+Mondo+Marco+Masini" title="Spartiti di Dentro di Te Fuori Dal Mondo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dentro+di+Te+Fuori+Dal+Mondo+Marco+Masini" title="Accordi di Dentro di Te Fuori Dal Mondo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dentro+di+Te+Fuori+Dal+Mondo+Marco+Masini" title="Testi di Dentro di Te Fuori Dal Mondo">testi</a><br>
<b>3</b>. Disperato - <a target="_blank" href="http://www.google.com/search?q=spartiti+Disperato+Marco+Masini" title="Spartiti di Disperato">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Disperato+Marco+Masini" title="Accordi di Disperato">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Disperato+Marco+Masini" title="Testi di Disperato">testi</a><br>
<b>4</b>. Caro Babbo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Caro+Babbo+Marco+Masini" title="Spartiti di Caro Babbo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Caro+Babbo+Marco+Masini" title="Accordi di Caro Babbo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Caro+Babbo+Marco+Masini" title="Testi di Caro Babbo">testi</a><br>
<b>5</b>. Ci Vorrebbe Il Mare - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ci+Vorrebbe+Il+Mare+Marco+Masini" title="Spartiti di Ci Vorrebbe Il Mare">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ci+Vorrebbe+Il+Mare+Marco+Masini" title="Accordi di Ci Vorrebbe Il Mare">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ci+Vorrebbe+Il+Mare+Marco+Masini" title="Testi di Ci Vorrebbe Il Mare">testi</a><br>
<b>6</b>. Le Ragazze Serie - <a target="_blank" href="http://www.google.com/search?q=spartiti+Le+Ragazze+Serie+Marco+Masini" title="Spartiti di Le Ragazze Serie">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Le+Ragazze+Serie+Marco+Masini" title="Accordi di Le Ragazze Serie">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Le+Ragazze+Serie+Marco+Masini" title="Testi di Le Ragazze Serie">testi</a><br>
<b>7</b>. A Cosa Pensi - <a target="_blank" href="http://www.google.com/search?q=spartiti+A+Cosa+Pensi+Marco+Masini" title="Spartiti di A Cosa Pensi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+A+Cosa+Pensi+Marco+Masini" title="Accordi di A Cosa Pensi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+A+Cosa+Pensi+Marco+Masini" title="Testi di A Cosa Pensi">testi</a><br>
<b>8</b>. Dal Buio - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dal+Buio+Marco+Masini" title="Spartiti di Dal Buio">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dal+Buio+Marco+Masini" title="Accordi di Dal Buio">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dal+Buio+Marco+Masini" title="Testi di Dal Buio">testi</a><br>
<h2><a href="<?php echo "$base_website_address/$spartiti_dir" ?>/index.html" title="Trova accordi, spartiti, tablature e testi di tantissimi artisti">Torna all'indice degli artisti</a></h2>
