<!--
title: Trova spartiti per chitarra, accordi, testi e tablature di Nek. Discografia Nek.
description: Trova tutti gli spartiti, accordi, testi e tablature di Nek. Discografia Nek.
keywords: Discografia, Nek, spartiti, accordi, testi, tablature
template: tablature
-->
<h1>Trova spartiti per chitarra, accordi, testi e tablature di Nek</h1><h2>Leggere gli spartiti per chitarra, gli accordi e le tablature:</h2>
<?php require("tabdescription.php"); ?>

<h2>Discografia Nek:</h2>
<h2>Esencial (2006) </h2>
<b>1</b>. Laura No Está - <a target="_blank" href="http://www.google.com/search?q=spartiti+Laura+No+Est%E1+Nek" title="Spartiti di Laura No Está">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Laura+No+Est%E1+Nek" title="Accordi di Laura No Está">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Laura+No+Est%E1+Nek" title="Testi di Laura No Está">testi</a><br>
<b>2</b>. Si Sé Que Te Tengo A Tí - <a target="_blank" href="http://www.google.com/search?q=spartiti+Si+S%E9+Que+Te+Tengo+A+T%ED+Nek" title="Spartiti di Si Sé Que Te Tengo A Tí">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Si+S%E9+Que+Te+Tengo+A+T%ED+Nek" title="Accordi di Si Sé Que Te Tengo A Tí">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Si+S%E9+Que+Te+Tengo+A+T%ED+Nek" title="Testi di Si Sé Que Te Tengo A Tí">testi</a><br>
<b>3</b>. Al Menos Ahora - <a target="_blank" href="http://www.google.com/search?q=spartiti+Al+Menos+Ahora+Nek" title="Spartiti di Al Menos Ahora">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Al+Menos+Ahora+Nek" title="Accordi di Al Menos Ahora">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Al+Menos+Ahora+Nek" title="Testi di Al Menos Ahora">testi</a><br>
<b>4</b>. Para Ti Sería - <a target="_blank" href="http://www.google.com/search?q=spartiti+Para+Ti+Ser%EDa+Nek" title="Spartiti di Para Ti Sería">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Para+Ti+Ser%EDa+Nek" title="Accordi di Para Ti Sería">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Para+Ti+Ser%EDa+Nek" title="Testi di Para Ti Sería">testi</a><br>
<b>5</b>. Tu Nombre - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tu+Nombre+Nek" title="Spartiti di Tu Nombre">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tu+Nombre+Nek" title="Accordi di Tu Nombre">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tu+Nombre+Nek" title="Testi di Tu Nombre">testi</a><br>
<b>6</b>. No Preguntes Porque - <a target="_blank" href="http://www.google.com/search?q=spartiti+No+Preguntes+Porque+Nek" title="Spartiti di No Preguntes Porque">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+No+Preguntes+Porque+Nek" title="Accordi di No Preguntes Porque">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+No+Preguntes+Porque+Nek" title="Testi di No Preguntes Porque">testi</a><br>
<b>7</b>. Cielo Y Tierra - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cielo+Y+Tierra+Nek" title="Spartiti di Cielo Y Tierra">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cielo+Y+Tierra+Nek" title="Accordi di Cielo Y Tierra">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cielo+Y+Tierra+Nek" title="Testi di Cielo Y Tierra">testi</a><br>
<b>8</b>. A Contramano - <a target="_blank" href="http://www.google.com/search?q=spartiti+A+Contramano+Nek" title="Spartiti di A Contramano">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+A+Contramano+Nek" title="Accordi di A Contramano">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+A+Contramano+Nek" title="Testi di A Contramano">testi</a><br>
<b>9</b>. El Año Cero - <a target="_blank" href="http://www.google.com/search?q=spartiti+El+A%F1o+Cero+Nek" title="Spartiti di El Año Cero">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+El+A%F1o+Cero+Nek" title="Accordi di El Año Cero">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+El+A%F1o+Cero+Nek" title="Testi di El Año Cero">testi</a><br>
<b>10</b>. Tan Solo Tú - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tan+Solo+T%FA+Nek" title="Spartiti di Tan Solo Tú">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tan+Solo+T%FA+Nek" title="Accordi di Tan Solo Tú">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tan+Solo+T%FA+Nek" title="Testi di Tan Solo Tú">testi</a><br>
<b>11</b>. La Inquietud - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Inquietud+Nek" title="Spartiti di La Inquietud">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Inquietud+Nek" title="Accordi di La Inquietud">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Inquietud+Nek" title="Testi di La Inquietud">testi</a><br>
<b>12</b>. Quédate - <a target="_blank" href="http://www.google.com/search?q=spartiti+Qu%E9date+Nek" title="Spartiti di Quédate">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Qu%E9date+Nek" title="Accordi di Quédate">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Qu%E9date+Nek" title="Testi di Quédate">testi</a><br>
<b>13</b>. Ya Está Bien Así - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ya+Est%E1+Bien+As%ED+Nek" title="Spartiti di Ya Está Bien Así">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ya+Est%E1+Bien+As%ED+Nek" title="Accordi di Ya Está Bien Así">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ya+Est%E1+Bien+As%ED+Nek" title="Testi di Ya Está Bien Así">testi</a><br>
<h2>Nella Stanza 26 (2006) </h2>
<b>1</b>. Notte Di Febbraio - <a target="_blank" href="http://www.google.com/search?q=spartiti+Notte+Di+Febbraio+Nek" title="Spartiti di Notte Di Febbraio">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Notte+Di+Febbraio+Nek" title="Accordi di Notte Di Febbraio">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Notte+Di+Febbraio+Nek" title="Testi di Notte Di Febbraio">testi</a><br>
<b>2</b>. Cri - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cri+Nek" title="Spartiti di Cri">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cri+Nek" title="Accordi di Cri">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cri+Nek" title="Testi di Cri">testi</a><br>
<b>3</b>. Instabile - <a target="_blank" href="http://www.google.com/search?q=spartiti+Instabile+Nek" title="Spartiti di Instabile">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Instabile+Nek" title="Accordi di Instabile">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Instabile+Nek" title="Testi di Instabile">testi</a><br>
<b>4</b>. Fumo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Fumo+Nek" title="Spartiti di Fumo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Fumo+Nek" title="Accordi di Fumo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Fumo+Nek" title="Testi di Fumo">testi</a><br>
<b>5</b>. Attimi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Attimi+Nek" title="Spartiti di Attimi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Attimi+Nek" title="Accordi di Attimi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Attimi+Nek" title="Testi di Attimi">testi</a><br>
<b>6</b>. Nella Stanza 26 - <a target="_blank" href="http://www.google.com/search?q=spartiti+Nella+Stanza+26+Nek" title="Spartiti di Nella Stanza 26">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Nella+Stanza+26+Nek" title="Accordi di Nella Stanza 26">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Nella+Stanza+26+Nek" title="Testi di Nella Stanza 26">testi</a><br>
<b>7</b>. Sei - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sei+Nek" title="Spartiti di Sei">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sei+Nek" title="Accordi di Sei">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sei+Nek" title="Testi di Sei">testi</a><br>
<b>8</b>. Ancora Un Giorno Di Te - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ancora+Un+Giorno+Di+Te+Nek" title="Spartiti di Ancora Un Giorno Di Te">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ancora+Un+Giorno+Di+Te+Nek" title="Accordi di Ancora Un Giorno Di Te">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ancora+Un+Giorno+Di+Te+Nek" title="Testi di Ancora Un Giorno Di Te">testi</a><br>
<b>9</b>. Serenità - <a target="_blank" href="http://www.google.com/search?q=spartiti+Serenit%E0+Nek" title="Spartiti di Serenità">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Serenit%E0+Nek" title="Accordi di Serenità">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Serenit%E0+Nek" title="Testi di Serenità">testi</a><br>
<b>10</b>. Contro Le Mie Ombre - <a target="_blank" href="http://www.google.com/search?q=spartiti+Contro+Le+Mie+Ombre+Nek" title="Spartiti di Contro Le Mie Ombre">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Contro+Le+Mie+Ombre+Nek" title="Accordi di Contro Le Mie Ombre">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Contro+Le+Mie+Ombre+Nek" title="Testi di Contro Le Mie Ombre">testi</a><br>
<h2>Una Parte De Mi (2005) </h2>
<b>1</b>. A Contramano - <a target="_blank" href="http://www.google.com/search?q=spartiti+A+Contramano+Nek" title="Spartiti di A Contramano">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+A+Contramano+Nek" title="Accordi di A Contramano">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+A+Contramano+Nek" title="Testi di A Contramano">testi</a><br>
<b>2</b>. Para Ti Seria - <a target="_blank" href="http://www.google.com/search?q=spartiti+Para+Ti+Seria+Nek" title="Spartiti di Para Ti Seria">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Para+Ti+Seria+Nek" title="Accordi di Para Ti Seria">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Para+Ti+Seria+Nek" title="Testi di Para Ti Seria">testi</a><br>
<b>3</b>. La Inquietud - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Inquietud+Nek" title="Spartiti di La Inquietud">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Inquietud+Nek" title="Accordi di La Inquietud">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Inquietud+Nek" title="Testi di La Inquietud">testi</a><br>
<b>4</b>. Noche Arriesgada - <a target="_blank" href="http://www.google.com/search?q=spartiti+Noche+Arriesgada+Nek" title="Spartiti di Noche Arriesgada">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Noche+Arriesgada+Nek" title="Accordi di Noche Arriesgada">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Noche+Arriesgada+Nek" title="Testi di Noche Arriesgada">testi</a><br>
<b>5</b>. Abrazame - <a target="_blank" href="http://www.google.com/search?q=spartiti+Abrazame+Nek" title="Spartiti di Abrazame">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Abrazame+Nek" title="Accordi di Abrazame">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Abrazame+Nek" title="Testi di Abrazame">testi</a><br>
<b>6</b>. Daria Todo Lo Que Tengo Y MÁs - <a target="_blank" href="http://www.google.com/search?q=spartiti+Daria+Todo+Lo+Que+Tengo+Y+M%C1s+Nek" title="Spartiti di Daria Todo Lo Que Tengo Y MÁs">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Daria+Todo+Lo+Que+Tengo+Y+M%C1s+Nek" title="Accordi di Daria Todo Lo Que Tengo Y MÁs">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Daria+Todo+Lo+Que+Tengo+Y+M%C1s+Nek" title="Testi di Daria Todo Lo Que Tengo Y MÁs">testi</a><br>
<b>7</b>. Ya Esta Bien Asi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ya+Esta+Bien+Asi+Nek" title="Spartiti di Ya Esta Bien Asi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ya+Esta+Bien+Asi+Nek" title="Accordi di Ya Esta Bien Asi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ya+Esta+Bien+Asi+Nek" title="Testi di Ya Esta Bien Asi">testi</a><br>
<b>8</b>. Una Parte De Mi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Una+Parte+De+Mi+Nek" title="Spartiti di Una Parte De Mi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Una+Parte+De+Mi+Nek" title="Accordi di Una Parte De Mi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Una+Parte+De+Mi+Nek" title="Testi di Una Parte De Mi">testi</a><br>
<b>9</b>. No Vale Un Adios - <a target="_blank" href="http://www.google.com/search?q=spartiti+No+Vale+Un+Adios+Nek" title="Spartiti di No Vale Un Adios">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+No+Vale+Un+Adios+Nek" title="Accordi di No Vale Un Adios">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+No+Vale+Un+Adios+Nek" title="Testi di No Vale Un Adios">testi</a><br>
<b>10</b>. Y Estoy Aqui - <a target="_blank" href="http://www.google.com/search?q=spartiti+Y+Estoy+Aqui+Nek" title="Spartiti di Y Estoy Aqui">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Y+Estoy+Aqui+Nek" title="Accordi di Y Estoy Aqui">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Y+Estoy+Aqui+Nek" title="Testi di Y Estoy Aqui">testi</a><br>
<h2>Una Parte Di Me (2005) </h2>
<b>1</b>. Contromano - <a target="_blank" href="http://www.google.com/search?q=spartiti+Contromano+Nek" title="Spartiti di Contromano">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Contromano+Nek" title="Accordi di Contromano">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Contromano+Nek" title="Testi di Contromano">testi</a><br>
<b>2</b>. Lascia Che Io Sia - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lascia+Che+Io+Sia+Nek" title="Spartiti di Lascia Che Io Sia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lascia+Che+Io+Sia+Nek" title="Accordi di Lascia Che Io Sia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lascia+Che+Io+Sia+Nek" title="Testi di Lascia Che Io Sia">testi</a><br>
<b>3</b>. L'inquietudine - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%27inquietudine+Nek" title="Spartiti di L'inquietudine">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%27inquietudine+Nek" title="Accordi di L'inquietudine">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%27inquietudine+Nek" title="Testi di L'inquietudine">testi</a><br>
<b>4</b>. Notte Bastarda - <a target="_blank" href="http://www.google.com/search?q=spartiti+Notte+Bastarda+Nek" title="Spartiti di Notte Bastarda">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Notte+Bastarda+Nek" title="Accordi di Notte Bastarda">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Notte+Bastarda+Nek" title="Testi di Notte Bastarda">testi</a><br>
<b>5</b>. Abbracciami - <a target="_blank" href="http://www.google.com/search?q=spartiti+Abbracciami+Nek" title="Spartiti di Abbracciami">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Abbracciami+Nek" title="Accordi di Abbracciami">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Abbracciami+Nek" title="Testi di Abbracciami">testi</a><br>
<b>6</b>. Darei Di Piu' Di Tutto Quel Che Ho - <a target="_blank" href="http://www.google.com/search?q=spartiti+Darei+Di+Piu%27+Di+Tutto+Quel+Che+Ho+Nek" title="Spartiti di Darei Di Piu' Di Tutto Quel Che Ho">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Darei+Di+Piu%27+Di+Tutto+Quel+Che+Ho+Nek" title="Accordi di Darei Di Piu' Di Tutto Quel Che Ho">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Darei+Di+Piu%27+Di+Tutto+Quel+Che+Ho+Nek" title="Testi di Darei Di Piu' Di Tutto Quel Che Ho">testi</a><br>
<b>7</b>. Va Bene Cosi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Va+Bene+Cosi+Nek" title="Spartiti di Va Bene Cosi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Va+Bene+Cosi+Nek" title="Accordi di Va Bene Cosi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Va+Bene+Cosi+Nek" title="Testi di Va Bene Cosi">testi</a><br>
<b>8</b>. Una Parte Di Me - <a target="_blank" href="http://www.google.com/search?q=spartiti+Una+Parte+Di+Me+Nek" title="Spartiti di Una Parte Di Me">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Una+Parte+Di+Me+Nek" title="Accordi di Una Parte Di Me">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Una+Parte+Di+Me+Nek" title="Testi di Una Parte Di Me">testi</a><br>
<b>9</b>. Non Vale Un Addio - <a target="_blank" href="http://www.google.com/search?q=spartiti+Non+Vale+Un+Addio+Nek" title="Spartiti di Non Vale Un Addio">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Non+Vale+Un+Addio+Nek" title="Accordi di Non Vale Un Addio">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Non+Vale+Un+Addio+Nek" title="Testi di Non Vale Un Addio">testi</a><br>
<b>10</b>. Io Sono Qui - <a target="_blank" href="http://www.google.com/search?q=spartiti+Io+Sono+Qui+Nek" title="Spartiti di Io Sono Qui">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Io+Sono+Qui+Nek" title="Accordi di Io Sono Qui">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Io+Sono+Qui+Nek" title="Testi di Io Sono Qui">testi</a><br>
<h2>The Best Of Nek - L'Anno Zero (2003) </h2>
<b>1</b>. Almeno Stavolta - <a target="_blank" href="http://www.google.com/search?q=spartiti+Almeno+Stavolta+Nek" title="Spartiti di Almeno Stavolta">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Almeno+Stavolta+Nek" title="Accordi di Almeno Stavolta">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Almeno+Stavolta+Nek" title="Testi di Almeno Stavolta">testi</a><br>
<b>2</b>. L'Anno Zero - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%27Anno+Zero+Nek" title="Spartiti di L'Anno Zero">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%27Anno+Zero+Nek" title="Accordi di L'Anno Zero">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%27Anno+Zero+Nek" title="Testi di L'Anno Zero">testi</a><br>
<b>3</b>. In Te - <a target="_blank" href="http://www.google.com/search?q=spartiti+In+Te+Nek" title="Spartiti di In Te">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+In+Te+Nek" title="Accordi di In Te">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+In+Te+Nek" title="Testi di In Te">testi</a><br>
<b>4</b>. Cuori In Tempesta - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cuori+In+Tempesta+Nek" title="Spartiti di Cuori In Tempesta">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cuori+In+Tempesta+Nek" title="Accordi di Cuori In Tempesta">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cuori+In+Tempesta+Nek" title="Testi di Cuori In Tempesta">testi</a><br>
<b>5</b>. Angeli Nel Ghetto - <a target="_blank" href="http://www.google.com/search?q=spartiti+Angeli+Nel+Ghetto+Nek" title="Spartiti di Angeli Nel Ghetto">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Angeli+Nel+Ghetto+Nek" title="Accordi di Angeli Nel Ghetto">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Angeli+Nel+Ghetto+Nek" title="Testi di Angeli Nel Ghetto">testi</a><br>
<b>6</b>. Dimmi Cos'è - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dimmi+Cos%27%E8+Nek" title="Spartiti di Dimmi Cos'è">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dimmi+Cos%27%E8+Nek" title="Accordi di Dimmi Cos'è">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dimmi+Cos%27%E8+Nek" title="Testi di Dimmi Cos'è">testi</a><br>
<b>7</b>. Tu Sei, Tu Sai - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tu+Sei%2C+Tu+Sai+Nek" title="Spartiti di Tu Sei, Tu Sai">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tu+Sei%2C+Tu+Sai+Nek" title="Accordi di Tu Sei, Tu Sai">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tu+Sei%2C+Tu+Sai+Nek" title="Testi di Tu Sei, Tu Sai">testi</a><br>
<b>8</b>. Laura Non C'è - <a target="_blank" href="http://www.google.com/search?q=spartiti+Laura+Non+C%27%E8+Nek" title="Spartiti di Laura Non C'è">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Laura+Non+C%27%E8+Nek" title="Accordi di Laura Non C'è">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Laura+Non+C%27%E8+Nek" title="Testi di Laura Non C'è">testi</a><br>
<b>9</b>. Sei Grande - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sei+Grande+Nek" title="Spartiti di Sei Grande">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sei+Grande+Nek" title="Accordi di Sei Grande">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sei+Grande+Nek" title="Testi di Sei Grande">testi</a><br>
<b>10</b>. Se Io Non Avessi Te - <a target="_blank" href="http://www.google.com/search?q=spartiti+Se+Io+Non+Avessi+Te+Nek" title="Spartiti di Se Io Non Avessi Te">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Se+Io+Non+Avessi+Te+Nek" title="Accordi di Se Io Non Avessi Te">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Se+Io+Non+Avessi+Te+Nek" title="Testi di Se Io Non Avessi Te">testi</a><br>
<b>11</b>. Sto Con Te - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sto+Con+Te+Nek" title="Spartiti di Sto Con Te">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sto+Con+Te+Nek" title="Accordi di Sto Con Te">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sto+Con+Te+Nek" title="Testi di Sto Con Te">testi</a><br>
<b>12</b>. Se Una Regola C'è - <a target="_blank" href="http://www.google.com/search?q=spartiti+Se+Una+Regola+C%27%E8+Nek" title="Spartiti di Se Una Regola C'è">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Se+Una+Regola+C%27%E8+Nek" title="Accordi di Se Una Regola C'è">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Se+Una+Regola+C%27%E8+Nek" title="Testi di Se Una Regola C'è">testi</a><br>
<b>13</b>. Ci Sei Tu - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ci+Sei+Tu+Nek" title="Spartiti di Ci Sei Tu">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ci+Sei+Tu+Nek" title="Accordi di Ci Sei Tu">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ci+Sei+Tu+Nek" title="Testi di Ci Sei Tu">testi</a><br>
<b>14</b>. Sul Treno - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sul+Treno+Nek" title="Spartiti di Sul Treno">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sul+Treno+Nek" title="Accordi di Sul Treno">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sul+Treno+Nek" title="Testi di Sul Treno">testi</a><br>
<b>15</b>. La Vita E' - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Vita+E%27+Nek" title="Spartiti di La Vita E'">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Vita+E%27+Nek" title="Accordi di La Vita E'">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Vita+E%27+Nek" title="Testi di La Vita E'">testi</a><br>
<b>16</b>. Sei Solo Tu - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sei+Solo+Tu+Nek" title="Spartiti di Sei Solo Tu">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sei+Solo+Tu+Nek" title="Accordi di Sei Solo Tu">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sei+Solo+Tu+Nek" title="Testi di Sei Solo Tu">testi</a><br>
<b>17</b>. Parliamo Al Singolare - <a target="_blank" href="http://www.google.com/search?q=spartiti+Parliamo+Al+Singolare+Nek" title="Spartiti di Parliamo Al Singolare">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Parliamo+Al+Singolare+Nek" title="Accordi di Parliamo Al Singolare">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Parliamo+Al+Singolare+Nek" title="Testi di Parliamo Al Singolare">testi</a><br>
<b>18</b>. Cielo E Terra - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cielo+E+Terra+Nek" title="Spartiti di Cielo E Terra">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cielo+E+Terra+Nek" title="Accordi di Cielo E Terra">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cielo+E+Terra+Nek" title="Testi di Cielo E Terra">testi</a><br>
<h2>Las Cosas Que Defendere (2002) </h2>
<b>1</b>. Las Cosas Que Defendere - <a target="_blank" href="http://www.google.com/search?q=spartiti+Las+Cosas+Que+Defendere+Nek" title="Spartiti di Las Cosas Que Defendere">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Las+Cosas+Que+Defendere+Nek" title="Accordi di Las Cosas Que Defendere">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Las+Cosas+Que+Defendere+Nek" title="Testi di Las Cosas Que Defendere">testi</a><br>
<b>2</b>. Tan Sólo Tú - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tan+S%F3lo+T%FA+Nek" title="Spartiti di Tan Sólo Tú">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tan+S%F3lo+T%FA+Nek" title="Accordi di Tan Sólo Tú">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tan+S%F3lo+T%FA+Nek" title="Testi di Tan Sólo Tú">testi</a><br>
<b>3</b>. Hablemos En Pasado - <a target="_blank" href="http://www.google.com/search?q=spartiti+Hablemos+En+Pasado+Nek" title="Spartiti di Hablemos En Pasado">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Hablemos+En+Pasado+Nek" title="Accordi di Hablemos En Pasado">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Hablemos+En+Pasado+Nek" title="Testi di Hablemos En Pasado">testi</a><br>
<b>4</b>. Cuando Tu No Estas - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cuando+Tu+No+Estas+Nek" title="Spartiti di Cuando Tu No Estas">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cuando+Tu+No+Estas+Nek" title="Accordi di Cuando Tu No Estas">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cuando+Tu+No+Estas+Nek" title="Testi di Cuando Tu No Estas">testi</a><br>
<b>5</b>. Hazme Amarte - <a target="_blank" href="http://www.google.com/search?q=spartiti+Hazme+Amarte+Nek" title="Spartiti di Hazme Amarte">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Hazme+Amarte+Nek" title="Accordi di Hazme Amarte">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Hazme+Amarte+Nek" title="Testi di Hazme Amarte">testi</a><br>
<b>6</b>. Cielo Y Tierra - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cielo+Y+Tierra+Nek" title="Spartiti di Cielo Y Tierra">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cielo+Y+Tierra+Nek" title="Accordi di Cielo Y Tierra">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cielo+Y+Tierra+Nek" title="Testi di Cielo Y Tierra">testi</a><br>
<b>7</b>. Todo De Ti - <a target="_blank" href="http://www.google.com/search?q=spartiti+Todo+De+Ti+Nek" title="Spartiti di Todo De Ti">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Todo+De+Ti+Nek" title="Accordi di Todo De Ti">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Todo+De+Ti+Nek" title="Testi di Todo De Ti">testi</a><br>
<b>8</b>. Laberinto - <a target="_blank" href="http://www.google.com/search?q=spartiti+Laberinto+Nek" title="Spartiti di Laberinto">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Laberinto+Nek" title="Accordi di Laberinto">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Laberinto+Nek" title="Testi di Laberinto">testi</a><br>
<b>9</b>. Mi Naturaleza - <a target="_blank" href="http://www.google.com/search?q=spartiti+Mi+Naturaleza+Nek" title="Spartiti di Mi Naturaleza">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Mi+Naturaleza+Nek" title="Accordi di Mi Naturaleza">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Mi+Naturaleza+Nek" title="Testi di Mi Naturaleza">testi</a><br>
<b>10</b>. La Consecuencia - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Consecuencia+Nek" title="Spartiti di La Consecuencia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Consecuencia+Nek" title="Accordi di La Consecuencia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Consecuencia+Nek" title="Testi di La Consecuencia">testi</a><br>
<b>11</b>. Cielo Y Tierra (w/Dante Thomas) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cielo+Y+Tierra+%28w%2FDante+Thomas%29+Nek" title="Spartiti di Cielo Y Tierra (w/Dante Thomas)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cielo+Y+Tierra+%28w%2FDante+Thomas%29+Nek" title="Accordi di Cielo Y Tierra (w/Dante Thomas)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cielo+Y+Tierra+%28w%2FDante+Thomas%29+Nek" title="Testi di Cielo Y Tierra (w/Dante Thomas)">testi</a><br>
<h2>Le Cose Da Difendere (2002) </h2>
<b>1</b>. Le Cose Da Difendere - <a target="_blank" href="http://www.google.com/search?q=spartiti+Le+Cose+Da+Difendere+Nek" title="Spartiti di Le Cose Da Difendere">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Le+Cose+Da+Difendere+Nek" title="Accordi di Le Cose Da Difendere">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Le+Cose+Da+Difendere+Nek" title="Testi di Le Cose Da Difendere">testi</a><br>
<b>2</b>. Sei Solo Tu - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sei+Solo+Tu+Nek" title="Spartiti di Sei Solo Tu">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sei+Solo+Tu+Nek" title="Accordi di Sei Solo Tu">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sei+Solo+Tu+Nek" title="Testi di Sei Solo Tu">testi</a><br>
<b>3</b>. Parliamo Al Singolare - <a target="_blank" href="http://www.google.com/search?q=spartiti+Parliamo+Al+Singolare+Nek" title="Spartiti di Parliamo Al Singolare">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Parliamo+Al+Singolare+Nek" title="Accordi di Parliamo Al Singolare">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Parliamo+Al+Singolare+Nek" title="Testi di Parliamo Al Singolare">testi</a><br>
<b>4</b>. Quando Non Ci Sei - <a target="_blank" href="http://www.google.com/search?q=spartiti+Quando+Non+Ci+Sei+Nek" title="Spartiti di Quando Non Ci Sei">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Quando+Non+Ci+Sei+Nek" title="Accordi di Quando Non Ci Sei">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Quando+Non+Ci+Sei+Nek" title="Testi di Quando Non Ci Sei">testi</a><br>
<b>5</b>. Fatti Amare - <a target="_blank" href="http://www.google.com/search?q=spartiti+Fatti+Amare+Nek" title="Spartiti di Fatti Amare">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Fatti+Amare+Nek" title="Accordi di Fatti Amare">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Fatti+Amare+Nek" title="Testi di Fatti Amare">testi</a><br>
<b>6</b>. Cielo E Terra - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cielo+E+Terra+Nek" title="Spartiti di Cielo E Terra">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cielo+E+Terra+Nek" title="Accordi di Cielo E Terra">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cielo+E+Terra+Nek" title="Testi di Cielo E Terra">testi</a><br>
<b>7</b>. Tutto Di Te - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tutto+Di+Te+Nek" title="Spartiti di Tutto Di Te">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tutto+Di+Te+Nek" title="Accordi di Tutto Di Te">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tutto+Di+Te+Nek" title="Testi di Tutto Di Te">testi</a><br>
<b>8</b>. Labirinto - <a target="_blank" href="http://www.google.com/search?q=spartiti+Labirinto+Nek" title="Spartiti di Labirinto">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Labirinto+Nek" title="Accordi di Labirinto">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Labirinto+Nek" title="Testi di Labirinto">testi</a><br>
<b>9</b>. La Mia Natura - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Mia+Natura+Nek" title="Spartiti di La Mia Natura">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Mia+Natura+Nek" title="Accordi di La Mia Natura">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Mia+Natura+Nek" title="Testi di La Mia Natura">testi</a><br>
<b>10</b>. Di Conseguenza - <a target="_blank" href="http://www.google.com/search?q=spartiti+Di+Conseguenza+Nek" title="Spartiti di Di Conseguenza">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Di+Conseguenza+Nek" title="Accordi di Di Conseguenza">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Di+Conseguenza+Nek" title="Testi di Di Conseguenza">testi</a><br>
<b>11</b>. Cielo E Terra (w/Dante Thomas) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cielo+E+Terra+%28w%2FDante+Thomas%29+Nek" title="Spartiti di Cielo E Terra (w/Dante Thomas)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cielo+E+Terra+%28w%2FDante+Thomas%29+Nek" title="Accordi di Cielo E Terra (w/Dante Thomas)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cielo+E+Terra+%28w%2FDante+Thomas%29+Nek" title="Testi di Cielo E Terra (w/Dante Thomas)">testi</a><br>
<h2>La Vida Es (2000) </h2>
<b>1</b>. Llegas Tú - <a target="_blank" href="http://www.google.com/search?q=spartiti+Llegas+T%FA+Nek" title="Spartiti di Llegas Tú">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Llegas+T%FA+Nek" title="Accordi di Llegas Tú">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Llegas+T%FA+Nek" title="Testi di Llegas Tú">testi</a><br>
<b>2</b>. Miami - <a target="_blank" href="http://www.google.com/search?q=spartiti+Miami+Nek" title="Spartiti di Miami">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Miami+Nek" title="Accordi di Miami">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Miami+Nek" title="Testi di Miami">testi</a><br>
<b>3</b>. La Vida Es - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Vida+Es+Nek" title="Spartiti di La Vida Es">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Vida+Es+Nek" title="Accordi di La Vida Es">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Vida+Es+Nek" title="Testi di La Vida Es">testi</a><br>
<b>4</b>. Nuestro Mejor Día - <a target="_blank" href="http://www.google.com/search?q=spartiti+Nuestro+Mejor+D%EDa+Nek" title="Spartiti di Nuestro Mejor Día">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Nuestro+Mejor+D%EDa+Nek" title="Accordi di Nuestro Mejor Día">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Nuestro+Mejor+D%EDa+Nek" title="Testi di Nuestro Mejor Día">testi</a><br>
<b>5</b>. Jjeno De Energia - <a target="_blank" href="http://www.google.com/search?q=spartiti+Jjeno+De+Energia+Nek" title="Spartiti di Jjeno De Energia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Jjeno+De+Energia+Nek" title="Accordi di Jjeno De Energia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Jjeno+De+Energia+Nek" title="Testi di Jjeno De Energia">testi</a><br>
<b>6</b>. En El Tren - <a target="_blank" href="http://www.google.com/search?q=spartiti+En+El+Tren+Nek" title="Spartiti di En El Tren">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+En+El+Tren+Nek" title="Accordi di En El Tren">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+En+El+Tren+Nek" title="Testi di En El Tren">testi</a><br>
<b>7</b>. Celos - <a target="_blank" href="http://www.google.com/search?q=spartiti+Celos+Nek" title="Spartiti di Celos">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Celos+Nek" title="Accordi di Celos">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Celos+Nek" title="Testi di Celos">testi</a><br>
<b>8</b>. Viviré - <a target="_blank" href="http://www.google.com/search?q=spartiti+Vivir%E9+Nek" title="Spartiti di Viviré">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Vivir%E9+Nek" title="Accordi di Viviré">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Vivir%E9+Nek" title="Testi di Viviré">testi</a><br>
<b>9</b>. Volveras A Vivir - <a target="_blank" href="http://www.google.com/search?q=spartiti+Volveras+A+Vivir+Nek" title="Spartiti di Volveras A Vivir">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Volveras+A+Vivir+Nek" title="Accordi di Volveras A Vivir">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Volveras+A+Vivir+Nek" title="Testi di Volveras A Vivir">testi</a><br>
<b>10</b>. Creo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Creo+Nek" title="Spartiti di Creo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Creo+Nek" title="Accordi di Creo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Creo+Nek" title="Testi di Creo">testi</a><br>
<b>11</b>. Comenzar De Cero - <a target="_blank" href="http://www.google.com/search?q=spartiti+Comenzar+De+Cero+Nek" title="Spartiti di Comenzar De Cero">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Comenzar+De+Cero+Nek" title="Accordi di Comenzar De Cero">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Comenzar+De+Cero+Nek" title="Testi di Comenzar De Cero">testi</a><br>
<b>12</b>. Tu Me Das - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tu+Me+Das+Nek" title="Spartiti di Tu Me Das">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tu+Me+Das+Nek" title="Accordi di Tu Me Das">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tu+Me+Das+Nek" title="Testi di Tu Me Das">testi</a><br>
<b>13</b>. Lejos De Mi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lejos+De+Mi+Nek" title="Spartiti di Lejos De Mi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lejos+De+Mi+Nek" title="Accordi di Lejos De Mi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lejos+De+Mi+Nek" title="Testi di Lejos De Mi">testi</a><br>
<b>14</b>. Llegas Tu (Version Acustica) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Llegas+Tu+%28Version+Acustica%29+Nek" title="Spartiti di Llegas Tu (Version Acustica)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Llegas+Tu+%28Version+Acustica%29+Nek" title="Accordi di Llegas Tu (Version Acustica)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Llegas+Tu+%28Version+Acustica%29+Nek" title="Testi di Llegas Tu (Version Acustica)">testi</a><br>
<h2>La Vita E' (2000) </h2>
<b>1</b>. Ci Sei Tu - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ci+Sei+Tu+Nek" title="Spartiti di Ci Sei Tu">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ci+Sei+Tu+Nek" title="Accordi di Ci Sei Tu">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ci+Sei+Tu+Nek" title="Testi di Ci Sei Tu">testi</a><br>
<b>2</b>. Miami - <a target="_blank" href="http://www.google.com/search?q=spartiti+Miami+Nek" title="Spartiti di Miami">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Miami+Nek" title="Accordi di Miami">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Miami+Nek" title="Testi di Miami">testi</a><br>
<b>3</b>. La Vita E' - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Vita+E%27+Nek" title="Spartiti di La Vita E'">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Vita+E%27+Nek" title="Accordi di La Vita E'">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Vita+E%27+Nek" title="Testi di La Vita E'">testi</a><br>
<b>4</b>. Il Nostro Giorno In Più - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Nostro+Giorno+In+Pi%F9+Nek" title="Spartiti di Il Nostro Giorno In Più">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Nostro+Giorno+In+Pi%F9+Nek" title="Accordi di Il Nostro Giorno In Più">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Nostro+Giorno+In+Pi%F9+Nek" title="Testi di Il Nostro Giorno In Più">testi</a><br>
<b>5</b>. Pieno D'Energia - <a target="_blank" href="http://www.google.com/search?q=spartiti+Pieno+D%27Energia+Nek" title="Spartiti di Pieno D'Energia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Pieno+D%27Energia+Nek" title="Accordi di Pieno D'Energia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Pieno+D%27Energia+Nek" title="Testi di Pieno D'Energia">testi</a><br>
<b>6</b>. Sul Treno - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sul+Treno+Nek" title="Spartiti di Sul Treno">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sul+Treno+Nek" title="Accordi di Sul Treno">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sul+Treno+Nek" title="Testi di Sul Treno">testi</a><br>
<b>7</b>. Sana Gelosia - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sana+Gelosia+Nek" title="Spartiti di Sana Gelosia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sana+Gelosia+Nek" title="Accordi di Sana Gelosia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sana+Gelosia+Nek" title="Testi di Sana Gelosia">testi</a><br>
<b>8</b>. Mi Piace Vivere - <a target="_blank" href="http://www.google.com/search?q=spartiti+Mi+Piace+Vivere+Nek" title="Spartiti di Mi Piace Vivere">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Mi+Piace+Vivere+Nek" title="Accordi di Mi Piace Vivere">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Mi+Piace+Vivere+Nek" title="Testi di Mi Piace Vivere">testi</a><br>
<b>9</b>. Meglio Esserci - <a target="_blank" href="http://www.google.com/search?q=spartiti+Meglio+Esserci+Nek" title="Spartiti di Meglio Esserci">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Meglio+Esserci+Nek" title="Accordi di Meglio Esserci">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Meglio+Esserci+Nek" title="Testi di Meglio Esserci">testi</a><br>
<b>10</b>. Credo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Credo+Nek" title="Spartiti di Credo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Credo+Nek" title="Accordi di Credo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Credo+Nek" title="Testi di Credo">testi</a><br>
<b>11</b>. Missile Speciale - <a target="_blank" href="http://www.google.com/search?q=spartiti+Missile+Speciale+Nek" title="Spartiti di Missile Speciale">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Missile+Speciale+Nek" title="Accordi di Missile Speciale">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Missile+Speciale+Nek" title="Testi di Missile Speciale">testi</a><br>
<b>12</b>. Tu Mi Dai - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tu+Mi+Dai+Nek" title="Spartiti di Tu Mi Dai">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tu+Mi+Dai+Nek" title="Accordi di Tu Mi Dai">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tu+Mi+Dai+Nek" title="Testi di Tu Mi Dai">testi</a><br>
<b>13</b>. Con La Terra Sotto Di Me - <a target="_blank" href="http://www.google.com/search?q=spartiti+Con+La+Terra+Sotto+Di+Me+Nek" title="Spartiti di Con La Terra Sotto Di Me">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Con+La+Terra+Sotto+Di+Me+Nek" title="Accordi di Con La Terra Sotto Di Me">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Con+La+Terra+Sotto+Di+Me+Nek" title="Testi di Con La Terra Sotto Di Me">testi</a><br>
<b>14</b>. Ci Sei Tu (Guitar-Vox Version) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ci+Sei+Tu+%28Guitar-Vox+Version%29+Nek" title="Spartiti di Ci Sei Tu (Guitar-Vox Version)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ci+Sei+Tu+%28Guitar-Vox+Version%29+Nek" title="Accordi di Ci Sei Tu (Guitar-Vox Version)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ci+Sei+Tu+%28Guitar-Vox+Version%29+Nek" title="Testi di Ci Sei Tu (Guitar-Vox Version)">testi</a><br>
<h2>Entre Tu Y Yo (1998) </h2>
<b>1</b>. Si Sé Que Te Tengo A Ti - <a target="_blank" href="http://www.google.com/search?q=spartiti+Si+S%E9+Que+Te+Tengo+A+Ti+Nek" title="Spartiti di Si Sé Que Te Tengo A Ti">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Si+S%E9+Que+Te+Tengo+A+Ti+Nek" title="Accordi di Si Sé Que Te Tengo A Ti">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Si+S%E9+Que+Te+Tengo+A+Ti+Nek" title="Testi di Si Sé Que Te Tengo A Ti">testi</a><br>
<b>2</b>. Quédate - <a target="_blank" href="http://www.google.com/search?q=spartiti+Qu%E9date+Nek" title="Spartiti di Quédate">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Qu%E9date+Nek" title="Accordi di Quédate">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Qu%E9date+Nek" title="Testi di Quédate">testi</a><br>
<b>3</b>. Quiero Ser - <a target="_blank" href="http://www.google.com/search?q=spartiti+Quiero+Ser+Nek" title="Spartiti di Quiero Ser">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Quiero+Ser+Nek" title="Accordi di Quiero Ser">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Quiero+Ser+Nek" title="Testi di Quiero Ser">testi</a><br>
<b>4</b>. No Preguntes Por Qué - <a target="_blank" href="http://www.google.com/search?q=spartiti+No+Preguntes+Por+Qu%E9+Nek" title="Spartiti di No Preguntes Por Qué">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+No+Preguntes+Por+Qu%E9+Nek" title="Accordi di No Preguntes Por Qué">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+No+Preguntes+Por+Qu%E9+Nek" title="Testi di No Preguntes Por Qué">testi</a><br>
<b>5</b>. Una Obsesion - <a target="_blank" href="http://www.google.com/search?q=spartiti+Una+Obsesion+Nek" title="Spartiti di Una Obsesion">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Una+Obsesion+Nek" title="Accordi di Una Obsesion">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Una+Obsesion+Nek" title="Testi di Una Obsesion">testi</a><br>
<b>6</b>. Llegarás - <a target="_blank" href="http://www.google.com/search?q=spartiti+Llegar%E1s+Nek" title="Spartiti di Llegarás">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Llegar%E1s+Nek" title="Accordi di Llegarás">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Llegar%E1s+Nek" title="Testi di Llegarás">testi</a><br>
<b>7</b>. Su Tal Vez, Su Quizá - <a target="_blank" href="http://www.google.com/search?q=spartiti+Su+Tal+Vez%2C+Su+Quiz%E1+Nek" title="Spartiti di Su Tal Vez, Su Quizá">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Su+Tal+Vez%2C+Su+Quiz%E1+Nek" title="Accordi di Su Tal Vez, Su Quizá">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Su+Tal+Vez%2C+Su+Quiz%E1+Nek" title="Testi di Su Tal Vez, Su Quizá">testi</a><br>
<b>8</b>. Los Secretos De Tu Intimidad - <a target="_blank" href="http://www.google.com/search?q=spartiti+Los+Secretos+De+Tu+Intimidad+Nek" title="Spartiti di Los Secretos De Tu Intimidad">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Los+Secretos+De+Tu+Intimidad+Nek" title="Accordi di Los Secretos De Tu Intimidad">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Los+Secretos+De+Tu+Intimidad+Nek" title="Testi di Los Secretos De Tu Intimidad">testi</a><br>
<b>9</b>. Entre Los Dos - <a target="_blank" href="http://www.google.com/search?q=spartiti+Entre+Los+Dos+Nek" title="Spartiti di Entre Los Dos">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Entre+Los+Dos+Nek" title="Accordi di Entre Los Dos">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Entre+Los+Dos+Nek" title="Testi di Entre Los Dos">testi</a><br>
<b>10</b>. El Mundo Está Llamándome - <a target="_blank" href="http://www.google.com/search?q=spartiti+El+Mundo+Est%E1+Llam%E1ndome+Nek" title="Spartiti di El Mundo Está Llamándome">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+El+Mundo+Est%E1+Llam%E1ndome+Nek" title="Accordi di El Mundo Está Llamándome">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+El+Mundo+Est%E1+Llam%E1ndome+Nek" title="Testi di El Mundo Está Llamándome">testi</a><br>
<b>11</b>. Una Dosis De Tí - <a target="_blank" href="http://www.google.com/search?q=spartiti+Una+Dosis+De+T%ED+Nek" title="Spartiti di Una Dosis De Tí">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Una+Dosis+De+T%ED+Nek" title="Accordi di Una Dosis De Tí">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Una+Dosis+De+T%ED+Nek" title="Testi di Una Dosis De Tí">testi</a><br>
<b>12</b>. Como Te Mueves - <a target="_blank" href="http://www.google.com/search?q=spartiti+Como+Te+Mueves+Nek" title="Spartiti di Como Te Mueves">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Como+Te+Mueves+Nek" title="Accordi di Como Te Mueves">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Como+Te+Mueves+Nek" title="Testi di Como Te Mueves">testi</a><br>
<b>13</b>. ...Nunca Estás Lejos - <a target="_blank" href="http://www.google.com/search?q=spartiti+...Nunca+Est%E1s+Lejos+Nek" title="Spartiti di ...Nunca Estás Lejos">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+...Nunca+Est%E1s+Lejos+Nek" title="Accordi di ...Nunca Estás Lejos">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+...Nunca+Est%E1s+Lejos+Nek" title="Testi di ...Nunca Estás Lejos">testi</a><br>
<h2>In Due (1998) </h2>
<b>1</b>. Se Io Non Avessi Te - <a target="_blank" href="http://www.google.com/search?q=spartiti+Se+Io+Non+Avessi+Te+Nek" title="Spartiti di Se Io Non Avessi Te">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Se+Io+Non+Avessi+Te+Nek" title="Accordi di Se Io Non Avessi Te">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Se+Io+Non+Avessi+Te+Nek" title="Testi di Se Io Non Avessi Te">testi</a><br>
<b>2</b>. Sto Con Te - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sto+Con+Te+Nek" title="Spartiti di Sto Con Te">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sto+Con+Te+Nek" title="Accordi di Sto Con Te">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sto+Con+Te+Nek" title="Testi di Sto Con Te">testi</a><br>
<b>3</b>. Noi Due - <a target="_blank" href="http://www.google.com/search?q=spartiti+Noi+Due+Nek" title="Spartiti di Noi Due">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Noi+Due+Nek" title="Accordi di Noi Due">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Noi+Due+Nek" title="Testi di Noi Due">testi</a><br>
<b>4</b>. Se Una Regola C'è - <a target="_blank" href="http://www.google.com/search?q=spartiti+Se+Una+Regola+C%27%E8+Nek" title="Spartiti di Se Una Regola C'è">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Se+Una+Regola+C%27%E8+Nek" title="Accordi di Se Una Regola C'è">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Se+Una+Regola+C%27%E8+Nek" title="Testi di Se Una Regola C'è">testi</a><br>
<b>5</b>. Ho In Testa Te - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ho+In+Testa+Te+Nek" title="Spartiti di Ho In Testa Te">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ho+In+Testa+Te+Nek" title="Accordi di Ho In Testa Te">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ho+In+Testa+Te+Nek" title="Testi di Ho In Testa Te">testi</a><br>
<b>6</b>. Giusto O No - <a target="_blank" href="http://www.google.com/search?q=spartiti+Giusto+O+No+Nek" title="Spartiti di Giusto O No">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Giusto+O+No+Nek" title="Accordi di Giusto O No">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Giusto+O+No+Nek" title="Testi di Giusto O No">testi</a><br>
<b>7</b>. Con Un Ma E Con Un Se - <a target="_blank" href="http://www.google.com/search?q=spartiti+Con+Un+Ma+E+Con+Un+Se+Nek" title="Spartiti di Con Un Ma E Con Un Se">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Con+Un+Ma+E+Con+Un+Se+Nek" title="Accordi di Con Un Ma E Con Un Se">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Con+Un+Ma+E+Con+Un+Se+Nek" title="Testi di Con Un Ma E Con Un Se">testi</a><br>
<b>8</b>. Basta Uno Sguardo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Basta+Uno+Sguardo+Nek" title="Spartiti di Basta Uno Sguardo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Basta+Uno+Sguardo+Nek" title="Accordi di Basta Uno Sguardo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Basta+Uno+Sguardo+Nek" title="Testi di Basta Uno Sguardo">testi</a><br>
<b>9</b>. Se Vuoi Se Puoi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Se+Vuoi+Se+Puoi+Nek" title="Spartiti di Se Vuoi Se Puoi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Se+Vuoi+Se+Puoi+Nek" title="Accordi di Se Vuoi Se Puoi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Se+Vuoi+Se+Puoi+Nek" title="Testi di Se Vuoi Se Puoi">testi</a><br>
<b>10</b>. C'è Tutto Un Mondo - <a target="_blank" href="http://www.google.com/search?q=spartiti+C%27%E8+Tutto+Un+Mondo+Nek" title="Spartiti di C'è Tutto Un Mondo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+C%27%E8+Tutto+Un+Mondo+Nek" title="Accordi di C'è Tutto Un Mondo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+C%27%E8+Tutto+Un+Mondo+Nek" title="Testi di C'è Tutto Un Mondo">testi</a><br>
<b>11</b>. Una Dose Di Te - <a target="_blank" href="http://www.google.com/search?q=spartiti+Una+Dose+Di+Te+Nek" title="Spartiti di Una Dose Di Te">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Una+Dose+Di+Te+Nek" title="Accordi di Una Dose Di Te">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Una+Dose+Di+Te+Nek" title="Testi di Una Dose Di Te">testi</a><br>
<b>12</b>. Le Vibrazioni Di Una Donna - <a target="_blank" href="http://www.google.com/search?q=spartiti+Le+Vibrazioni+Di+Una+Donna+Nek" title="Spartiti di Le Vibrazioni Di Una Donna">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Le+Vibrazioni+Di+Una+Donna+Nek" title="Accordi di Le Vibrazioni Di Una Donna">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Le+Vibrazioni+Di+Una+Donna+Nek" title="Testi di Le Vibrazioni Di Una Donna">testi</a><br>
<b>13</b>. Nemmeno Un Secondo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Nemmeno+Un+Secondo+Nek" title="Spartiti di Nemmeno Un Secondo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Nemmeno+Un+Secondo+Nek" title="Accordi di Nemmeno Un Secondo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Nemmeno+Un+Secondo+Nek" title="Testi di Nemmeno Un Secondo">testi</a><br>
<b>14</b>. "...Non Sei Mai Lontano" - <a target="_blank" href="http://www.google.com/search?q=spartiti+%22...Non+Sei+Mai+Lontano%22+Nek" title="Spartiti di "...Non Sei Mai Lontano"">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+%22...Non+Sei+Mai+Lontano%22+Nek" title="Accordi di "...Non Sei Mai Lontano"">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+%22...Non+Sei+Mai+Lontano%22+Nek" title="Testi di "...Non Sei Mai Lontano"">testi</a><br>
<h2>Nek (Espana) (1996) </h2>
<b>1</b>. Laura No Està - <a target="_blank" href="http://www.google.com/search?q=spartiti+Laura+No+Est%E0+Nek" title="Spartiti di Laura No Està">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Laura+No+Est%E0+Nek" title="Accordi di Laura No Està">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Laura+No+Est%E0+Nek" title="Testi di Laura No Està">testi</a><br>
<b>2</b>. Tu Nombre - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tu+Nombre+Nek" title="Spartiti di Tu Nombre">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tu+Nombre+Nek" title="Accordi di Tu Nombre">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tu+Nombre+Nek" title="Testi di Tu Nombre">testi</a><br>
<b>3</b>. Espérame - <a target="_blank" href="http://www.google.com/search?q=spartiti+Esp%E9rame+Nek" title="Spartiti di Espérame">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Esp%E9rame+Nek" title="Accordi di Espérame">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Esp%E9rame+Nek" title="Testi di Espérame">testi</a><br>
<b>4</b>. Tú Estás Aquí - <a target="_blank" href="http://www.google.com/search?q=spartiti+T%FA+Est%E1s+Aqu%ED+Nek" title="Spartiti di Tú Estás Aquí">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+T%FA+Est%E1s+Aqu%ED+Nek" title="Accordi di Tú Estás Aquí">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+T%FA+Est%E1s+Aqu%ED+Nek" title="Testi di Tú Estás Aquí">testi</a><br>
<b>5</b>. Tu - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tu+Nek" title="Spartiti di Tu">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tu+Nek" title="Accordi di Tu">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tu+Nek" title="Testi di Tu">testi</a><br>
<b>6</b>. Dime Porqué - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dime+Porqu%E9+Nek" title="Spartiti di Dime Porqué">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dime+Porqu%E9+Nek" title="Accordi di Dime Porqué">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dime+Porqu%E9+Nek" title="Testi di Dime Porqué">testi</a><br>
<b>7</b>. Cómo Vivir Sin Ti - <a target="_blank" href="http://www.google.com/search?q=spartiti+C%F3mo+Vivir+Sin+Ti+Nek" title="Spartiti di Cómo Vivir Sin Ti">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+C%F3mo+Vivir+Sin+Ti+Nek" title="Accordi di Cómo Vivir Sin Ti">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+C%F3mo+Vivir+Sin+Ti+Nek" title="Testi di Cómo Vivir Sin Ti">testi</a><br>
<b>8</b>. Nada Como Vivir - <a target="_blank" href="http://www.google.com/search?q=spartiti+Nada+Como+Vivir+Nek" title="Spartiti di Nada Como Vivir">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Nada+Como+Vivir+Nek" title="Accordi di Nada Como Vivir">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Nada+Como+Vivir+Nek" title="Testi di Nada Como Vivir">testi</a><br>
<b>9</b>. Queda Mucho Más - <a target="_blank" href="http://www.google.com/search?q=spartiti+Queda+Mucho+M%E1s+Nek" title="Spartiti di Queda Mucho Más">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Queda+Mucho+M%E1s+Nek" title="Accordi di Queda Mucho Más">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Queda+Mucho+M%E1s+Nek" title="Testi di Queda Mucho Más">testi</a><br>
<b>10</b>. Seguimos Juntos - <a target="_blank" href="http://www.google.com/search?q=spartiti+Seguimos+Juntos+Nek" title="Spartiti di Seguimos Juntos">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Seguimos+Juntos+Nek" title="Accordi di Seguimos Juntos">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Seguimos+Juntos+Nek" title="Testi di Seguimos Juntos">testi</a><br>
<b>11</b>. Laura No Està - Raio Vocal Version - <a target="_blank" href="http://www.google.com/search?q=spartiti+Laura+No+Est%E0+-+Raio+Vocal+Version+Nek" title="Spartiti di Laura No Està - Raio Vocal Version">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Laura+No+Est%E0+-+Raio+Vocal+Version+Nek" title="Accordi di Laura No Està - Raio Vocal Version">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Laura+No+Est%E0+-+Raio+Vocal+Version+Nek" title="Testi di Laura No Està - Raio Vocal Version">testi</a><br>
<h2>Lei, Gli Amici E Tutto Il Resto (1996) </h2>
<b>1</b>. Laura Non C'è - <a target="_blank" href="http://www.google.com/search?q=spartiti+Laura+Non+C%27%E8+Nek" title="Spartiti di Laura Non C'è">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Laura+Non+C%27%E8+Nek" title="Accordi di Laura Non C'è">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Laura+Non+C%27%E8+Nek" title="Testi di Laura Non C'è">testi</a><br>
<b>2</b>. Sei Grande - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sei+Grande+Nek" title="Spartiti di Sei Grande">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sei+Grande+Nek" title="Accordi di Sei Grande">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sei+Grande+Nek" title="Testi di Sei Grande">testi</a><br>
<b>3</b>. Restiamo Qui - <a target="_blank" href="http://www.google.com/search?q=spartiti+Restiamo+Qui+Nek" title="Spartiti di Restiamo Qui">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Restiamo+Qui+Nek" title="Accordi di Restiamo Qui">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Restiamo+Qui+Nek" title="Testi di Restiamo Qui">testi</a><br>
<b>4</b>. Vivere Senza Te - <a target="_blank" href="http://www.google.com/search?q=spartiti+Vivere+Senza+Te+Nek" title="Spartiti di Vivere Senza Te">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Vivere+Senza+Te+Nek" title="Accordi di Vivere Senza Te">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Vivere+Senza+Te+Nek" title="Testi di Vivere Senza Te">testi</a><br>
<b>5</b>. Tu Sei, Tu Sai - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tu+Sei%2C+Tu+Sai+Nek" title="Spartiti di Tu Sei, Tu Sai">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tu+Sei%2C+Tu+Sai+Nek" title="Accordi di Tu Sei, Tu Sai">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tu+Sei%2C+Tu+Sai+Nek" title="Testi di Tu Sei, Tu Sai">testi</a><br>
<b>6</b>. Sei - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sei+Nek" title="Spartiti di Sei">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sei+Nek" title="Accordi di Sei">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sei+Nek" title="Testi di Sei">testi</a><br>
<b>7</b>. Dimmi Cos'è - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dimmi+Cos%27%E8+Nek" title="Spartiti di Dimmi Cos'è">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dimmi+Cos%27%E8+Nek" title="Accordi di Dimmi Cos'è">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dimmi+Cos%27%E8+Nek" title="Testi di Dimmi Cos'è">testi</a><br>
<b>8</b>. Vai Sola - <a target="_blank" href="http://www.google.com/search?q=spartiti+Vai+Sola+Nek" title="Spartiti di Vai Sola">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Vai+Sola+Nek" title="Accordi di Vai Sola">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Vai+Sola+Nek" title="Testi di Vai Sola">testi</a><br>
<b>9</b>. Solo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Solo+Nek" title="Spartiti di Solo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Solo+Nek" title="Accordi di Solo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Solo+Nek" title="Testi di Solo">testi</a><br>
<b>10</b>. E Non Mi Dire Che Ho Bevuto - <a target="_blank" href="http://www.google.com/search?q=spartiti+E+Non+Mi+Dire+Che+Ho+Bevuto+Nek" title="Spartiti di E Non Mi Dire Che Ho Bevuto">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+E+Non+Mi+Dire+Che+Ho+Bevuto+Nek" title="Accordi di E Non Mi Dire Che Ho Bevuto">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+E+Non+Mi+Dire+Che+Ho+Bevuto+Nek" title="Testi di E Non Mi Dire Che Ho Bevuto">testi</a><br>
<b>11</b>. Nati Per Vivere - <a target="_blank" href="http://www.google.com/search?q=spartiti+Nati+Per+Vivere+Nek" title="Spartiti di Nati Per Vivere">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Nati+Per+Vivere+Nek" title="Accordi di Nati Per Vivere">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Nati+Per+Vivere+Nek" title="Testi di Nati Per Vivere">testi</a><br>
<b>12</b>. Andare, Partire, Tornare - <a target="_blank" href="http://www.google.com/search?q=spartiti+Andare%2C+Partire%2C+Tornare+Nek" title="Spartiti di Andare, Partire, Tornare">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Andare%2C+Partire%2C+Tornare+Nek" title="Accordi di Andare, Partire, Tornare">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Andare%2C+Partire%2C+Tornare+Nek" title="Testi di Andare, Partire, Tornare">testi</a><br>
<b>13</b>. Di Più - <a target="_blank" href="http://www.google.com/search?q=spartiti+Di+Pi%F9+Nek" title="Spartiti di Di Più">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Di+Pi%F9+Nek" title="Accordi di Di Più">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Di+Pi%F9+Nek" title="Testi di Di Più">testi</a><br>
<b>14</b>. Fianco A Fianco - <a target="_blank" href="http://www.google.com/search?q=spartiti+Fianco+A+Fianco+Nek" title="Spartiti di Fianco A Fianco">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Fianco+A+Fianco+Nek" title="Accordi di Fianco A Fianco">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Fianco+A+Fianco+Nek" title="Testi di Fianco A Fianco">testi</a><br>
<h2>Calore Umano (1994) </h2>
<b>1</b>. Calore Umano - <a target="_blank" href="http://www.google.com/search?q=spartiti+Calore+Umano+Nek" title="Spartiti di Calore Umano">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Calore+Umano+Nek" title="Accordi di Calore Umano">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Calore+Umano+Nek" title="Testi di Calore Umano">testi</a><br>
<b>2</b>. Voglia Di Te - <a target="_blank" href="http://www.google.com/search?q=spartiti+Voglia+Di+Te+Nek" title="Spartiti di Voglia Di Te">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Voglia+Di+Te+Nek" title="Accordi di Voglia Di Te">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Voglia+Di+Te+Nek" title="Testi di Voglia Di Te">testi</a><br>
<b>3</b>. Cuori In Tempesta - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cuori+In+Tempesta+Nek" title="Spartiti di Cuori In Tempesta">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cuori+In+Tempesta+Nek" title="Accordi di Cuori In Tempesta">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cuori+In+Tempesta+Nek" title="Testi di Cuori In Tempesta">testi</a><br>
<b>4</b>. Ragazze Della 5a B - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ragazze+Della+5a+B+Nek" title="Spartiti di Ragazze Della 5a B">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ragazze+Della+5a+B+Nek" title="Accordi di Ragazze Della 5a B">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ragazze+Della+5a+B+Nek" title="Testi di Ragazze Della 5a B">testi</a><br>
<b>5</b>. L'Amore C'è - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%27Amore+C%27%E8+Nek" title="Spartiti di L'Amore C'è">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%27Amore+C%27%E8+Nek" title="Accordi di L'Amore C'è">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%27Amore+C%27%E8+Nek" title="Testi di L'Amore C'è">testi</a><br>
<b>6</b>. Però Vorrei Ci Fosse Amore - <a target="_blank" href="http://www.google.com/search?q=spartiti+Per%F2+Vorrei+Ci+Fosse+Amore+Nek" title="Spartiti di Però Vorrei Ci Fosse Amore">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Per%F2+Vorrei+Ci+Fosse+Amore+Nek" title="Accordi di Però Vorrei Ci Fosse Amore">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Per%F2+Vorrei+Ci+Fosse+Amore+Nek" title="Testi di Però Vorrei Ci Fosse Amore">testi</a><br>
<b>7</b>. Paese Turchese - <a target="_blank" href="http://www.google.com/search?q=spartiti+Paese+Turchese+Nek" title="Spartiti di Paese Turchese">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Paese+Turchese+Nek" title="Accordi di Paese Turchese">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Paese+Turchese+Nek" title="Testi di Paese Turchese">testi</a><br>
<b>8</b>. Facciamo Un Week-End - <a target="_blank" href="http://www.google.com/search?q=spartiti+Facciamo+Un+Week-End+Nek" title="Spartiti di Facciamo Un Week-End">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Facciamo+Un+Week-End+Nek" title="Accordi di Facciamo Un Week-End">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Facciamo+Un+Week-End+Nek" title="Testi di Facciamo Un Week-End">testi</a><br>
<b>9</b>. Quando Sarò Lontano - <a target="_blank" href="http://www.google.com/search?q=spartiti+Quando+Sar%F2+Lontano+Nek" title="Spartiti di Quando Sarò Lontano">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Quando+Sar%F2+Lontano+Nek" title="Accordi di Quando Sarò Lontano">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Quando+Sar%F2+Lontano+Nek" title="Testi di Quando Sarò Lontano">testi</a><br>
<b>10</b>. Angeli Nel Ghetto - <a target="_blank" href="http://www.google.com/search?q=spartiti+Angeli+Nel+Ghetto+Nek" title="Spartiti di Angeli Nel Ghetto">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Angeli+Nel+Ghetto+Nek" title="Accordi di Angeli Nel Ghetto">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Angeli+Nel+Ghetto+Nek" title="Testi di Angeli Nel Ghetto">testi</a><br>
<h2>In Te (1993) </h2>
<b>1</b>. Uomo Con Te - <a target="_blank" href="http://www.google.com/search?q=spartiti+Uomo+Con+Te+Nek" title="Spartiti di Uomo Con Te">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Uomo+Con+Te+Nek" title="Accordi di Uomo Con Te">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Uomo+Con+Te+Nek" title="Testi di Uomo Con Te">testi</a><br>
<b>2</b>. Il Muro Di Berlino C'è - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Muro+Di+Berlino+C%27%E8+Nek" title="Spartiti di Il Muro Di Berlino C'è">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Muro+Di+Berlino+C%27%E8+Nek" title="Accordi di Il Muro Di Berlino C'è">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Muro+Di+Berlino+C%27%E8+Nek" title="Testi di Il Muro Di Berlino C'è">testi</a><br>
<b>3</b>. In Te - <a target="_blank" href="http://www.google.com/search?q=spartiti+In+Te+Nek" title="Spartiti di In Te">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+In+Te+Nek" title="Accordi di In Te">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+In+Te+Nek" title="Testi di In Te">testi</a><br>
<b>4</b>. 2 Come Noi - <a target="_blank" href="http://www.google.com/search?q=spartiti+2+Come+Noi+Nek" title="Spartiti di 2 Come Noi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+2+Come+Noi+Nek" title="Accordi di 2 Come Noi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+2+Come+Noi+Nek" title="Testi di 2 Come Noi">testi</a><br>
<b>5</b>. Jane - <a target="_blank" href="http://www.google.com/search?q=spartiti+Jane+Nek" title="Spartiti di Jane">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Jane+Nek" title="Accordi di Jane">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Jane+Nek" title="Testi di Jane">testi</a><br>
<b>6</b>. Amami - <a target="_blank" href="http://www.google.com/search?q=spartiti+Amami+Nek" title="Spartiti di Amami">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Amami+Nek" title="Accordi di Amami">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Amami+Nek" title="Testi di Amami">testi</a><br>
<b>7</b>. Figli Di Chi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Figli+Di+Chi+Nek" title="Spartiti di Figli Di Chi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Figli+Di+Chi+Nek" title="Accordi di Figli Di Chi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Figli+Di+Chi+Nek" title="Testi di Figli Di Chi">testi</a><br>
<b>8</b>. Rimani Qui - <a target="_blank" href="http://www.google.com/search?q=spartiti+Rimani+Qui+Nek" title="Spartiti di Rimani Qui">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Rimani+Qui+Nek" title="Accordi di Rimani Qui">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Rimani+Qui+Nek" title="Testi di Rimani Qui">testi</a><br>
<b>9</b>. Amico Mio - <a target="_blank" href="http://www.google.com/search?q=spartiti+Amico+Mio+Nek" title="Spartiti di Amico Mio">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Amico+Mio+Nek" title="Accordi di Amico Mio">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Amico+Mio+Nek" title="Testi di Amico Mio">testi</a><br>
<h2>Nek (1992) </h2>
<b>1</b>. Amico Mio - <a target="_blank" href="http://www.google.com/search?q=spartiti+Amico+Mio+Nek" title="Spartiti di Amico Mio">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Amico+Mio+Nek" title="Accordi di Amico Mio">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Amico+Mio+Nek" title="Testi di Amico Mio">testi</a><br>
<b>2</b>. Sogni Miei - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sogni+Miei+Nek" title="Spartiti di Sogni Miei">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sogni+Miei+Nek" title="Accordi di Sogni Miei">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sogni+Miei+Nek" title="Testi di Sogni Miei">testi</a><br>
<b>3</b>. Amami - <a target="_blank" href="http://www.google.com/search?q=spartiti+Amami+Nek" title="Spartiti di Amami">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Amami+Nek" title="Accordi di Amami">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Amami+Nek" title="Testi di Amami">testi</a><br>
<b>4</b>. Rimani Qui - <a target="_blank" href="http://www.google.com/search?q=spartiti+Rimani+Qui+Nek" title="Spartiti di Rimani Qui">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Rimani+Qui+Nek" title="Accordi di Rimani Qui">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Rimani+Qui+Nek" title="Testi di Rimani Qui">testi</a><br>
<b>5</b>. Reggae Rock - <a target="_blank" href="http://www.google.com/search?q=spartiti+Reggae+Rock+Nek" title="Spartiti di Reggae Rock">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Reggae+Rock+Nek" title="Accordi di Reggae Rock">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Reggae+Rock+Nek" title="Testi di Reggae Rock">testi</a><br>
<b>6</b>. Uomini Fragili - <a target="_blank" href="http://www.google.com/search?q=spartiti+Uomini+Fragili+Nek" title="Spartiti di Uomini Fragili">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Uomini+Fragili+Nek" title="Accordi di Uomini Fragili">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Uomini+Fragili+Nek" title="Testi di Uomini Fragili">testi</a><br>
<b>7</b>. Valery - <a target="_blank" href="http://www.google.com/search?q=spartiti+Valery+Nek" title="Spartiti di Valery">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Valery+Nek" title="Accordi di Valery">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Valery+Nek" title="Testi di Valery">testi</a><br>
<b>8</b>. Il Monte - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Monte+Nek" title="Spartiti di Il Monte">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Monte+Nek" title="Accordi di Il Monte">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Monte+Nek" title="Testi di Il Monte">testi</a><br>
<b>9</b>. Manager - <a target="_blank" href="http://www.google.com/search?q=spartiti+Manager+Nek" title="Spartiti di Manager">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Manager+Nek" title="Accordi di Manager">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Manager+Nek" title="Testi di Manager">testi</a><br>
<b>10</b>. Stai Con Me - <a target="_blank" href="http://www.google.com/search?q=spartiti+Stai+Con+Me+Nek" title="Spartiti di Stai Con Me">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Stai+Con+Me+Nek" title="Accordi di Stai Con Me">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Stai+Con+Me+Nek" title="Testi di Stai Con Me">testi</a><br>
<h2><a href="<?php echo "$base_website_address/$spartiti_dir" ?>/index.html" title="Trova accordi, spartiti, tablature e testi di tantissimi artisti">Torna all'indice degli artisti</a></h2>
