<!--
title: Trova spartiti per chitarra, accordi, testi e tablature di Green Day. Discografia Green Day.
description: Trova tutti gli spartiti, accordi, testi e tablature di Green Day. Discografia Green Day.
keywords: Discografia, Green Day, spartiti, accordi, testi, tablature
template: tablature
-->
<h1>Trova spartiti per chitarra, accordi, testi e tablature di Green Day</h1><h2>Leggere gli spartiti per chitarra, gli accordi e le tablature:</h2>
<?php require("tabdescription.php"); ?>
<?php require("adsense_leaderboard.php"); ?>
<h2>Discografia Green Day:</h2>
<h2>American Idiot (2004) </h2>
<b>1</b>. American Idiot - <a target="_blank" href="http://www.google.com/search?q=spartiti+American+Idiot+Green+Day" title="Spartiti di American Idiot">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+American+Idiot+Green+Day" title="Accordi di American Idiot">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+American+Idiot+Green+Day" title="Testi di American Idiot">testi</a><br>
<b>2</b>. Jesus Of Suburbia - <a target="_blank" href="http://www.google.com/search?q=spartiti+Jesus+Of+Suburbia+Green+Day" title="Spartiti di Jesus Of Suburbia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Jesus+Of+Suburbia+Green+Day" title="Accordi di Jesus Of Suburbia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Jesus+Of+Suburbia+Green+Day" title="Testi di Jesus Of Suburbia">testi</a><br>
<b>3</b>. Holiday - <a target="_blank" href="http://www.google.com/search?q=spartiti+Holiday+Green+Day" title="Spartiti di Holiday">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Holiday+Green+Day" title="Accordi di Holiday">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Holiday+Green+Day" title="Testi di Holiday">testi</a><br>
<b>4</b>. Boulevard Of Broken Dreams - <a target="_blank" href="http://www.google.com/search?q=spartiti+Boulevard+Of+Broken+Dreams+Green+Day" title="Spartiti di Boulevard Of Broken Dreams">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Boulevard+Of+Broken+Dreams+Green+Day" title="Accordi di Boulevard Of Broken Dreams">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Boulevard+Of+Broken+Dreams+Green+Day" title="Testi di Boulevard Of Broken Dreams">testi</a><br>
<b>5</b>. Are We The Waiting - <a target="_blank" href="http://www.google.com/search?q=spartiti+Are+We+The+Waiting+Green+Day" title="Spartiti di Are We The Waiting">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Are+We+The+Waiting+Green+Day" title="Accordi di Are We The Waiting">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Are+We+The+Waiting+Green+Day" title="Testi di Are We The Waiting">testi</a><br>
<b>6</b>. St. Jimmy - <a target="_blank" href="http://www.google.com/search?q=spartiti+St.+Jimmy+Green+Day" title="Spartiti di St. Jimmy">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+St.+Jimmy+Green+Day" title="Accordi di St. Jimmy">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+St.+Jimmy+Green+Day" title="Testi di St. Jimmy">testi</a><br>
<b>7</b>. Give Me Novocaine - <a target="_blank" href="http://www.google.com/search?q=spartiti+Give+Me+Novocaine+Green+Day" title="Spartiti di Give Me Novocaine">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Give+Me+Novocaine+Green+Day" title="Accordi di Give Me Novocaine">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Give+Me+Novocaine+Green+Day" title="Testi di Give Me Novocaine">testi</a><br>
<b>8</b>. She's A Rebel - <a target="_blank" href="http://www.google.com/search?q=spartiti+She%27s+A+Rebel+Green+Day" title="Spartiti di She's A Rebel">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+She%27s+A+Rebel+Green+Day" title="Accordi di She's A Rebel">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+She%27s+A+Rebel+Green+Day" title="Testi di She's A Rebel">testi</a><br>
<b>9</b>. Extraordinary Girl - <a target="_blank" href="http://www.google.com/search?q=spartiti+Extraordinary+Girl+Green+Day" title="Spartiti di Extraordinary Girl">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Extraordinary+Girl+Green+Day" title="Accordi di Extraordinary Girl">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Extraordinary+Girl+Green+Day" title="Testi di Extraordinary Girl">testi</a><br>
<b>10</b>. Letterbomb - <a target="_blank" href="http://www.google.com/search?q=spartiti+Letterbomb+Green+Day" title="Spartiti di Letterbomb">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Letterbomb+Green+Day" title="Accordi di Letterbomb">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Letterbomb+Green+Day" title="Testi di Letterbomb">testi</a><br>
<b>11</b>. Wake Me Up When September Ends - <a target="_blank" href="http://www.google.com/search?q=spartiti+Wake+Me+Up+When+September+Ends+Green+Day" title="Spartiti di Wake Me Up When September Ends">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Wake+Me+Up+When+September+Ends+Green+Day" title="Accordi di Wake Me Up When September Ends">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Wake+Me+Up+When+September+Ends+Green+Day" title="Testi di Wake Me Up When September Ends">testi</a><br>
<b>12</b>. Homecoming - <a target="_blank" href="http://www.google.com/search?q=spartiti+Homecoming+Green+Day" title="Spartiti di Homecoming">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Homecoming+Green+Day" title="Accordi di Homecoming">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Homecoming+Green+Day" title="Testi di Homecoming">testi</a><br>
<b>13</b>. Whatsername - <a target="_blank" href="http://www.google.com/search?q=spartiti+Whatsername+Green+Day" title="Spartiti di Whatsername">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Whatsername+Green+Day" title="Accordi di Whatsername">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Whatsername+Green+Day" title="Testi di Whatsername">testi</a><br>
<h2>Shenanigans (2002) </h2>
<b>1</b>. Suffocate - <a target="_blank" href="http://www.google.com/search?q=spartiti+Suffocate+Green+Day" title="Spartiti di Suffocate">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Suffocate+Green+Day" title="Accordi di Suffocate">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Suffocate+Green+Day" title="Testi di Suffocate">testi</a><br>
<b>2</b>. Desensitized - <a target="_blank" href="http://www.google.com/search?q=spartiti+Desensitized+Green+Day" title="Spartiti di Desensitized">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Desensitized+Green+Day" title="Accordi di Desensitized">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Desensitized+Green+Day" title="Testi di Desensitized">testi</a><br>
<b>3</b>. You Lied - <a target="_blank" href="http://www.google.com/search?q=spartiti+You+Lied+Green+Day" title="Spartiti di You Lied">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+You+Lied+Green+Day" title="Accordi di You Lied">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+You+Lied+Green+Day" title="Testi di You Lied">testi</a><br>
<b>4</b>. Outsider - <a target="_blank" href="http://www.google.com/search?q=spartiti+Outsider+Green+Day" title="Spartiti di Outsider">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Outsider+Green+Day" title="Accordi di Outsider">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Outsider+Green+Day" title="Testi di Outsider">testi</a><br>
<b>5</b>. Don't Wanna Fall In Love - <a target="_blank" href="http://www.google.com/search?q=spartiti+Don%27t+Wanna+Fall+In+Love+Green+Day" title="Spartiti di Don't Wanna Fall In Love">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Don%27t+Wanna+Fall+In+Love+Green+Day" title="Accordi di Don't Wanna Fall In Love">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Don%27t+Wanna+Fall+In+Love+Green+Day" title="Testi di Don't Wanna Fall In Love">testi</a><br>
<b>6</b>. Scumbag - <a target="_blank" href="http://www.google.com/search?q=spartiti+Scumbag+Green+Day" title="Spartiti di Scumbag">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Scumbag+Green+Day" title="Accordi di Scumbag">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Scumbag+Green+Day" title="Testi di Scumbag">testi</a><br>
<b>7</b>. I Want To Be On TV - <a target="_blank" href="http://www.google.com/search?q=spartiti+I+Want+To+Be+On+TV+Green+Day" title="Spartiti di I Want To Be On TV">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+I+Want+To+Be+On+TV+Green+Day" title="Accordi di I Want To Be On TV">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+I+Want+To+Be+On+TV+Green+Day" title="Testi di I Want To Be On TV">testi</a><br>
<b>8</b>. Tired Of Waiting - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tired+Of+Waiting+Green+Day" title="Spartiti di Tired Of Waiting">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tired+Of+Waiting+Green+Day" title="Accordi di Tired Of Waiting">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tired+Of+Waiting+Green+Day" title="Testi di Tired Of Waiting">testi</a><br>
<b>9</b>. Sick Of Me - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sick+Of+Me+Green+Day" title="Spartiti di Sick Of Me">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sick+Of+Me+Green+Day" title="Accordi di Sick Of Me">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sick+Of+Me+Green+Day" title="Testi di Sick Of Me">testi</a><br>
<b>10</b>. Rotting - <a target="_blank" href="http://www.google.com/search?q=spartiti+Rotting+Green+Day" title="Spartiti di Rotting">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Rotting+Green+Day" title="Accordi di Rotting">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Rotting+Green+Day" title="Testi di Rotting">testi</a><br>
<b>11</b>. Do Da Da - <a target="_blank" href="http://www.google.com/search?q=spartiti+Do+Da+Da+Green+Day" title="Spartiti di Do Da Da">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Do+Da+Da+Green+Day" title="Accordi di Do Da Da">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Do+Da+Da+Green+Day" title="Testi di Do Da Da">testi</a><br>
<b>12</b>. On The Wagon - <a target="_blank" href="http://www.google.com/search?q=spartiti+On+The+Wagon+Green+Day" title="Spartiti di On The Wagon">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+On+The+Wagon+Green+Day" title="Accordi di On The Wagon">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+On+The+Wagon+Green+Day" title="Testi di On The Wagon">testi</a><br>
<b>13</b>. Ha Ha You're Dead - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ha+Ha+You%27re+Dead+Green+Day" title="Spartiti di Ha Ha You're Dead">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ha+Ha+You%27re+Dead+Green+Day" title="Accordi di Ha Ha You're Dead">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ha+Ha+You%27re+Dead+Green+Day" title="Testi di Ha Ha You're Dead">testi</a><br>
<b>14</b>. Espionage - <a target="_blank" href="http://www.google.com/search?q=spartiti+Espionage+Green+Day" title="Spartiti di Espionage">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Espionage+Green+Day" title="Accordi di Espionage">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Espionage+Green+Day" title="Testi di Espionage">testi</a><br>
<h2>International Superhits! (2001) </h2>
<b>1</b>. Maria - <a target="_blank" href="http://www.google.com/search?q=spartiti+Maria+Green+Day" title="Spartiti di Maria">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Maria+Green+Day" title="Accordi di Maria">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Maria+Green+Day" title="Testi di Maria">testi</a><br>
<b>2</b>. Poprocks & Coke - <a target="_blank" href="http://www.google.com/search?q=spartiti+Poprocks+%26+Coke+Green+Day" title="Spartiti di Poprocks & Coke">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Poprocks+%26+Coke+Green+Day" title="Accordi di Poprocks & Coke">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Poprocks+%26+Coke+Green+Day" title="Testi di Poprocks & Coke">testi</a><br>
<b>3</b>. Longview - <a target="_blank" href="http://www.google.com/search?q=spartiti+Longview+Green+Day" title="Spartiti di Longview">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Longview+Green+Day" title="Accordi di Longview">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Longview+Green+Day" title="Testi di Longview">testi</a><br>
<b>4</b>. Welcome To Paradise - <a target="_blank" href="http://www.google.com/search?q=spartiti+Welcome+To+Paradise+Green+Day" title="Spartiti di Welcome To Paradise">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Welcome+To+Paradise+Green+Day" title="Accordi di Welcome To Paradise">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Welcome+To+Paradise+Green+Day" title="Testi di Welcome To Paradise">testi</a><br>
<b>5</b>. Basket Case - <a target="_blank" href="http://www.google.com/search?q=spartiti+Basket+Case+Green+Day" title="Spartiti di Basket Case">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Basket+Case+Green+Day" title="Accordi di Basket Case">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Basket+Case+Green+Day" title="Testi di Basket Case">testi</a><br>
<b>6</b>. When I Come Around - <a target="_blank" href="http://www.google.com/search?q=spartiti+When+I+Come+Around+Green+Day" title="Spartiti di When I Come Around">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+When+I+Come+Around+Green+Day" title="Accordi di When I Come Around">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+When+I+Come+Around+Green+Day" title="Testi di When I Come Around">testi</a><br>
<b>7</b>. She - <a target="_blank" href="http://www.google.com/search?q=spartiti+She+Green+Day" title="Spartiti di She">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+She+Green+Day" title="Accordi di She">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+She+Green+Day" title="Testi di She">testi</a><br>
<b>8</b>. J.A.R. (Jason Andrew Relva) - <a target="_blank" href="http://www.google.com/search?q=spartiti+J.A.R.+%28Jason+Andrew+Relva%29+Green+Day" title="Spartiti di J.A.R. (Jason Andrew Relva)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+J.A.R.+%28Jason+Andrew+Relva%29+Green+Day" title="Accordi di J.A.R. (Jason Andrew Relva)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+J.A.R.+%28Jason+Andrew+Relva%29+Green+Day" title="Testi di J.A.R. (Jason Andrew Relva)">testi</a><br>
<b>9</b>. Geek Stink Breath - <a target="_blank" href="http://www.google.com/search?q=spartiti+Geek+Stink+Breath+Green+Day" title="Spartiti di Geek Stink Breath">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Geek+Stink+Breath+Green+Day" title="Accordi di Geek Stink Breath">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Geek+Stink+Breath+Green+Day" title="Testi di Geek Stink Breath">testi</a><br>
<b>10</b>. Brain Stew - <a target="_blank" href="http://www.google.com/search?q=spartiti+Brain+Stew+Green+Day" title="Spartiti di Brain Stew">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Brain+Stew+Green+Day" title="Accordi di Brain Stew">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Brain+Stew+Green+Day" title="Testi di Brain Stew">testi</a><br>
<b>11</b>. Jaded - <a target="_blank" href="http://www.google.com/search?q=spartiti+Jaded+Green+Day" title="Spartiti di Jaded">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Jaded+Green+Day" title="Accordi di Jaded">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Jaded+Green+Day" title="Testi di Jaded">testi</a><br>
<b>12</b>. Walking Contradiction - <a target="_blank" href="http://www.google.com/search?q=spartiti+Walking+Contradiction+Green+Day" title="Spartiti di Walking Contradiction">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Walking+Contradiction+Green+Day" title="Accordi di Walking Contradiction">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Walking+Contradiction+Green+Day" title="Testi di Walking Contradiction">testi</a><br>
<b>13</b>. Stuck With Me - <a target="_blank" href="http://www.google.com/search?q=spartiti+Stuck+With+Me+Green+Day" title="Spartiti di Stuck With Me">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Stuck+With+Me+Green+Day" title="Accordi di Stuck With Me">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Stuck+With+Me+Green+Day" title="Testi di Stuck With Me">testi</a><br>
<b>14</b>. Hitchin' A Ride - <a target="_blank" href="http://www.google.com/search?q=spartiti+Hitchin%27+A+Ride+Green+Day" title="Spartiti di Hitchin' A Ride">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Hitchin%27+A+Ride+Green+Day" title="Accordi di Hitchin' A Ride">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Hitchin%27+A+Ride+Green+Day" title="Testi di Hitchin' A Ride">testi</a><br>
<b>15</b>. Good Riddance (Time Of Your Life) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Good+Riddance+%28Time+Of+Your+Life%29+Green+Day" title="Spartiti di Good Riddance (Time Of Your Life)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Good+Riddance+%28Time+Of+Your+Life%29+Green+Day" title="Accordi di Good Riddance (Time Of Your Life)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Good+Riddance+%28Time+Of+Your+Life%29+Green+Day" title="Testi di Good Riddance (Time Of Your Life)">testi</a><br>
<b>16</b>. Redundant - <a target="_blank" href="http://www.google.com/search?q=spartiti+Redundant+Green+Day" title="Spartiti di Redundant">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Redundant+Green+Day" title="Accordi di Redundant">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Redundant+Green+Day" title="Testi di Redundant">testi</a><br>
<b>17</b>. Nice Guys Finish Last - <a target="_blank" href="http://www.google.com/search?q=spartiti+Nice+Guys+Finish+Last+Green+Day" title="Spartiti di Nice Guys Finish Last">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Nice+Guys+Finish+Last+Green+Day" title="Accordi di Nice Guys Finish Last">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Nice+Guys+Finish+Last+Green+Day" title="Testi di Nice Guys Finish Last">testi</a><br>
<b>18</b>. Minority - <a target="_blank" href="http://www.google.com/search?q=spartiti+Minority+Green+Day" title="Spartiti di Minority">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Minority+Green+Day" title="Accordi di Minority">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Minority+Green+Day" title="Testi di Minority">testi</a><br>
<b>19</b>. Warning - <a target="_blank" href="http://www.google.com/search?q=spartiti+Warning+Green+Day" title="Spartiti di Warning">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Warning+Green+Day" title="Accordi di Warning">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Warning+Green+Day" title="Testi di Warning">testi</a><br>
<b>20</b>. Waiting - <a target="_blank" href="http://www.google.com/search?q=spartiti+Waiting+Green+Day" title="Spartiti di Waiting">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Waiting+Green+Day" title="Accordi di Waiting">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Waiting+Green+Day" title="Testi di Waiting">testi</a><br>
<b>21</b>. Macy's Day Parade - <a target="_blank" href="http://www.google.com/search?q=spartiti+Macy%27s+Day+Parade+Green+Day" title="Spartiti di Macy's Day Parade">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Macy%27s+Day+Parade+Green+Day" title="Accordi di Macy's Day Parade">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Macy%27s+Day+Parade+Green+Day" title="Testi di Macy's Day Parade">testi</a><br>
<h2>Warning (2000) </h2>
<b>1</b>. Warning - <a target="_blank" href="http://www.google.com/search?q=spartiti+Warning+Green+Day" title="Spartiti di Warning">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Warning+Green+Day" title="Accordi di Warning">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Warning+Green+Day" title="Testi di Warning">testi</a><br>
<b>2</b>. Blood, Sex, and Booze - <a target="_blank" href="http://www.google.com/search?q=spartiti+Blood%2C+Sex%2C+and+Booze+Green+Day" title="Spartiti di Blood, Sex, and Booze">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Blood%2C+Sex%2C+and+Booze+Green+Day" title="Accordi di Blood, Sex, and Booze">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Blood%2C+Sex%2C+and+Booze+Green+Day" title="Testi di Blood, Sex, and Booze">testi</a><br>
<b>3</b>. Church On Sunday - <a target="_blank" href="http://www.google.com/search?q=spartiti+Church+On+Sunday+Green+Day" title="Spartiti di Church On Sunday">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Church+On+Sunday+Green+Day" title="Accordi di Church On Sunday">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Church+On+Sunday+Green+Day" title="Testi di Church On Sunday">testi</a><br>
<b>4</b>. Fashion Victim - <a target="_blank" href="http://www.google.com/search?q=spartiti+Fashion+Victim+Green+Day" title="Spartiti di Fashion Victim">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Fashion+Victim+Green+Day" title="Accordi di Fashion Victim">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Fashion+Victim+Green+Day" title="Testi di Fashion Victim">testi</a><br>
<b>5</b>. Castawaye - <a target="_blank" href="http://www.google.com/search?q=spartiti+Castawaye+Green+Day" title="Spartiti di Castawaye">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Castawaye+Green+Day" title="Accordi di Castawaye">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Castawaye+Green+Day" title="Testi di Castawaye">testi</a><br>
<b>6</b>. Misery - <a target="_blank" href="http://www.google.com/search?q=spartiti+Misery+Green+Day" title="Spartiti di Misery">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Misery+Green+Day" title="Accordi di Misery">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Misery+Green+Day" title="Testi di Misery">testi</a><br>
<b>7</b>. Deadbeat Holiday - <a target="_blank" href="http://www.google.com/search?q=spartiti+Deadbeat+Holiday+Green+Day" title="Spartiti di Deadbeat Holiday">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Deadbeat+Holiday+Green+Day" title="Accordi di Deadbeat Holiday">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Deadbeat+Holiday+Green+Day" title="Testi di Deadbeat Holiday">testi</a><br>
<b>8</b>. Hold On - <a target="_blank" href="http://www.google.com/search?q=spartiti+Hold+On+Green+Day" title="Spartiti di Hold On">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Hold+On+Green+Day" title="Accordi di Hold On">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Hold+On+Green+Day" title="Testi di Hold On">testi</a><br>
<b>9</b>. Jackass - <a target="_blank" href="http://www.google.com/search?q=spartiti+Jackass+Green+Day" title="Spartiti di Jackass">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Jackass+Green+Day" title="Accordi di Jackass">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Jackass+Green+Day" title="Testi di Jackass">testi</a><br>
<b>10</b>. Waiting - <a target="_blank" href="http://www.google.com/search?q=spartiti+Waiting+Green+Day" title="Spartiti di Waiting">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Waiting+Green+Day" title="Accordi di Waiting">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Waiting+Green+Day" title="Testi di Waiting">testi</a><br>
<b>11</b>. Minority - <a target="_blank" href="http://www.google.com/search?q=spartiti+Minority+Green+Day" title="Spartiti di Minority">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Minority+Green+Day" title="Accordi di Minority">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Minority+Green+Day" title="Testi di Minority">testi</a><br>
<b>12</b>. Macy's Day Parade - <a target="_blank" href="http://www.google.com/search?q=spartiti+Macy%27s+Day+Parade+Green+Day" title="Spartiti di Macy's Day Parade">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Macy%27s+Day+Parade+Green+Day" title="Accordi di Macy's Day Parade">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Macy%27s+Day+Parade+Green+Day" title="Testi di Macy's Day Parade">testi</a><br>
<h2>Nimrod (1997) </h2>
<b>1</b>. Nice Guys Finish Last - <a target="_blank" href="http://www.google.com/search?q=spartiti+Nice+Guys+Finish+Last+Green+Day" title="Spartiti di Nice Guys Finish Last">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Nice+Guys+Finish+Last+Green+Day" title="Accordi di Nice Guys Finish Last">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Nice+Guys+Finish+Last+Green+Day" title="Testi di Nice Guys Finish Last">testi</a><br>
<b>2</b>. Hitchin' A Ride - <a target="_blank" href="http://www.google.com/search?q=spartiti+Hitchin%27+A+Ride+Green+Day" title="Spartiti di Hitchin' A Ride">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Hitchin%27+A+Ride+Green+Day" title="Accordi di Hitchin' A Ride">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Hitchin%27+A+Ride+Green+Day" title="Testi di Hitchin' A Ride">testi</a><br>
<b>3</b>. The Grouch - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+Grouch+Green+Day" title="Spartiti di The Grouch">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+Grouch+Green+Day" title="Accordi di The Grouch">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+Grouch+Green+Day" title="Testi di The Grouch">testi</a><br>
<b>4</b>. Redundant - <a target="_blank" href="http://www.google.com/search?q=spartiti+Redundant+Green+Day" title="Spartiti di Redundant">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Redundant+Green+Day" title="Accordi di Redundant">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Redundant+Green+Day" title="Testi di Redundant">testi</a><br>
<b>5</b>. Scattered - <a target="_blank" href="http://www.google.com/search?q=spartiti+Scattered+Green+Day" title="Spartiti di Scattered">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Scattered+Green+Day" title="Accordi di Scattered">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Scattered+Green+Day" title="Testi di Scattered">testi</a><br>
<b>6</b>. All The Time - <a target="_blank" href="http://www.google.com/search?q=spartiti+All+The+Time+Green+Day" title="Spartiti di All The Time">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+All+The+Time+Green+Day" title="Accordi di All The Time">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+All+The+Time+Green+Day" title="Testi di All The Time">testi</a><br>
<b>7</b>. Worry Rock - <a target="_blank" href="http://www.google.com/search?q=spartiti+Worry+Rock+Green+Day" title="Spartiti di Worry Rock">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Worry+Rock+Green+Day" title="Accordi di Worry Rock">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Worry+Rock+Green+Day" title="Testi di Worry Rock">testi</a><br>
<b>8</b>. Platypus (I Hate You) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Platypus+%28I+Hate+You%29+Green+Day" title="Spartiti di Platypus (I Hate You)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Platypus+%28I+Hate+You%29+Green+Day" title="Accordi di Platypus (I Hate You)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Platypus+%28I+Hate+You%29+Green+Day" title="Testi di Platypus (I Hate You)">testi</a><br>
<b>9</b>. Uptight - <a target="_blank" href="http://www.google.com/search?q=spartiti+Uptight+Green+Day" title="Spartiti di Uptight">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Uptight+Green+Day" title="Accordi di Uptight">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Uptight+Green+Day" title="Testi di Uptight">testi</a><br>
<b>10</b>. Last Ride In - <a target="_blank" href="http://www.google.com/search?q=spartiti+Last+Ride+In+Green+Day" title="Spartiti di Last Ride In">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Last+Ride+In+Green+Day" title="Accordi di Last Ride In">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Last+Ride+In+Green+Day" title="Testi di Last Ride In">testi</a><br>
<b>11</b>. Jinx - <a target="_blank" href="http://www.google.com/search?q=spartiti+Jinx+Green+Day" title="Spartiti di Jinx">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Jinx+Green+Day" title="Accordi di Jinx">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Jinx+Green+Day" title="Testi di Jinx">testi</a><br>
<b>12</b>. Haushinka - <a target="_blank" href="http://www.google.com/search?q=spartiti+Haushinka+Green+Day" title="Spartiti di Haushinka">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Haushinka+Green+Day" title="Accordi di Haushinka">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Haushinka+Green+Day" title="Testi di Haushinka">testi</a><br>
<b>13</b>. Walking Alone - <a target="_blank" href="http://www.google.com/search?q=spartiti+Walking+Alone+Green+Day" title="Spartiti di Walking Alone">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Walking+Alone+Green+Day" title="Accordi di Walking Alone">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Walking+Alone+Green+Day" title="Testi di Walking Alone">testi</a><br>
<b>14</b>. Reject - <a target="_blank" href="http://www.google.com/search?q=spartiti+Reject+Green+Day" title="Spartiti di Reject">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Reject+Green+Day" title="Accordi di Reject">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Reject+Green+Day" title="Testi di Reject">testi</a><br>
<b>15</b>. Take Bake - <a target="_blank" href="http://www.google.com/search?q=spartiti+Take+Bake+Green+Day" title="Spartiti di Take Bake">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Take+Bake+Green+Day" title="Accordi di Take Bake">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Take+Bake+Green+Day" title="Testi di Take Bake">testi</a><br>
<b>16</b>. King For A Day - <a target="_blank" href="http://www.google.com/search?q=spartiti+King+For+A+Day+Green+Day" title="Spartiti di King For A Day">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+King+For+A+Day+Green+Day" title="Accordi di King For A Day">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+King+For+A+Day+Green+Day" title="Testi di King For A Day">testi</a><br>
<b>17</b>. Good Riddance (Time Of Your Life) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Good+Riddance+%28Time+Of+Your+Life%29+Green+Day" title="Spartiti di Good Riddance (Time Of Your Life)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Good+Riddance+%28Time+Of+Your+Life%29+Green+Day" title="Accordi di Good Riddance (Time Of Your Life)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Good+Riddance+%28Time+Of+Your+Life%29+Green+Day" title="Testi di Good Riddance (Time Of Your Life)">testi</a><br>
<b>18</b>. Prosthetic Head - <a target="_blank" href="http://www.google.com/search?q=spartiti+Prosthetic+Head+Green+Day" title="Spartiti di Prosthetic Head">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Prosthetic+Head+Green+Day" title="Accordi di Prosthetic Head">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Prosthetic+Head+Green+Day" title="Testi di Prosthetic Head">testi</a><br>
<b>19</b>. Desensitized (Japenese Import Version) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Desensitized+%28Japenese+Import+Version%29+Green+Day" title="Spartiti di Desensitized (Japenese Import Version)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Desensitized+%28Japenese+Import+Version%29+Green+Day" title="Accordi di Desensitized (Japenese Import Version)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Desensitized+%28Japenese+Import+Version%29+Green+Day" title="Testi di Desensitized (Japenese Import Version)">testi</a><br>
<h2>Insomniac (1994) </h2>
<b>1</b>. Armatage Shanks - <a target="_blank" href="http://www.google.com/search?q=spartiti+Armatage+Shanks+Green+Day" title="Spartiti di Armatage Shanks">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Armatage+Shanks+Green+Day" title="Accordi di Armatage Shanks">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Armatage+Shanks+Green+Day" title="Testi di Armatage Shanks">testi</a><br>
<b>2</b>. Brat - <a target="_blank" href="http://www.google.com/search?q=spartiti+Brat+Green+Day" title="Spartiti di Brat">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Brat+Green+Day" title="Accordi di Brat">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Brat+Green+Day" title="Testi di Brat">testi</a><br>
<b>3</b>. Stuck with Me - <a target="_blank" href="http://www.google.com/search?q=spartiti+Stuck+with+Me+Green+Day" title="Spartiti di Stuck with Me">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Stuck+with+Me+Green+Day" title="Accordi di Stuck with Me">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Stuck+with+Me+Green+Day" title="Testi di Stuck with Me">testi</a><br>
<b>4</b>. Geek Stink Breath - <a target="_blank" href="http://www.google.com/search?q=spartiti+Geek+Stink+Breath+Green+Day" title="Spartiti di Geek Stink Breath">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Geek+Stink+Breath+Green+Day" title="Accordi di Geek Stink Breath">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Geek+Stink+Breath+Green+Day" title="Testi di Geek Stink Breath">testi</a><br>
<b>5</b>. No Pride - <a target="_blank" href="http://www.google.com/search?q=spartiti+No+Pride+Green+Day" title="Spartiti di No Pride">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+No+Pride+Green+Day" title="Accordi di No Pride">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+No+Pride+Green+Day" title="Testi di No Pride">testi</a><br>
<b>6</b>. Bab's Uvula Who? - <a target="_blank" href="http://www.google.com/search?q=spartiti+Bab%27s+Uvula+Who%3F+Green+Day" title="Spartiti di Bab's Uvula Who?">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Bab%27s+Uvula+Who%3F+Green+Day" title="Accordi di Bab's Uvula Who?">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Bab%27s+Uvula+Who%3F+Green+Day" title="Testi di Bab's Uvula Who?">testi</a><br>
<b>7</b>. 86 - <a target="_blank" href="http://www.google.com/search?q=spartiti+86+Green+Day" title="Spartiti di 86">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+86+Green+Day" title="Accordi di 86">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+86+Green+Day" title="Testi di 86">testi</a><br>
<b>8</b>. Panic Song - <a target="_blank" href="http://www.google.com/search?q=spartiti+Panic+Song+Green+Day" title="Spartiti di Panic Song">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Panic+Song+Green+Day" title="Accordi di Panic Song">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Panic+Song+Green+Day" title="Testi di Panic Song">testi</a><br>
<b>9</b>. Stuart and the Ave - <a target="_blank" href="http://www.google.com/search?q=spartiti+Stuart+and+the+Ave+Green+Day" title="Spartiti di Stuart and the Ave">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Stuart+and+the+Ave+Green+Day" title="Accordi di Stuart and the Ave">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Stuart+and+the+Ave+Green+Day" title="Testi di Stuart and the Ave">testi</a><br>
<b>10</b>. Brain Stew - <a target="_blank" href="http://www.google.com/search?q=spartiti+Brain+Stew+Green+Day" title="Spartiti di Brain Stew">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Brain+Stew+Green+Day" title="Accordi di Brain Stew">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Brain+Stew+Green+Day" title="Testi di Brain Stew">testi</a><br>
<b>11</b>. Jaded - <a target="_blank" href="http://www.google.com/search?q=spartiti+Jaded+Green+Day" title="Spartiti di Jaded">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Jaded+Green+Day" title="Accordi di Jaded">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Jaded+Green+Day" title="Testi di Jaded">testi</a><br>
<b>12</b>. Westbound Sign - <a target="_blank" href="http://www.google.com/search?q=spartiti+Westbound+Sign+Green+Day" title="Spartiti di Westbound Sign">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Westbound+Sign+Green+Day" title="Accordi di Westbound Sign">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Westbound+Sign+Green+Day" title="Testi di Westbound Sign">testi</a><br>
<b>13</b>. Tight Wad Hill - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tight+Wad+Hill+Green+Day" title="Spartiti di Tight Wad Hill">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tight+Wad+Hill+Green+Day" title="Accordi di Tight Wad Hill">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tight+Wad+Hill+Green+Day" title="Testi di Tight Wad Hill">testi</a><br>
<b>14</b>. Walking Contradiction - <a target="_blank" href="http://www.google.com/search?q=spartiti+Walking+Contradiction+Green+Day" title="Spartiti di Walking Contradiction">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Walking+Contradiction+Green+Day" title="Accordi di Walking Contradiction">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Walking+Contradiction+Green+Day" title="Testi di Walking Contradiction">testi</a><br>
<h2>Dookie (1994) </h2>
<b>1</b>. Burnout - <a target="_blank" href="http://www.google.com/search?q=spartiti+Burnout+Green+Day" title="Spartiti di Burnout">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Burnout+Green+Day" title="Accordi di Burnout">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Burnout+Green+Day" title="Testi di Burnout">testi</a><br>
<b>2</b>. Having A Blast - <a target="_blank" href="http://www.google.com/search?q=spartiti+Having+A+Blast+Green+Day" title="Spartiti di Having A Blast">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Having+A+Blast+Green+Day" title="Accordi di Having A Blast">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Having+A+Blast+Green+Day" title="Testi di Having A Blast">testi</a><br>
<b>3</b>. Chump - <a target="_blank" href="http://www.google.com/search?q=spartiti+Chump+Green+Day" title="Spartiti di Chump">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Chump+Green+Day" title="Accordi di Chump">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Chump+Green+Day" title="Testi di Chump">testi</a><br>
<b>4</b>. Longview - <a target="_blank" href="http://www.google.com/search?q=spartiti+Longview+Green+Day" title="Spartiti di Longview">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Longview+Green+Day" title="Accordi di Longview">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Longview+Green+Day" title="Testi di Longview">testi</a><br>
<b>5</b>. Welcome To Paradise - <a target="_blank" href="http://www.google.com/search?q=spartiti+Welcome+To+Paradise+Green+Day" title="Spartiti di Welcome To Paradise">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Welcome+To+Paradise+Green+Day" title="Accordi di Welcome To Paradise">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Welcome+To+Paradise+Green+Day" title="Testi di Welcome To Paradise">testi</a><br>
<b>6</b>. Pulling Teeth - <a target="_blank" href="http://www.google.com/search?q=spartiti+Pulling+Teeth+Green+Day" title="Spartiti di Pulling Teeth">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Pulling+Teeth+Green+Day" title="Accordi di Pulling Teeth">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Pulling+Teeth+Green+Day" title="Testi di Pulling Teeth">testi</a><br>
<b>7</b>. Basket Case - <a target="_blank" href="http://www.google.com/search?q=spartiti+Basket+Case+Green+Day" title="Spartiti di Basket Case">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Basket+Case+Green+Day" title="Accordi di Basket Case">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Basket+Case+Green+Day" title="Testi di Basket Case">testi</a><br>
<b>8</b>. She - <a target="_blank" href="http://www.google.com/search?q=spartiti+She+Green+Day" title="Spartiti di She">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+She+Green+Day" title="Accordi di She">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+She+Green+Day" title="Testi di She">testi</a><br>
<b>9</b>. Sassafras Roots - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sassafras+Roots+Green+Day" title="Spartiti di Sassafras Roots">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sassafras+Roots+Green+Day" title="Accordi di Sassafras Roots">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sassafras+Roots+Green+Day" title="Testi di Sassafras Roots">testi</a><br>
<b>10</b>. When I Come Around - <a target="_blank" href="http://www.google.com/search?q=spartiti+When+I+Come+Around+Green+Day" title="Spartiti di When I Come Around">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+When+I+Come+Around+Green+Day" title="Accordi di When I Come Around">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+When+I+Come+Around+Green+Day" title="Testi di When I Come Around">testi</a><br>
<b>11</b>. Coming Clean - <a target="_blank" href="http://www.google.com/search?q=spartiti+Coming+Clean+Green+Day" title="Spartiti di Coming Clean">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Coming+Clean+Green+Day" title="Accordi di Coming Clean">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Coming+Clean+Green+Day" title="Testi di Coming Clean">testi</a><br>
<b>12</b>. Emenius Sleepus - <a target="_blank" href="http://www.google.com/search?q=spartiti+Emenius+Sleepus+Green+Day" title="Spartiti di Emenius Sleepus">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Emenius+Sleepus+Green+Day" title="Accordi di Emenius Sleepus">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Emenius+Sleepus+Green+Day" title="Testi di Emenius Sleepus">testi</a><br>
<b>13</b>. In the End - <a target="_blank" href="http://www.google.com/search?q=spartiti+In+the+End+Green+Day" title="Spartiti di In the End">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+In+the+End+Green+Day" title="Accordi di In the End">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+In+the+End+Green+Day" title="Testi di In the End">testi</a><br>
<b>14</b>. F.O.D. - <a target="_blank" href="http://www.google.com/search?q=spartiti+F.O.D.+Green+Day" title="Spartiti di F.O.D.">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+F.O.D.+Green+Day" title="Accordi di F.O.D.">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+F.O.D.+Green+Day" title="Testi di F.O.D.">testi</a><br>
<b>15</b>. All By Myself - <a target="_blank" href="http://www.google.com/search?q=spartiti+All+By+Myself+Green+Day" title="Spartiti di All By Myself">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+All+By+Myself+Green+Day" title="Accordi di All By Myself">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+All+By+Myself+Green+Day" title="Testi di All By Myself">testi</a><br>
<h2>Kerplunk (1991) </h2>
<b>1</b>. 2000 Light Years Away - <a target="_blank" href="http://www.google.com/search?q=spartiti+2000+Light+Years+Away+Green+Day" title="Spartiti di 2000 Light Years Away">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+2000+Light+Years+Away+Green+Day" title="Accordi di 2000 Light Years Away">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+2000+Light+Years+Away+Green+Day" title="Testi di 2000 Light Years Away">testi</a><br>
<b>2</b>. One for the Razorbacks - <a target="_blank" href="http://www.google.com/search?q=spartiti+One+for+the+Razorbacks+Green+Day" title="Spartiti di One for the Razorbacks">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+One+for+the+Razorbacks+Green+Day" title="Accordi di One for the Razorbacks">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+One+for+the+Razorbacks+Green+Day" title="Testi di One for the Razorbacks">testi</a><br>
<b>3</b>. Welcome to Paradise - <a target="_blank" href="http://www.google.com/search?q=spartiti+Welcome+to+Paradise+Green+Day" title="Spartiti di Welcome to Paradise">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Welcome+to+Paradise+Green+Day" title="Accordi di Welcome to Paradise">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Welcome+to+Paradise+Green+Day" title="Testi di Welcome to Paradise">testi</a><br>
<b>4</b>. Christie Road - <a target="_blank" href="http://www.google.com/search?q=spartiti+Christie+Road+Green+Day" title="Spartiti di Christie Road">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Christie+Road+Green+Day" title="Accordi di Christie Road">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Christie+Road+Green+Day" title="Testi di Christie Road">testi</a><br>
<b>5</b>. Private Ale - <a target="_blank" href="http://www.google.com/search?q=spartiti+Private+Ale+Green+Day" title="Spartiti di Private Ale">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Private+Ale+Green+Day" title="Accordi di Private Ale">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Private+Ale+Green+Day" title="Testi di Private Ale">testi</a><br>
<b>6</b>. Dominated Love Slave - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dominated+Love+Slave+Green+Day" title="Spartiti di Dominated Love Slave">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dominated+Love+Slave+Green+Day" title="Accordi di Dominated Love Slave">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dominated+Love+Slave+Green+Day" title="Testi di Dominated Love Slave">testi</a><br>
<b>7</b>. One of My Lies - <a target="_blank" href="http://www.google.com/search?q=spartiti+One+of+My+Lies+Green+Day" title="Spartiti di One of My Lies">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+One+of+My+Lies+Green+Day" title="Accordi di One of My Lies">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+One+of+My+Lies+Green+Day" title="Testi di One of My Lies">testi</a><br>
<b>8</b>. 80 - <a target="_blank" href="http://www.google.com/search?q=spartiti+80+Green+Day" title="Spartiti di 80">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+80+Green+Day" title="Accordi di 80">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+80+Green+Day" title="Testi di 80">testi</a><br>
<b>9</b>. Android - <a target="_blank" href="http://www.google.com/search?q=spartiti+Android+Green+Day" title="Spartiti di Android">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Android+Green+Day" title="Accordi di Android">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Android+Green+Day" title="Testi di Android">testi</a><br>
<b>10</b>. No One Knows - <a target="_blank" href="http://www.google.com/search?q=spartiti+No+One+Knows+Green+Day" title="Spartiti di No One Knows">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+No+One+Knows+Green+Day" title="Accordi di No One Knows">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+No+One+Knows+Green+Day" title="Testi di No One Knows">testi</a><br>
<b>11</b>. Who Wrote Holden Caulfield? - <a target="_blank" href="http://www.google.com/search?q=spartiti+Who+Wrote+Holden+Caulfield%3F+Green+Day" title="Spartiti di Who Wrote Holden Caulfield?">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Who+Wrote+Holden+Caulfield%3F+Green+Day" title="Accordi di Who Wrote Holden Caulfield?">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Who+Wrote+Holden+Caulfield%3F+Green+Day" title="Testi di Who Wrote Holden Caulfield?">testi</a><br>
<b>12</b>. Words I Might Have Ate - <a target="_blank" href="http://www.google.com/search?q=spartiti+Words+I+Might+Have+Ate+Green+Day" title="Spartiti di Words I Might Have Ate">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Words+I+Might+Have+Ate+Green+Day" title="Accordi di Words I Might Have Ate">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Words+I+Might+Have+Ate+Green+Day" title="Testi di Words I Might Have Ate">testi</a><br>
<b>13</b>. Sweet Children - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sweet+Children+Green+Day" title="Spartiti di Sweet Children">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sweet+Children+Green+Day" title="Accordi di Sweet Children">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sweet+Children+Green+Day" title="Testi di Sweet Children">testi</a><br>
<b>14</b>. Best Thing in Town - <a target="_blank" href="http://www.google.com/search?q=spartiti+Best+Thing+in+Town+Green+Day" title="Spartiti di Best Thing in Town">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Best+Thing+in+Town+Green+Day" title="Accordi di Best Thing in Town">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Best+Thing+in+Town+Green+Day" title="Testi di Best Thing in Town">testi</a><br>
<b>15</b>. Strangeland - <a target="_blank" href="http://www.google.com/search?q=spartiti+Strangeland+Green+Day" title="Spartiti di Strangeland">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Strangeland+Green+Day" title="Accordi di Strangeland">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Strangeland+Green+Day" title="Testi di Strangeland">testi</a><br>
<b>16</b>. My Generation - <a target="_blank" href="http://www.google.com/search?q=spartiti+My+Generation+Green+Day" title="Spartiti di My Generation">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+My+Generation+Green+Day" title="Accordi di My Generation">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+My+Generation+Green+Day" title="Testi di My Generation">testi</a><br>
<h2>1,039 Smoothed Out Slappy Hours (1990) </h2>
<b>1</b>. At the Library - <a target="_blank" href="http://www.google.com/search?q=spartiti+At+the+Library+Green+Day" title="Spartiti di At the Library">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+At+the+Library+Green+Day" title="Accordi di At the Library">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+At+the+Library+Green+Day" title="Testi di At the Library">testi</a><br>
<b>2</b>. Don't Leave Me - <a target="_blank" href="http://www.google.com/search?q=spartiti+Don%27t+Leave+Me+Green+Day" title="Spartiti di Don't Leave Me">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Don%27t+Leave+Me+Green+Day" title="Accordi di Don't Leave Me">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Don%27t+Leave+Me+Green+Day" title="Testi di Don't Leave Me">testi</a><br>
<b>3</b>. I Was There - <a target="_blank" href="http://www.google.com/search?q=spartiti+I+Was+There+Green+Day" title="Spartiti di I Was There">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+I+Was+There+Green+Day" title="Accordi di I Was There">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+I+Was+There+Green+Day" title="Testi di I Was There">testi</a><br>
<b>4</b>. Disappearing Boy - <a target="_blank" href="http://www.google.com/search?q=spartiti+Disappearing+Boy+Green+Day" title="Spartiti di Disappearing Boy">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Disappearing+Boy+Green+Day" title="Accordi di Disappearing Boy">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Disappearing+Boy+Green+Day" title="Testi di Disappearing Boy">testi</a><br>
<b>5</b>. Green Day - <a target="_blank" href="http://www.google.com/search?q=spartiti+Green+Day+Green+Day" title="Spartiti di Green Day">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Green+Day+Green+Day" title="Accordi di Green Day">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Green+Day+Green+Day" title="Testi di Green Day">testi</a><br>
<b>6</b>. Going to Pasalacqua - <a target="_blank" href="http://www.google.com/search?q=spartiti+Going+to+Pasalacqua+Green+Day" title="Spartiti di Going to Pasalacqua">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Going+to+Pasalacqua+Green+Day" title="Accordi di Going to Pasalacqua">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Going+to+Pasalacqua+Green+Day" title="Testi di Going to Pasalacqua">testi</a><br>
<b>7</b>. 16 - <a target="_blank" href="http://www.google.com/search?q=spartiti+16+Green+Day" title="Spartiti di 16">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+16+Green+Day" title="Accordi di 16">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+16+Green+Day" title="Testi di 16">testi</a><br>
<b>8</b>. Road to Acceptance - <a target="_blank" href="http://www.google.com/search?q=spartiti+Road+to+Acceptance+Green+Day" title="Spartiti di Road to Acceptance">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Road+to+Acceptance+Green+Day" title="Accordi di Road to Acceptance">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Road+to+Acceptance+Green+Day" title="Testi di Road to Acceptance">testi</a><br>
<b>9</b>. Rest - <a target="_blank" href="http://www.google.com/search?q=spartiti+Rest+Green+Day" title="Spartiti di Rest">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Rest+Green+Day" title="Accordi di Rest">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Rest+Green+Day" title="Testi di Rest">testi</a><br>
<b>10</b>. The Judge's Daughter - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+Judge%27s+Daughter+Green+Day" title="Spartiti di The Judge's Daughter">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+Judge%27s+Daughter+Green+Day" title="Accordi di The Judge's Daughter">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+Judge%27s+Daughter+Green+Day" title="Testi di The Judge's Daughter">testi</a><br>
<b>11</b>. Paper Lanterns - <a target="_blank" href="http://www.google.com/search?q=spartiti+Paper+Lanterns+Green+Day" title="Spartiti di Paper Lanterns">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Paper+Lanterns+Green+Day" title="Accordi di Paper Lanterns">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Paper+Lanterns+Green+Day" title="Testi di Paper Lanterns">testi</a><br>
<b>12</b>. Why Do You Want Him? - <a target="_blank" href="http://www.google.com/search?q=spartiti+Why+Do+You+Want+Him%3F+Green+Day" title="Spartiti di Why Do You Want Him?">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Why+Do+You+Want+Him%3F+Green+Day" title="Accordi di Why Do You Want Him?">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Why+Do+You+Want+Him%3F+Green+Day" title="Testi di Why Do You Want Him?">testi</a><br>
<b>13</b>. 409 in Your Coffeemaker - <a target="_blank" href="http://www.google.com/search?q=spartiti+409+in+Your+Coffeemaker+Green+Day" title="Spartiti di 409 in Your Coffeemaker">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+409+in+Your+Coffeemaker+Green+Day" title="Accordi di 409 in Your Coffeemaker">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+409+in+Your+Coffeemaker+Green+Day" title="Testi di 409 in Your Coffeemaker">testi</a><br>
<b>14</b>. Knowledge - <a target="_blank" href="http://www.google.com/search?q=spartiti+Knowledge+Green+Day" title="Spartiti di Knowledge">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Knowledge+Green+Day" title="Accordi di Knowledge">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Knowledge+Green+Day" title="Testi di Knowledge">testi</a><br>
<b>15</b>. 1,000 Hours - <a target="_blank" href="http://www.google.com/search?q=spartiti+1%2C000+Hours+Green+Day" title="Spartiti di 1,000 Hours">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+1%2C000+Hours+Green+Day" title="Accordi di 1,000 Hours">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+1%2C000+Hours+Green+Day" title="Testi di 1,000 Hours">testi</a><br>
<b>16</b>. Dry Ice - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dry+Ice+Green+Day" title="Spartiti di Dry Ice">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dry+Ice+Green+Day" title="Accordi di Dry Ice">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dry+Ice+Green+Day" title="Testi di Dry Ice">testi</a><br>
<b>17</b>. Only of You - <a target="_blank" href="http://www.google.com/search?q=spartiti+Only+of+You+Green+Day" title="Spartiti di Only of You">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Only+of+You+Green+Day" title="Accordi di Only of You">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Only+of+You+Green+Day" title="Testi di Only of You">testi</a><br>
<b>18</b>. The One I Want - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+One+I+Want+Green+Day" title="Spartiti di The One I Want">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+One+I+Want+Green+Day" title="Accordi di The One I Want">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+One+I+Want+Green+Day" title="Testi di The One I Want">testi</a><br>
<b>19</b>. I Want to Be Alone - <a target="_blank" href="http://www.google.com/search?q=spartiti+I+Want+to+Be+Alone+Green+Day" title="Spartiti di I Want to Be Alone">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+I+Want+to+Be+Alone+Green+Day" title="Accordi di I Want to Be Alone">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+I+Want+to+Be+Alone+Green+Day" title="Testi di I Want to Be Alone">testi</a><br>
<h2>Altre Canzoni </h2>
<b>1</b>. Blitzkrieg Bop - <a target="_blank" href="http://www.google.com/search?q=spartiti+Blitzkrieg+Bop+Green+Day" title="Spartiti di Blitzkrieg Bop">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Blitzkrieg+Bop+Green+Day" title="Accordi di Blitzkrieg Bop">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Blitzkrieg+Bop+Green+Day" title="Testi di Blitzkrieg Bop">testi</a><br>
<b>2</b>. Boulevard Of Broken Dreams (Remix) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Boulevard+Of+Broken+Dreams+%28Remix%29+Green+Day" title="Spartiti di Boulevard Of Broken Dreams (Remix)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Boulevard+Of+Broken+Dreams+%28Remix%29+Green+Day" title="Accordi di Boulevard Of Broken Dreams (Remix)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Boulevard+Of+Broken+Dreams+%28Remix%29+Green+Day" title="Testi di Boulevard Of Broken Dreams (Remix)">testi</a><br>
<b>3</b>. Desensitized - <a target="_blank" href="http://www.google.com/search?q=spartiti+Desensitized+Green+Day" title="Spartiti di Desensitized">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Desensitized+Green+Day" title="Accordi di Desensitized">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Desensitized+Green+Day" title="Testi di Desensitized">testi</a><br>
<b>4</b>. Do Da Da - <a target="_blank" href="http://www.google.com/search?q=spartiti+Do+Da+Da+Green+Day" title="Spartiti di Do Da Da">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Do+Da+Da+Green+Day" title="Accordi di Do Da Da">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Do+Da+Da+Green+Day" title="Testi di Do Da Da">testi</a><br>
<b>5</b>. Don't Want To Fall In Love - <a target="_blank" href="http://www.google.com/search?q=spartiti+Don%27t+Want+To+Fall+In+Love+Green+Day" title="Spartiti di Don't Want To Fall In Love">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Don%27t+Want+To+Fall+In+Love+Green+Day" title="Accordi di Don't Want To Fall In Love">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Don%27t+Want+To+Fall+In+Love+Green+Day" title="Testi di Don't Want To Fall In Love">testi</a><br>
<b>6</b>. DUI (Driving Under the Influence) - <a target="_blank" href="http://www.google.com/search?q=spartiti+DUI+%28Driving+Under+the+Influence%29+Green+Day" title="Spartiti di DUI (Driving Under the Influence)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+DUI+%28Driving+Under+the+Influence%29+Green+Day" title="Accordi di DUI (Driving Under the Influence)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+DUI+%28Driving+Under+the+Influence%29+Green+Day" title="Testi di DUI (Driving Under the Influence)">testi</a><br>
<b>7</b>. Eye Of The Tiger - <a target="_blank" href="http://www.google.com/search?q=spartiti+Eye+Of+The+Tiger+Green+Day" title="Spartiti di Eye Of The Tiger">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Eye+Of+The+Tiger+Green+Day" title="Accordi di Eye Of The Tiger">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Eye+Of+The+Tiger+Green+Day" title="Testi di Eye Of The Tiger">testi</a><br>
<b>8</b>. Favorite Son - <a target="_blank" href="http://www.google.com/search?q=spartiti+Favorite+Son+Green+Day" title="Spartiti di Favorite Son">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Favorite+Son+Green+Day" title="Accordi di Favorite Son">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Favorite+Son+Green+Day" title="Testi di Favorite Son">testi</a><br>
<b>9</b>. Governator - <a target="_blank" href="http://www.google.com/search?q=spartiti+Governator+Green+Day" title="Spartiti di Governator">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Governator+Green+Day" title="Accordi di Governator">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Governator+Green+Day" title="Testi di Governator">testi</a><br>
<b>10</b>. I Don't Wanna Know If You Are Lonely - <a target="_blank" href="http://www.google.com/search?q=spartiti+I+Don%27t+Wanna+Know+If+You+Are+Lonely+Green+Day" title="Spartiti di I Don't Wanna Know If You Are Lonely">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+I+Don%27t+Wanna+Know+If+You+Are+Lonely+Green+Day" title="Accordi di I Don't Wanna Know If You Are Lonely">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+I+Don%27t+Wanna+Know+If+You+Are+Lonely+Green+Day" title="Testi di I Don't Wanna Know If You Are Lonely">testi</a><br>
<b>11</b>. I Don't Wanna Know If You Are Lonely - <a target="_blank" href="http://www.google.com/search?q=spartiti+I+Don%27t+Wanna+Know+If+You+Are+Lonely+Green+Day" title="Spartiti di I Don't Wanna Know If You Are Lonely">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+I+Don%27t+Wanna+Know+If+You+Are+Lonely+Green+Day" title="Accordi di I Don't Wanna Know If You Are Lonely">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+I+Don%27t+Wanna+Know+If+You+Are+Lonely+Green+Day" title="Testi di I Don't Wanna Know If You Are Lonely">testi</a><br>
<b>12</b>. I Fought The Law - <a target="_blank" href="http://www.google.com/search?q=spartiti+I+Fought+The+Law+Green+Day" title="Spartiti di I Fought The Law">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+I+Fought+The+Law+Green+Day" title="Accordi di I Fought The Law">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+I+Fought+The+Law+Green+Day" title="Testi di I Fought The Law">testi</a><br>
<b>13</b>. I Saw My Parents Kissing Santa Claws - <a target="_blank" href="http://www.google.com/search?q=spartiti+I+Saw+My+Parents+Kissing+Santa+Claws+Green+Day" title="Spartiti di I Saw My Parents Kissing Santa Claws">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+I+Saw+My+Parents+Kissing+Santa+Claws+Green+Day" title="Accordi di I Saw My Parents Kissing Santa Claws">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+I+Saw+My+Parents+Kissing+Santa+Claws+Green+Day" title="Testi di I Saw My Parents Kissing Santa Claws">testi</a><br>
<b>14</b>. I Want To Be On T.V. - <a target="_blank" href="http://www.google.com/search?q=spartiti+I+Want+To+Be+On+T.V.+Green+Day" title="Spartiti di I Want To Be On T.V.">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+I+Want+To+Be+On+T.V.+Green+Day" title="Accordi di I Want To Be On T.V.">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+I+Want+To+Be+On+T.V.+Green+Day" title="Testi di I Want To Be On T.V.">testi</a><br>
<b>15</b>. Johnny Be Good - <a target="_blank" href="http://www.google.com/search?q=spartiti+Johnny+Be+Good+Green+Day" title="Spartiti di Johnny Be Good">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Johnny+Be+Good+Green+Day" title="Accordi di Johnny Be Good">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Johnny+Be+Good+Green+Day" title="Testi di Johnny Be Good">testi</a><br>
<b>16</b>. Life During Wartime - <a target="_blank" href="http://www.google.com/search?q=spartiti+Life+During+Wartime+Green+Day" title="Spartiti di Life During Wartime">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Life+During+Wartime+Green+Day" title="Accordi di Life During Wartime">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Life+During+Wartime+Green+Day" title="Testi di Life During Wartime">testi</a><br>
<b>17</b>. Like A Rat Does Cheese - <a target="_blank" href="http://www.google.com/search?q=spartiti+Like+A+Rat+Does+Cheese+Green+Day" title="Spartiti di Like A Rat Does Cheese">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Like+A+Rat+Does+Cheese+Green+Day" title="Accordi di Like A Rat Does Cheese">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Like+A+Rat+Does+Cheese+Green+Day" title="Testi di Like A Rat Does Cheese">testi</a><br>
<b>18</b>. Mechanical Man - <a target="_blank" href="http://www.google.com/search?q=spartiti+Mechanical+Man+Green+Day" title="Spartiti di Mechanical Man">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Mechanical+Man+Green+Day" title="Accordi di Mechanical Man">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Mechanical+Man+Green+Day" title="Testi di Mechanical Man">testi</a><br>
<b>19</b>. Minnesota Girl - <a target="_blank" href="http://www.google.com/search?q=spartiti+Minnesota+Girl+Green+Day" title="Spartiti di Minnesota Girl">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Minnesota+Girl+Green+Day" title="Accordi di Minnesota Girl">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Minnesota+Girl+Green+Day" title="Testi di Minnesota Girl">testi</a><br>
<b>20</b>. On The Wagon - <a target="_blank" href="http://www.google.com/search?q=spartiti+On+The+Wagon+Green+Day" title="Spartiti di On The Wagon">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+On+The+Wagon+Green+Day" title="Accordi di On The Wagon">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+On+The+Wagon+Green+Day" title="Testi di On The Wagon">testi</a><br>
<b>21</b>. Rotting - <a target="_blank" href="http://www.google.com/search?q=spartiti+Rotting+Green+Day" title="Spartiti di Rotting">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Rotting+Green+Day" title="Accordi di Rotting">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Rotting+Green+Day" title="Testi di Rotting">testi</a><br>
<b>22</b>. Santa Claus Is Coming To Town - <a target="_blank" href="http://www.google.com/search?q=spartiti+Santa+Claus+Is+Coming+To+Town+Green+Day" title="Spartiti di Santa Claus Is Coming To Town">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Santa+Claus+Is+Coming+To+Town+Green+Day" title="Accordi di Santa Claus Is Coming To Town">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Santa+Claus+Is+Coming+To+Town+Green+Day" title="Testi di Santa Claus Is Coming To Town">testi</a><br>
<b>23</b>. Shoplifter - <a target="_blank" href="http://www.google.com/search?q=spartiti+Shoplifter+Green+Day" title="Spartiti di Shoplifter">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Shoplifter+Green+Day" title="Accordi di Shoplifter">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Shoplifter+Green+Day" title="Testi di Shoplifter">testi</a><br>
<b>24</b>. Shout - <a target="_blank" href="http://www.google.com/search?q=spartiti+Shout+Green+Day" title="Spartiti di Shout">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Shout+Green+Day" title="Accordi di Shout">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Shout+Green+Day" title="Testi di Shout">testi</a><br>
<b>25</b>. Sick - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sick+Green+Day" title="Spartiti di Sick">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sick+Green+Day" title="Accordi di Sick">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sick+Green+Day" title="Testi di Sick">testi</a><br>
<b>26</b>. Suffocate - <a target="_blank" href="http://www.google.com/search?q=spartiti+Suffocate+Green+Day" title="Spartiti di Suffocate">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Suffocate+Green+Day" title="Accordi di Suffocate">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Suffocate+Green+Day" title="Testi di Suffocate">testi</a><br>
<b>27</b>. Teenage Lobotomy - <a target="_blank" href="http://www.google.com/search?q=spartiti+Teenage+Lobotomy+Green+Day" title="Spartiti di Teenage Lobotomy">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Teenage+Lobotomy+Green+Day" title="Accordi di Teenage Lobotomy">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Teenage+Lobotomy+Green+Day" title="Testi di Teenage Lobotomy">testi</a><br>
<b>28</b>. The Angel And The Jerk - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+Angel+And+The+Jerk+Green+Day" title="Spartiti di The Angel And The Jerk">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+Angel+And+The+Jerk+Green+Day" title="Accordi di The Angel And The Jerk">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+Angel+And+The+Jerk+Green+Day" title="Testi di The Angel And The Jerk">testi</a><br>
<b>29</b>. The Ballad Of Wilhelm Fink - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+Ballad+Of+Wilhelm+Fink+Green+Day" title="Spartiti di The Ballad Of Wilhelm Fink">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+Ballad+Of+Wilhelm+Fink+Green+Day" title="Accordi di The Ballad Of Wilhelm Fink">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+Ballad+Of+Wilhelm+Fink+Green+Day" title="Testi di The Ballad Of Wilhelm Fink">testi</a><br>
<b>30</b>. The Ballad Of Wilhelm Fink - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+Ballad+Of+Wilhelm+Fink+Green+Day" title="Spartiti di The Ballad Of Wilhelm Fink">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+Ballad+Of+Wilhelm+Fink+Green+Day" title="Accordi di The Ballad Of Wilhelm Fink">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+Ballad+Of+Wilhelm+Fink+Green+Day" title="Testi di The Ballad Of Wilhelm Fink">testi</a><br>
<b>31</b>. The Kids Are Alright - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+Kids+Are+Alright+Green+Day" title="Spartiti di The Kids Are Alright">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+Kids+Are+Alright+Green+Day" title="Accordi di The Kids Are Alright">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+Kids+Are+Alright+Green+Day" title="Testi di The Kids Are Alright">testi</a><br>
<b>32</b>. The Saints Are Coming - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+Saints+Are+Coming+Green+Day" title="Spartiti di The Saints Are Coming">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+Saints+Are+Coming+Green+Day" title="Accordi di The Saints Are Coming">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+Saints+Are+Coming+Green+Day" title="Testi di The Saints Are Coming">testi</a><br>
<b>33</b>. The Saints Are Coming - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+Saints+Are+Coming+Green+Day" title="Spartiti di The Saints Are Coming">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+Saints+Are+Coming+Green+Day" title="Accordi di The Saints Are Coming">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+Saints+Are+Coming+Green+Day" title="Testi di The Saints Are Coming">testi</a><br>
<b>34</b>. Things I Heard Today - <a target="_blank" href="http://www.google.com/search?q=spartiti+Things+I+Heard+Today+Green+Day" title="Spartiti di Things I Heard Today">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Things+I+Heard+Today+Green+Day" title="Accordi di Things I Heard Today">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Things+I+Heard+Today+Green+Day" title="Testi di Things I Heard Today">testi</a><br>
<b>35</b>. Tired Of Waiting For You - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tired+Of+Waiting+For+You+Green+Day" title="Spartiti di Tired Of Waiting For You">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tired+Of+Waiting+For+You+Green+Day" title="Accordi di Tired Of Waiting For You">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tired+Of+Waiting+For+You+Green+Day" title="Testi di Tired Of Waiting For You">testi</a><br>
<b>36</b>. Too Much, Too Soon - <a target="_blank" href="http://www.google.com/search?q=spartiti+Too+Much%2C+Too+Soon+Green+Day" title="Spartiti di Too Much, Too Soon">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Too+Much%2C+Too+Soon+Green+Day" title="Accordi di Too Much, Too Soon">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Too+Much%2C+Too+Soon+Green+Day" title="Testi di Too Much, Too Soon">testi</a><br>
<b>37</b>. We Are The Champions - <a target="_blank" href="http://www.google.com/search?q=spartiti+We+Are+The+Champions+Green+Day" title="Spartiti di We Are The Champions">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+We+Are+The+Champions+Green+Day" title="Accordi di We Are The Champions">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+We+Are+The+Champions+Green+Day" title="Testi di We Are The Champions">testi</a><br>
<b>38</b>. Why Does It Always Rain On Me? - <a target="_blank" href="http://www.google.com/search?q=spartiti+Why+Does+It+Always+Rain+On+Me%3F+Green+Day" title="Spartiti di Why Does It Always Rain On Me?">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Why+Does+It+Always+Rain+On+Me%3F+Green+Day" title="Accordi di Why Does It Always Rain On Me?">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Why+Does+It+Always+Rain+On+Me%3F+Green+Day" title="Testi di Why Does It Always Rain On Me?">testi</a><br>
<b>39</b>. You Lied - <a target="_blank" href="http://www.google.com/search?q=spartiti+You+Lied+Green+Day" title="Spartiti di You Lied">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+You+Lied+Green+Day" title="Accordi di You Lied">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+You+Lied+Green+Day" title="Testi di You Lied">testi</a><br>
<h2><a href="<?php echo "$base_website_address/$spartiti_dir" ?>/index.html" title="Trova accordi, spartiti, tablature e testi di tantissimi artisti">Torna all'indice degli artisti</a></h2>
