<!--
title: Trova spartiti per chitarra, accordi, testi e tablature di Dire Straits. Discografia Dire Straits.
description: Trova tutti gli spartiti, accordi, testi e tablature di Dire Straits. Discografia Dire Straits.
keywords: Discografia, Dire Straits, spartiti, accordi, testi, tablature
template: tablature
-->
<h1>Trova spartiti per chitarra, accordi, testi e tablature di Dire Straits</h1><h2>Leggere gli spartiti per chitarra, gli accordi e le tablature:</h2>
<?php require("tabdescription.php"); ?>
<?php require("adsense_leaderboard.php"); ?>
<h2>Discografia Dire Straits:</h2>
<h2>Live At The BBC (1995) </h2>
<b>1</b>. Down To The Waterline - <a target="_blank" href="http://www.google.com/search?q=spartiti+Down+To+The+Waterline+Dire+Straits" title="Spartiti di Down To The Waterline">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Down+To+The+Waterline+Dire+Straits" title="Accordi di Down To The Waterline">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Down+To+The+Waterline+Dire+Straits" title="Testi di Down To The Waterline">testi</a><br>
<b>2</b>. Six Blade Knife - <a target="_blank" href="http://www.google.com/search?q=spartiti+Six+Blade+Knife+Dire+Straits" title="Spartiti di Six Blade Knife">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Six+Blade+Knife+Dire+Straits" title="Accordi di Six Blade Knife">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Six+Blade+Knife+Dire+Straits" title="Testi di Six Blade Knife">testi</a><br>
<b>3</b>. Water Of Love - <a target="_blank" href="http://www.google.com/search?q=spartiti+Water+Of+Love+Dire+Straits" title="Spartiti di Water Of Love">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Water+Of+Love+Dire+Straits" title="Accordi di Water Of Love">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Water+Of+Love+Dire+Straits" title="Testi di Water Of Love">testi</a><br>
<b>4</b>. Wild West End - <a target="_blank" href="http://www.google.com/search?q=spartiti+Wild+West+End+Dire+Straits" title="Spartiti di Wild West End">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Wild+West+End+Dire+Straits" title="Accordi di Wild West End">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Wild+West+End+Dire+Straits" title="Testi di Wild West End">testi</a><br>
<b>5</b>. Sultans Of Swing - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sultans+Of+Swing+Dire+Straits" title="Spartiti di Sultans Of Swing">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sultans+Of+Swing+Dire+Straits" title="Accordi di Sultans Of Swing">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sultans+Of+Swing+Dire+Straits" title="Testi di Sultans Of Swing">testi</a><br>
<b>6</b>. Lions - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lions+Dire+Straits" title="Spartiti di Lions">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lions+Dire+Straits" title="Accordi di Lions">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lions+Dire+Straits" title="Testi di Lions">testi</a><br>
<b>7</b>. What's The Matter Baby? - <a target="_blank" href="http://www.google.com/search?q=spartiti+What%27s+The+Matter+Baby%3F+Dire+Straits" title="Spartiti di What's The Matter Baby?">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+What%27s+The+Matter+Baby%3F+Dire+Straits" title="Accordi di What's The Matter Baby?">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+What%27s+The+Matter+Baby%3F+Dire+Straits" title="Testi di What's The Matter Baby?">testi</a><br>
<b>8</b>. Tunnel Of Love - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tunnel+Of+Love+Dire+Straits" title="Spartiti di Tunnel Of Love">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tunnel+Of+Love+Dire+Straits" title="Accordi di Tunnel Of Love">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tunnel+Of+Love+Dire+Straits" title="Testi di Tunnel Of Love">testi</a><br>
<h2>On Every Street (1991) </h2>
<b>1</b>. Calling Elvis - <a target="_blank" href="http://www.google.com/search?q=spartiti+Calling+Elvis+Dire+Straits" title="Spartiti di Calling Elvis">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Calling+Elvis+Dire+Straits" title="Accordi di Calling Elvis">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Calling+Elvis+Dire+Straits" title="Testi di Calling Elvis">testi</a><br>
<b>2</b>. On Every Street - <a target="_blank" href="http://www.google.com/search?q=spartiti+On+Every+Street+Dire+Straits" title="Spartiti di On Every Street">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+On+Every+Street+Dire+Straits" title="Accordi di On Every Street">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+On+Every+Street+Dire+Straits" title="Testi di On Every Street">testi</a><br>
<b>3</b>. When It Comes To You - <a target="_blank" href="http://www.google.com/search?q=spartiti+When+It+Comes+To+You+Dire+Straits" title="Spartiti di When It Comes To You">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+When+It+Comes+To+You+Dire+Straits" title="Accordi di When It Comes To You">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+When+It+Comes+To+You+Dire+Straits" title="Testi di When It Comes To You">testi</a><br>
<b>4</b>. Fade To Black - <a target="_blank" href="http://www.google.com/search?q=spartiti+Fade+To+Black+Dire+Straits" title="Spartiti di Fade To Black">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Fade+To+Black+Dire+Straits" title="Accordi di Fade To Black">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Fade+To+Black+Dire+Straits" title="Testi di Fade To Black">testi</a><br>
<b>5</b>. The Bug - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+Bug+Dire+Straits" title="Spartiti di The Bug">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+Bug+Dire+Straits" title="Accordi di The Bug">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+Bug+Dire+Straits" title="Testi di The Bug">testi</a><br>
<b>6</b>. You And Your Friend - <a target="_blank" href="http://www.google.com/search?q=spartiti+You+And+Your+Friend+Dire+Straits" title="Spartiti di You And Your Friend">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+You+And+Your+Friend+Dire+Straits" title="Accordi di You And Your Friend">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+You+And+Your+Friend+Dire+Straits" title="Testi di You And Your Friend">testi</a><br>
<b>7</b>. Heavy Fuel - <a target="_blank" href="http://www.google.com/search?q=spartiti+Heavy+Fuel+Dire+Straits" title="Spartiti di Heavy Fuel">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Heavy+Fuel+Dire+Straits" title="Accordi di Heavy Fuel">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Heavy+Fuel+Dire+Straits" title="Testi di Heavy Fuel">testi</a><br>
<b>8</b>. Iron Hand - <a target="_blank" href="http://www.google.com/search?q=spartiti+Iron+Hand+Dire+Straits" title="Spartiti di Iron Hand">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Iron+Hand+Dire+Straits" title="Accordi di Iron Hand">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Iron+Hand+Dire+Straits" title="Testi di Iron Hand">testi</a><br>
<b>9</b>. Ticket To Heaven - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ticket+To+Heaven+Dire+Straits" title="Spartiti di Ticket To Heaven">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ticket+To+Heaven+Dire+Straits" title="Accordi di Ticket To Heaven">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ticket+To+Heaven+Dire+Straits" title="Testi di Ticket To Heaven">testi</a><br>
<b>10</b>. My Parties - <a target="_blank" href="http://www.google.com/search?q=spartiti+My+Parties+Dire+Straits" title="Spartiti di My Parties">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+My+Parties+Dire+Straits" title="Accordi di My Parties">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+My+Parties+Dire+Straits" title="Testi di My Parties">testi</a><br>
<b>11</b>. The Planet Of New Orleans - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+Planet+Of+New+Orleans+Dire+Straits" title="Spartiti di The Planet Of New Orleans">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+Planet+Of+New+Orleans+Dire+Straits" title="Accordi di The Planet Of New Orleans">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+Planet+Of+New+Orleans+Dire+Straits" title="Testi di The Planet Of New Orleans">testi</a><br>
<b>12</b>. How Long - <a target="_blank" href="http://www.google.com/search?q=spartiti+How+Long+Dire+Straits" title="Spartiti di How Long">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+How+Long+Dire+Straits" title="Accordi di How Long">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+How+Long+Dire+Straits" title="Testi di How Long">testi</a><br>
<h2>Money For Nothing (1988) </h2>
<b>1</b>. Sultans Of Swing - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sultans+Of+Swing+Dire+Straits" title="Spartiti di Sultans Of Swing">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sultans+Of+Swing+Dire+Straits" title="Accordi di Sultans Of Swing">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sultans+Of+Swing+Dire+Straits" title="Testi di Sultans Of Swing">testi</a><br>
<b>2</b>. Down To The Waterline - <a target="_blank" href="http://www.google.com/search?q=spartiti+Down+To+The+Waterline+Dire+Straits" title="Spartiti di Down To The Waterline">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Down+To+The+Waterline+Dire+Straits" title="Accordi di Down To The Waterline">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Down+To+The+Waterline+Dire+Straits" title="Testi di Down To The Waterline">testi</a><br>
<b>3</b>. Portobello Belle - <a target="_blank" href="http://www.google.com/search?q=spartiti+Portobello+Belle+Dire+Straits" title="Spartiti di Portobello Belle">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Portobello+Belle+Dire+Straits" title="Accordi di Portobello Belle">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Portobello+Belle+Dire+Straits" title="Testi di Portobello Belle">testi</a><br>
<b>4</b>. Twisting By The Pool (Remix) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Twisting+By+The+Pool+%28Remix%29+Dire+Straits" title="Spartiti di Twisting By The Pool (Remix)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Twisting+By+The+Pool+%28Remix%29+Dire+Straits" title="Accordi di Twisting By The Pool (Remix)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Twisting+By+The+Pool+%28Remix%29+Dire+Straits" title="Testi di Twisting By The Pool (Remix)">testi</a><br>
<b>5</b>. Tunnel Of Love - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tunnel+Of+Love+Dire+Straits" title="Spartiti di Tunnel Of Love">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tunnel+Of+Love+Dire+Straits" title="Accordi di Tunnel Of Love">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tunnel+Of+Love+Dire+Straits" title="Testi di Tunnel Of Love">testi</a><br>
<b>6</b>. Romeo And Juliet - <a target="_blank" href="http://www.google.com/search?q=spartiti+Romeo+And+Juliet+Dire+Straits" title="Spartiti di Romeo And Juliet">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Romeo+And+Juliet+Dire+Straits" title="Accordi di Romeo And Juliet">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Romeo+And+Juliet+Dire+Straits" title="Testi di Romeo And Juliet">testi</a><br>
<b>7</b>. Where Do You Think You're Going? - <a target="_blank" href="http://www.google.com/search?q=spartiti+Where+Do+You+Think+You%27re+Going%3F+Dire+Straits" title="Spartiti di Where Do You Think You're Going?">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Where+Do+You+Think+You%27re+Going%3F+Dire+Straits" title="Accordi di Where Do You Think You're Going?">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Where+Do+You+Think+You%27re+Going%3F+Dire+Straits" title="Testi di Where Do You Think You're Going?">testi</a><br>
<b>8</b>. Walk Of Life - <a target="_blank" href="http://www.google.com/search?q=spartiti+Walk+Of+Life+Dire+Straits" title="Spartiti di Walk Of Life">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Walk+Of+Life+Dire+Straits" title="Accordi di Walk Of Life">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Walk+Of+Life+Dire+Straits" title="Testi di Walk Of Life">testi</a><br>
<b>9</b>. Private Investigations - <a target="_blank" href="http://www.google.com/search?q=spartiti+Private+Investigations+Dire+Straits" title="Spartiti di Private Investigations">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Private+Investigations+Dire+Straits" title="Accordi di Private Investigations">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Private+Investigations+Dire+Straits" title="Testi di Private Investigations">testi</a><br>
<b>10</b>. Telegraph Road (Live Remix) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Telegraph+Road+%28Live+Remix%29+Dire+Straits" title="Spartiti di Telegraph Road (Live Remix)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Telegraph+Road+%28Live+Remix%29+Dire+Straits" title="Accordi di Telegraph Road (Live Remix)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Telegraph+Road+%28Live+Remix%29+Dire+Straits" title="Testi di Telegraph Road (Live Remix)">testi</a><br>
<b>11</b>. Money For Nothing - <a target="_blank" href="http://www.google.com/search?q=spartiti+Money+For+Nothing+Dire+Straits" title="Spartiti di Money For Nothing">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Money+For+Nothing+Dire+Straits" title="Accordi di Money For Nothing">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Money+For+Nothing+Dire+Straits" title="Testi di Money For Nothing">testi</a><br>
<b>12</b>. Brothers In Arms (7" Mix) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Brothers+In+Arms+%287%22+Mix%29+Dire+Straits" title="Spartiti di Brothers In Arms (7" Mix)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Brothers+In+Arms+%287%22+Mix%29+Dire+Straits" title="Accordi di Brothers In Arms (7" Mix)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Brothers+In+Arms+%287%22+Mix%29+Dire+Straits" title="Testi di Brothers In Arms (7" Mix)">testi</a><br>
<h2>Brothers In Arms (1985) </h2>
<b>1</b>. So Far Away - <a target="_blank" href="http://www.google.com/search?q=spartiti+So+Far+Away+Dire+Straits" title="Spartiti di So Far Away">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+So+Far+Away+Dire+Straits" title="Accordi di So Far Away">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+So+Far+Away+Dire+Straits" title="Testi di So Far Away">testi</a><br>
<b>2</b>. Money For Nothing - <a target="_blank" href="http://www.google.com/search?q=spartiti+Money+For+Nothing+Dire+Straits" title="Spartiti di Money For Nothing">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Money+For+Nothing+Dire+Straits" title="Accordi di Money For Nothing">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Money+For+Nothing+Dire+Straits" title="Testi di Money For Nothing">testi</a><br>
<b>3</b>. Walk Of Life - <a target="_blank" href="http://www.google.com/search?q=spartiti+Walk+Of+Life+Dire+Straits" title="Spartiti di Walk Of Life">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Walk+Of+Life+Dire+Straits" title="Accordi di Walk Of Life">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Walk+Of+Life+Dire+Straits" title="Testi di Walk Of Life">testi</a><br>
<b>4</b>. Your Latest Trick - <a target="_blank" href="http://www.google.com/search?q=spartiti+Your+Latest+Trick+Dire+Straits" title="Spartiti di Your Latest Trick">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Your+Latest+Trick+Dire+Straits" title="Accordi di Your Latest Trick">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Your+Latest+Trick+Dire+Straits" title="Testi di Your Latest Trick">testi</a><br>
<b>5</b>. Why Worry - <a target="_blank" href="http://www.google.com/search?q=spartiti+Why+Worry+Dire+Straits" title="Spartiti di Why Worry">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Why+Worry+Dire+Straits" title="Accordi di Why Worry">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Why+Worry+Dire+Straits" title="Testi di Why Worry">testi</a><br>
<b>6</b>. Ride Across The River - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ride+Across+The+River+Dire+Straits" title="Spartiti di Ride Across The River">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ride+Across+The+River+Dire+Straits" title="Accordi di Ride Across The River">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ride+Across+The+River+Dire+Straits" title="Testi di Ride Across The River">testi</a><br>
<b>7</b>. The Man's Too Strong - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+Man%27s+Too+Strong+Dire+Straits" title="Spartiti di The Man's Too Strong">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+Man%27s+Too+Strong+Dire+Straits" title="Accordi di The Man's Too Strong">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+Man%27s+Too+Strong+Dire+Straits" title="Testi di The Man's Too Strong">testi</a><br>
<b>8</b>. One World - <a target="_blank" href="http://www.google.com/search?q=spartiti+One+World+Dire+Straits" title="Spartiti di One World">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+One+World+Dire+Straits" title="Accordi di One World">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+One+World+Dire+Straits" title="Testi di One World">testi</a><br>
<b>9</b>. Brothers In Arms - <a target="_blank" href="http://www.google.com/search?q=spartiti+Brothers+In+Arms+Dire+Straits" title="Spartiti di Brothers In Arms">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Brothers+In+Arms+Dire+Straits" title="Accordi di Brothers In Arms">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Brothers+In+Arms+Dire+Straits" title="Testi di Brothers In Arms">testi</a><br>
<h2>Alchemy Live (1984) </h2>
<b>1</b>. Once Upon A Time In The West - <a target="_blank" href="http://www.google.com/search?q=spartiti+Once+Upon+A+Time+In+The+West+Dire+Straits" title="Spartiti di Once Upon A Time In The West">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Once+Upon+A+Time+In+The+West+Dire+Straits" title="Accordi di Once Upon A Time In The West">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Once+Upon+A+Time+In+The+West+Dire+Straits" title="Testi di Once Upon A Time In The West">testi</a><br>
<b>2</b>. Expresso Love - <a target="_blank" href="http://www.google.com/search?q=spartiti+Expresso+Love+Dire+Straits" title="Spartiti di Expresso Love">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Expresso+Love+Dire+Straits" title="Accordi di Expresso Love">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Expresso+Love+Dire+Straits" title="Testi di Expresso Love">testi</a><br>
<b>3</b>. Romeo And Juliet - <a target="_blank" href="http://www.google.com/search?q=spartiti+Romeo+And+Juliet+Dire+Straits" title="Spartiti di Romeo And Juliet">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Romeo+And+Juliet+Dire+Straits" title="Accordi di Romeo And Juliet">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Romeo+And+Juliet+Dire+Straits" title="Testi di Romeo And Juliet">testi</a><br>
<b>4</b>. Love Over Gold - <a target="_blank" href="http://www.google.com/search?q=spartiti+Love+Over+Gold+Dire+Straits" title="Spartiti di Love Over Gold">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Love+Over+Gold+Dire+Straits" title="Accordi di Love Over Gold">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Love+Over+Gold+Dire+Straits" title="Testi di Love Over Gold">testi</a><br>
<b>5</b>. Private Investigations - <a target="_blank" href="http://www.google.com/search?q=spartiti+Private+Investigations+Dire+Straits" title="Spartiti di Private Investigations">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Private+Investigations+Dire+Straits" title="Accordi di Private Investigations">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Private+Investigations+Dire+Straits" title="Testi di Private Investigations">testi</a><br>
<b>6</b>. Sultans Of Swing - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sultans+Of+Swing+Dire+Straits" title="Spartiti di Sultans Of Swing">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sultans+Of+Swing+Dire+Straits" title="Accordi di Sultans Of Swing">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sultans+Of+Swing+Dire+Straits" title="Testi di Sultans Of Swing">testi</a><br>
<b>7</b>. Tunnel Of Love - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tunnel+Of+Love+Dire+Straits" title="Spartiti di Tunnel Of Love">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tunnel+Of+Love+Dire+Straits" title="Accordi di Tunnel Of Love">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tunnel+Of+Love+Dire+Straits" title="Testi di Tunnel Of Love">testi</a><br>
<b>8</b>. Telegraph Road - <a target="_blank" href="http://www.google.com/search?q=spartiti+Telegraph+Road+Dire+Straits" title="Spartiti di Telegraph Road">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Telegraph+Road+Dire+Straits" title="Accordi di Telegraph Road">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Telegraph+Road+Dire+Straits" title="Testi di Telegraph Road">testi</a><br>
<b>9</b>. Solid Rock - <a target="_blank" href="http://www.google.com/search?q=spartiti+Solid+Rock+Dire+Straits" title="Spartiti di Solid Rock">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Solid+Rock+Dire+Straits" title="Accordi di Solid Rock">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Solid+Rock+Dire+Straits" title="Testi di Solid Rock">testi</a><br>
<h2>Love Over Gold (1982) </h2>
<b>1</b>. Telegraph Road - <a target="_blank" href="http://www.google.com/search?q=spartiti+Telegraph+Road+Dire+Straits" title="Spartiti di Telegraph Road">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Telegraph+Road+Dire+Straits" title="Accordi di Telegraph Road">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Telegraph+Road+Dire+Straits" title="Testi di Telegraph Road">testi</a><br>
<b>2</b>. Private Investigations - <a target="_blank" href="http://www.google.com/search?q=spartiti+Private+Investigations+Dire+Straits" title="Spartiti di Private Investigations">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Private+Investigations+Dire+Straits" title="Accordi di Private Investigations">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Private+Investigations+Dire+Straits" title="Testi di Private Investigations">testi</a><br>
<b>3</b>. Industrial Disease - <a target="_blank" href="http://www.google.com/search?q=spartiti+Industrial+Disease+Dire+Straits" title="Spartiti di Industrial Disease">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Industrial+Disease+Dire+Straits" title="Accordi di Industrial Disease">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Industrial+Disease+Dire+Straits" title="Testi di Industrial Disease">testi</a><br>
<b>4</b>. Love Over Gold - <a target="_blank" href="http://www.google.com/search?q=spartiti+Love+Over+Gold+Dire+Straits" title="Spartiti di Love Over Gold">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Love+Over+Gold+Dire+Straits" title="Accordi di Love Over Gold">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Love+Over+Gold+Dire+Straits" title="Testi di Love Over Gold">testi</a><br>
<b>5</b>. It Never Rains - <a target="_blank" href="http://www.google.com/search?q=spartiti+It+Never+Rains+Dire+Straits" title="Spartiti di It Never Rains">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+It+Never+Rains+Dire+Straits" title="Accordi di It Never Rains">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+It+Never+Rains+Dire+Straits" title="Testi di It Never Rains">testi</a><br>
<h2>Making Movies (1980) </h2>
<b>1</b>. Tunnel Of Love - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tunnel+Of+Love+Dire+Straits" title="Spartiti di Tunnel Of Love">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tunnel+Of+Love+Dire+Straits" title="Accordi di Tunnel Of Love">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tunnel+Of+Love+Dire+Straits" title="Testi di Tunnel Of Love">testi</a><br>
<b>2</b>. Romeo And Juliet - <a target="_blank" href="http://www.google.com/search?q=spartiti+Romeo+And+Juliet+Dire+Straits" title="Spartiti di Romeo And Juliet">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Romeo+And+Juliet+Dire+Straits" title="Accordi di Romeo And Juliet">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Romeo+And+Juliet+Dire+Straits" title="Testi di Romeo And Juliet">testi</a><br>
<b>3</b>. Skateaway - <a target="_blank" href="http://www.google.com/search?q=spartiti+Skateaway+Dire+Straits" title="Spartiti di Skateaway">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Skateaway+Dire+Straits" title="Accordi di Skateaway">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Skateaway+Dire+Straits" title="Testi di Skateaway">testi</a><br>
<b>4</b>. Expresso Love - <a target="_blank" href="http://www.google.com/search?q=spartiti+Expresso+Love+Dire+Straits" title="Spartiti di Expresso Love">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Expresso+Love+Dire+Straits" title="Accordi di Expresso Love">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Expresso+Love+Dire+Straits" title="Testi di Expresso Love">testi</a><br>
<b>5</b>. Hand In Hand - <a target="_blank" href="http://www.google.com/search?q=spartiti+Hand+In+Hand+Dire+Straits" title="Spartiti di Hand In Hand">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Hand+In+Hand+Dire+Straits" title="Accordi di Hand In Hand">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Hand+In+Hand+Dire+Straits" title="Testi di Hand In Hand">testi</a><br>
<b>6</b>. Solid Rock - <a target="_blank" href="http://www.google.com/search?q=spartiti+Solid+Rock+Dire+Straits" title="Spartiti di Solid Rock">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Solid+Rock+Dire+Straits" title="Accordi di Solid Rock">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Solid+Rock+Dire+Straits" title="Testi di Solid Rock">testi</a><br>
<b>7</b>. Les Boys - <a target="_blank" href="http://www.google.com/search?q=spartiti+Les+Boys+Dire+Straits" title="Spartiti di Les Boys">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Les+Boys+Dire+Straits" title="Accordi di Les Boys">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Les+Boys+Dire+Straits" title="Testi di Les Boys">testi</a><br>
<h2>Communique (1979) </h2>
<b>1</b>. Once Upon A Time In The West - <a target="_blank" href="http://www.google.com/search?q=spartiti+Once+Upon+A+Time+In+The+West+Dire+Straits" title="Spartiti di Once Upon A Time In The West">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Once+Upon+A+Time+In+The+West+Dire+Straits" title="Accordi di Once Upon A Time In The West">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Once+Upon+A+Time+In+The+West+Dire+Straits" title="Testi di Once Upon A Time In The West">testi</a><br>
<b>2</b>. News - <a target="_blank" href="http://www.google.com/search?q=spartiti+News+Dire+Straits" title="Spartiti di News">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+News+Dire+Straits" title="Accordi di News">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+News+Dire+Straits" title="Testi di News">testi</a><br>
<b>3</b>. Where Do You Think You're Going? - <a target="_blank" href="http://www.google.com/search?q=spartiti+Where+Do+You+Think+You%27re+Going%3F+Dire+Straits" title="Spartiti di Where Do You Think You're Going?">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Where+Do+You+Think+You%27re+Going%3F+Dire+Straits" title="Accordi di Where Do You Think You're Going?">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Where+Do+You+Think+You%27re+Going%3F+Dire+Straits" title="Testi di Where Do You Think You're Going?">testi</a><br>
<b>4</b>. Communique - <a target="_blank" href="http://www.google.com/search?q=spartiti+Communique+Dire+Straits" title="Spartiti di Communique">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Communique+Dire+Straits" title="Accordi di Communique">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Communique+Dire+Straits" title="Testi di Communique">testi</a><br>
<b>5</b>. Lady Writer - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lady+Writer+Dire+Straits" title="Spartiti di Lady Writer">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lady+Writer+Dire+Straits" title="Accordi di Lady Writer">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lady+Writer+Dire+Straits" title="Testi di Lady Writer">testi</a><br>
<b>6</b>. Angel Of Mercy - <a target="_blank" href="http://www.google.com/search?q=spartiti+Angel+Of+Mercy+Dire+Straits" title="Spartiti di Angel Of Mercy">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Angel+Of+Mercy+Dire+Straits" title="Accordi di Angel Of Mercy">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Angel+Of+Mercy+Dire+Straits" title="Testi di Angel Of Mercy">testi</a><br>
<b>7</b>. Portobello Belle - <a target="_blank" href="http://www.google.com/search?q=spartiti+Portobello+Belle+Dire+Straits" title="Spartiti di Portobello Belle">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Portobello+Belle+Dire+Straits" title="Accordi di Portobello Belle">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Portobello+Belle+Dire+Straits" title="Testi di Portobello Belle">testi</a><br>
<b>8</b>. Single Handed Sailor - <a target="_blank" href="http://www.google.com/search?q=spartiti+Single+Handed+Sailor+Dire+Straits" title="Spartiti di Single Handed Sailor">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Single+Handed+Sailor+Dire+Straits" title="Accordi di Single Handed Sailor">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Single+Handed+Sailor+Dire+Straits" title="Testi di Single Handed Sailor">testi</a><br>
<b>9</b>. Follow Me Home - <a target="_blank" href="http://www.google.com/search?q=spartiti+Follow+Me+Home+Dire+Straits" title="Spartiti di Follow Me Home">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Follow+Me+Home+Dire+Straits" title="Accordi di Follow Me Home">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Follow+Me+Home+Dire+Straits" title="Testi di Follow Me Home">testi</a><br>
<h2>Dire Straits (1978) </h2>
<b>1</b>. Down To The Waterline - <a target="_blank" href="http://www.google.com/search?q=spartiti+Down+To+The+Waterline+Dire+Straits" title="Spartiti di Down To The Waterline">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Down+To+The+Waterline+Dire+Straits" title="Accordi di Down To The Waterline">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Down+To+The+Waterline+Dire+Straits" title="Testi di Down To The Waterline">testi</a><br>
<b>2</b>. Water Of Love - <a target="_blank" href="http://www.google.com/search?q=spartiti+Water+Of+Love+Dire+Straits" title="Spartiti di Water Of Love">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Water+Of+Love+Dire+Straits" title="Accordi di Water Of Love">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Water+Of+Love+Dire+Straits" title="Testi di Water Of Love">testi</a><br>
<b>3</b>. Setting Me Up - <a target="_blank" href="http://www.google.com/search?q=spartiti+Setting+Me+Up+Dire+Straits" title="Spartiti di Setting Me Up">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Setting+Me+Up+Dire+Straits" title="Accordi di Setting Me Up">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Setting+Me+Up+Dire+Straits" title="Testi di Setting Me Up">testi</a><br>
<b>4</b>. Six Blade Knife - <a target="_blank" href="http://www.google.com/search?q=spartiti+Six+Blade+Knife+Dire+Straits" title="Spartiti di Six Blade Knife">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Six+Blade+Knife+Dire+Straits" title="Accordi di Six Blade Knife">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Six+Blade+Knife+Dire+Straits" title="Testi di Six Blade Knife">testi</a><br>
<b>5</b>. Southbound Again - <a target="_blank" href="http://www.google.com/search?q=spartiti+Southbound+Again+Dire+Straits" title="Spartiti di Southbound Again">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Southbound+Again+Dire+Straits" title="Accordi di Southbound Again">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Southbound+Again+Dire+Straits" title="Testi di Southbound Again">testi</a><br>
<b>6</b>. Sultans Of Swing - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sultans+Of+Swing+Dire+Straits" title="Spartiti di Sultans Of Swing">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sultans+Of+Swing+Dire+Straits" title="Accordi di Sultans Of Swing">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sultans+Of+Swing+Dire+Straits" title="Testi di Sultans Of Swing">testi</a><br>
<b>7</b>. In The Gallery - <a target="_blank" href="http://www.google.com/search?q=spartiti+In+The+Gallery+Dire+Straits" title="Spartiti di In The Gallery">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+In+The+Gallery+Dire+Straits" title="Accordi di In The Gallery">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+In+The+Gallery+Dire+Straits" title="Testi di In The Gallery">testi</a><br>
<b>8</b>. Wild West End - <a target="_blank" href="http://www.google.com/search?q=spartiti+Wild+West+End+Dire+Straits" title="Spartiti di Wild West End">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Wild+West+End+Dire+Straits" title="Accordi di Wild West End">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Wild+West+End+Dire+Straits" title="Testi di Wild West End">testi</a><br>
<b>9</b>. Lions - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lions+Dire+Straits" title="Spartiti di Lions">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lions+Dire+Straits" title="Accordi di Lions">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lions+Dire+Straits" title="Testi di Lions">testi</a><br>
<h2><a href="<?php echo "$base_website_address/$spartiti_dir" ?>/index.html" title="Trova accordi, spartiti, tablature e testi di tantissimi artisti">Torna all'indice degli artisti</a></h2>
