<!--
title: Trova spartiti per chitarra, accordi, testi e tablature di Cat Stevens. Discografia Cat Stevens.
description: Trova tutti gli spartiti, accordi, testi e tablature di Cat Stevens. Discografia Cat Stevens.
keywords: Discografia, Cat Stevens, spartiti, accordi, testi, tablature
template: tablature
-->
<h1>Trova spartiti per chitarra, accordi, testi e tablature di Cat Stevens</h1><h2>Leggere gli spartiti per chitarra, gli accordi e le tablature:</h2>
<?php require("tabdescription.php"); ?>
<?php require("adsense_leaderboard.php"); ?>
<h2>Discografia Cat Stevens:</h2>
<h2>The Very Best Of Cat Stevens (2000) </h2>
<b>1</b>. Matthew & Son - <a target="_blank" href="http://www.google.com/search?q=spartiti+Matthew+%26+Son+Cat+Stevens" title="Spartiti di Matthew & Son">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Matthew+%26+Son+Cat+Stevens" title="Accordi di Matthew & Son">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Matthew+%26+Son+Cat+Stevens" title="Testi di Matthew & Son">testi</a><br>
<b>2</b>. The First Cut Is The Deepest - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+First+Cut+Is+The+Deepest+Cat+Stevens" title="Spartiti di The First Cut Is The Deepest">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+First+Cut+Is+The+Deepest+Cat+Stevens" title="Accordi di The First Cut Is The Deepest">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+First+Cut+Is+The+Deepest+Cat+Stevens" title="Testi di The First Cut Is The Deepest">testi</a><br>
<b>3</b>. Lady D'arbanville - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lady+D%27arbanville+Cat+Stevens" title="Spartiti di Lady D'arbanville">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lady+D%27arbanville+Cat+Stevens" title="Accordi di Lady D'arbanville">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lady+D%27arbanville+Cat+Stevens" title="Testi di Lady D'arbanville">testi</a><br>
<b>4</b>. I've Got A Thing About Seeing My Grandson Grow Old - <a target="_blank" href="http://www.google.com/search?q=spartiti+I%27ve+Got+A+Thing+About+Seeing+My+Grandson+Grow+Old+Cat+Stevens" title="Spartiti di I've Got A Thing About Seeing My Grandson Grow Old">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+I%27ve+Got+A+Thing+About+Seeing+My+Grandson+Grow+Old+Cat+Stevens" title="Accordi di I've Got A Thing About Seeing My Grandson Grow Old">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+I%27ve+Got+A+Thing+About+Seeing+My+Grandson+Grow+Old+Cat+Stevens" title="Testi di I've Got A Thing About Seeing My Grandson Grow Old">testi</a><br>
<b>5</b>. Wild World - <a target="_blank" href="http://www.google.com/search?q=spartiti+Wild+World+Cat+Stevens" title="Spartiti di Wild World">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Wild+World+Cat+Stevens" title="Accordi di Wild World">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Wild+World+Cat+Stevens" title="Testi di Wild World">testi</a><br>
<b>6</b>. Where Do The Children Play - <a target="_blank" href="http://www.google.com/search?q=spartiti+Where+Do+The+Children+Play+Cat+Stevens" title="Spartiti di Where Do The Children Play">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Where+Do+The+Children+Play+Cat+Stevens" title="Accordi di Where Do The Children Play">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Where+Do+The+Children+Play+Cat+Stevens" title="Testi di Where Do The Children Play">testi</a><br>
<b>7</b>. Hard-headed Woman - <a target="_blank" href="http://www.google.com/search?q=spartiti+Hard-headed+Woman+Cat+Stevens" title="Spartiti di Hard-headed Woman">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Hard-headed+Woman+Cat+Stevens" title="Accordi di Hard-headed Woman">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Hard-headed+Woman+Cat+Stevens" title="Testi di Hard-headed Woman">testi</a><br>
<b>8</b>. Father And Son - <a target="_blank" href="http://www.google.com/search?q=spartiti+Father+And+Son+Cat+Stevens" title="Spartiti di Father And Son">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Father+And+Son+Cat+Stevens" title="Accordi di Father And Son">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Father+And+Son+Cat+Stevens" title="Testi di Father And Son">testi</a><br>
<b>9</b>. The Wind - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+Wind+Cat+Stevens" title="Spartiti di The Wind">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+Wind+Cat+Stevens" title="Accordi di The Wind">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+Wind+Cat+Stevens" title="Testi di The Wind">testi</a><br>
<b>10</b>. Morning Has Broken - <a target="_blank" href="http://www.google.com/search?q=spartiti+Morning+Has+Broken+Cat+Stevens" title="Spartiti di Morning Has Broken">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Morning+Has+Broken+Cat+Stevens" title="Accordi di Morning Has Broken">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Morning+Has+Broken+Cat+Stevens" title="Testi di Morning Has Broken">testi</a><br>
<b>11</b>. Moonshadow - <a target="_blank" href="http://www.google.com/search?q=spartiti+Moonshadow+Cat+Stevens" title="Spartiti di Moonshadow">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Moonshadow+Cat+Stevens" title="Accordi di Moonshadow">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Moonshadow+Cat+Stevens" title="Testi di Moonshadow">testi</a><br>
<b>12</b>. Peace Train - <a target="_blank" href="http://www.google.com/search?q=spartiti+Peace+Train+Cat+Stevens" title="Spartiti di Peace Train">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Peace+Train+Cat+Stevens" title="Accordi di Peace Train">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Peace+Train+Cat+Stevens" title="Testi di Peace Train">testi</a><br>
<b>13</b>. Sitting - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sitting+Cat+Stevens" title="Spartiti di Sitting">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sitting+Cat+Stevens" title="Accordi di Sitting">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sitting+Cat+Stevens" title="Testi di Sitting">testi</a><br>
<b>14</b>. Can't Keep It In - <a target="_blank" href="http://www.google.com/search?q=spartiti+Can%27t+Keep+It+In+Cat+Stevens" title="Spartiti di Can't Keep It In">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Can%27t+Keep+It+In+Cat+Stevens" title="Accordi di Can't Keep It In">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Can%27t+Keep+It+In+Cat+Stevens" title="Testi di Can't Keep It In">testi</a><br>
<b>15</b>. The Foreigner Suite - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+Foreigner+Suite+Cat+Stevens" title="Spartiti di The Foreigner Suite">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+Foreigner+Suite+Cat+Stevens" title="Accordi di The Foreigner Suite">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+Foreigner+Suite+Cat+Stevens" title="Testi di The Foreigner Suite">testi</a><br>
<b>16</b>. Oh Very Young - <a target="_blank" href="http://www.google.com/search?q=spartiti+Oh+Very+Young+Cat+Stevens" title="Spartiti di Oh Very Young">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Oh+Very+Young+Cat+Stevens" title="Accordi di Oh Very Young">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Oh+Very+Young+Cat+Stevens" title="Testi di Oh Very Young">testi</a><br>
<b>17</b>. Another Saturday Night - <a target="_blank" href="http://www.google.com/search?q=spartiti+Another+Saturday+Night+Cat+Stevens" title="Spartiti di Another Saturday Night">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Another+Saturday+Night+Cat+Stevens" title="Accordi di Another Saturday Night">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Another+Saturday+Night+Cat+Stevens" title="Testi di Another Saturday Night">testi</a><br>
<b>18</b>. Majik Of Majiks - <a target="_blank" href="http://www.google.com/search?q=spartiti+Majik+Of+Majiks+Cat+Stevens" title="Spartiti di Majik Of Majiks">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Majik+Of+Majiks+Cat+Stevens" title="Accordi di Majik Of Majiks">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Majik+Of+Majiks+Cat+Stevens" title="Testi di Majik Of Majiks">testi</a><br>
<b>19</b>. (Remember The Days Of The) Old Schoolyard - <a target="_blank" href="http://www.google.com/search?q=spartiti+%28Remember+The+Days+Of+The%29+Old+Schoolyard+Cat+Stevens" title="Spartiti di (Remember The Days Of The) Old Schoolyard">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+%28Remember+The+Days+Of+The%29+Old+Schoolyard+Cat+Stevens" title="Accordi di (Remember The Days Of The) Old Schoolyard">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+%28Remember+The+Days+Of+The%29+Old+Schoolyard+Cat+Stevens" title="Testi di (Remember The Days Of The) Old Schoolyard">testi</a><br>
<b>20</b>. Just Another Night - <a target="_blank" href="http://www.google.com/search?q=spartiti+Just+Another+Night+Cat+Stevens" title="Spartiti di Just Another Night">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Just+Another+Night+Cat+Stevens" title="Accordi di Just Another Night">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Just+Another+Night+Cat+Stevens" title="Testi di Just Another Night">testi</a><br>
<h2>Footsteps In The Dark: Greatest Hits Volume Two (1984) </h2>
<b>1</b>. The Wind - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+Wind+Cat+Stevens" title="Spartiti di The Wind">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+Wind+Cat+Stevens" title="Accordi di The Wind">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+Wind+Cat+Stevens" title="Testi di The Wind">testi</a><br>
<b>2</b>. (I Never Wanted) To Be A Star - <a target="_blank" href="http://www.google.com/search?q=spartiti+%28I+Never+Wanted%29+To+Be+A+Star+Cat+Stevens" title="Spartiti di (I Never Wanted) To Be A Star">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+%28I+Never+Wanted%29+To+Be+A+Star+Cat+Stevens" title="Accordi di (I Never Wanted) To Be A Star">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+%28I+Never+Wanted%29+To+Be+A+Star+Cat+Stevens" title="Testi di (I Never Wanted) To Be A Star">testi</a><br>
<b>3</b>. Katmandu - <a target="_blank" href="http://www.google.com/search?q=spartiti+Katmandu+Cat+Stevens" title="Spartiti di Katmandu">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Katmandu+Cat+Stevens" title="Accordi di Katmandu">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Katmandu+Cat+Stevens" title="Testi di Katmandu">testi</a><br>
<b>4</b>. I Want To Live In A Wigwam - <a target="_blank" href="http://www.google.com/search?q=spartiti+I+Want+To+Live+In+A+Wigwam+Cat+Stevens" title="Spartiti di I Want To Live In A Wigwam">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+I+Want+To+Live+In+A+Wigwam+Cat+Stevens" title="Accordi di I Want To Live In A Wigwam">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+I+Want+To+Live+In+A+Wigwam+Cat+Stevens" title="Testi di I Want To Live In A Wigwam">testi</a><br>
<b>5</b>. Trouble - <a target="_blank" href="http://www.google.com/search?q=spartiti+Trouble+Cat+Stevens" title="Spartiti di Trouble">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Trouble+Cat+Stevens" title="Accordi di Trouble">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Trouble+Cat+Stevens" title="Testi di Trouble">testi</a><br>
<b>6</b>. On The Road To Findout - <a target="_blank" href="http://www.google.com/search?q=spartiti+On+The+Road+To+Findout+Cat+Stevens" title="Spartiti di On The Road To Findout">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+On+The+Road+To+Findout+Cat+Stevens" title="Accordi di On The Road To Findout">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+On+The+Road+To+Findout+Cat+Stevens" title="Testi di On The Road To Findout">testi</a><br>
<b>7</b>. If You Want To Sing Out, Sing Out - <a target="_blank" href="http://www.google.com/search?q=spartiti+If+You+Want+To+Sing+Out%2C+Sing+Out+Cat+Stevens" title="Spartiti di If You Want To Sing Out, Sing Out">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+If+You+Want+To+Sing+Out%2C+Sing+Out+Cat+Stevens" title="Accordi di If You Want To Sing Out, Sing Out">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+If+You+Want+To+Sing+Out%2C+Sing+Out+Cat+Stevens" title="Testi di If You Want To Sing Out, Sing Out">testi</a><br>
<b>8</b>. Where Do The Children Play - <a target="_blank" href="http://www.google.com/search?q=spartiti+Where+Do+The+Children+Play+Cat+Stevens" title="Spartiti di Where Do The Children Play">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Where+Do+The+Children+Play+Cat+Stevens" title="Accordi di Where Do The Children Play">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Where+Do+The+Children+Play+Cat+Stevens" title="Testi di Where Do The Children Play">testi</a><br>
<b>9</b>. Daytime - <a target="_blank" href="http://www.google.com/search?q=spartiti+Daytime+Cat+Stevens" title="Spartiti di Daytime">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Daytime+Cat+Stevens" title="Accordi di Daytime">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Daytime+Cat+Stevens" title="Testi di Daytime">testi</a><br>
<b>10</b>. Don't Be Shy - <a target="_blank" href="http://www.google.com/search?q=spartiti+Don%27t+Be+Shy+Cat+Stevens" title="Spartiti di Don't Be Shy">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Don%27t+Be+Shy+Cat+Stevens" title="Accordi di Don't Be Shy">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Don%27t+Be+Shy+Cat+Stevens" title="Testi di Don't Be Shy">testi</a><br>
<b>11</b>. How Can I Tell You - <a target="_blank" href="http://www.google.com/search?q=spartiti+How+Can+I+Tell+You+Cat+Stevens" title="Spartiti di How Can I Tell You">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+How+Can+I+Tell+You+Cat+Stevens" title="Accordi di How Can I Tell You">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+How+Can+I+Tell+You+Cat+Stevens" title="Testi di How Can I Tell You">testi</a><br>
<b>12</b>. Father And Son - <a target="_blank" href="http://www.google.com/search?q=spartiti+Father+And+Son+Cat+Stevens" title="Spartiti di Father And Son">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Father+And+Son+Cat+Stevens" title="Accordi di Father And Son">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Father+And+Son+Cat+Stevens" title="Testi di Father And Son">testi</a><br>
<b>13</b>. The Hurt - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+Hurt+Cat+Stevens" title="Spartiti di The Hurt">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+Hurt+Cat+Stevens" title="Accordi di The Hurt">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+Hurt+Cat+Stevens" title="Testi di The Hurt">testi</a><br>
<b>14</b>. Silent Sunlight - <a target="_blank" href="http://www.google.com/search?q=spartiti+Silent+Sunlight+Cat+Stevens" title="Spartiti di Silent Sunlight">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Silent+Sunlight+Cat+Stevens" title="Accordi di Silent Sunlight">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Silent+Sunlight+Cat+Stevens" title="Testi di Silent Sunlight">testi</a><br>
<h2>Back To Earth (1978) </h2>
<b>1</b>. Just Another Night - <a target="_blank" href="http://www.google.com/search?q=spartiti+Just+Another+Night+Cat+Stevens" title="Spartiti di Just Another Night">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Just+Another+Night+Cat+Stevens" title="Accordi di Just Another Night">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Just+Another+Night+Cat+Stevens" title="Testi di Just Another Night">testi</a><br>
<b>2</b>. Daytime - <a target="_blank" href="http://www.google.com/search?q=spartiti+Daytime+Cat+Stevens" title="Spartiti di Daytime">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Daytime+Cat+Stevens" title="Accordi di Daytime">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Daytime+Cat+Stevens" title="Testi di Daytime">testi</a><br>
<b>3</b>. Bad Brakes - <a target="_blank" href="http://www.google.com/search?q=spartiti+Bad+Brakes+Cat+Stevens" title="Spartiti di Bad Brakes">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Bad+Brakes+Cat+Stevens" title="Accordi di Bad Brakes">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Bad+Brakes+Cat+Stevens" title="Testi di Bad Brakes">testi</a><br>
<b>4</b>. Randy - <a target="_blank" href="http://www.google.com/search?q=spartiti+Randy+Cat+Stevens" title="Spartiti di Randy">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Randy+Cat+Stevens" title="Accordi di Randy">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Randy+Cat+Stevens" title="Testi di Randy">testi</a><br>
<b>5</b>. The Artist - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+Artist+Cat+Stevens" title="Spartiti di The Artist">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+Artist+Cat+Stevens" title="Accordi di The Artist">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+Artist+Cat+Stevens" title="Testi di The Artist">testi</a><br>
<b>6</b>. Last Love Song - <a target="_blank" href="http://www.google.com/search?q=spartiti+Last+Love+Song+Cat+Stevens" title="Spartiti di Last Love Song">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Last+Love+Song+Cat+Stevens" title="Accordi di Last Love Song">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Last+Love+Song+Cat+Stevens" title="Testi di Last Love Song">testi</a><br>
<b>7</b>. Nascimento - <a target="_blank" href="http://www.google.com/search?q=spartiti+Nascimento+Cat+Stevens" title="Spartiti di Nascimento">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Nascimento+Cat+Stevens" title="Accordi di Nascimento">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Nascimento+Cat+Stevens" title="Testi di Nascimento">testi</a><br>
<b>8</b>. Father - <a target="_blank" href="http://www.google.com/search?q=spartiti+Father+Cat+Stevens" title="Spartiti di Father">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Father+Cat+Stevens" title="Accordi di Father">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Father+Cat+Stevens" title="Testi di Father">testi</a><br>
<b>9</b>. New York Times - <a target="_blank" href="http://www.google.com/search?q=spartiti+New+York+Times+Cat+Stevens" title="Spartiti di New York Times">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+New+York+Times+Cat+Stevens" title="Accordi di New York Times">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+New+York+Times+Cat+Stevens" title="Testi di New York Times">testi</a><br>
<b>10</b>. Never - <a target="_blank" href="http://www.google.com/search?q=spartiti+Never+Cat+Stevens" title="Spartiti di Never">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Never+Cat+Stevens" title="Accordi di Never">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Never+Cat+Stevens" title="Testi di Never">testi</a><br>
<h2>Izitso (1977) </h2>
<b>1</b>. (Remember The Days Of The) Old Schoolyard - <a target="_blank" href="http://www.google.com/search?q=spartiti+%28Remember+The+Days+Of+The%29+Old+Schoolyard+Cat+Stevens" title="Spartiti di (Remember The Days Of The) Old Schoolyard">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+%28Remember+The+Days+Of+The%29+Old+Schoolyard+Cat+Stevens" title="Accordi di (Remember The Days Of The) Old Schoolyard">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+%28Remember+The+Days+Of+The%29+Old+Schoolyard+Cat+Stevens" title="Testi di (Remember The Days Of The) Old Schoolyard">testi</a><br>
<b>2</b>. Life - <a target="_blank" href="http://www.google.com/search?q=spartiti+Life+Cat+Stevens" title="Spartiti di Life">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Life+Cat+Stevens" title="Accordi di Life">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Life+Cat+Stevens" title="Testi di Life">testi</a><br>
<b>3</b>. Killin' Time - <a target="_blank" href="http://www.google.com/search?q=spartiti+Killin%27+Time+Cat+Stevens" title="Spartiti di Killin' Time">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Killin%27+Time+Cat+Stevens" title="Accordi di Killin' Time">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Killin%27+Time+Cat+Stevens" title="Testi di Killin' Time">testi</a><br>
<b>4</b>. Kypros - <a target="_blank" href="http://www.google.com/search?q=spartiti+Kypros+Cat+Stevens" title="Spartiti di Kypros">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Kypros+Cat+Stevens" title="Accordi di Kypros">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Kypros+Cat+Stevens" title="Testi di Kypros">testi</a><br>
<b>5</b>. Bonfire - <a target="_blank" href="http://www.google.com/search?q=spartiti+Bonfire+Cat+Stevens" title="Spartiti di Bonfire">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Bonfire+Cat+Stevens" title="Accordi di Bonfire">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Bonfire+Cat+Stevens" title="Testi di Bonfire">testi</a><br>
<b>6</b>. (I Never Wanted) To Be A Star - <a target="_blank" href="http://www.google.com/search?q=spartiti+%28I+Never+Wanted%29+To+Be+A+Star+Cat+Stevens" title="Spartiti di (I Never Wanted) To Be A Star">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+%28I+Never+Wanted%29+To+Be+A+Star+Cat+Stevens" title="Accordi di (I Never Wanted) To Be A Star">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+%28I+Never+Wanted%29+To+Be+A+Star+Cat+Stevens" title="Testi di (I Never Wanted) To Be A Star">testi</a><br>
<b>7</b>. Crazy - <a target="_blank" href="http://www.google.com/search?q=spartiti+Crazy+Cat+Stevens" title="Spartiti di Crazy">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Crazy+Cat+Stevens" title="Accordi di Crazy">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Crazy+Cat+Stevens" title="Testi di Crazy">testi</a><br>
<b>8</b>. Sweet Jamaica - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sweet+Jamaica+Cat+Stevens" title="Spartiti di Sweet Jamaica">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sweet+Jamaica+Cat+Stevens" title="Accordi di Sweet Jamaica">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sweet+Jamaica+Cat+Stevens" title="Testi di Sweet Jamaica">testi</a><br>
<b>9</b>. Was Dog A Doughnut - <a target="_blank" href="http://www.google.com/search?q=spartiti+Was+Dog+A+Doughnut+Cat+Stevens" title="Spartiti di Was Dog A Doughnut">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Was+Dog+A+Doughnut+Cat+Stevens" title="Accordi di Was Dog A Doughnut">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Was+Dog+A+Doughnut+Cat+Stevens" title="Testi di Was Dog A Doughnut">testi</a><br>
<b>10</b>. Child For A Day - <a target="_blank" href="http://www.google.com/search?q=spartiti+Child+For+A+Day+Cat+Stevens" title="Spartiti di Child For A Day">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Child+For+A+Day+Cat+Stevens" title="Accordi di Child For A Day">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Child+For+A+Day+Cat+Stevens" title="Testi di Child For A Day">testi</a><br>
<h2>The Doves [Single] (1977) </h2>
<b>1</b>. (I Never Wanted) To Be A Star - <a target="_blank" href="http://www.google.com/search?q=spartiti+%28I+Never+Wanted%29+To+Be+A+Star+Cat+Stevens" title="Spartiti di (I Never Wanted) To Be A Star">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+%28I+Never+Wanted%29+To+Be+A+Star+Cat+Stevens" title="Accordi di (I Never Wanted) To Be A Star">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+%28I+Never+Wanted%29+To+Be+A+Star+Cat+Stevens" title="Testi di (I Never Wanted) To Be A Star">testi</a><br>
<b>2</b>. The Doves - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+Doves+Cat+Stevens" title="Spartiti di The Doves">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+Doves+Cat+Stevens" title="Accordi di The Doves">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+Doves+Cat+Stevens" title="Testi di The Doves">testi</a><br>
<h2>Greatest Hits (1975) </h2>
<b>1</b>. Wild World - <a target="_blank" href="http://www.google.com/search?q=spartiti+Wild+World+Cat+Stevens" title="Spartiti di Wild World">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Wild+World+Cat+Stevens" title="Accordi di Wild World">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Wild+World+Cat+Stevens" title="Testi di Wild World">testi</a><br>
<b>2</b>. Oh Very Young - <a target="_blank" href="http://www.google.com/search?q=spartiti+Oh+Very+Young+Cat+Stevens" title="Spartiti di Oh Very Young">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Oh+Very+Young+Cat+Stevens" title="Accordi di Oh Very Young">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Oh+Very+Young+Cat+Stevens" title="Testi di Oh Very Young">testi</a><br>
<b>3</b>. Can't Keep It In - <a target="_blank" href="http://www.google.com/search?q=spartiti+Can%27t+Keep+It+In+Cat+Stevens" title="Spartiti di Can't Keep It In">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Can%27t+Keep+It+In+Cat+Stevens" title="Accordi di Can't Keep It In">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Can%27t+Keep+It+In+Cat+Stevens" title="Testi di Can't Keep It In">testi</a><br>
<b>4</b>. Hard-headed Woman - <a target="_blank" href="http://www.google.com/search?q=spartiti+Hard-headed+Woman+Cat+Stevens" title="Spartiti di Hard-headed Woman">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Hard-headed+Woman+Cat+Stevens" title="Accordi di Hard-headed Woman">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Hard-headed+Woman+Cat+Stevens" title="Testi di Hard-headed Woman">testi</a><br>
<b>5</b>. Moonshadow - <a target="_blank" href="http://www.google.com/search?q=spartiti+Moonshadow+Cat+Stevens" title="Spartiti di Moonshadow">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Moonshadow+Cat+Stevens" title="Accordi di Moonshadow">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Moonshadow+Cat+Stevens" title="Testi di Moonshadow">testi</a><br>
<b>6</b>. Two Fine People - <a target="_blank" href="http://www.google.com/search?q=spartiti+Two+Fine+People+Cat+Stevens" title="Spartiti di Two Fine People">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Two+Fine+People+Cat+Stevens" title="Accordi di Two Fine People">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Two+Fine+People+Cat+Stevens" title="Testi di Two Fine People">testi</a><br>
<b>7</b>. Peace Train - <a target="_blank" href="http://www.google.com/search?q=spartiti+Peace+Train+Cat+Stevens" title="Spartiti di Peace Train">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Peace+Train+Cat+Stevens" title="Accordi di Peace Train">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Peace+Train+Cat+Stevens" title="Testi di Peace Train">testi</a><br>
<b>8</b>. Ready - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ready+Cat+Stevens" title="Spartiti di Ready">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ready+Cat+Stevens" title="Accordi di Ready">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ready+Cat+Stevens" title="Testi di Ready">testi</a><br>
<b>9</b>. Father And Son - <a target="_blank" href="http://www.google.com/search?q=spartiti+Father+And+Son+Cat+Stevens" title="Spartiti di Father And Son">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Father+And+Son+Cat+Stevens" title="Accordi di Father And Son">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Father+And+Son+Cat+Stevens" title="Testi di Father And Son">testi</a><br>
<b>10</b>. Sitting - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sitting+Cat+Stevens" title="Spartiti di Sitting">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sitting+Cat+Stevens" title="Accordi di Sitting">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sitting+Cat+Stevens" title="Testi di Sitting">testi</a><br>
<b>11</b>. Morning Has Broken - <a target="_blank" href="http://www.google.com/search?q=spartiti+Morning+Has+Broken+Cat+Stevens" title="Spartiti di Morning Has Broken">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Morning+Has+Broken+Cat+Stevens" title="Accordi di Morning Has Broken">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Morning+Has+Broken+Cat+Stevens" title="Testi di Morning Has Broken">testi</a><br>
<b>12</b>. Another Saturday Night - <a target="_blank" href="http://www.google.com/search?q=spartiti+Another+Saturday+Night+Cat+Stevens" title="Spartiti di Another Saturday Night">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Another+Saturday+Night+Cat+Stevens" title="Accordi di Another Saturday Night">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Another+Saturday+Night+Cat+Stevens" title="Testi di Another Saturday Night">testi</a><br>
<h2>Numbers (1975) </h2>
<b>1</b>. Whistlestar - <a target="_blank" href="http://www.google.com/search?q=spartiti+Whistlestar+Cat+Stevens" title="Spartiti di Whistlestar">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Whistlestar+Cat+Stevens" title="Accordi di Whistlestar">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Whistlestar+Cat+Stevens" title="Testi di Whistlestar">testi</a><br>
<b>2</b>. Novim's Nightmare - <a target="_blank" href="http://www.google.com/search?q=spartiti+Novim%27s+Nightmare+Cat+Stevens" title="Spartiti di Novim's Nightmare">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Novim%27s+Nightmare+Cat+Stevens" title="Accordi di Novim's Nightmare">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Novim%27s+Nightmare+Cat+Stevens" title="Testi di Novim's Nightmare">testi</a><br>
<b>3</b>. Majik Of Majiks - <a target="_blank" href="http://www.google.com/search?q=spartiti+Majik+Of+Majiks+Cat+Stevens" title="Spartiti di Majik Of Majiks">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Majik+Of+Majiks+Cat+Stevens" title="Accordi di Majik Of Majiks">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Majik+Of+Majiks+Cat+Stevens" title="Testi di Majik Of Majiks">testi</a><br>
<b>4</b>. Drywood - <a target="_blank" href="http://www.google.com/search?q=spartiti+Drywood+Cat+Stevens" title="Spartiti di Drywood">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Drywood+Cat+Stevens" title="Accordi di Drywood">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Drywood+Cat+Stevens" title="Testi di Drywood">testi</a><br>
<b>5</b>. Banapple Gas - <a target="_blank" href="http://www.google.com/search?q=spartiti+Banapple+Gas+Cat+Stevens" title="Spartiti di Banapple Gas">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Banapple+Gas+Cat+Stevens" title="Accordi di Banapple Gas">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Banapple+Gas+Cat+Stevens" title="Testi di Banapple Gas">testi</a><br>
<b>6</b>. Land O' Free Love & Goodbye - <a target="_blank" href="http://www.google.com/search?q=spartiti+Land+O%27+Free+Love+%26+Goodbye+Cat+Stevens" title="Spartiti di Land O' Free Love & Goodbye">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Land+O%27+Free+Love+%26+Goodbye+Cat+Stevens" title="Accordi di Land O' Free Love & Goodbye">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Land+O%27+Free+Love+%26+Goodbye+Cat+Stevens" title="Testi di Land O' Free Love & Goodbye">testi</a><br>
<b>7</b>. Jzero - <a target="_blank" href="http://www.google.com/search?q=spartiti+Jzero+Cat+Stevens" title="Spartiti di Jzero">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Jzero+Cat+Stevens" title="Accordi di Jzero">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Jzero+Cat+Stevens" title="Testi di Jzero">testi</a><br>
<b>8</b>. Home - <a target="_blank" href="http://www.google.com/search?q=spartiti+Home+Cat+Stevens" title="Spartiti di Home">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Home+Cat+Stevens" title="Accordi di Home">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Home+Cat+Stevens" title="Testi di Home">testi</a><br>
<b>9</b>. Monad's Anthem - <a target="_blank" href="http://www.google.com/search?q=spartiti+Monad%27s+Anthem+Cat+Stevens" title="Spartiti di Monad's Anthem">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Monad%27s+Anthem+Cat+Stevens" title="Accordi di Monad's Anthem">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Monad%27s+Anthem+Cat+Stevens" title="Testi di Monad's Anthem">testi</a><br>
<h2>Saturnight (1974) </h2>
<b>1</b>. Wild World - <a target="_blank" href="http://www.google.com/search?q=spartiti+Wild+World+Cat+Stevens" title="Spartiti di Wild World">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Wild+World+Cat+Stevens" title="Accordi di Wild World">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Wild+World+Cat+Stevens" title="Testi di Wild World">testi</a><br>
<b>2</b>. Oh Very Young - <a target="_blank" href="http://www.google.com/search?q=spartiti+Oh+Very+Young+Cat+Stevens" title="Spartiti di Oh Very Young">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Oh+Very+Young+Cat+Stevens" title="Accordi di Oh Very Young">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Oh+Very+Young+Cat+Stevens" title="Testi di Oh Very Young">testi</a><br>
<b>3</b>. Sitting - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sitting+Cat+Stevens" title="Spartiti di Sitting">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sitting+Cat+Stevens" title="Accordi di Sitting">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sitting+Cat+Stevens" title="Testi di Sitting">testi</a><br>
<b>4</b>. Where Do The Children Play - <a target="_blank" href="http://www.google.com/search?q=spartiti+Where+Do+The+Children+Play+Cat+Stevens" title="Spartiti di Where Do The Children Play">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Where+Do+The+Children+Play+Cat+Stevens" title="Accordi di Where Do The Children Play">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Where+Do+The+Children+Play+Cat+Stevens" title="Testi di Where Do The Children Play">testi</a><br>
<b>5</b>. Lady D'arbanville - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lady+D%27arbanville+Cat+Stevens" title="Spartiti di Lady D'arbanville">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lady+D%27arbanville+Cat+Stevens" title="Accordi di Lady D'arbanville">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lady+D%27arbanville+Cat+Stevens" title="Testi di Lady D'arbanville">testi</a><br>
<b>6</b>. Another Saturday Night - <a target="_blank" href="http://www.google.com/search?q=spartiti+Another+Saturday+Night+Cat+Stevens" title="Spartiti di Another Saturday Night">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Another+Saturday+Night+Cat+Stevens" title="Accordi di Another Saturday Night">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Another+Saturday+Night+Cat+Stevens" title="Testi di Another Saturday Night">testi</a><br>
<b>7</b>. Hard-headed Woman - <a target="_blank" href="http://www.google.com/search?q=spartiti+Hard-headed+Woman+Cat+Stevens" title="Spartiti di Hard-headed Woman">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Hard-headed+Woman+Cat+Stevens" title="Accordi di Hard-headed Woman">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Hard-headed+Woman+Cat+Stevens" title="Testi di Hard-headed Woman">testi</a><br>
<b>8</b>. Peace Train - <a target="_blank" href="http://www.google.com/search?q=spartiti+Peace+Train+Cat+Stevens" title="Spartiti di Peace Train">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Peace+Train+Cat+Stevens" title="Accordi di Peace Train">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Peace+Train+Cat+Stevens" title="Testi di Peace Train">testi</a><br>
<b>9</b>. Father And Son - <a target="_blank" href="http://www.google.com/search?q=spartiti+Father+And+Son+Cat+Stevens" title="Spartiti di Father And Son">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Father+And+Son+Cat+Stevens" title="Accordi di Father And Son">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Father+And+Son+Cat+Stevens" title="Testi di Father And Son">testi</a><br>
<b>10</b>. King Of Trees - <a target="_blank" href="http://www.google.com/search?q=spartiti+King+Of+Trees+Cat+Stevens" title="Spartiti di King Of Trees">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+King+Of+Trees+Cat+Stevens" title="Accordi di King Of Trees">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+King+Of+Trees+Cat+Stevens" title="Testi di King Of Trees">testi</a><br>
<b>11</b>. A Bad Penny - <a target="_blank" href="http://www.google.com/search?q=spartiti+A+Bad+Penny+Cat+Stevens" title="Spartiti di A Bad Penny">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+A+Bad+Penny+Cat+Stevens" title="Accordi di A Bad Penny">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+A+Bad+Penny+Cat+Stevens" title="Testi di A Bad Penny">testi</a><br>
<b>12</b>. Bitterblue - <a target="_blank" href="http://www.google.com/search?q=spartiti+Bitterblue+Cat+Stevens" title="Spartiti di Bitterblue">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Bitterblue+Cat+Stevens" title="Accordi di Bitterblue">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Bitterblue+Cat+Stevens" title="Testi di Bitterblue">testi</a><br>
<h2>Buddha And The Chocolate Box (1974) </h2>
<b>1</b>. Music - <a target="_blank" href="http://www.google.com/search?q=spartiti+Music+Cat+Stevens" title="Spartiti di Music">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Music+Cat+Stevens" title="Accordi di Music">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Music+Cat+Stevens" title="Testi di Music">testi</a><br>
<b>2</b>. Oh Very Young - <a target="_blank" href="http://www.google.com/search?q=spartiti+Oh+Very+Young+Cat+Stevens" title="Spartiti di Oh Very Young">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Oh+Very+Young+Cat+Stevens" title="Accordi di Oh Very Young">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Oh+Very+Young+Cat+Stevens" title="Testi di Oh Very Young">testi</a><br>
<b>3</b>. Sun C/79 - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sun+C%2F79+Cat+Stevens" title="Spartiti di Sun C/79">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sun+C%2F79+Cat+Stevens" title="Accordi di Sun C/79">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sun+C%2F79+Cat+Stevens" title="Testi di Sun C/79">testi</a><br>
<b>4</b>. Ghost Town - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ghost+Town+Cat+Stevens" title="Spartiti di Ghost Town">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ghost+Town+Cat+Stevens" title="Accordi di Ghost Town">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ghost+Town+Cat+Stevens" title="Testi di Ghost Town">testi</a><br>
<b>5</b>. Jesus - <a target="_blank" href="http://www.google.com/search?q=spartiti+Jesus+Cat+Stevens" title="Spartiti di Jesus">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Jesus+Cat+Stevens" title="Accordi di Jesus">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Jesus+Cat+Stevens" title="Testi di Jesus">testi</a><br>
<b>6</b>. Ready - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ready+Cat+Stevens" title="Spartiti di Ready">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ready+Cat+Stevens" title="Accordi di Ready">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ready+Cat+Stevens" title="Testi di Ready">testi</a><br>
<b>7</b>. King Of Trees - <a target="_blank" href="http://www.google.com/search?q=spartiti+King+Of+Trees+Cat+Stevens" title="Spartiti di King Of Trees">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+King+Of+Trees+Cat+Stevens" title="Accordi di King Of Trees">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+King+Of+Trees+Cat+Stevens" title="Testi di King Of Trees">testi</a><br>
<b>8</b>. A Bad Penny - <a target="_blank" href="http://www.google.com/search?q=spartiti+A+Bad+Penny+Cat+Stevens" title="Spartiti di A Bad Penny">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+A+Bad+Penny+Cat+Stevens" title="Accordi di A Bad Penny">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+A+Bad+Penny+Cat+Stevens" title="Testi di A Bad Penny">testi</a><br>
<b>9</b>. Home In The Sky - <a target="_blank" href="http://www.google.com/search?q=spartiti+Home+In+The+Sky+Cat+Stevens" title="Spartiti di Home In The Sky">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Home+In+The+Sky+Cat+Stevens" title="Accordi di Home In The Sky">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Home+In+The+Sky+Cat+Stevens" title="Testi di Home In The Sky">testi</a><br>
<h2>Foreigner (1973) </h2>
<b>1</b>. The Foreigner Suite - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+Foreigner+Suite+Cat+Stevens" title="Spartiti di The Foreigner Suite">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+Foreigner+Suite+Cat+Stevens" title="Accordi di The Foreigner Suite">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+Foreigner+Suite+Cat+Stevens" title="Testi di The Foreigner Suite">testi</a><br>
<b>2</b>. The Hurt - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+Hurt+Cat+Stevens" title="Spartiti di The Hurt">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+Hurt+Cat+Stevens" title="Accordi di The Hurt">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+Hurt+Cat+Stevens" title="Testi di The Hurt">testi</a><br>
<b>3</b>. How Many Times - <a target="_blank" href="http://www.google.com/search?q=spartiti+How+Many+Times+Cat+Stevens" title="Spartiti di How Many Times">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+How+Many+Times+Cat+Stevens" title="Accordi di How Many Times">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+How+Many+Times+Cat+Stevens" title="Testi di How Many Times">testi</a><br>
<b>4</b>. Later - <a target="_blank" href="http://www.google.com/search?q=spartiti+Later+Cat+Stevens" title="Spartiti di Later">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Later+Cat+Stevens" title="Accordi di Later">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Later+Cat+Stevens" title="Testi di Later">testi</a><br>
<b>5</b>. 100 I Dream - <a target="_blank" href="http://www.google.com/search?q=spartiti+100+I+Dream+Cat+Stevens" title="Spartiti di 100 I Dream">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+100+I+Dream+Cat+Stevens" title="Accordi di 100 I Dream">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+100+I+Dream+Cat+Stevens" title="Testi di 100 I Dream">testi</a><br>
<h2>Catch Bull At Four (1972) </h2>
<b>1</b>. Sitting - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sitting+Cat+Stevens" title="Spartiti di Sitting">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sitting+Cat+Stevens" title="Accordi di Sitting">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sitting+Cat+Stevens" title="Testi di Sitting">testi</a><br>
<b>2</b>. The Boy With The Moon And Star On His Head - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+Boy+With+The+Moon+And+Star+On+His+Head+Cat+Stevens" title="Spartiti di The Boy With The Moon And Star On His Head">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+Boy+With+The+Moon+And+Star+On+His+Head+Cat+Stevens" title="Accordi di The Boy With The Moon And Star On His Head">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+Boy+With+The+Moon+And+Star+On+His+Head+Cat+Stevens" title="Testi di The Boy With The Moon And Star On His Head">testi</a><br>
<b>3</b>. Angelsea - <a target="_blank" href="http://www.google.com/search?q=spartiti+Angelsea+Cat+Stevens" title="Spartiti di Angelsea">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Angelsea+Cat+Stevens" title="Accordi di Angelsea">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Angelsea+Cat+Stevens" title="Testi di Angelsea">testi</a><br>
<b>4</b>. Silent Sunlight - <a target="_blank" href="http://www.google.com/search?q=spartiti+Silent+Sunlight+Cat+Stevens" title="Spartiti di Silent Sunlight">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Silent+Sunlight+Cat+Stevens" title="Accordi di Silent Sunlight">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Silent+Sunlight+Cat+Stevens" title="Testi di Silent Sunlight">testi</a><br>
<b>5</b>. Can't Keep It In - <a target="_blank" href="http://www.google.com/search?q=spartiti+Can%27t+Keep+It+In+Cat+Stevens" title="Spartiti di Can't Keep It In">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Can%27t+Keep+It+In+Cat+Stevens" title="Accordi di Can't Keep It In">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Can%27t+Keep+It+In+Cat+Stevens" title="Testi di Can't Keep It In">testi</a><br>
<b>6</b>. 18th Avenue - (Kansas City Nightmare) - <a target="_blank" href="http://www.google.com/search?q=spartiti+18th+Avenue+-+%28Kansas+City+Nightmare%29+Cat+Stevens" title="Spartiti di 18th Avenue - (Kansas City Nightmare)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+18th+Avenue+-+%28Kansas+City+Nightmare%29+Cat+Stevens" title="Accordi di 18th Avenue - (Kansas City Nightmare)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+18th+Avenue+-+%28Kansas+City+Nightmare%29+Cat+Stevens" title="Testi di 18th Avenue - (Kansas City Nightmare)">testi</a><br>
<b>7</b>. Freezing Steel - <a target="_blank" href="http://www.google.com/search?q=spartiti+Freezing+Steel+Cat+Stevens" title="Spartiti di Freezing Steel">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Freezing+Steel+Cat+Stevens" title="Accordi di Freezing Steel">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Freezing+Steel+Cat+Stevens" title="Testi di Freezing Steel">testi</a><br>
<b>8</b>. O Caritas - <a target="_blank" href="http://www.google.com/search?q=spartiti+O+Caritas+Cat+Stevens" title="Spartiti di O Caritas">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+O+Caritas+Cat+Stevens" title="Accordi di O Caritas">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+O+Caritas+Cat+Stevens" title="Testi di O Caritas">testi</a><br>
<b>9</b>. Sweet Scarlet - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sweet+Scarlet+Cat+Stevens" title="Spartiti di Sweet Scarlet">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sweet+Scarlet+Cat+Stevens" title="Accordi di Sweet Scarlet">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sweet+Scarlet+Cat+Stevens" title="Testi di Sweet Scarlet">testi</a><br>
<b>10</b>. Ruins - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ruins+Cat+Stevens" title="Spartiti di Ruins">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ruins+Cat+Stevens" title="Accordi di Ruins">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ruins+Cat+Stevens" title="Testi di Ruins">testi</a><br>
<h2>Crab Dance [Single] (1972) </h2>
<b>1</b>. Sitting - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sitting+Cat+Stevens" title="Spartiti di Sitting">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sitting+Cat+Stevens" title="Accordi di Sitting">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sitting+Cat+Stevens" title="Testi di Sitting">testi</a><br>
<b>2</b>. Crab Dance - <a target="_blank" href="http://www.google.com/search?q=spartiti+Crab+Dance+Cat+Stevens" title="Spartiti di Crab Dance">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Crab+Dance+Cat+Stevens" title="Accordi di Crab Dance">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Crab+Dance+Cat+Stevens" title="Testi di Crab Dance">testi</a><br>
<h2>Teaser And The Firecat (1971) </h2>
<b>1</b>. The Wind - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+Wind+Cat+Stevens" title="Spartiti di The Wind">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+Wind+Cat+Stevens" title="Accordi di The Wind">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+Wind+Cat+Stevens" title="Testi di The Wind">testi</a><br>
<b>2</b>. Rubylove - <a target="_blank" href="http://www.google.com/search?q=spartiti+Rubylove+Cat+Stevens" title="Spartiti di Rubylove">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Rubylove+Cat+Stevens" title="Accordi di Rubylove">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Rubylove+Cat+Stevens" title="Testi di Rubylove">testi</a><br>
<b>3</b>. If I Laugh - <a target="_blank" href="http://www.google.com/search?q=spartiti+If+I+Laugh+Cat+Stevens" title="Spartiti di If I Laugh">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+If+I+Laugh+Cat+Stevens" title="Accordi di If I Laugh">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+If+I+Laugh+Cat+Stevens" title="Testi di If I Laugh">testi</a><br>
<b>4</b>. Changes Iv - <a target="_blank" href="http://www.google.com/search?q=spartiti+Changes+Iv+Cat+Stevens" title="Spartiti di Changes Iv">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Changes+Iv+Cat+Stevens" title="Accordi di Changes Iv">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Changes+Iv+Cat+Stevens" title="Testi di Changes Iv">testi</a><br>
<b>5</b>. How Can I Tell You - <a target="_blank" href="http://www.google.com/search?q=spartiti+How+Can+I+Tell+You+Cat+Stevens" title="Spartiti di How Can I Tell You">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+How+Can+I+Tell+You+Cat+Stevens" title="Accordi di How Can I Tell You">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+How+Can+I+Tell+You+Cat+Stevens" title="Testi di How Can I Tell You">testi</a><br>
<b>6</b>. Tuesday's Dead - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tuesday%27s+Dead+Cat+Stevens" title="Spartiti di Tuesday's Dead">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tuesday%27s+Dead+Cat+Stevens" title="Accordi di Tuesday's Dead">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tuesday%27s+Dead+Cat+Stevens" title="Testi di Tuesday's Dead">testi</a><br>
<b>7</b>. Morning Has Broken - <a target="_blank" href="http://www.google.com/search?q=spartiti+Morning+Has+Broken+Cat+Stevens" title="Spartiti di Morning Has Broken">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Morning+Has+Broken+Cat+Stevens" title="Accordi di Morning Has Broken">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Morning+Has+Broken+Cat+Stevens" title="Testi di Morning Has Broken">testi</a><br>
<b>8</b>. Bitterblue - <a target="_blank" href="http://www.google.com/search?q=spartiti+Bitterblue+Cat+Stevens" title="Spartiti di Bitterblue">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Bitterblue+Cat+Stevens" title="Accordi di Bitterblue">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Bitterblue+Cat+Stevens" title="Testi di Bitterblue">testi</a><br>
<b>9</b>. Moonshadow - <a target="_blank" href="http://www.google.com/search?q=spartiti+Moonshadow+Cat+Stevens" title="Spartiti di Moonshadow">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Moonshadow+Cat+Stevens" title="Accordi di Moonshadow">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Moonshadow+Cat+Stevens" title="Testi di Moonshadow">testi</a><br>
<b>10</b>. Peace Train - <a target="_blank" href="http://www.google.com/search?q=spartiti+Peace+Train+Cat+Stevens" title="Spartiti di Peace Train">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Peace+Train+Cat+Stevens" title="Accordi di Peace Train">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Peace+Train+Cat+Stevens" title="Testi di Peace Train">testi</a><br>
<h2>Tea For The Tillerman (1970) </h2>
<b>1</b>. Where Do The Children Play - <a target="_blank" href="http://www.google.com/search?q=spartiti+Where+Do+The+Children+Play+Cat+Stevens" title="Spartiti di Where Do The Children Play">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Where+Do+The+Children+Play+Cat+Stevens" title="Accordi di Where Do The Children Play">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Where+Do+The+Children+Play+Cat+Stevens" title="Testi di Where Do The Children Play">testi</a><br>
<b>2</b>. Hard-headed Woman - <a target="_blank" href="http://www.google.com/search?q=spartiti+Hard-headed+Woman+Cat+Stevens" title="Spartiti di Hard-headed Woman">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Hard-headed+Woman+Cat+Stevens" title="Accordi di Hard-headed Woman">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Hard-headed+Woman+Cat+Stevens" title="Testi di Hard-headed Woman">testi</a><br>
<b>3</b>. Wild World - <a target="_blank" href="http://www.google.com/search?q=spartiti+Wild+World+Cat+Stevens" title="Spartiti di Wild World">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Wild+World+Cat+Stevens" title="Accordi di Wild World">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Wild+World+Cat+Stevens" title="Testi di Wild World">testi</a><br>
<b>4</b>. Sad Lisa - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sad+Lisa+Cat+Stevens" title="Spartiti di Sad Lisa">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sad+Lisa+Cat+Stevens" title="Accordi di Sad Lisa">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sad+Lisa+Cat+Stevens" title="Testi di Sad Lisa">testi</a><br>
<b>5</b>. Miles From Nowhere - <a target="_blank" href="http://www.google.com/search?q=spartiti+Miles+From+Nowhere+Cat+Stevens" title="Spartiti di Miles From Nowhere">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Miles+From+Nowhere+Cat+Stevens" title="Accordi di Miles From Nowhere">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Miles+From+Nowhere+Cat+Stevens" title="Testi di Miles From Nowhere">testi</a><br>
<b>6</b>. But I Might Die Tonight - <a target="_blank" href="http://www.google.com/search?q=spartiti+But+I+Might+Die+Tonight+Cat+Stevens" title="Spartiti di But I Might Die Tonight">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+But+I+Might+Die+Tonight+Cat+Stevens" title="Accordi di But I Might Die Tonight">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+But+I+Might+Die+Tonight+Cat+Stevens" title="Testi di But I Might Die Tonight">testi</a><br>
<b>7</b>. Longer Boats - <a target="_blank" href="http://www.google.com/search?q=spartiti+Longer+Boats+Cat+Stevens" title="Spartiti di Longer Boats">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Longer+Boats+Cat+Stevens" title="Accordi di Longer Boats">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Longer+Boats+Cat+Stevens" title="Testi di Longer Boats">testi</a><br>
<b>8</b>. Into White - <a target="_blank" href="http://www.google.com/search?q=spartiti+Into+White+Cat+Stevens" title="Spartiti di Into White">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Into+White+Cat+Stevens" title="Accordi di Into White">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Into+White+Cat+Stevens" title="Testi di Into White">testi</a><br>
<b>9</b>. On The Road To Findout - <a target="_blank" href="http://www.google.com/search?q=spartiti+On+The+Road+To+Findout+Cat+Stevens" title="Spartiti di On The Road To Findout">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+On+The+Road+To+Findout+Cat+Stevens" title="Accordi di On The Road To Findout">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+On+The+Road+To+Findout+Cat+Stevens" title="Testi di On The Road To Findout">testi</a><br>
<b>10</b>. Father And Son - <a target="_blank" href="http://www.google.com/search?q=spartiti+Father+And+Son+Cat+Stevens" title="Spartiti di Father And Son">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Father+And+Son+Cat+Stevens" title="Accordi di Father And Son">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Father+And+Son+Cat+Stevens" title="Testi di Father And Son">testi</a><br>
<b>11</b>. Tea For The Tillerman - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tea+For+The+Tillerman+Cat+Stevens" title="Spartiti di Tea For The Tillerman">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tea+For+The+Tillerman+Cat+Stevens" title="Accordi di Tea For The Tillerman">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tea+For+The+Tillerman+Cat+Stevens" title="Testi di Tea For The Tillerman">testi</a><br>
<h2>Mona Bone Jakon (1970) </h2>
<b>1</b>. Lady D'arbanville - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lady+D%27arbanville+Cat+Stevens" title="Spartiti di Lady D'arbanville">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lady+D%27arbanville+Cat+Stevens" title="Accordi di Lady D'arbanville">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lady+D%27arbanville+Cat+Stevens" title="Testi di Lady D'arbanville">testi</a><br>
<b>2</b>. Maybe You're Right - <a target="_blank" href="http://www.google.com/search?q=spartiti+Maybe+You%27re+Right+Cat+Stevens" title="Spartiti di Maybe You're Right">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Maybe+You%27re+Right+Cat+Stevens" title="Accordi di Maybe You're Right">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Maybe+You%27re+Right+Cat+Stevens" title="Testi di Maybe You're Right">testi</a><br>
<b>3</b>. Pop Star - <a target="_blank" href="http://www.google.com/search?q=spartiti+Pop+Star+Cat+Stevens" title="Spartiti di Pop Star">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Pop+Star+Cat+Stevens" title="Accordi di Pop Star">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Pop+Star+Cat+Stevens" title="Testi di Pop Star">testi</a><br>
<b>4</b>. I Think I See The Light - <a target="_blank" href="http://www.google.com/search?q=spartiti+I+Think+I+See+The+Light+Cat+Stevens" title="Spartiti di I Think I See The Light">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+I+Think+I+See+The+Light+Cat+Stevens" title="Accordi di I Think I See The Light">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+I+Think+I+See+The+Light+Cat+Stevens" title="Testi di I Think I See The Light">testi</a><br>
<b>5</b>. Trouble - <a target="_blank" href="http://www.google.com/search?q=spartiti+Trouble+Cat+Stevens" title="Spartiti di Trouble">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Trouble+Cat+Stevens" title="Accordi di Trouble">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Trouble+Cat+Stevens" title="Testi di Trouble">testi</a><br>
<b>6</b>. Mona Bone Jakon - <a target="_blank" href="http://www.google.com/search?q=spartiti+Mona+Bone+Jakon+Cat+Stevens" title="Spartiti di Mona Bone Jakon">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Mona+Bone+Jakon+Cat+Stevens" title="Accordi di Mona Bone Jakon">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Mona+Bone+Jakon+Cat+Stevens" title="Testi di Mona Bone Jakon">testi</a><br>
<b>7</b>. I Wish, I Wish - <a target="_blank" href="http://www.google.com/search?q=spartiti+I+Wish%2C+I+Wish+Cat+Stevens" title="Spartiti di I Wish, I Wish">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+I+Wish%2C+I+Wish+Cat+Stevens" title="Accordi di I Wish, I Wish">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+I+Wish%2C+I+Wish+Cat+Stevens" title="Testi di I Wish, I Wish">testi</a><br>
<b>8</b>. Katmandu - <a target="_blank" href="http://www.google.com/search?q=spartiti+Katmandu+Cat+Stevens" title="Spartiti di Katmandu">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Katmandu+Cat+Stevens" title="Accordi di Katmandu">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Katmandu+Cat+Stevens" title="Testi di Katmandu">testi</a><br>
<b>9</b>. Time - <a target="_blank" href="http://www.google.com/search?q=spartiti+Time+Cat+Stevens" title="Spartiti di Time">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Time+Cat+Stevens" title="Accordi di Time">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Time+Cat+Stevens" title="Testi di Time">testi</a><br>
<b>10</b>. Fill My Eyes - <a target="_blank" href="http://www.google.com/search?q=spartiti+Fill+My+Eyes+Cat+Stevens" title="Spartiti di Fill My Eyes">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Fill+My+Eyes+Cat+Stevens" title="Accordi di Fill My Eyes">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Fill+My+Eyes+Cat+Stevens" title="Testi di Fill My Eyes">testi</a><br>
<b>11</b>. Lilywhite - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lilywhite+Cat+Stevens" title="Spartiti di Lilywhite">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lilywhite+Cat+Stevens" title="Accordi di Lilywhite">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lilywhite+Cat+Stevens" title="Testi di Lilywhite">testi</a><br>
<h2>New Masters (1967) </h2>
<b>1</b>. Kitty - <a target="_blank" href="http://www.google.com/search?q=spartiti+Kitty+Cat+Stevens" title="Spartiti di Kitty">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Kitty+Cat+Stevens" title="Accordi di Kitty">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Kitty+Cat+Stevens" title="Testi di Kitty">testi</a><br>
<b>2</b>. I'm So Sleepy - <a target="_blank" href="http://www.google.com/search?q=spartiti+I%27m+So+Sleepy+Cat+Stevens" title="Spartiti di I'm So Sleepy">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+I%27m+So+Sleepy+Cat+Stevens" title="Accordi di I'm So Sleepy">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+I%27m+So+Sleepy+Cat+Stevens" title="Testi di I'm So Sleepy">testi</a><br>
<b>3</b>. Northern Wind - <a target="_blank" href="http://www.google.com/search?q=spartiti+Northern+Wind+Cat+Stevens" title="Spartiti di Northern Wind">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Northern+Wind+Cat+Stevens" title="Accordi di Northern Wind">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Northern+Wind+Cat+Stevens" title="Testi di Northern Wind">testi</a><br>
<b>4</b>. The Laughing Apple - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+Laughing+Apple+Cat+Stevens" title="Spartiti di The Laughing Apple">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+Laughing+Apple+Cat+Stevens" title="Accordi di The Laughing Apple">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+Laughing+Apple+Cat+Stevens" title="Testi di The Laughing Apple">testi</a><br>
<b>5</b>. Smash Your Heart - <a target="_blank" href="http://www.google.com/search?q=spartiti+Smash+Your+Heart+Cat+Stevens" title="Spartiti di Smash Your Heart">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Smash+Your+Heart+Cat+Stevens" title="Accordi di Smash Your Heart">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Smash+Your+Heart+Cat+Stevens" title="Testi di Smash Your Heart">testi</a><br>
<b>6</b>. Moonstone - <a target="_blank" href="http://www.google.com/search?q=spartiti+Moonstone+Cat+Stevens" title="Spartiti di Moonstone">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Moonstone+Cat+Stevens" title="Accordi di Moonstone">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Moonstone+Cat+Stevens" title="Testi di Moonstone">testi</a><br>
<b>7</b>. The First Cut Is The Deepest - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+First+Cut+Is+The+Deepest+Cat+Stevens" title="Spartiti di The First Cut Is The Deepest">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+First+Cut+Is+The+Deepest+Cat+Stevens" title="Accordi di The First Cut Is The Deepest">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+First+Cut+Is+The+Deepest+Cat+Stevens" title="Testi di The First Cut Is The Deepest">testi</a><br>
<b>8</b>. I'm Gonna Be King - <a target="_blank" href="http://www.google.com/search?q=spartiti+I%27m+Gonna+Be+King+Cat+Stevens" title="Spartiti di I'm Gonna Be King">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+I%27m+Gonna+Be+King+Cat+Stevens" title="Accordi di I'm Gonna Be King">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+I%27m+Gonna+Be+King+Cat+Stevens" title="Testi di I'm Gonna Be King">testi</a><br>
<b>9</b>. Ceylon City - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ceylon+City+Cat+Stevens" title="Spartiti di Ceylon City">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ceylon+City+Cat+Stevens" title="Accordi di Ceylon City">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ceylon+City+Cat+Stevens" title="Testi di Ceylon City">testi</a><br>
<b>10</b>. Blackness Of The Night - <a target="_blank" href="http://www.google.com/search?q=spartiti+Blackness+Of+The+Night+Cat+Stevens" title="Spartiti di Blackness Of The Night">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Blackness+Of+The+Night+Cat+Stevens" title="Accordi di Blackness Of The Night">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Blackness+Of+The+Night+Cat+Stevens" title="Testi di Blackness Of The Night">testi</a><br>
<b>11</b>. Come On Baby (Shift That Log) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Come+On+Baby+%28Shift+That+Log%29+Cat+Stevens" title="Spartiti di Come On Baby (Shift That Log)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Come+On+Baby+%28Shift+That+Log%29+Cat+Stevens" title="Accordi di Come On Baby (Shift That Log)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Come+On+Baby+%28Shift+That+Log%29+Cat+Stevens" title="Testi di Come On Baby (Shift That Log)">testi</a><br>
<b>12</b>. I Love Them All - <a target="_blank" href="http://www.google.com/search?q=spartiti+I+Love+Them+All+Cat+Stevens" title="Spartiti di I Love Them All">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+I+Love+Them+All+Cat+Stevens" title="Accordi di I Love Them All">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+I+Love+Them+All+Cat+Stevens" title="Testi di I Love Them All">testi</a><br>
<b>13</b>. Image Of Hell - <a target="_blank" href="http://www.google.com/search?q=spartiti+Image+Of+Hell+Cat+Stevens" title="Spartiti di Image Of Hell">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Image+Of+Hell+Cat+Stevens" title="Accordi di Image Of Hell">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Image+Of+Hell+Cat+Stevens" title="Testi di Image Of Hell">testi</a><br>
<b>14</b>. Lovely City (When Do You Laugh) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lovely+City+%28When+Do+You+Laugh%29+Cat+Stevens" title="Spartiti di Lovely City (When Do You Laugh)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lovely+City+%28When+Do+You+Laugh%29+Cat+Stevens" title="Accordi di Lovely City (When Do You Laugh)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lovely+City+%28When+Do+You+Laugh%29+Cat+Stevens" title="Testi di Lovely City (When Do You Laugh)">testi</a><br>
<b>15</b>. The View From The Top - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+View+From+The+Top+Cat+Stevens" title="Spartiti di The View From The Top">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+View+From+The+Top+Cat+Stevens" title="Accordi di The View From The Top">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+View+From+The+Top+Cat+Stevens" title="Testi di The View From The Top">testi</a><br>
<b>16</b>. Here Comes My Wife - <a target="_blank" href="http://www.google.com/search?q=spartiti+Here+Comes+My+Wife+Cat+Stevens" title="Spartiti di Here Comes My Wife">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Here+Comes+My+Wife+Cat+Stevens" title="Accordi di Here Comes My Wife">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Here+Comes+My+Wife+Cat+Stevens" title="Testi di Here Comes My Wife">testi</a><br>
<b>17</b>. It's A Super (Dupa) Life - <a target="_blank" href="http://www.google.com/search?q=spartiti+It%27s+A+Super+%28Dupa%29+Life+Cat+Stevens" title="Spartiti di It's A Super (Dupa) Life">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+It%27s+A+Super+%28Dupa%29+Life+Cat+Stevens" title="Accordi di It's A Super (Dupa) Life">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+It%27s+A+Super+%28Dupa%29+Life+Cat+Stevens" title="Testi di It's A Super (Dupa) Life">testi</a><br>
<b>18</b>. Where Are You - <a target="_blank" href="http://www.google.com/search?q=spartiti+Where+Are+You+Cat+Stevens" title="Spartiti di Where Are You">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Where+Are+You+Cat+Stevens" title="Accordi di Where Are You">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Where+Are+You+Cat+Stevens" title="Testi di Where Are You">testi</a><br>
<b>19</b>. A Bad Night - <a target="_blank" href="http://www.google.com/search?q=spartiti+A+Bad+Night+Cat+Stevens" title="Spartiti di A Bad Night">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+A+Bad+Night+Cat+Stevens" title="Accordi di A Bad Night">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+A+Bad+Night+Cat+Stevens" title="Testi di A Bad Night">testi</a><br>
<h2>Matthew & Son (1966) </h2>
<b>1</b>. Matthew & Son - <a target="_blank" href="http://www.google.com/search?q=spartiti+Matthew+%26+Son+Cat+Stevens" title="Spartiti di Matthew & Son">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Matthew+%26+Son+Cat+Stevens" title="Accordi di Matthew & Son">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Matthew+%26+Son+Cat+Stevens" title="Testi di Matthew & Son">testi</a><br>
<b>2</b>. I Love My Dog - <a target="_blank" href="http://www.google.com/search?q=spartiti+I+Love+My+Dog+Cat+Stevens" title="Spartiti di I Love My Dog">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+I+Love+My+Dog+Cat+Stevens" title="Accordi di I Love My Dog">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+I+Love+My+Dog+Cat+Stevens" title="Testi di I Love My Dog">testi</a><br>
<b>3</b>. Here Comes My Baby - <a target="_blank" href="http://www.google.com/search?q=spartiti+Here+Comes+My+Baby+Cat+Stevens" title="Spartiti di Here Comes My Baby">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Here+Comes+My+Baby+Cat+Stevens" title="Accordi di Here Comes My Baby">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Here+Comes+My+Baby+Cat+Stevens" title="Testi di Here Comes My Baby">testi</a><br>
<b>4</b>. Bring Another Bottle Baby - <a target="_blank" href="http://www.google.com/search?q=spartiti+Bring+Another+Bottle+Baby+Cat+Stevens" title="Spartiti di Bring Another Bottle Baby">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Bring+Another+Bottle+Baby+Cat+Stevens" title="Accordi di Bring Another Bottle Baby">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Bring+Another+Bottle+Baby+Cat+Stevens" title="Testi di Bring Another Bottle Baby">testi</a><br>
<b>5</b>. I've Found A Love - <a target="_blank" href="http://www.google.com/search?q=spartiti+I%27ve+Found+A+Love+Cat+Stevens" title="Spartiti di I've Found A Love">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+I%27ve+Found+A+Love+Cat+Stevens" title="Accordi di I've Found A Love">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+I%27ve+Found+A+Love+Cat+Stevens" title="Testi di I've Found A Love">testi</a><br>
<b>6</b>. I See A Road - <a target="_blank" href="http://www.google.com/search?q=spartiti+I+See+A+Road+Cat+Stevens" title="Spartiti di I See A Road">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+I+See+A+Road+Cat+Stevens" title="Accordi di I See A Road">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+I+See+A+Road+Cat+Stevens" title="Testi di I See A Road">testi</a><br>
<b>7</b>. Baby Get Your Head Screwed On - <a target="_blank" href="http://www.google.com/search?q=spartiti+Baby+Get+Your+Head+Screwed+On+Cat+Stevens" title="Spartiti di Baby Get Your Head Screwed On">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Baby+Get+Your+Head+Screwed+On+Cat+Stevens" title="Accordi di Baby Get Your Head Screwed On">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Baby+Get+Your+Head+Screwed+On+Cat+Stevens" title="Testi di Baby Get Your Head Screwed On">testi</a><br>
<b>8</b>. Granny - <a target="_blank" href="http://www.google.com/search?q=spartiti+Granny+Cat+Stevens" title="Spartiti di Granny">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Granny+Cat+Stevens" title="Accordi di Granny">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Granny+Cat+Stevens" title="Testi di Granny">testi</a><br>
<b>9</b>. When I Speak To The Flowers - <a target="_blank" href="http://www.google.com/search?q=spartiti+When+I+Speak+To+The+Flowers+Cat+Stevens" title="Spartiti di When I Speak To The Flowers">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+When+I+Speak+To+The+Flowers+Cat+Stevens" title="Accordi di When I Speak To The Flowers">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+When+I+Speak+To+The+Flowers+Cat+Stevens" title="Testi di When I Speak To The Flowers">testi</a><br>
<b>10</b>. The Tramp - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+Tramp+Cat+Stevens" title="Spartiti di The Tramp">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+Tramp+Cat+Stevens" title="Accordi di The Tramp">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+Tramp+Cat+Stevens" title="Testi di The Tramp">testi</a><br>
<b>11</b>. Come On And Dance - <a target="_blank" href="http://www.google.com/search?q=spartiti+Come+On+And+Dance+Cat+Stevens" title="Spartiti di Come On And Dance">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Come+On+And+Dance+Cat+Stevens" title="Accordi di Come On And Dance">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Come+On+And+Dance+Cat+Stevens" title="Testi di Come On And Dance">testi</a><br>
<b>12</b>. Hummingbird - <a target="_blank" href="http://www.google.com/search?q=spartiti+Hummingbird+Cat+Stevens" title="Spartiti di Hummingbird">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Hummingbird+Cat+Stevens" title="Accordi di Hummingbird">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Hummingbird+Cat+Stevens" title="Testi di Hummingbird">testi</a><br>
<b>13</b>. Lady - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lady+Cat+Stevens" title="Spartiti di Lady">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lady+Cat+Stevens" title="Accordi di Lady">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lady+Cat+Stevens" title="Testi di Lady">testi</a><br>
<b>14</b>. School Is Out - <a target="_blank" href="http://www.google.com/search?q=spartiti+School+Is+Out+Cat+Stevens" title="Spartiti di School Is Out">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+School+Is+Out+Cat+Stevens" title="Accordi di School Is Out">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+School+Is+Out+Cat+Stevens" title="Testi di School Is Out">testi</a><br>
<b>15</b>. I'm Gonna Get Me A Gun - <a target="_blank" href="http://www.google.com/search?q=spartiti+I%27m+Gonna+Get+Me+A+Gun+Cat+Stevens" title="Spartiti di I'm Gonna Get Me A Gun">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+I%27m+Gonna+Get+Me+A+Gun+Cat+Stevens" title="Accordi di I'm Gonna Get Me A Gun">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+I%27m+Gonna+Get+Me+A+Gun+Cat+Stevens" title="Testi di I'm Gonna Get Me A Gun">testi</a><br>
<h2><a href="http://<?php echo "$base_website_address/$spartiti_dir" ?>/index.html" title="Trova accordi, spartiti, tablature e testi di tantissimi artisti">Torna all'indice degli artisti</a></h2>
