<!--
title: Trova spartiti per chitarra, accordi, testi e tablature di Evanescence. Discografia Evanescence.
description: Trova tutti gli spartiti, accordi, testi e tablature di Evanescence. Discografia Evanescence.
keywords: Discografia, Evanescence, spartiti, accordi, testi, tablature
template: tablature
-->
<h1>Trova spartiti per chitarra, accordi, testi e tablature di Evanescence</h1><h2>Leggere gli spartiti per chitarra, gli accordi e le tablature:</h2>
<?php require("tabdescription.php"); ?>

<h2>Discografia Evanescence:</h2>
<h2>The Open Door (2006) </h2>
<b>1</b>. Sweet Sacrifice - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sweet+Sacrifice+Evanescence" title="Spartiti di Sweet Sacrifice">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sweet+Sacrifice+Evanescence" title="Accordi di Sweet Sacrifice">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sweet+Sacrifice+Evanescence" title="Testi di Sweet Sacrifice">testi</a><br>
<b>2</b>. Call Me When You're Sober - <a target="_blank" href="http://www.google.com/search?q=spartiti+Call+Me+When+You%27re+Sober+Evanescence" title="Spartiti di Call Me When You're Sober">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Call+Me+When+You%27re+Sober+Evanescence" title="Accordi di Call Me When You're Sober">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Call+Me+When+You%27re+Sober+Evanescence" title="Testi di Call Me When You're Sober">testi</a><br>
<b>3</b>. Weight Of The World - <a target="_blank" href="http://www.google.com/search?q=spartiti+Weight+Of+The+World+Evanescence" title="Spartiti di Weight Of The World">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Weight+Of+The+World+Evanescence" title="Accordi di Weight Of The World">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Weight+Of+The+World+Evanescence" title="Testi di Weight Of The World">testi</a><br>
<b>4</b>. Lithium - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lithium+Evanescence" title="Spartiti di Lithium">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lithium+Evanescence" title="Accordi di Lithium">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lithium+Evanescence" title="Testi di Lithium">testi</a><br>
<b>5</b>. Cloud Nine - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cloud+Nine+Evanescence" title="Spartiti di Cloud Nine">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cloud+Nine+Evanescence" title="Accordi di Cloud Nine">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cloud+Nine+Evanescence" title="Testi di Cloud Nine">testi</a><br>
<b>6</b>. Snow White Queen - <a target="_blank" href="http://www.google.com/search?q=spartiti+Snow+White+Queen+Evanescence" title="Spartiti di Snow White Queen">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Snow+White+Queen+Evanescence" title="Accordi di Snow White Queen">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Snow+White+Queen+Evanescence" title="Testi di Snow White Queen">testi</a><br>
<b>7</b>. Lacrymosa - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lacrymosa+Evanescence" title="Spartiti di Lacrymosa">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lacrymosa+Evanescence" title="Accordi di Lacrymosa">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lacrymosa+Evanescence" title="Testi di Lacrymosa">testi</a><br>
<b>8</b>. Like You - <a target="_blank" href="http://www.google.com/search?q=spartiti+Like+You+Evanescence" title="Spartiti di Like You">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Like+You+Evanescence" title="Accordi di Like You">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Like+You+Evanescence" title="Testi di Like You">testi</a><br>
<b>9</b>. Lose Control - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lose+Control+Evanescence" title="Spartiti di Lose Control">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lose+Control+Evanescence" title="Accordi di Lose Control">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lose+Control+Evanescence" title="Testi di Lose Control">testi</a><br>
<b>10</b>. The Only One - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+Only+One+Evanescence" title="Spartiti di The Only One">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+Only+One+Evanescence" title="Accordi di The Only One">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+Only+One+Evanescence" title="Testi di The Only One">testi</a><br>
<b>11</b>. Your Star - <a target="_blank" href="http://www.google.com/search?q=spartiti+Your+Star+Evanescence" title="Spartiti di Your Star">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Your+Star+Evanescence" title="Accordi di Your Star">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Your+Star+Evanescence" title="Testi di Your Star">testi</a><br>
<b>12</b>. All That I'm Living For - <a target="_blank" href="http://www.google.com/search?q=spartiti+All+That+I%27m+Living+For+Evanescence" title="Spartiti di All That I'm Living For">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+All+That+I%27m+Living+For+Evanescence" title="Accordi di All That I'm Living For">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+All+That+I%27m+Living+For+Evanescence" title="Testi di All That I'm Living For">testi</a><br>
<b>13</b>. Good Enough - <a target="_blank" href="http://www.google.com/search?q=spartiti+Good+Enough+Evanescence" title="Spartiti di Good Enough">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Good+Enough+Evanescence" title="Accordi di Good Enough">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Good+Enough+Evanescence" title="Testi di Good Enough">testi</a><br>
<b>14</b>. The Last Song I'm Wasting On You - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+Last+Song+I%27m+Wasting+On+You+Evanescence" title="Spartiti di The Last Song I'm Wasting On You">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+Last+Song+I%27m+Wasting+On+You+Evanescence" title="Accordi di The Last Song I'm Wasting On You">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+Last+Song+I%27m+Wasting+On+You+Evanescence" title="Testi di The Last Song I'm Wasting On You">testi</a><br>
<h2>Anywhere But Home (2004) </h2>
<b>1</b>. Haunted - <a target="_blank" href="http://www.google.com/search?q=spartiti+Haunted+Evanescence" title="Spartiti di Haunted">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Haunted+Evanescence" title="Accordi di Haunted">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Haunted+Evanescence" title="Testi di Haunted">testi</a><br>
<b>2</b>. Going Under - <a target="_blank" href="http://www.google.com/search?q=spartiti+Going+Under+Evanescence" title="Spartiti di Going Under">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Going+Under+Evanescence" title="Accordi di Going Under">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Going+Under+Evanescence" title="Testi di Going Under">testi</a><br>
<b>3</b>. Taking Over Me - <a target="_blank" href="http://www.google.com/search?q=spartiti+Taking+Over+Me+Evanescence" title="Spartiti di Taking Over Me">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Taking+Over+Me+Evanescence" title="Accordi di Taking Over Me">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Taking+Over+Me+Evanescence" title="Testi di Taking Over Me">testi</a><br>
<b>4</b>. Everybody's Fool - <a target="_blank" href="http://www.google.com/search?q=spartiti+Everybody%27s+Fool+Evanescence" title="Spartiti di Everybody's Fool">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Everybody%27s+Fool+Evanescence" title="Accordi di Everybody's Fool">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Everybody%27s+Fool+Evanescence" title="Testi di Everybody's Fool">testi</a><br>
<b>5</b>. Thoughtless - <a target="_blank" href="http://www.google.com/search?q=spartiti+Thoughtless+Evanescence" title="Spartiti di Thoughtless">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Thoughtless+Evanescence" title="Accordi di Thoughtless">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Thoughtless+Evanescence" title="Testi di Thoughtless">testi</a><br>
<b>6</b>. My Last Breath - <a target="_blank" href="http://www.google.com/search?q=spartiti+My+Last+Breath+Evanescence" title="Spartiti di My Last Breath">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+My+Last+Breath+Evanescence" title="Accordi di My Last Breath">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+My+Last+Breath+Evanescence" title="Testi di My Last Breath">testi</a><br>
<b>7</b>. Farther Away - <a target="_blank" href="http://www.google.com/search?q=spartiti+Farther+Away+Evanescence" title="Spartiti di Farther Away">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Farther+Away+Evanescence" title="Accordi di Farther Away">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Farther+Away+Evanescence" title="Testi di Farther Away">testi</a><br>
<b>8</b>. Breathe No More - <a target="_blank" href="http://www.google.com/search?q=spartiti+Breathe+No+More+Evanescence" title="Spartiti di Breathe No More">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Breathe+No+More+Evanescence" title="Accordi di Breathe No More">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Breathe+No+More+Evanescence" title="Testi di Breathe No More">testi</a><br>
<b>9</b>. My Immortal - <a target="_blank" href="http://www.google.com/search?q=spartiti+My+Immortal+Evanescence" title="Spartiti di My Immortal">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+My+Immortal+Evanescence" title="Accordi di My Immortal">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+My+Immortal+Evanescence" title="Testi di My Immortal">testi</a><br>
<b>10</b>. Bring Me To Life - <a target="_blank" href="http://www.google.com/search?q=spartiti+Bring+Me+To+Life+Evanescence" title="Spartiti di Bring Me To Life">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Bring+Me+To+Life+Evanescence" title="Accordi di Bring Me To Life">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Bring+Me+To+Life+Evanescence" title="Testi di Bring Me To Life">testi</a><br>
<b>11</b>. Tourniquet - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tourniquet+Evanescence" title="Spartiti di Tourniquet">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tourniquet+Evanescence" title="Accordi di Tourniquet">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tourniquet+Evanescence" title="Testi di Tourniquet">testi</a><br>
<b>12</b>. Imaginary - <a target="_blank" href="http://www.google.com/search?q=spartiti+Imaginary+Evanescence" title="Spartiti di Imaginary">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Imaginary+Evanescence" title="Accordi di Imaginary">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Imaginary+Evanescence" title="Testi di Imaginary">testi</a><br>
<b>13</b>. Whisper - <a target="_blank" href="http://www.google.com/search?q=spartiti+Whisper+Evanescence" title="Spartiti di Whisper">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Whisper+Evanescence" title="Accordi di Whisper">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Whisper+Evanescence" title="Testi di Whisper">testi</a><br>
<b>14</b>. Missing - <a target="_blank" href="http://www.google.com/search?q=spartiti+Missing+Evanescence" title="Spartiti di Missing">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Missing+Evanescence" title="Accordi di Missing">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Missing+Evanescence" title="Testi di Missing">testi</a><br>
<h2>Fallen (2003) </h2>
<b>1</b>. Bring Me To Life - <a target="_blank" href="http://www.google.com/search?q=spartiti+Bring+Me+To+Life+Evanescence" title="Spartiti di Bring Me To Life">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Bring+Me+To+Life+Evanescence" title="Accordi di Bring Me To Life">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Bring+Me+To+Life+Evanescence" title="Testi di Bring Me To Life">testi</a><br>
<b>2</b>. Everybody's Fool - <a target="_blank" href="http://www.google.com/search?q=spartiti+Everybody%27s+Fool+Evanescence" title="Spartiti di Everybody's Fool">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Everybody%27s+Fool+Evanescence" title="Accordi di Everybody's Fool">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Everybody%27s+Fool+Evanescence" title="Testi di Everybody's Fool">testi</a><br>
<b>3</b>. Going Under - <a target="_blank" href="http://www.google.com/search?q=spartiti+Going+Under+Evanescence" title="Spartiti di Going Under">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Going+Under+Evanescence" title="Accordi di Going Under">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Going+Under+Evanescence" title="Testi di Going Under">testi</a><br>
<b>4</b>. Haunted - <a target="_blank" href="http://www.google.com/search?q=spartiti+Haunted+Evanescence" title="Spartiti di Haunted">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Haunted+Evanescence" title="Accordi di Haunted">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Haunted+Evanescence" title="Testi di Haunted">testi</a><br>
<b>5</b>. Hello - <a target="_blank" href="http://www.google.com/search?q=spartiti+Hello+Evanescence" title="Spartiti di Hello">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Hello+Evanescence" title="Accordi di Hello">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Hello+Evanescence" title="Testi di Hello">testi</a><br>
<b>6</b>. Imaginary - <a target="_blank" href="http://www.google.com/search?q=spartiti+Imaginary+Evanescence" title="Spartiti di Imaginary">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Imaginary+Evanescence" title="Accordi di Imaginary">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Imaginary+Evanescence" title="Testi di Imaginary">testi</a><br>
<b>7</b>. My Last Breath - <a target="_blank" href="http://www.google.com/search?q=spartiti+My+Last+Breath+Evanescence" title="Spartiti di My Last Breath">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+My+Last+Breath+Evanescence" title="Accordi di My Last Breath">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+My+Last+Breath+Evanescence" title="Testi di My Last Breath">testi</a><br>
<b>8</b>. My Immortal - <a target="_blank" href="http://www.google.com/search?q=spartiti+My+Immortal+Evanescence" title="Spartiti di My Immortal">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+My+Immortal+Evanescence" title="Accordi di My Immortal">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+My+Immortal+Evanescence" title="Testi di My Immortal">testi</a><br>
<b>9</b>. Taking Over Me - <a target="_blank" href="http://www.google.com/search?q=spartiti+Taking+Over+Me+Evanescence" title="Spartiti di Taking Over Me">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Taking+Over+Me+Evanescence" title="Accordi di Taking Over Me">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Taking+Over+Me+Evanescence" title="Testi di Taking Over Me">testi</a><br>
<b>10</b>. Tourniquet - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tourniquet+Evanescence" title="Spartiti di Tourniquet">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tourniquet+Evanescence" title="Accordi di Tourniquet">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tourniquet+Evanescence" title="Testi di Tourniquet">testi</a><br>
<b>11</b>. Whisper - <a target="_blank" href="http://www.google.com/search?q=spartiti+Whisper+Evanescence" title="Spartiti di Whisper">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Whisper+Evanescence" title="Accordi di Whisper">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Whisper+Evanescence" title="Testi di Whisper">testi</a><br>
<h2>Origin (2000) </h2>
<b>1</b>. Whisper - <a target="_blank" href="http://www.google.com/search?q=spartiti+Whisper+Evanescence" title="Spartiti di Whisper">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Whisper+Evanescence" title="Accordi di Whisper">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Whisper+Evanescence" title="Testi di Whisper">testi</a><br>
<b>2</b>. Imaginary - <a target="_blank" href="http://www.google.com/search?q=spartiti+Imaginary+Evanescence" title="Spartiti di Imaginary">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Imaginary+Evanescence" title="Accordi di Imaginary">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Imaginary+Evanescence" title="Testi di Imaginary">testi</a><br>
<b>3</b>. My Immortal - <a target="_blank" href="http://www.google.com/search?q=spartiti+My+Immortal+Evanescence" title="Spartiti di My Immortal">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+My+Immortal+Evanescence" title="Accordi di My Immortal">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+My+Immortal+Evanescence" title="Testi di My Immortal">testi</a><br>
<b>4</b>. Where Will You Go - <a target="_blank" href="http://www.google.com/search?q=spartiti+Where+Will+You+Go+Evanescence" title="Spartiti di Where Will You Go">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Where+Will+You+Go+Evanescence" title="Accordi di Where Will You Go">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Where+Will+You+Go+Evanescence" title="Testi di Where Will You Go">testi</a><br>
<b>5</b>. Field Of Innocence - <a target="_blank" href="http://www.google.com/search?q=spartiti+Field+Of+Innocence+Evanescence" title="Spartiti di Field Of Innocence">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Field+Of+Innocence+Evanescence" title="Accordi di Field Of Innocence">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Field+Of+Innocence+Evanescence" title="Testi di Field Of Innocence">testi</a><br>
<b>6</b>. Even In Death - <a target="_blank" href="http://www.google.com/search?q=spartiti+Even+In+Death+Evanescence" title="Spartiti di Even In Death">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Even+In+Death+Evanescence" title="Accordi di Even In Death">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Even+In+Death+Evanescence" title="Testi di Even In Death">testi</a><br>
<b>7</b>. Anywhere - <a target="_blank" href="http://www.google.com/search?q=spartiti+Anywhere+Evanescence" title="Spartiti di Anywhere">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Anywhere+Evanescence" title="Accordi di Anywhere">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Anywhere+Evanescence" title="Testi di Anywhere">testi</a><br>
<b>8</b>. Lies - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lies+Evanescence" title="Spartiti di Lies">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lies+Evanescence" title="Accordi di Lies">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lies+Evanescence" title="Testi di Lies">testi</a><br>
<b>9</b>. Away From Me - <a target="_blank" href="http://www.google.com/search?q=spartiti+Away+From+Me+Evanescence" title="Spartiti di Away From Me">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Away+From+Me+Evanescence" title="Accordi di Away From Me">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Away+From+Me+Evanescence" title="Testi di Away From Me">testi</a><br>
<b>10</b>. Listen To The Rain - <a target="_blank" href="http://www.google.com/search?q=spartiti+Listen+To+The+Rain+Evanescence" title="Spartiti di Listen To The Rain">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Listen+To+The+Rain+Evanescence" title="Accordi di Listen To The Rain">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Listen+To+The+Rain+Evanescence" title="Testi di Listen To The Rain">testi</a><br>
<b>11</b>. Surrender - <a target="_blank" href="http://www.google.com/search?q=spartiti+Surrender+Evanescence" title="Spartiti di Surrender">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Surrender+Evanescence" title="Accordi di Surrender">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Surrender+Evanescence" title="Testi di Surrender">testi</a><br>
<h2>EP (1998) </h2>
<b>1</b>. Where Will You Go - <a target="_blank" href="http://www.google.com/search?q=spartiti+Where+Will+You+Go+Evanescence" title="Spartiti di Where Will You Go">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Where+Will+You+Go+Evanescence" title="Accordi di Where Will You Go">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Where+Will+You+Go+Evanescence" title="Testi di Where Will You Go">testi</a><br>
<b>2</b>. Solitude - <a target="_blank" href="http://www.google.com/search?q=spartiti+Solitude+Evanescence" title="Spartiti di Solitude">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Solitude+Evanescence" title="Accordi di Solitude">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Solitude+Evanescence" title="Testi di Solitude">testi</a><br>
<b>3</b>. Imaginary - <a target="_blank" href="http://www.google.com/search?q=spartiti+Imaginary+Evanescence" title="Spartiti di Imaginary">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Imaginary+Evanescence" title="Accordi di Imaginary">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Imaginary+Evanescence" title="Testi di Imaginary">testi</a><br>
<b>4</b>. Exodus - <a target="_blank" href="http://www.google.com/search?q=spartiti+Exodus+Evanescence" title="Spartiti di Exodus">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Exodus+Evanescence" title="Accordi di Exodus">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Exodus+Evanescence" title="Testi di Exodus">testi</a><br>
<b>5</b>. So Close - <a target="_blank" href="http://www.google.com/search?q=spartiti+So+Close+Evanescence" title="Spartiti di So Close">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+So+Close+Evanescence" title="Accordi di So Close">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+So+Close+Evanescence" title="Testi di So Close">testi</a><br>
<b>6</b>. Understanding (Wash It All Away) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Understanding+%28Wash+It+All+Away%29+Evanescence" title="Spartiti di Understanding (Wash It All Away)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Understanding+%28Wash+It+All+Away%29+Evanescence" title="Accordi di Understanding (Wash It All Away)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Understanding+%28Wash+It+All+Away%29+Evanescence" title="Testi di Understanding (Wash It All Away)">testi</a><br>
<b>7</b>. The End - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+End+Evanescence" title="Spartiti di The End">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+End+Evanescence" title="Accordi di The End">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+End+Evanescence" title="Testi di The End">testi</a><br>
<h2>Altre Canzoni </h2>
<b>1</b>. Anything For You - <a target="_blank" href="http://www.google.com/search?q=spartiti+Anything+For+You+Evanescence" title="Spartiti di Anything For You">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Anything+For+You+Evanescence" title="Accordi di Anything For You">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Anything+For+You+Evanescence" title="Testi di Anything For You">testi</a><br>
<b>2</b>. Ascension Of The Spirit - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ascension+Of+The+Spirit+Evanescence" title="Spartiti di Ascension Of The Spirit">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ascension+Of+The+Spirit+Evanescence" title="Accordi di Ascension Of The Spirit">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ascension+Of+The+Spirit+Evanescence" title="Testi di Ascension Of The Spirit">testi</a><br>
<b>3</b>. Before The Dawn - <a target="_blank" href="http://www.google.com/search?q=spartiti+Before+The+Dawn+Evanescence" title="Spartiti di Before The Dawn">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Before+The+Dawn+Evanescence" title="Accordi di Before The Dawn">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Before+The+Dawn+Evanescence" title="Testi di Before The Dawn">testi</a><br>
<b>4</b>. Bleed - <a target="_blank" href="http://www.google.com/search?q=spartiti+Bleed+Evanescence" title="Spartiti di Bleed">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Bleed+Evanescence" title="Accordi di Bleed">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Bleed+Evanescence" title="Testi di Bleed">testi</a><br>
<b>5</b>. Call Me When You're Sober - <a target="_blank" href="http://www.google.com/search?q=spartiti+Call+Me+When+You%27re+Sober+Evanescence" title="Spartiti di Call Me When You're Sober">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Call+Me+When+You%27re+Sober+Evanescence" title="Accordi di Call Me When You're Sober">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Call+Me+When+You%27re+Sober+Evanescence" title="Testi di Call Me When You're Sober">testi</a><br>
<b>6</b>. Eternal - <a target="_blank" href="http://www.google.com/search?q=spartiti+Eternal+Evanescence" title="Spartiti di Eternal">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Eternal+Evanescence" title="Accordi di Eternal">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Eternal+Evanescence" title="Testi di Eternal">testi</a><br>
<b>7</b>. Forgive Me - <a target="_blank" href="http://www.google.com/search?q=spartiti+Forgive+Me+Evanescence" title="Spartiti di Forgive Me">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Forgive+Me+Evanescence" title="Accordi di Forgive Me">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Forgive+Me+Evanescence" title="Testi di Forgive Me">testi</a><br>
<b>8</b>. Give Unto Me - <a target="_blank" href="http://www.google.com/search?q=spartiti+Give+Unto+Me+Evanescence" title="Spartiti di Give Unto Me">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Give+Unto+Me+Evanescence" title="Accordi di Give Unto Me">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Give+Unto+Me+Evanescence" title="Testi di Give Unto Me">testi</a><br>
<b>9</b>. Goodnight - <a target="_blank" href="http://www.google.com/search?q=spartiti+Goodnight+Evanescence" title="Spartiti di Goodnight">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Goodnight+Evanescence" title="Accordi di Goodnight">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Goodnight+Evanescence" title="Testi di Goodnight">testi</a><br>
<b>10</b>. Heart Shaped Box - <a target="_blank" href="http://www.google.com/search?q=spartiti+Heart+Shaped+Box+Evanescence" title="Spartiti di Heart Shaped Box">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Heart+Shaped+Box+Evanescence" title="Accordi di Heart Shaped Box">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Heart+Shaped+Box+Evanescence" title="Testi di Heart Shaped Box">testi</a><br>
<b>11</b>. I Must Be Dreaming - <a target="_blank" href="http://www.google.com/search?q=spartiti+I+Must+Be+Dreaming+Evanescence" title="Spartiti di I Must Be Dreaming">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+I+Must+Be+Dreaming+Evanescence" title="Accordi di I Must Be Dreaming">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+I+Must+Be+Dreaming+Evanescence" title="Testi di I Must Be Dreaming">testi</a><br>
<b>12</b>. October - <a target="_blank" href="http://www.google.com/search?q=spartiti+October+Evanescence" title="Spartiti di October">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+October+Evanescence" title="Accordi di October">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+October+Evanescence" title="Testi di October">testi</a><br>
<b>13</b>. Origin - <a target="_blank" href="http://www.google.com/search?q=spartiti+Origin+Evanescence" title="Spartiti di Origin">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Origin+Evanescence" title="Accordi di Origin">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Origin+Evanescence" title="Testi di Origin">testi</a><br>
<b>14</b>. The Last Song I'm Wasting On You - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+Last+Song+I%27m+Wasting+On+You+Evanescence" title="Spartiti di The Last Song I'm Wasting On You">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+Last+Song+I%27m+Wasting+On+You+Evanescence" title="Accordi di The Last Song I'm Wasting On You">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+Last+Song+I%27m+Wasting+On+You+Evanescence" title="Testi di The Last Song I'm Wasting On You">testi</a><br>
<b>15</b>. Understanding (Sound Asleep) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Understanding+%28Sound+Asleep%29+Evanescence" title="Spartiti di Understanding (Sound Asleep)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Understanding+%28Sound+Asleep%29+Evanescence" title="Accordi di Understanding (Sound Asleep)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Understanding+%28Sound+Asleep%29+Evanescence" title="Testi di Understanding (Sound Asleep)">testi</a><br>
<b>16</b>. You - <a target="_blank" href="http://www.google.com/search?q=spartiti+You+Evanescence" title="Spartiti di You">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+You+Evanescence" title="Accordi di You">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+You+Evanescence" title="Testi di You">testi</a><br>
<h2><a href="<?php echo "$base_website_address/$spartiti_dir" ?>/index.html" title="Trova accordi, spartiti, tablature e testi di tantissimi artisti">Torna all'indice degli artisti</a></h2>
