<!--
title: Trova spartiti per chitarra, accordi, testi e tablature di Francesco Guccini. Discografia Francesco Guccini.
description: Trova tutti gli spartiti, accordi, testi e tablature di Francesco Guccini. Discografia Francesco Guccini.
keywords: Discografia, Francesco Guccini, spartiti, accordi, testi, tablature
template: tablature
-->
<h1>Trova spartiti per chitarra, accordi, testi e tablature di Francesco Guccini</h1><h2>Leggere gli spartiti per chitarra, gli accordi e le tablature:</h2>
<?php require("tabdescription.php"); ?>
<?php require("adsense_leaderboard.php"); ?>
<h2>Discografia Francesco Guccini:</h2>
<h2>Anfiteatro Live (2005) </h2>
<b>1</b>. Canzone Per Un'amica - <a target="_blank" href="http://www.google.com/search?q=spartiti+Canzone+Per+Un%27amica+Francesco+Guccini" title="Spartiti di Canzone Per Un'amica">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Canzone+Per+Un%27amica+Francesco+Guccini" title="Accordi di Canzone Per Un'amica">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Canzone+Per+Un%27amica+Francesco+Guccini" title="Testi di Canzone Per Un'amica">testi</a><br>
<b>2</b>. Una Canzone - <a target="_blank" href="http://www.google.com/search?q=spartiti+Una+Canzone+Francesco+Guccini" title="Spartiti di Una Canzone">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Una+Canzone+Francesco+Guccini" title="Accordi di Una Canzone">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Una+Canzone+Francesco+Guccini" title="Testi di Una Canzone">testi</a><br>
<b>3</b>. Odysseus - <a target="_blank" href="http://www.google.com/search?q=spartiti+Odysseus+Francesco+Guccini" title="Spartiti di Odysseus">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Odysseus+Francesco+Guccini" title="Accordi di Odysseus">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Odysseus+Francesco+Guccini" title="Testi di Odysseus">testi</a><br>
<b>4</b>. Cristoforo Colombo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cristoforo+Colombo+Francesco+Guccini" title="Spartiti di Cristoforo Colombo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cristoforo+Colombo+Francesco+Guccini" title="Accordi di Cristoforo Colombo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cristoforo+Colombo+Francesco+Guccini" title="Testi di Cristoforo Colombo">testi</a><br>
<b>5</b>. Farewell - <a target="_blank" href="http://www.google.com/search?q=spartiti+Farewell+Francesco+Guccini" title="Spartiti di Farewell">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Farewell+Francesco+Guccini" title="Accordi di Farewell">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Farewell+Francesco+Guccini" title="Testi di Farewell">testi</a><br>
<b>6</b>. Scirocco - <a target="_blank" href="http://www.google.com/search?q=spartiti+Scirocco+Francesco+Guccini" title="Spartiti di Scirocco">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Scirocco+Francesco+Guccini" title="Accordi di Scirocco">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Scirocco+Francesco+Guccini" title="Testi di Scirocco">testi</a><br>
<b>7</b>. La Ziatta (La Tieta) - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Ziatta+%28La+Tieta%29+Francesco+Guccini" title="Spartiti di La Ziatta (La Tieta)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Ziatta+%28La+Tieta%29+Francesco+Guccini" title="Accordi di La Ziatta (La Tieta)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Ziatta+%28La+Tieta%29+Francesco+Guccini" title="Testi di La Ziatta (La Tieta)">testi</a><br>
<b>8</b>. Autogrill - <a target="_blank" href="http://www.google.com/search?q=spartiti+Autogrill+Francesco+Guccini" title="Spartiti di Autogrill">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Autogrill+Francesco+Guccini" title="Accordi di Autogrill">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Autogrill+Francesco+Guccini" title="Testi di Autogrill">testi</a><br>
<b>9</b>. Certo Non Sai - <a target="_blank" href="http://www.google.com/search?q=spartiti+Certo+Non+Sai+Francesco+Guccini" title="Spartiti di Certo Non Sai">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Certo+Non+Sai+Francesco+Guccini" title="Accordi di Certo Non Sai">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Certo+Non+Sai+Francesco+Guccini" title="Testi di Certo Non Sai">testi</a><br>
<b>10</b>. Shomér, Ma Mi-llailah? - <a target="_blank" href="http://www.google.com/search?q=spartiti+Shom%E9r%2C+Ma+Mi-llailah%3F+Francesco+Guccini" title="Spartiti di Shomér, Ma Mi-llailah?">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Shom%E9r%2C+Ma+Mi-llailah%3F+Francesco+Guccini" title="Accordi di Shomér, Ma Mi-llailah?">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Shom%E9r%2C+Ma+Mi-llailah%3F+Francesco+Guccini" title="Testi di Shomér, Ma Mi-llailah?">testi</a><br>
<b>11</b>. Il Vecchio E Il Bambino - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Vecchio+E+Il+Bambino+Francesco+Guccini" title="Spartiti di Il Vecchio E Il Bambino">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Vecchio+E+Il+Bambino+Francesco+Guccini" title="Accordi di Il Vecchio E Il Bambino">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Vecchio+E+Il+Bambino+Francesco+Guccini" title="Testi di Il Vecchio E Il Bambino">testi</a><br>
<b>12</b>. Cirano - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cirano+Francesco+Guccini" title="Spartiti di Cirano">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cirano+Francesco+Guccini" title="Accordi di Cirano">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cirano+Francesco+Guccini" title="Testi di Cirano">testi</a><br>
<b>13</b>. Auschwitz - <a target="_blank" href="http://www.google.com/search?q=spartiti+Auschwitz+Francesco+Guccini" title="Spartiti di Auschwitz">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Auschwitz+Francesco+Guccini" title="Accordi di Auschwitz">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Auschwitz+Francesco+Guccini" title="Testi di Auschwitz">testi</a><br>
<b>14</b>. Canzone Per Il Che - <a target="_blank" href="http://www.google.com/search?q=spartiti+Canzone+Per+Il+Che+Francesco+Guccini" title="Spartiti di Canzone Per Il Che">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Canzone+Per+Il+Che+Francesco+Guccini" title="Accordi di Canzone Per Il Che">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Canzone+Per+Il+Che+Francesco+Guccini" title="Testi di Canzone Per Il Che">testi</a><br>
<b>15</b>. Piazza Alimonda - <a target="_blank" href="http://www.google.com/search?q=spartiti+Piazza+Alimonda+Francesco+Guccini" title="Spartiti di Piazza Alimonda">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Piazza+Alimonda+Francesco+Guccini" title="Accordi di Piazza Alimonda">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Piazza+Alimonda+Francesco+Guccini" title="Testi di Piazza Alimonda">testi</a><br>
<b>16</b>. Dio E' Morto - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dio+E%27+Morto+Francesco+Guccini" title="Spartiti di Dio E' Morto">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dio+E%27+Morto+Francesco+Guccini" title="Accordi di Dio E' Morto">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dio+E%27+Morto+Francesco+Guccini" title="Testi di Dio E' Morto">testi</a><br>
<b>17</b>. La Locomotiva - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Locomotiva+Francesco+Guccini" title="Spartiti di La Locomotiva">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Locomotiva+Francesco+Guccini" title="Accordi di La Locomotiva">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Locomotiva+Francesco+Guccini" title="Testi di La Locomotiva">testi</a><br>
<h2>Ritratti (2004) </h2>
<b>1</b>. Odysseus - <a target="_blank" href="http://www.google.com/search?q=spartiti+Odysseus+Francesco+Guccini" title="Spartiti di Odysseus">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Odysseus+Francesco+Guccini" title="Accordi di Odysseus">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Odysseus+Francesco+Guccini" title="Testi di Odysseus">testi</a><br>
<b>2</b>. Una Canzone - <a target="_blank" href="http://www.google.com/search?q=spartiti+Una+Canzone+Francesco+Guccini" title="Spartiti di Una Canzone">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Una+Canzone+Francesco+Guccini" title="Accordi di Una Canzone">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Una+Canzone+Francesco+Guccini" title="Testi di Una Canzone">testi</a><br>
<b>3</b>. Canzone Per Il Che - <a target="_blank" href="http://www.google.com/search?q=spartiti+Canzone+Per+Il+Che+Francesco+Guccini" title="Spartiti di Canzone Per Il Che">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Canzone+Per+Il+Che+Francesco+Guccini" title="Accordi di Canzone Per Il Che">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Canzone+Per+Il+Che+Francesco+Guccini" title="Testi di Canzone Per Il Che">testi</a><br>
<b>4</b>. Piazza Alimonda - <a target="_blank" href="http://www.google.com/search?q=spartiti+Piazza+Alimonda+Francesco+Guccini" title="Spartiti di Piazza Alimonda">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Piazza+Alimonda+Francesco+Guccini" title="Accordi di Piazza Alimonda">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Piazza+Alimonda+Francesco+Guccini" title="Testi di Piazza Alimonda">testi</a><br>
<b>5</b>. Vite - <a target="_blank" href="http://www.google.com/search?q=spartiti+Vite+Francesco+Guccini" title="Spartiti di Vite">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Vite+Francesco+Guccini" title="Accordi di Vite">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Vite+Francesco+Guccini" title="Testi di Vite">testi</a><br>
<b>6</b>. Cristoforo Colombo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cristoforo+Colombo+Francesco+Guccini" title="Spartiti di Cristoforo Colombo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cristoforo+Colombo+Francesco+Guccini" title="Accordi di Cristoforo Colombo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cristoforo+Colombo+Francesco+Guccini" title="Testi di Cristoforo Colombo">testi</a><br>
<b>7</b>. Certo Non Sai - <a target="_blank" href="http://www.google.com/search?q=spartiti+Certo+Non+Sai+Francesco+Guccini" title="Spartiti di Certo Non Sai">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Certo+Non+Sai+Francesco+Guccini" title="Accordi di Certo Non Sai">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Certo+Non+Sai+Francesco+Guccini" title="Testi di Certo Non Sai">testi</a><br>
<b>8</b>. La Ziatta (La Tieta) - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Ziatta+%28La+Tieta%29+Francesco+Guccini" title="Spartiti di La Ziatta (La Tieta)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Ziatta+%28La+Tieta%29+Francesco+Guccini" title="Accordi di La Ziatta (La Tieta)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Ziatta+%28La+Tieta%29+Francesco+Guccini" title="Testi di La Ziatta (La Tieta)">testi</a><br>
<b>9</b>. La Tua Libertà - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Tua+Libert%E0+Francesco+Guccini" title="Spartiti di La Tua Libertà">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Tua+Libert%E0+Francesco+Guccini" title="Accordi di La Tua Libertà">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Tua+Libert%E0+Francesco+Guccini" title="Testi di La Tua Libertà">testi</a><br>
<h2>Stagioni (2000) </h2>
<b>1</b>. Addio (Intro) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Addio+%28Intro%29+Francesco+Guccini" title="Spartiti di Addio (Intro)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Addio+%28Intro%29+Francesco+Guccini" title="Accordi di Addio (Intro)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Addio+%28Intro%29+Francesco+Guccini" title="Testi di Addio (Intro)">testi</a><br>
<b>2</b>. Stagioni - <a target="_blank" href="http://www.google.com/search?q=spartiti+Stagioni+Francesco+Guccini" title="Spartiti di Stagioni">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Stagioni+Francesco+Guccini" title="Accordi di Stagioni">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Stagioni+Francesco+Guccini" title="Testi di Stagioni">testi</a><br>
<b>3</b>. Autunno - <a target="_blank" href="http://www.google.com/search?q=spartiti+Autunno+Francesco+Guccini" title="Spartiti di Autunno">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Autunno+Francesco+Guccini" title="Accordi di Autunno">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Autunno+Francesco+Guccini" title="Testi di Autunno">testi</a><br>
<b>4</b>. E Un Giorno... - <a target="_blank" href="http://www.google.com/search?q=spartiti+E+Un+Giorno...+Francesco+Guccini" title="Spartiti di E Un Giorno...">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+E+Un+Giorno...+Francesco+Guccini" title="Accordi di E Un Giorno...">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+E+Un+Giorno...+Francesco+Guccini" title="Testi di E Un Giorno...">testi</a><br>
<b>5</b>. Ho Ancora La Forza - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ho+Ancora+La+Forza+Francesco+Guccini" title="Spartiti di Ho Ancora La Forza">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ho+Ancora+La+Forza+Francesco+Guccini" title="Accordi di Ho Ancora La Forza">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ho+Ancora+La+Forza+Francesco+Guccini" title="Testi di Ho Ancora La Forza">testi</a><br>
<b>6</b>. Inverno '60 - <a target="_blank" href="http://www.google.com/search?q=spartiti+Inverno+%2760+Francesco+Guccini" title="Spartiti di Inverno '60">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Inverno+%2760+Francesco+Guccini" title="Accordi di Inverno '60">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Inverno+%2760+Francesco+Guccini" title="Testi di Inverno '60">testi</a><br>
<b>7</b>. Don Chisciotte - <a target="_blank" href="http://www.google.com/search?q=spartiti+Don+Chisciotte+Francesco+Guccini" title="Spartiti di Don Chisciotte">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Don+Chisciotte+Francesco+Guccini" title="Accordi di Don Chisciotte">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Don+Chisciotte+Francesco+Guccini" title="Testi di Don Chisciotte">testi</a><br>
<b>8</b>. Primavera '59 - <a target="_blank" href="http://www.google.com/search?q=spartiti+Primavera+%2759+Francesco+Guccini" title="Spartiti di Primavera '59">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Primavera+%2759+Francesco+Guccini" title="Accordi di Primavera '59">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Primavera+%2759+Francesco+Guccini" title="Testi di Primavera '59">testi</a><br>
<b>9</b>. Addio - <a target="_blank" href="http://www.google.com/search?q=spartiti+Addio+Francesco+Guccini" title="Spartiti di Addio">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Addio+Francesco+Guccini" title="Accordi di Addio">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Addio+Francesco+Guccini" title="Testi di Addio">testi</a><br>
<h2>Guccini Live Collection - Disc 2 (1998) </h2>
<b>1</b>. Eskimo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Eskimo+Francesco+Guccini" title="Spartiti di Eskimo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Eskimo+Francesco+Guccini" title="Accordi di Eskimo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Eskimo+Francesco+Guccini" title="Testi di Eskimo">testi</a><br>
<b>2</b>. Auschwitz - <a target="_blank" href="http://www.google.com/search?q=spartiti+Auschwitz+Francesco+Guccini" title="Spartiti di Auschwitz">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Auschwitz+Francesco+Guccini" title="Accordi di Auschwitz">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Auschwitz+Francesco+Guccini" title="Testi di Auschwitz">testi</a><br>
<b>3</b>. Canzone Delle Osterie Di Fuori Porta - <a target="_blank" href="http://www.google.com/search?q=spartiti+Canzone+Delle+Osterie+Di+Fuori+Porta+Francesco+Guccini" title="Spartiti di Canzone Delle Osterie Di Fuori Porta">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Canzone+Delle+Osterie+Di+Fuori+Porta+Francesco+Guccini" title="Accordi di Canzone Delle Osterie Di Fuori Porta">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Canzone+Delle+Osterie+Di+Fuori+Porta+Francesco+Guccini" title="Testi di Canzone Delle Osterie Di Fuori Porta">testi</a><br>
<b>4</b>. Farewell - <a target="_blank" href="http://www.google.com/search?q=spartiti+Farewell+Francesco+Guccini" title="Spartiti di Farewell">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Farewell+Francesco+Guccini" title="Accordi di Farewell">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Farewell+Francesco+Guccini" title="Testi di Farewell">testi</a><br>
<b>5</b>. Incontro - <a target="_blank" href="http://www.google.com/search?q=spartiti+Incontro+Francesco+Guccini" title="Spartiti di Incontro">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Incontro+Francesco+Guccini" title="Accordi di Incontro">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Incontro+Francesco+Guccini" title="Testi di Incontro">testi</a><br>
<b>6</b>. Due Anni Dopo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Due+Anni+Dopo+Francesco+Guccini" title="Spartiti di Due Anni Dopo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Due+Anni+Dopo+Francesco+Guccini" title="Accordi di Due Anni Dopo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Due+Anni+Dopo+Francesco+Guccini" title="Testi di Due Anni Dopo">testi</a><br>
<b>7</b>. Primavera Di Praga - <a target="_blank" href="http://www.google.com/search?q=spartiti+Primavera+Di+Praga+Francesco+Guccini" title="Spartiti di Primavera Di Praga">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Primavera+Di+Praga+Francesco+Guccini" title="Accordi di Primavera Di Praga">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Primavera+Di+Praga+Francesco+Guccini" title="Testi di Primavera Di Praga">testi</a><br>
<b>8</b>. Scirocco - <a target="_blank" href="http://www.google.com/search?q=spartiti+Scirocco+Francesco+Guccini" title="Spartiti di Scirocco">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Scirocco+Francesco+Guccini" title="Accordi di Scirocco">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Scirocco+Francesco+Guccini" title="Testi di Scirocco">testi</a><br>
<b>9</b>. L'Avvelenata - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%27Avvelenata+Francesco+Guccini" title="Spartiti di L'Avvelenata">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%27Avvelenata+Francesco+Guccini" title="Accordi di L'Avvelenata">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%27Avvelenata+Francesco+Guccini" title="Testi di L'Avvelenata">testi</a><br>
<b>10</b>. Dio E' Morto - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dio+E%27+Morto+Francesco+Guccini" title="Spartiti di Dio E' Morto">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dio+E%27+Morto+Francesco+Guccini" title="Accordi di Dio E' Morto">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dio+E%27+Morto+Francesco+Guccini" title="Testi di Dio E' Morto">testi</a><br>
<b>11</b>. La Locomotiva - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Locomotiva+Francesco+Guccini" title="Spartiti di La Locomotiva">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Locomotiva+Francesco+Guccini" title="Accordi di La Locomotiva">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Locomotiva+Francesco+Guccini" title="Testi di La Locomotiva">testi</a><br>
<b>12</b>. Statale 17 - <a target="_blank" href="http://www.google.com/search?q=spartiti+Statale+17+Francesco+Guccini" title="Spartiti di Statale 17">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Statale+17+Francesco+Guccini" title="Accordi di Statale 17">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Statale+17+Francesco+Guccini" title="Testi di Statale 17">testi</a><br>
<b>13</b>. Noi Non Ci Saremo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Noi+Non+Ci+Saremo+Francesco+Guccini" title="Spartiti di Noi Non Ci Saremo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Noi+Non+Ci+Saremo+Francesco+Guccini" title="Accordi di Noi Non Ci Saremo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Noi+Non+Ci+Saremo+Francesco+Guccini" title="Testi di Noi Non Ci Saremo">testi</a><br>
<h2>Guccini Live Collection - Disc 1 (1998) </h2>
<b>1</b>. Canzone Per Un'Amica - <a target="_blank" href="http://www.google.com/search?q=spartiti+Canzone+Per+Un%27Amica+Francesco+Guccini" title="Spartiti di Canzone Per Un'Amica">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Canzone+Per+Un%27Amica+Francesco+Guccini" title="Accordi di Canzone Per Un'Amica">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Canzone+Per+Un%27Amica+Francesco+Guccini" title="Testi di Canzone Per Un'Amica">testi</a><br>
<b>2</b>. Canzone Per Silvia - <a target="_blank" href="http://www.google.com/search?q=spartiti+Canzone+Per+Silvia+Francesco+Guccini" title="Spartiti di Canzone Per Silvia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Canzone+Per+Silvia+Francesco+Guccini" title="Accordi di Canzone Per Silvia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Canzone+Per+Silvia+Francesco+Guccini" title="Testi di Canzone Per Silvia">testi</a><br>
<b>3</b>. Quello Che Non... - <a target="_blank" href="http://www.google.com/search?q=spartiti+Quello+Che+Non...+Francesco+Guccini" title="Spartiti di Quello Che Non...">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Quello+Che+Non...+Francesco+Guccini" title="Accordi di Quello Che Non...">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Quello+Che+Non...+Francesco+Guccini" title="Testi di Quello Che Non...">testi</a><br>
<b>4</b>. Il Vecchio E Il Bambino - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Vecchio+E+Il+Bambino+Francesco+Guccini" title="Spartiti di Il Vecchio E Il Bambino">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Vecchio+E+Il+Bambino+Francesco+Guccini" title="Accordi di Il Vecchio E Il Bambino">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Vecchio+E+Il+Bambino+Francesco+Guccini" title="Testi di Il Vecchio E Il Bambino">testi</a><br>
<b>5</b>. Quattro Stracci - <a target="_blank" href="http://www.google.com/search?q=spartiti+Quattro+Stracci+Francesco+Guccini" title="Spartiti di Quattro Stracci">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Quattro+Stracci+Francesco+Guccini" title="Accordi di Quattro Stracci">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Quattro+Stracci+Francesco+Guccini" title="Testi di Quattro Stracci">testi</a><br>
<b>6</b>. Cirano - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cirano+Francesco+Guccini" title="Spartiti di Cirano">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cirano+Francesco+Guccini" title="Accordi di Cirano">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cirano+Francesco+Guccini" title="Testi di Cirano">testi</a><br>
<b>7</b>. Venezia - <a target="_blank" href="http://www.google.com/search?q=spartiti+Venezia+Francesco+Guccini" title="Spartiti di Venezia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Venezia+Francesco+Guccini" title="Accordi di Venezia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Venezia+Francesco+Guccini" title="Testi di Venezia">testi</a><br>
<b>8</b>. Bologna - <a target="_blank" href="http://www.google.com/search?q=spartiti+Bologna+Francesco+Guccini" title="Spartiti di Bologna">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Bologna+Francesco+Guccini" title="Accordi di Bologna">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Bologna+Francesco+Guccini" title="Testi di Bologna">testi</a><br>
<b>9</b>. Canzone Quasi D'Amore - <a target="_blank" href="http://www.google.com/search?q=spartiti+Canzone+Quasi+D%27Amore+Francesco+Guccini" title="Spartiti di Canzone Quasi D'Amore">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Canzone+Quasi+D%27Amore+Francesco+Guccini" title="Accordi di Canzone Quasi D'Amore">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Canzone+Quasi+D%27Amore+Francesco+Guccini" title="Testi di Canzone Quasi D'Amore">testi</a><br>
<b>10</b>. Via Paolo Fabbri 43 - <a target="_blank" href="http://www.google.com/search?q=spartiti+Via+Paolo+Fabbri+43+Francesco+Guccini" title="Spartiti di Via Paolo Fabbri 43">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Via+Paolo+Fabbri+43+Francesco+Guccini" title="Accordi di Via Paolo Fabbri 43">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Via+Paolo+Fabbri+43+Francesco+Guccini" title="Testi di Via Paolo Fabbri 43">testi</a><br>
<b>11</b>. Autogrill - <a target="_blank" href="http://www.google.com/search?q=spartiti+Autogrill+Francesco+Guccini" title="Spartiti di Autogrill">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Autogrill+Francesco+Guccini" title="Accordi di Autogrill">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Autogrill+Francesco+Guccini" title="Testi di Autogrill">testi</a><br>
<b>12</b>. L'Isola Non Trovata - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%27Isola+Non+Trovata+Francesco+Guccini" title="Spartiti di L'Isola Non Trovata">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%27Isola+Non+Trovata+Francesco+Guccini" title="Accordi di L'Isola Non Trovata">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%27Isola+Non+Trovata+Francesco+Guccini" title="Testi di L'Isola Non Trovata">testi</a><br>
<b>13</b>. Asia - <a target="_blank" href="http://www.google.com/search?q=spartiti+Asia+Francesco+Guccini" title="Spartiti di Asia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Asia+Francesco+Guccini" title="Accordi di Asia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Asia+Francesco+Guccini" title="Testi di Asia">testi</a><br>
<b>14</b>. Un Altro Giorno E' Andato - <a target="_blank" href="http://www.google.com/search?q=spartiti+Un+Altro+Giorno+E%27+Andato+Francesco+Guccini" title="Spartiti di Un Altro Giorno E' Andato">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Un+Altro+Giorno+E%27+Andato+Francesco+Guccini" title="Accordi di Un Altro Giorno E' Andato">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Un+Altro+Giorno+E%27+Andato+Francesco+Guccini" title="Testi di Un Altro Giorno E' Andato">testi</a><br>
<h2>D'Amore Di Morte E Di Altre Sciocchezze (1996) </h2>
<b>1</b>. Lettera - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lettera+Francesco+Guccini" title="Spartiti di Lettera">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lettera+Francesco+Guccini" title="Accordi di Lettera">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lettera+Francesco+Guccini" title="Testi di Lettera">testi</a><br>
<b>2</b>. Vorrei - <a target="_blank" href="http://www.google.com/search?q=spartiti+Vorrei+Francesco+Guccini" title="Spartiti di Vorrei">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Vorrei+Francesco+Guccini" title="Accordi di Vorrei">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Vorrei+Francesco+Guccini" title="Testi di Vorrei">testi</a><br>
<b>3</b>. Quattro Stracci - <a target="_blank" href="http://www.google.com/search?q=spartiti+Quattro+Stracci+Francesco+Guccini" title="Spartiti di Quattro Stracci">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Quattro+Stracci+Francesco+Guccini" title="Accordi di Quattro Stracci">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Quattro+Stracci+Francesco+Guccini" title="Testi di Quattro Stracci">testi</a><br>
<b>4</b>. Stelle - <a target="_blank" href="http://www.google.com/search?q=spartiti+Stelle+Francesco+Guccini" title="Spartiti di Stelle">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Stelle+Francesco+Guccini" title="Accordi di Stelle">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Stelle+Francesco+Guccini" title="Testi di Stelle">testi</a><br>
<b>5</b>. Canzone Delle Colombe E Del Fiore - <a target="_blank" href="http://www.google.com/search?q=spartiti+Canzone+Delle+Colombe+E+Del+Fiore+Francesco+Guccini" title="Spartiti di Canzone Delle Colombe E Del Fiore">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Canzone+Delle+Colombe+E+Del+Fiore+Francesco+Guccini" title="Accordi di Canzone Delle Colombe E Del Fiore">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Canzone+Delle+Colombe+E+Del+Fiore+Francesco+Guccini" title="Testi di Canzone Delle Colombe E Del Fiore">testi</a><br>
<b>6</b>. Il Caduto - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Caduto+Francesco+Guccini" title="Spartiti di Il Caduto">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Caduto+Francesco+Guccini" title="Accordi di Il Caduto">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Caduto+Francesco+Guccini" title="Testi di Il Caduto">testi</a><br>
<b>7</b>. Cirano - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cirano+Francesco+Guccini" title="Spartiti di Cirano">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cirano+Francesco+Guccini" title="Accordi di Cirano">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cirano+Francesco+Guccini" title="Testi di Cirano">testi</a><br>
<b>8</b>. Il Matto - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Matto+Francesco+Guccini" title="Spartiti di Il Matto">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Matto+Francesco+Guccini" title="Accordi di Il Matto">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Matto+Francesco+Guccini" title="Testi di Il Matto">testi</a><br>
<b>9</b>. I Fichi - <a target="_blank" href="http://www.google.com/search?q=spartiti+I+Fichi+Francesco+Guccini" title="Spartiti di I Fichi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+I+Fichi+Francesco+Guccini" title="Accordi di I Fichi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+I+Fichi+Francesco+Guccini" title="Testi di I Fichi">testi</a><br>
<h2>Parnassius Guccinii (1994) </h2>
<b>1</b>. Canzone Per Silvia - <a target="_blank" href="http://www.google.com/search?q=spartiti+Canzone+Per+Silvia+Francesco+Guccini" title="Spartiti di Canzone Per Silvia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Canzone+Per+Silvia+Francesco+Guccini" title="Accordi di Canzone Per Silvia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Canzone+Per+Silvia+Francesco+Guccini" title="Testi di Canzone Per Silvia">testi</a><br>
<b>2</b>. Acque - <a target="_blank" href="http://www.google.com/search?q=spartiti+Acque+Francesco+Guccini" title="Spartiti di Acque">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Acque+Francesco+Guccini" title="Accordi di Acque">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Acque+Francesco+Guccini" title="Testi di Acque">testi</a><br>
<b>3</b>. Samantha - <a target="_blank" href="http://www.google.com/search?q=spartiti+Samantha+Francesco+Guccini" title="Spartiti di Samantha">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Samantha+Francesco+Guccini" title="Accordi di Samantha">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Samantha+Francesco+Guccini" title="Testi di Samantha">testi</a><br>
<b>4</b>. Farewell - <a target="_blank" href="http://www.google.com/search?q=spartiti+Farewell+Francesco+Guccini" title="Spartiti di Farewell">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Farewell+Francesco+Guccini" title="Accordi di Farewell">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Farewell+Francesco+Guccini" title="Testi di Farewell">testi</a><br>
<b>5</b>. Nostra Signora Dell'Ipocrisia - <a target="_blank" href="http://www.google.com/search?q=spartiti+Nostra+Signora+Dell%27Ipocrisia+Francesco+Guccini" title="Spartiti di Nostra Signora Dell'Ipocrisia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Nostra+Signora+Dell%27Ipocrisia+Francesco+Guccini" title="Accordi di Nostra Signora Dell'Ipocrisia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Nostra+Signora+Dell%27Ipocrisia+Francesco+Guccini" title="Testi di Nostra Signora Dell'Ipocrisia">testi</a><br>
<b>6</b>. Dovevo Fare Del Cinema - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dovevo+Fare+Del+Cinema+Francesco+Guccini" title="Spartiti di Dovevo Fare Del Cinema">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dovevo+Fare+Del+Cinema+Francesco+Guccini" title="Accordi di Dovevo Fare Del Cinema">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dovevo+Fare+Del+Cinema+Francesco+Guccini" title="Testi di Dovevo Fare Del Cinema">testi</a><br>
<b>7</b>. Non Bisognerebbe - <a target="_blank" href="http://www.google.com/search?q=spartiti+Non+Bisognerebbe+Francesco+Guccini" title="Spartiti di Non Bisognerebbe">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Non+Bisognerebbe+Francesco+Guccini" title="Accordi di Non Bisognerebbe">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Non+Bisognerebbe+Francesco+Guccini" title="Testi di Non Bisognerebbe">testi</a><br>
<b>8</b>. Luna Fortuna - <a target="_blank" href="http://www.google.com/search?q=spartiti+Luna+Fortuna+Francesco+Guccini" title="Spartiti di Luna Fortuna">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Luna+Fortuna+Francesco+Guccini" title="Accordi di Luna Fortuna">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Luna+Fortuna+Francesco+Guccini" title="Testi di Luna Fortuna">testi</a><br>
<b>9</b>. Parole - <a target="_blank" href="http://www.google.com/search?q=spartiti+Parole+Francesco+Guccini" title="Spartiti di Parole">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Parole+Francesco+Guccini" title="Accordi di Parole">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Parole+Francesco+Guccini" title="Testi di Parole">testi</a><br>
<h2>Quello Che Non... (1990) </h2>
<b>1</b>. Quello Che Non... - <a target="_blank" href="http://www.google.com/search?q=spartiti+Quello+Che+Non...+Francesco+Guccini" title="Spartiti di Quello Che Non...">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Quello+Che+Non...+Francesco+Guccini" title="Accordi di Quello Che Non...">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Quello+Che+Non...+Francesco+Guccini" title="Testi di Quello Che Non...">testi</a><br>
<b>2</b>. Canzone Delle Domande Consuete - <a target="_blank" href="http://www.google.com/search?q=spartiti+Canzone+Delle+Domande+Consuete+Francesco+Guccini" title="Spartiti di Canzone Delle Domande Consuete">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Canzone+Delle+Domande+Consuete+Francesco+Guccini" title="Accordi di Canzone Delle Domande Consuete">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Canzone+Delle+Domande+Consuete+Francesco+Guccini" title="Testi di Canzone Delle Domande Consuete">testi</a><br>
<b>3</b>. Canzone Per Anna - <a target="_blank" href="http://www.google.com/search?q=spartiti+Canzone+Per+Anna+Francesco+Guccini" title="Spartiti di Canzone Per Anna">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Canzone+Per+Anna+Francesco+Guccini" title="Accordi di Canzone Per Anna">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Canzone+Per+Anna+Francesco+Guccini" title="Testi di Canzone Per Anna">testi</a><br>
<b>4</b>. Ballando Con Una Sconosciuta - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ballando+Con+Una+Sconosciuta+Francesco+Guccini" title="Spartiti di Ballando Con Una Sconosciuta">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ballando+Con+Una+Sconosciuta+Francesco+Guccini" title="Accordi di Ballando Con Una Sconosciuta">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ballando+Con+Una+Sconosciuta+Francesco+Guccini" title="Testi di Ballando Con Una Sconosciuta">testi</a><br>
<b>5</b>. Le Ragazze Della Notte - <a target="_blank" href="http://www.google.com/search?q=spartiti+Le+Ragazze+Della+Notte+Francesco+Guccini" title="Spartiti di Le Ragazze Della Notte">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Le+Ragazze+Della+Notte+Francesco+Guccini" title="Accordi di Le Ragazze Della Notte">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Le+Ragazze+Della+Notte+Francesco+Guccini" title="Testi di Le Ragazze Della Notte">testi</a><br>
<b>6</b>. Tango Per Due - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tango+Per+Due+Francesco+Guccini" title="Spartiti di Tango Per Due">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tango+Per+Due+Francesco+Guccini" title="Accordi di Tango Per Due">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tango+Per+Due+Francesco+Guccini" title="Testi di Tango Per Due">testi</a><br>
<b>7</b>. Cencio - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cencio+Francesco+Guccini" title="Spartiti di Cencio">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cencio+Francesco+Guccini" title="Accordi di Cencio">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cencio+Francesco+Guccini" title="Testi di Cencio">testi</a><br>
<b>8</b>. Emilia - <a target="_blank" href="http://www.google.com/search?q=spartiti+Emilia+Francesco+Guccini" title="Spartiti di Emilia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Emilia+Francesco+Guccini" title="Accordi di Emilia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Emilia+Francesco+Guccini" title="Testi di Emilia">testi</a><br>
<h2>...Quasi Come Dumas... (1988) </h2>
<b>1</b>. Due Anni Dopo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Due+Anni+Dopo+Francesco+Guccini" title="Spartiti di Due Anni Dopo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Due+Anni+Dopo+Francesco+Guccini" title="Accordi di Due Anni Dopo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Due+Anni+Dopo+Francesco+Guccini" title="Testi di Due Anni Dopo">testi</a><br>
<b>2</b>. Auschwitz - <a target="_blank" href="http://www.google.com/search?q=spartiti+Auschwitz+Francesco+Guccini" title="Spartiti di Auschwitz">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Auschwitz+Francesco+Guccini" title="Accordi di Auschwitz">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Auschwitz+Francesco+Guccini" title="Testi di Auschwitz">testi</a><br>
<b>3</b>. Ti Ricordi Quei Giorni - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ti+Ricordi+Quei+Giorni+Francesco+Guccini" title="Spartiti di Ti Ricordi Quei Giorni">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ti+Ricordi+Quei+Giorni+Francesco+Guccini" title="Accordi di Ti Ricordi Quei Giorni">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ti+Ricordi+Quei+Giorni+Francesco+Guccini" title="Testi di Ti Ricordi Quei Giorni">testi</a><br>
<b>4</b>. L'Ubriaco - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%27Ubriaco+Francesco+Guccini" title="Spartiti di L'Ubriaco">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%27Ubriaco+Francesco+Guccini" title="Accordi di L'Ubriaco">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%27Ubriaco+Francesco+Guccini" title="Testi di L'Ubriaco">testi</a><br>
<b>5</b>. Giorno D'Estate - <a target="_blank" href="http://www.google.com/search?q=spartiti+Giorno+D%27Estate+Francesco+Guccini" title="Spartiti di Giorno D'Estate">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Giorno+D%27Estate+Francesco+Guccini" title="Accordi di Giorno D'Estate">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Giorno+D%27Estate+Francesco+Guccini" title="Testi di Giorno D'Estate">testi</a><br>
<b>6</b>. Primavera Di Praga - <a target="_blank" href="http://www.google.com/search?q=spartiti+Primavera+Di+Praga+Francesco+Guccini" title="Spartiti di Primavera Di Praga">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Primavera+Di+Praga+Francesco+Guccini" title="Accordi di Primavera Di Praga">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Primavera+Di+Praga+Francesco+Guccini" title="Testi di Primavera Di Praga">testi</a><br>
<b>7</b>. L'Albero Ed Io - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%27Albero+Ed+Io+Francesco+Guccini" title="Spartiti di L'Albero Ed Io">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%27Albero+Ed+Io+Francesco+Guccini" title="Accordi di L'Albero Ed Io">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%27Albero+Ed+Io+Francesco+Guccini" title="Testi di L'Albero Ed Io">testi</a><br>
<b>8</b>. Per Quando E' Tardi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Per+Quando+E%27+Tardi+Francesco+Guccini" title="Spartiti di Per Quando E' Tardi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Per+Quando+E%27+Tardi+Francesco+Guccini" title="Accordi di Per Quando E' Tardi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Per+Quando+E%27+Tardi+Francesco+Guccini" title="Testi di Per Quando E' Tardi">testi</a><br>
<b>9</b>. Dio E' Morto - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dio+E%27+Morto+Francesco+Guccini" title="Spartiti di Dio E' Morto">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dio+E%27+Morto+Francesco+Guccini" title="Accordi di Dio E' Morto">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dio+E%27+Morto+Francesco+Guccini" title="Testi di Dio E' Morto">testi</a><br>
<b>10</b>. Al Trist - <a target="_blank" href="http://www.google.com/search?q=spartiti+Al+Trist+Francesco+Guccini" title="Spartiti di Al Trist">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Al+Trist+Francesco+Guccini" title="Accordi di Al Trist">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Al+Trist+Francesco+Guccini" title="Testi di Al Trist">testi</a><br>
<h2>Signora Bovary (1987) </h2>
<b>1</b>. Scirocco - <a target="_blank" href="http://www.google.com/search?q=spartiti+Scirocco+Francesco+Guccini" title="Spartiti di Scirocco">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Scirocco+Francesco+Guccini" title="Accordi di Scirocco">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Scirocco+Francesco+Guccini" title="Testi di Scirocco">testi</a><br>
<b>2</b>. Signora Bovary - <a target="_blank" href="http://www.google.com/search?q=spartiti+Signora+Bovary+Francesco+Guccini" title="Spartiti di Signora Bovary">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Signora+Bovary+Francesco+Guccini" title="Accordi di Signora Bovary">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Signora+Bovary+Francesco+Guccini" title="Testi di Signora Bovary">testi</a><br>
<b>3</b>. Von Loon - <a target="_blank" href="http://www.google.com/search?q=spartiti+Von+Loon+Francesco+Guccini" title="Spartiti di Von Loon">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Von+Loon+Francesco+Guccini" title="Accordi di Von Loon">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Von+Loon+Francesco+Guccini" title="Testi di Von Loon">testi</a><br>
<b>4</b>. Culodritto - <a target="_blank" href="http://www.google.com/search?q=spartiti+Culodritto+Francesco+Guccini" title="Spartiti di Culodritto">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Culodritto+Francesco+Guccini" title="Accordi di Culodritto">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Culodritto+Francesco+Guccini" title="Testi di Culodritto">testi</a><br>
<b>5</b>. Keaton - <a target="_blank" href="http://www.google.com/search?q=spartiti+Keaton+Francesco+Guccini" title="Spartiti di Keaton">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Keaton+Francesco+Guccini" title="Accordi di Keaton">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Keaton+Francesco+Guccini" title="Testi di Keaton">testi</a><br>
<b>6</b>. Le Piogge D'Aprile - <a target="_blank" href="http://www.google.com/search?q=spartiti+Le+Piogge+D%27Aprile+Francesco+Guccini" title="Spartiti di Le Piogge D'Aprile">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Le+Piogge+D%27Aprile+Francesco+Guccini" title="Accordi di Le Piogge D'Aprile">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Le+Piogge+D%27Aprile+Francesco+Guccini" title="Testi di Le Piogge D'Aprile">testi</a><br>
<b>7</b>. Canzone Di Notte N. 3 - <a target="_blank" href="http://www.google.com/search?q=spartiti+Canzone+Di+Notte+N.+3+Francesco+Guccini" title="Spartiti di Canzone Di Notte N. 3">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Canzone+Di+Notte+N.+3+Francesco+Guccini" title="Accordi di Canzone Di Notte N. 3">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Canzone+Di+Notte+N.+3+Francesco+Guccini" title="Testi di Canzone Di Notte N. 3">testi</a><br>
<h2>Fra La Via Emilia E Il West - Vol. 2 (1984) </h2>
<b>1</b>. Piccola Città - <a target="_blank" href="http://www.google.com/search?q=spartiti+Piccola+Citt%E0+Francesco+Guccini" title="Spartiti di Piccola Città">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Piccola+Citt%E0+Francesco+Guccini" title="Accordi di Piccola Città">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Piccola+Citt%E0+Francesco+Guccini" title="Testi di Piccola Città">testi</a><br>
<b>2</b>. Venezia - <a target="_blank" href="http://www.google.com/search?q=spartiti+Venezia+Francesco+Guccini" title="Spartiti di Venezia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Venezia+Francesco+Guccini" title="Accordi di Venezia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Venezia+Francesco+Guccini" title="Testi di Venezia">testi</a><br>
<b>3</b>. Bologna - <a target="_blank" href="http://www.google.com/search?q=spartiti+Bologna+Francesco+Guccini" title="Spartiti di Bologna">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Bologna+Francesco+Guccini" title="Accordi di Bologna">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Bologna+Francesco+Guccini" title="Testi di Bologna">testi</a><br>
<b>4</b>. Eskimo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Eskimo+Francesco+Guccini" title="Spartiti di Eskimo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Eskimo+Francesco+Guccini" title="Accordi di Eskimo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Eskimo+Francesco+Guccini" title="Testi di Eskimo">testi</a><br>
<b>5</b>. Incontro - <a target="_blank" href="http://www.google.com/search?q=spartiti+Incontro+Francesco+Guccini" title="Spartiti di Incontro">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Incontro+Francesco+Guccini" title="Accordi di Incontro">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Incontro+Francesco+Guccini" title="Testi di Incontro">testi</a><br>
<b>6</b>. Vedi Cara - <a target="_blank" href="http://www.google.com/search?q=spartiti+Vedi+Cara+Francesco+Guccini" title="Spartiti di Vedi Cara">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Vedi+Cara+Francesco+Guccini" title="Accordi di Vedi Cara">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Vedi+Cara+Francesco+Guccini" title="Testi di Vedi Cara">testi</a><br>
<b>7</b>. Un Altro Giorno E' Andato - <a target="_blank" href="http://www.google.com/search?q=spartiti+Un+Altro+Giorno+E%27+Andato+Francesco+Guccini" title="Spartiti di Un Altro Giorno E' Andato">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Un+Altro+Giorno+E%27+Andato+Francesco+Guccini" title="Accordi di Un Altro Giorno E' Andato">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Un+Altro+Giorno+E%27+Andato+Francesco+Guccini" title="Testi di Un Altro Giorno E' Andato">testi</a><br>
<b>8</b>. Canzone Quasi D'Amore - <a target="_blank" href="http://www.google.com/search?q=spartiti+Canzone+Quasi+D%27Amore+Francesco+Guccini" title="Spartiti di Canzone Quasi D'Amore">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Canzone+Quasi+D%27Amore+Francesco+Guccini" title="Accordi di Canzone Quasi D'Amore">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Canzone+Quasi+D%27Amore+Francesco+Guccini" title="Testi di Canzone Quasi D'Amore">testi</a><br>
<b>9</b>. La Locomotiva - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Locomotiva+Francesco+Guccini" title="Spartiti di La Locomotiva">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Locomotiva+Francesco+Guccini" title="Accordi di La Locomotiva">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Locomotiva+Francesco+Guccini" title="Testi di La Locomotiva">testi</a><br>
<h2>Fra La Via Emilia E Il West - Vol. 1 (1984) </h2>
<b>1</b>. Canzone Per Un'Amica - <a target="_blank" href="http://www.google.com/search?q=spartiti+Canzone+Per+Un%27Amica+Francesco+Guccini" title="Spartiti di Canzone Per Un'Amica">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Canzone+Per+Un%27Amica+Francesco+Guccini" title="Accordi di Canzone Per Un'Amica">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Canzone+Per+Un%27Amica+Francesco+Guccini" title="Testi di Canzone Per Un'Amica">testi</a><br>
<b>2</b>. Autogrill - <a target="_blank" href="http://www.google.com/search?q=spartiti+Autogrill+Francesco+Guccini" title="Spartiti di Autogrill">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Autogrill+Francesco+Guccini" title="Accordi di Autogrill">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Autogrill+Francesco+Guccini" title="Testi di Autogrill">testi</a><br>
<b>3</b>. Il Vecchio E Il Bambino - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Vecchio+E+Il+Bambino+Francesco+Guccini" title="Spartiti di Il Vecchio E Il Bambino">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Vecchio+E+Il+Bambino+Francesco+Guccini" title="Accordi di Il Vecchio E Il Bambino">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Vecchio+E+Il+Bambino+Francesco+Guccini" title="Testi di Il Vecchio E Il Bambino">testi</a><br>
<b>4</b>. Il Pensionato - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Pensionato+Francesco+Guccini" title="Spartiti di Il Pensionato">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Pensionato+Francesco+Guccini" title="Accordi di Il Pensionato">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Pensionato+Francesco+Guccini" title="Testi di Il Pensionato">testi</a><br>
<b>5</b>. L'Isola Non Trovata - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%27Isola+Non+Trovata+Francesco+Guccini" title="Spartiti di L'Isola Non Trovata">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%27Isola+Non+Trovata+Francesco+Guccini" title="Accordi di L'Isola Non Trovata">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%27Isola+Non+Trovata+Francesco+Guccini" title="Testi di L'Isola Non Trovata">testi</a><br>
<b>6</b>. Asia - <a target="_blank" href="http://www.google.com/search?q=spartiti+Asia+Francesco+Guccini" title="Spartiti di Asia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Asia+Francesco+Guccini" title="Accordi di Asia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Asia+Francesco+Guccini" title="Testi di Asia">testi</a><br>
<b>7</b>. Canzone Della Bambina Portoghese - <a target="_blank" href="http://www.google.com/search?q=spartiti+Canzone+Della+Bambina+Portoghese+Francesco+Guccini" title="Spartiti di Canzone Della Bambina Portoghese">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Canzone+Della+Bambina+Portoghese+Francesco+Guccini" title="Accordi di Canzone Della Bambina Portoghese">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Canzone+Della+Bambina+Portoghese+Francesco+Guccini" title="Testi di Canzone Della Bambina Portoghese">testi</a><br>
<b>8</b>. Canzone Delle Osterie Di Fuori Porta - <a target="_blank" href="http://www.google.com/search?q=spartiti+Canzone+Delle+Osterie+Di+Fuori+Porta+Francesco+Guccini" title="Spartiti di Canzone Delle Osterie Di Fuori Porta">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Canzone+Delle+Osterie+Di+Fuori+Porta+Francesco+Guccini" title="Accordi di Canzone Delle Osterie Di Fuori Porta">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Canzone+Delle+Osterie+Di+Fuori+Porta+Francesco+Guccini" title="Testi di Canzone Delle Osterie Di Fuori Porta">testi</a><br>
<b>9</b>. Il Frate - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Frate+Francesco+Guccini" title="Spartiti di Il Frate">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Frate+Francesco+Guccini" title="Accordi di Il Frate">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Frate+Francesco+Guccini" title="Testi di Il Frate">testi</a><br>
<h2>Guccini (1983) </h2>
<b>1</b>. Autogrill - <a target="_blank" href="http://www.google.com/search?q=spartiti+Autogrill+Francesco+Guccini" title="Spartiti di Autogrill">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Autogrill+Francesco+Guccini" title="Accordi di Autogrill">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Autogrill+Francesco+Guccini" title="Testi di Autogrill">testi</a><br>
<b>2</b>. Argentina - <a target="_blank" href="http://www.google.com/search?q=spartiti+Argentina+Francesco+Guccini" title="Spartiti di Argentina">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Argentina+Francesco+Guccini" title="Accordi di Argentina">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Argentina+Francesco+Guccini" title="Testi di Argentina">testi</a><br>
<b>3</b>. Gulliver - <a target="_blank" href="http://www.google.com/search?q=spartiti+Gulliver+Francesco+Guccini" title="Spartiti di Gulliver">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Gulliver+Francesco+Guccini" title="Accordi di Gulliver">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Gulliver+Francesco+Guccini" title="Testi di Gulliver">testi</a><br>
<b>4</b>. Shomér, Ma Mi-Llailah? - <a target="_blank" href="http://www.google.com/search?q=spartiti+Shom%E9r%2C+Ma+Mi-Llailah%3F+Francesco+Guccini" title="Spartiti di Shomér, Ma Mi-Llailah?">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Shom%E9r%2C+Ma+Mi-Llailah%3F+Francesco+Guccini" title="Accordi di Shomér, Ma Mi-Llailah?">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Shom%E9r%2C+Ma+Mi-Llailah%3F+Francesco+Guccini" title="Testi di Shomér, Ma Mi-Llailah?">testi</a><br>
<b>5</b>. Inutile - <a target="_blank" href="http://www.google.com/search?q=spartiti+Inutile+Francesco+Guccini" title="Spartiti di Inutile">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Inutile+Francesco+Guccini" title="Accordi di Inutile">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Inutile+Francesco+Guccini" title="Testi di Inutile">testi</a><br>
<b>6</b>. Gli Amici - <a target="_blank" href="http://www.google.com/search?q=spartiti+Gli+Amici+Francesco+Guccini" title="Spartiti di Gli Amici">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Gli+Amici+Francesco+Guccini" title="Accordi di Gli Amici">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Gli+Amici+Francesco+Guccini" title="Testi di Gli Amici">testi</a><br>
<h2>Metropolis (1981) </h2>
<b>1</b>. Bisanzio - <a target="_blank" href="http://www.google.com/search?q=spartiti+Bisanzio+Francesco+Guccini" title="Spartiti di Bisanzio">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Bisanzio+Francesco+Guccini" title="Accordi di Bisanzio">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Bisanzio+Francesco+Guccini" title="Testi di Bisanzio">testi</a><br>
<b>2</b>. Venezia - <a target="_blank" href="http://www.google.com/search?q=spartiti+Venezia+Francesco+Guccini" title="Spartiti di Venezia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Venezia+Francesco+Guccini" title="Accordi di Venezia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Venezia+Francesco+Guccini" title="Testi di Venezia">testi</a><br>
<b>3</b>. Antenòr - <a target="_blank" href="http://www.google.com/search?q=spartiti+Anten%F2r+Francesco+Guccini" title="Spartiti di Antenòr">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Anten%F2r+Francesco+Guccini" title="Accordi di Antenòr">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Anten%F2r+Francesco+Guccini" title="Testi di Antenòr">testi</a><br>
<b>4</b>. Bologna - <a target="_blank" href="http://www.google.com/search?q=spartiti+Bologna+Francesco+Guccini" title="Spartiti di Bologna">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Bologna+Francesco+Guccini" title="Accordi di Bologna">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Bologna+Francesco+Guccini" title="Testi di Bologna">testi</a><br>
<b>5</b>. Lager - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lager+Francesco+Guccini" title="Spartiti di Lager">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lager+Francesco+Guccini" title="Accordi di Lager">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lager+Francesco+Guccini" title="Testi di Lager">testi</a><br>
<b>6</b>. Black-Out - <a target="_blank" href="http://www.google.com/search?q=spartiti+Black-Out+Francesco+Guccini" title="Spartiti di Black-Out">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Black-Out+Francesco+Guccini" title="Accordi di Black-Out">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Black-Out+Francesco+Guccini" title="Testi di Black-Out">testi</a><br>
<b>7</b>. Milano (Poveri Bimbi Di) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Milano+%28Poveri+Bimbi+Di%29+Francesco+Guccini" title="Spartiti di Milano (Poveri Bimbi Di)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Milano+%28Poveri+Bimbi+Di%29+Francesco+Guccini" title="Accordi di Milano (Poveri Bimbi Di)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Milano+%28Poveri+Bimbi+Di%29+Francesco+Guccini" title="Testi di Milano (Poveri Bimbi Di)">testi</a><br>
<h2>Francesco Guccini & I Nomadi - Album Concerto (1979) </h2>
<b>1</b>. Canzone Per Un'Amica - <a target="_blank" href="http://www.google.com/search?q=spartiti+Canzone+Per+Un%27Amica+Francesco+Guccini" title="Spartiti di Canzone Per Un'Amica">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Canzone+Per+Un%27Amica+Francesco+Guccini" title="Accordi di Canzone Per Un'Amica">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Canzone+Per+Un%27Amica+Francesco+Guccini" title="Testi di Canzone Per Un'Amica">testi</a><br>
<b>2</b>. L'Atomica Cinese - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%27Atomica+Cinese+Francesco+Guccini" title="Spartiti di L'Atomica Cinese">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%27Atomica+Cinese+Francesco+Guccini" title="Accordi di L'Atomica Cinese">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%27Atomica+Cinese+Francesco+Guccini" title="Testi di L'Atomica Cinese">testi</a><br>
<b>3</b>. Noi Non Ci Saremo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Noi+Non+Ci+Saremo+Francesco+Guccini" title="Spartiti di Noi Non Ci Saremo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Noi+Non+Ci+Saremo+Francesco+Guccini" title="Accordi di Noi Non Ci Saremo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Noi+Non+Ci+Saremo+Francesco+Guccini" title="Testi di Noi Non Ci Saremo">testi</a><br>
<b>4</b>. Per Fare Un Uomo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Per+Fare+Un+Uomo+Francesco+Guccini" title="Spartiti di Per Fare Un Uomo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Per+Fare+Un+Uomo+Francesco+Guccini" title="Accordi di Per Fare Un Uomo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Per+Fare+Un+Uomo+Francesco+Guccini" title="Testi di Per Fare Un Uomo">testi</a><br>
<b>5</b>. Primavera Di Praga - <a target="_blank" href="http://www.google.com/search?q=spartiti+Primavera+Di+Praga+Francesco+Guccini" title="Spartiti di Primavera Di Praga">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Primavera+Di+Praga+Francesco+Guccini" title="Accordi di Primavera Di Praga">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Primavera+Di+Praga+Francesco+Guccini" title="Testi di Primavera Di Praga">testi</a><br>
<b>6</b>. Dio E' Morto - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dio+E%27+Morto+Francesco+Guccini" title="Spartiti di Dio E' Morto">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dio+E%27+Morto+Francesco+Guccini" title="Accordi di Dio E' Morto">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dio+E%27+Morto+Francesco+Guccini" title="Testi di Dio E' Morto">testi</a><br>
<b>7</b>. La Canzone Del Bambino Nel Vento (Auschwitz) - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Canzone+Del+Bambino+Nel+Vento+%28Auschwitz%29+Francesco+Guccini" title="Spartiti di La Canzone Del Bambino Nel Vento (Auschwitz)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Canzone+Del+Bambino+Nel+Vento+%28Auschwitz%29+Francesco+Guccini" title="Accordi di La Canzone Del Bambino Nel Vento (Auschwitz)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Canzone+Del+Bambino+Nel+Vento+%28Auschwitz%29+Francesco+Guccini" title="Testi di La Canzone Del Bambino Nel Vento (Auschwitz)">testi</a><br>
<b>8</b>. Noi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Noi+Francesco+Guccini" title="Spartiti di Noi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Noi+Francesco+Guccini" title="Accordi di Noi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Noi+Francesco+Guccini" title="Testi di Noi">testi</a><br>
<b>9</b>. Statale 17 - <a target="_blank" href="http://www.google.com/search?q=spartiti+Statale+17+Francesco+Guccini" title="Spartiti di Statale 17">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Statale+17+Francesco+Guccini" title="Accordi di Statale 17">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Statale+17+Francesco+Guccini" title="Testi di Statale 17">testi</a><br>
<h2>Amerigo (1978) </h2>
<b>1</b>. Amerigo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Amerigo+Francesco+Guccini" title="Spartiti di Amerigo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Amerigo+Francesco+Guccini" title="Accordi di Amerigo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Amerigo+Francesco+Guccini" title="Testi di Amerigo">testi</a><br>
<b>2</b>. Libera Nos Domine - <a target="_blank" href="http://www.google.com/search?q=spartiti+Libera+Nos+Domine+Francesco+Guccini" title="Spartiti di Libera Nos Domine">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Libera+Nos+Domine+Francesco+Guccini" title="Accordi di Libera Nos Domine">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Libera+Nos+Domine+Francesco+Guccini" title="Testi di Libera Nos Domine">testi</a><br>
<b>3</b>. 100, Pennsylvania Ave. - <a target="_blank" href="http://www.google.com/search?q=spartiti+100%2C+Pennsylvania+Ave.+Francesco+Guccini" title="Spartiti di 100, Pennsylvania Ave.">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+100%2C+Pennsylvania+Ave.+Francesco+Guccini" title="Accordi di 100, Pennsylvania Ave.">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+100%2C+Pennsylvania+Ave.+Francesco+Guccini" title="Testi di 100, Pennsylvania Ave.">testi</a><br>
<b>4</b>. Eskimo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Eskimo+Francesco+Guccini" title="Spartiti di Eskimo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Eskimo+Francesco+Guccini" title="Accordi di Eskimo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Eskimo+Francesco+Guccini" title="Testi di Eskimo">testi</a><br>
<b>5</b>. Le Cinque Anatre - <a target="_blank" href="http://www.google.com/search?q=spartiti+Le+Cinque+Anatre+Francesco+Guccini" title="Spartiti di Le Cinque Anatre">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Le+Cinque+Anatre+Francesco+Guccini" title="Accordi di Le Cinque Anatre">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Le+Cinque+Anatre+Francesco+Guccini" title="Testi di Le Cinque Anatre">testi</a><br>
<b>6</b>. Mondo Nuovo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Mondo+Nuovo+Francesco+Guccini" title="Spartiti di Mondo Nuovo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Mondo+Nuovo+Francesco+Guccini" title="Accordi di Mondo Nuovo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Mondo+Nuovo+Francesco+Guccini" title="Testi di Mondo Nuovo">testi</a><br>
<h2>Via Paolo Fabbri 43 (1976) </h2>
<b>1</b>. Piccola Storia Ignobile - <a target="_blank" href="http://www.google.com/search?q=spartiti+Piccola+Storia+Ignobile+Francesco+Guccini" title="Spartiti di Piccola Storia Ignobile">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Piccola+Storia+Ignobile+Francesco+Guccini" title="Accordi di Piccola Storia Ignobile">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Piccola+Storia+Ignobile+Francesco+Guccini" title="Testi di Piccola Storia Ignobile">testi</a><br>
<b>2</b>. Canzone Di Notte N. 2 - <a target="_blank" href="http://www.google.com/search?q=spartiti+Canzone+Di+Notte+N.+2+Francesco+Guccini" title="Spartiti di Canzone Di Notte N. 2">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Canzone+Di+Notte+N.+2+Francesco+Guccini" title="Accordi di Canzone Di Notte N. 2">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Canzone+Di+Notte+N.+2+Francesco+Guccini" title="Testi di Canzone Di Notte N. 2">testi</a><br>
<b>3</b>. L'Avvelenata - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%27Avvelenata+Francesco+Guccini" title="Spartiti di L'Avvelenata">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%27Avvelenata+Francesco+Guccini" title="Accordi di L'Avvelenata">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%27Avvelenata+Francesco+Guccini" title="Testi di L'Avvelenata">testi</a><br>
<b>4</b>. Via Paolo Fabbri 43 - <a target="_blank" href="http://www.google.com/search?q=spartiti+Via+Paolo+Fabbri+43+Francesco+Guccini" title="Spartiti di Via Paolo Fabbri 43">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Via+Paolo+Fabbri+43+Francesco+Guccini" title="Accordi di Via Paolo Fabbri 43">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Via+Paolo+Fabbri+43+Francesco+Guccini" title="Testi di Via Paolo Fabbri 43">testi</a><br>
<b>5</b>. Canzone Quasi D'Amore - <a target="_blank" href="http://www.google.com/search?q=spartiti+Canzone+Quasi+D%27Amore+Francesco+Guccini" title="Spartiti di Canzone Quasi D'Amore">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Canzone+Quasi+D%27Amore+Francesco+Guccini" title="Accordi di Canzone Quasi D'Amore">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Canzone+Quasi+D%27Amore+Francesco+Guccini" title="Testi di Canzone Quasi D'Amore">testi</a><br>
<b>6</b>. Il Pensionato - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Pensionato+Francesco+Guccini" title="Spartiti di Il Pensionato">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Pensionato+Francesco+Guccini" title="Accordi di Il Pensionato">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Pensionato+Francesco+Guccini" title="Testi di Il Pensionato">testi</a><br>
<h2>Stanze Di Vita Quotidiana (1974) </h2>
<b>1</b>. Canzone Delle Osterie Di Fuori Porta - <a target="_blank" href="http://www.google.com/search?q=spartiti+Canzone+Delle+Osterie+Di+Fuori+Porta+Francesco+Guccini" title="Spartiti di Canzone Delle Osterie Di Fuori Porta">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Canzone+Delle+Osterie+Di+Fuori+Porta+Francesco+Guccini" title="Accordi di Canzone Delle Osterie Di Fuori Porta">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Canzone+Delle+Osterie+Di+Fuori+Porta+Francesco+Guccini" title="Testi di Canzone Delle Osterie Di Fuori Porta">testi</a><br>
<b>2</b>. Canzone Della Triste Rinuncia - <a target="_blank" href="http://www.google.com/search?q=spartiti+Canzone+Della+Triste+Rinuncia+Francesco+Guccini" title="Spartiti di Canzone Della Triste Rinuncia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Canzone+Della+Triste+Rinuncia+Francesco+Guccini" title="Accordi di Canzone Della Triste Rinuncia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Canzone+Della+Triste+Rinuncia+Francesco+Guccini" title="Testi di Canzone Della Triste Rinuncia">testi</a><br>
<b>3</b>. Canzone Della Vita Quotidiana - <a target="_blank" href="http://www.google.com/search?q=spartiti+Canzone+Della+Vita+Quotidiana+Francesco+Guccini" title="Spartiti di Canzone Della Vita Quotidiana">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Canzone+Della+Vita+Quotidiana+Francesco+Guccini" title="Accordi di Canzone Della Vita Quotidiana">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Canzone+Della+Vita+Quotidiana+Francesco+Guccini" title="Testi di Canzone Della Vita Quotidiana">testi</a><br>
<b>4</b>. Canzone Per Piero - <a target="_blank" href="http://www.google.com/search?q=spartiti+Canzone+Per+Piero+Francesco+Guccini" title="Spartiti di Canzone Per Piero">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Canzone+Per+Piero+Francesco+Guccini" title="Accordi di Canzone Per Piero">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Canzone+Per+Piero+Francesco+Guccini" title="Testi di Canzone Per Piero">testi</a><br>
<b>5</b>. Canzone Delle Ragazze Che Se Ne Vanno - <a target="_blank" href="http://www.google.com/search?q=spartiti+Canzone+Delle+Ragazze+Che+Se+Ne+Vanno+Francesco+Guccini" title="Spartiti di Canzone Delle Ragazze Che Se Ne Vanno">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Canzone+Delle+Ragazze+Che+Se+Ne+Vanno+Francesco+Guccini" title="Accordi di Canzone Delle Ragazze Che Se Ne Vanno">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Canzone+Delle+Ragazze+Che+Se+Ne+Vanno+Francesco+Guccini" title="Testi di Canzone Delle Ragazze Che Se Ne Vanno">testi</a><br>
<b>6</b>. Canzone Delle Situazioni Differenti - <a target="_blank" href="http://www.google.com/search?q=spartiti+Canzone+Delle+Situazioni+Differenti+Francesco+Guccini" title="Spartiti di Canzone Delle Situazioni Differenti">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Canzone+Delle+Situazioni+Differenti+Francesco+Guccini" title="Accordi di Canzone Delle Situazioni Differenti">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Canzone+Delle+Situazioni+Differenti+Francesco+Guccini" title="Testi di Canzone Delle Situazioni Differenti">testi</a><br>
<h2>Opera Buffa (1973) </h2>
<b>1</b>. Il Bello - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Bello+Francesco+Guccini" title="Spartiti di Il Bello">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Bello+Francesco+Guccini" title="Accordi di Il Bello">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Bello+Francesco+Guccini" title="Testi di Il Bello">testi</a><br>
<b>2</b>. Di Mamme Ce N'è Una Sola - <a target="_blank" href="http://www.google.com/search?q=spartiti+Di+Mamme+Ce+N%27%E8+Una+Sola+Francesco+Guccini" title="Spartiti di Di Mamme Ce N'è Una Sola">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Di+Mamme+Ce+N%27%E8+Una+Sola+Francesco+Guccini" title="Accordi di Di Mamme Ce N'è Una Sola">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Di+Mamme+Ce+N%27%E8+Una+Sola+Francesco+Guccini" title="Testi di Di Mamme Ce N'è Una Sola">testi</a><br>
<b>3</b>. La Genesi - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Genesi+Francesco+Guccini" title="Spartiti di La Genesi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Genesi+Francesco+Guccini" title="Accordi di La Genesi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Genesi+Francesco+Guccini" title="Testi di La Genesi">testi</a><br>
<b>4</b>. Fantoni Cesira - <a target="_blank" href="http://www.google.com/search?q=spartiti+Fantoni+Cesira+Francesco+Guccini" title="Spartiti di Fantoni Cesira">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Fantoni+Cesira+Francesco+Guccini" title="Accordi di Fantoni Cesira">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Fantoni+Cesira+Francesco+Guccini" title="Testi di Fantoni Cesira">testi</a><br>
<b>5</b>. Talkin' Sul Sesso - <a target="_blank" href="http://www.google.com/search?q=spartiti+Talkin%27+Sul+Sesso+Francesco+Guccini" title="Spartiti di Talkin' Sul Sesso">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Talkin%27+Sul+Sesso+Francesco+Guccini" title="Accordi di Talkin' Sul Sesso">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Talkin%27+Sul+Sesso+Francesco+Guccini" title="Testi di Talkin' Sul Sesso">testi</a><br>
<b>6</b>. La Fiera Di San Lazzaro - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Fiera+Di+San+Lazzaro+Francesco+Guccini" title="Spartiti di La Fiera Di San Lazzaro">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Fiera+Di+San+Lazzaro+Francesco+Guccini" title="Accordi di La Fiera Di San Lazzaro">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Fiera+Di+San+Lazzaro+Francesco+Guccini" title="Testi di La Fiera Di San Lazzaro">testi</a><br>
<h2>Radici (1972) </h2>
<b>1</b>. Radici - <a target="_blank" href="http://www.google.com/search?q=spartiti+Radici+Francesco+Guccini" title="Spartiti di Radici">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Radici+Francesco+Guccini" title="Accordi di Radici">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Radici+Francesco+Guccini" title="Testi di Radici">testi</a><br>
<b>2</b>. La Locomotiva - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Locomotiva+Francesco+Guccini" title="Spartiti di La Locomotiva">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Locomotiva+Francesco+Guccini" title="Accordi di La Locomotiva">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Locomotiva+Francesco+Guccini" title="Testi di La Locomotiva">testi</a><br>
<b>3</b>. Piccola Città - <a target="_blank" href="http://www.google.com/search?q=spartiti+Piccola+Citt%E0+Francesco+Guccini" title="Spartiti di Piccola Città">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Piccola+Citt%E0+Francesco+Guccini" title="Accordi di Piccola Città">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Piccola+Citt%E0+Francesco+Guccini" title="Testi di Piccola Città">testi</a><br>
<b>4</b>. Incontro - <a target="_blank" href="http://www.google.com/search?q=spartiti+Incontro+Francesco+Guccini" title="Spartiti di Incontro">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Incontro+Francesco+Guccini" title="Accordi di Incontro">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Incontro+Francesco+Guccini" title="Testi di Incontro">testi</a><br>
<b>5</b>. Canzone Dei Dodici Mesi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Canzone+Dei+Dodici+Mesi+Francesco+Guccini" title="Spartiti di Canzone Dei Dodici Mesi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Canzone+Dei+Dodici+Mesi+Francesco+Guccini" title="Accordi di Canzone Dei Dodici Mesi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Canzone+Dei+Dodici+Mesi+Francesco+Guccini" title="Testi di Canzone Dei Dodici Mesi">testi</a><br>
<b>6</b>. Canzone Della Bambina Portoghese - <a target="_blank" href="http://www.google.com/search?q=spartiti+Canzone+Della+Bambina+Portoghese+Francesco+Guccini" title="Spartiti di Canzone Della Bambina Portoghese">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Canzone+Della+Bambina+Portoghese+Francesco+Guccini" title="Accordi di Canzone Della Bambina Portoghese">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Canzone+Della+Bambina+Portoghese+Francesco+Guccini" title="Testi di Canzone Della Bambina Portoghese">testi</a><br>
<b>7</b>. Il Vecchio E Il Bambino - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Vecchio+E+Il+Bambino+Francesco+Guccini" title="Spartiti di Il Vecchio E Il Bambino">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Vecchio+E+Il+Bambino+Francesco+Guccini" title="Accordi di Il Vecchio E Il Bambino">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Vecchio+E+Il+Bambino+Francesco+Guccini" title="Testi di Il Vecchio E Il Bambino">testi</a><br>
<h2>L'Isola Non Trovata (1971) </h2>
<b>1</b>. L'Isola Non Trovata - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%27Isola+Non+Trovata+Francesco+Guccini" title="Spartiti di L'Isola Non Trovata">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%27Isola+Non+Trovata+Francesco+Guccini" title="Accordi di L'Isola Non Trovata">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%27Isola+Non+Trovata+Francesco+Guccini" title="Testi di L'Isola Non Trovata">testi</a><br>
<b>2</b>. L'Orizzonte Di K.D. - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%27Orizzonte+Di+K.D.+Francesco+Guccini" title="Spartiti di L'Orizzonte Di K.D.">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%27Orizzonte+Di+K.D.+Francesco+Guccini" title="Accordi di L'Orizzonte Di K.D.">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%27Orizzonte+Di+K.D.+Francesco+Guccini" title="Testi di L'Orizzonte Di K.D.">testi</a><br>
<b>3</b>. La Collina - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Collina+Francesco+Guccini" title="Spartiti di La Collina">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Collina+Francesco+Guccini" title="Accordi di La Collina">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Collina+Francesco+Guccini" title="Testi di La Collina">testi</a><br>
<b>4</b>. Il Frate - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Frate+Francesco+Guccini" title="Spartiti di Il Frate">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Frate+Francesco+Guccini" title="Accordi di Il Frate">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Frate+Francesco+Guccini" title="Testi di Il Frate">testi</a><br>
<b>5</b>. Un Altro Giorno E' Andato - <a target="_blank" href="http://www.google.com/search?q=spartiti+Un+Altro+Giorno+E%27+Andato+Francesco+Guccini" title="Spartiti di Un Altro Giorno E' Andato">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Un+Altro+Giorno+E%27+Andato+Francesco+Guccini" title="Accordi di Un Altro Giorno E' Andato">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Un+Altro+Giorno+E%27+Andato+Francesco+Guccini" title="Testi di Un Altro Giorno E' Andato">testi</a><br>
<b>6</b>. Canzone Di Notte - <a target="_blank" href="http://www.google.com/search?q=spartiti+Canzone+Di+Notte+Francesco+Guccini" title="Spartiti di Canzone Di Notte">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Canzone+Di+Notte+Francesco+Guccini" title="Accordi di Canzone Di Notte">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Canzone+Di+Notte+Francesco+Guccini" title="Testi di Canzone Di Notte">testi</a><br>
<b>7</b>. Il Tema - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Tema+Francesco+Guccini" title="Spartiti di Il Tema">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Tema+Francesco+Guccini" title="Accordi di Il Tema">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Tema+Francesco+Guccini" title="Testi di Il Tema">testi</a><br>
<b>8</b>. L'Uomo - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%27Uomo+Francesco+Guccini" title="Spartiti di L'Uomo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%27Uomo+Francesco+Guccini" title="Accordi di L'Uomo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%27Uomo+Francesco+Guccini" title="Testi di L'Uomo">testi</a><br>
<b>9</b>. Asia - <a target="_blank" href="http://www.google.com/search?q=spartiti+Asia+Francesco+Guccini" title="Spartiti di Asia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Asia+Francesco+Guccini" title="Accordi di Asia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Asia+Francesco+Guccini" title="Testi di Asia">testi</a><br>
<b>10</b>. L'Isola Non Trovata (Reprise) - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%27Isola+Non+Trovata+%28Reprise%29+Francesco+Guccini" title="Spartiti di L'Isola Non Trovata (Reprise)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%27Isola+Non+Trovata+%28Reprise%29+Francesco+Guccini" title="Accordi di L'Isola Non Trovata (Reprise)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%27Isola+Non+Trovata+%28Reprise%29+Francesco+Guccini" title="Testi di L'Isola Non Trovata (Reprise)">testi</a><br>
<h2>Due Anni Dopo (1970) </h2>
<b>1</b>. Lui E Lei - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lui+E+Lei+Francesco+Guccini" title="Spartiti di Lui E Lei">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lui+E+Lei+Francesco+Guccini" title="Accordi di Lui E Lei">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lui+E+Lei+Francesco+Guccini" title="Testi di Lui E Lei">testi</a><br>
<b>2</b>. Primavera Di Praga - <a target="_blank" href="http://www.google.com/search?q=spartiti+Primavera+Di+Praga+Francesco+Guccini" title="Spartiti di Primavera Di Praga">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Primavera+Di+Praga+Francesco+Guccini" title="Accordi di Primavera Di Praga">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Primavera+Di+Praga+Francesco+Guccini" title="Testi di Primavera Di Praga">testi</a><br>
<b>3</b>. Giorno D'Estate - <a target="_blank" href="http://www.google.com/search?q=spartiti+Giorno+D%27Estate+Francesco+Guccini" title="Spartiti di Giorno D'Estate">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Giorno+D%27Estate+Francesco+Guccini" title="Accordi di Giorno D'Estate">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Giorno+D%27Estate+Francesco+Guccini" title="Testi di Giorno D'Estate">testi</a><br>
<b>4</b>. Il Compleanno - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Compleanno+Francesco+Guccini" title="Spartiti di Il Compleanno">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Compleanno+Francesco+Guccini" title="Accordi di Il Compleanno">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Compleanno+Francesco+Guccini" title="Testi di Il Compleanno">testi</a><br>
<b>5</b>. L'Albero Ed Io - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%27Albero+Ed+Io+Francesco+Guccini" title="Spartiti di L'Albero Ed Io">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%27Albero+Ed+Io+Francesco+Guccini" title="Accordi di L'Albero Ed Io">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%27Albero+Ed+Io+Francesco+Guccini" title="Testi di L'Albero Ed Io">testi</a><br>
<b>6</b>. Due Anni Dopo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Due+Anni+Dopo+Francesco+Guccini" title="Spartiti di Due Anni Dopo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Due+Anni+Dopo+Francesco+Guccini" title="Accordi di Due Anni Dopo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Due+Anni+Dopo+Francesco+Guccini" title="Testi di Due Anni Dopo">testi</a><br>
<b>7</b>. Per Quando E' Tardi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Per+Quando+E%27+Tardi+Francesco+Guccini" title="Spartiti di Per Quando E' Tardi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Per+Quando+E%27+Tardi+Francesco+Guccini" title="Accordi di Per Quando E' Tardi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Per+Quando+E%27+Tardi+Francesco+Guccini" title="Testi di Per Quando E' Tardi">testi</a><br>
<b>8</b>. Vedi Cara - <a target="_blank" href="http://www.google.com/search?q=spartiti+Vedi+Cara+Francesco+Guccini" title="Spartiti di Vedi Cara">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Vedi+Cara+Francesco+Guccini" title="Accordi di Vedi Cara">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Vedi+Cara+Francesco+Guccini" title="Testi di Vedi Cara">testi</a><br>
<b>9</b>. Ophelia - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ophelia+Francesco+Guccini" title="Spartiti di Ophelia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ophelia+Francesco+Guccini" title="Accordi di Ophelia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ophelia+Francesco+Guccini" title="Testi di Ophelia">testi</a><br>
<b>10</b>. L'Ubriaco - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%27Ubriaco+Francesco+Guccini" title="Spartiti di L'Ubriaco">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%27Ubriaco+Francesco+Guccini" title="Accordi di L'Ubriaco">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%27Ubriaco+Francesco+Guccini" title="Testi di L'Ubriaco">testi</a><br>
<b>11</b>. Al Trist - <a target="_blank" href="http://www.google.com/search?q=spartiti+Al+Trist+Francesco+Guccini" title="Spartiti di Al Trist">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Al+Trist+Francesco+Guccini" title="Accordi di Al Trist">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Al+Trist+Francesco+Guccini" title="Testi di Al Trist">testi</a><br>
<b>12</b>. La Verità - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Verit%E0+Francesco+Guccini" title="Spartiti di La Verità">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Verit%E0+Francesco+Guccini" title="Accordi di La Verità">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Verit%E0+Francesco+Guccini" title="Testi di La Verità">testi</a><br>
<h2>Folk Beat N. 1 (1967) </h2>
<b>1</b>. Noi Non Ci Saremo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Noi+Non+Ci+Saremo+Francesco+Guccini" title="Spartiti di Noi Non Ci Saremo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Noi+Non+Ci+Saremo+Francesco+Guccini" title="Accordi di Noi Non Ci Saremo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Noi+Non+Ci+Saremo+Francesco+Guccini" title="Testi di Noi Non Ci Saremo">testi</a><br>
<b>2</b>. In Morte Di S.F. - <a target="_blank" href="http://www.google.com/search?q=spartiti+In+Morte+Di+S.F.+Francesco+Guccini" title="Spartiti di In Morte Di S.F.">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+In+Morte+Di+S.F.+Francesco+Guccini" title="Accordi di In Morte Di S.F.">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+In+Morte+Di+S.F.+Francesco+Guccini" title="Testi di In Morte Di S.F.">testi</a><br>
<b>3</b>. Venerdì Santo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Venerd%EC+Santo+Francesco+Guccini" title="Spartiti di Venerdì Santo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Venerd%EC+Santo+Francesco+Guccini" title="Accordi di Venerdì Santo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Venerd%EC+Santo+Francesco+Guccini" title="Testi di Venerdì Santo">testi</a><br>
<b>4</b>. L'Atomica Cinese - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%27Atomica+Cinese+Francesco+Guccini" title="Spartiti di L'Atomica Cinese">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%27Atomica+Cinese+Francesco+Guccini" title="Accordi di L'Atomica Cinese">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%27Atomica+Cinese+Francesco+Guccini" title="Testi di L'Atomica Cinese">testi</a><br>
<b>5</b>. La Canzone Del Bambino Nel Vento (Auschwitz) - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Canzone+Del+Bambino+Nel+Vento+%28Auschwitz%29+Francesco+Guccini" title="Spartiti di La Canzone Del Bambino Nel Vento (Auschwitz)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Canzone+Del+Bambino+Nel+Vento+%28Auschwitz%29+Francesco+Guccini" title="Accordi di La Canzone Del Bambino Nel Vento (Auschwitz)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Canzone+Del+Bambino+Nel+Vento+%28Auschwitz%29+Francesco+Guccini" title="Testi di La Canzone Del Bambino Nel Vento (Auschwitz)">testi</a><br>
<b>6</b>. Talkin' Milano - <a target="_blank" href="http://www.google.com/search?q=spartiti+Talkin%27+Milano+Francesco+Guccini" title="Spartiti di Talkin' Milano">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Talkin%27+Milano+Francesco+Guccini" title="Accordi di Talkin' Milano">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Talkin%27+Milano+Francesco+Guccini" title="Testi di Talkin' Milano">testi</a><br>
<b>7</b>. Statale 17 - <a target="_blank" href="http://www.google.com/search?q=spartiti+Statale+17+Francesco+Guccini" title="Spartiti di Statale 17">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Statale+17+Francesco+Guccini" title="Accordi di Statale 17">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Statale+17+Francesco+Guccini" title="Testi di Statale 17">testi</a><br>
<b>8</b>. Il 3 Dicembre Del '39 - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+3+Dicembre+Del+%2739+Francesco+Guccini" title="Spartiti di Il 3 Dicembre Del '39">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+3+Dicembre+Del+%2739+Francesco+Guccini" title="Accordi di Il 3 Dicembre Del '39">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+3+Dicembre+Del+%2739+Francesco+Guccini" title="Testi di Il 3 Dicembre Del '39">testi</a><br>
<b>9</b>. La Ballata Degli Annegati - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Ballata+Degli+Annegati+Francesco+Guccini" title="Spartiti di La Ballata Degli Annegati">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Ballata+Degli+Annegati+Francesco+Guccini" title="Accordi di La Ballata Degli Annegati">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Ballata+Degli+Annegati+Francesco+Guccini" title="Testi di La Ballata Degli Annegati">testi</a><br>
<b>10</b>. Il Sociale E L'Antisociale - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Sociale+E+L%27Antisociale+Francesco+Guccini" title="Spartiti di Il Sociale E L'Antisociale">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Sociale+E+L%27Antisociale+Francesco+Guccini" title="Accordi di Il Sociale E L'Antisociale">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Sociale+E+L%27Antisociale+Francesco+Guccini" title="Testi di Il Sociale E L'Antisociale">testi</a><br>
<h2><a href="http://<?php echo "$base_website_address/$spartiti_dir" ?>/index.html" title="Trova accordi, spartiti, tablature e testi di tantissimi artisti">Torna all'indice degli artisti</a></h2>
