<!--
title: Trova spartiti per chitarra, accordi, testi e tablature di Nirvana. Discografia Nirvana.
description: Trova tutti gli spartiti, accordi, testi e tablature di Nirvana. Discografia Nirvana.
keywords: Discografia, Nirvana, spartiti, accordi, testi, tablature
template: tablature
-->
<h1>Trova spartiti per chitarra, accordi, testi e tablature di Nirvana</h1><h2>Leggere gli spartiti per chitarra, gli accordi e le tablature:</h2>
<?php require("tabdescription.php"); ?>

<h2>Discografia Nirvana:</h2>
<h2>With The Lights Out - Cd 3 (2004) </h2>
<b>1</b>. Rape Me (Solo Acoustic) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Rape+Me+%28Solo+Acoustic%29+Nirvana" title="Spartiti di Rape Me (Solo Acoustic)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Rape+Me+%28Solo+Acoustic%29+Nirvana" title="Accordi di Rape Me (Solo Acoustic)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Rape+Me+%28Solo+Acoustic%29+Nirvana" title="Testi di Rape Me (Solo Acoustic)">testi</a><br>
<b>2</b>. Rape Me (Electric) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Rape+Me+%28Electric%29+Nirvana" title="Spartiti di Rape Me (Electric)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Rape+Me+%28Electric%29+Nirvana" title="Accordi di Rape Me (Electric)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Rape+Me+%28Electric%29+Nirvana" title="Testi di Rape Me (Electric)">testi</a><br>
<b>3</b>. Scentless Apprentice - <a target="_blank" href="http://www.google.com/search?q=spartiti+Scentless+Apprentice+Nirvana" title="Spartiti di Scentless Apprentice">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Scentless+Apprentice+Nirvana" title="Accordi di Scentless Apprentice">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Scentless+Apprentice+Nirvana" title="Testi di Scentless Apprentice">testi</a><br>
<b>4</b>. Heart-Shaped Box - <a target="_blank" href="http://www.google.com/search?q=spartiti+Heart-Shaped+Box+Nirvana" title="Spartiti di Heart-Shaped Box">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Heart-Shaped+Box+Nirvana" title="Accordi di Heart-Shaped Box">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Heart-Shaped+Box+Nirvana" title="Testi di Heart-Shaped Box">testi</a><br>
<b>5</b>. I Hate Myself And Want To Die - <a target="_blank" href="http://www.google.com/search?q=spartiti+I+Hate+Myself+And+Want+To+Die+Nirvana" title="Spartiti di I Hate Myself And Want To Die">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+I+Hate+Myself+And+Want+To+Die+Nirvana" title="Accordi di I Hate Myself And Want To Die">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+I+Hate+Myself+And+Want+To+Die+Nirvana" title="Testi di I Hate Myself And Want To Die">testi</a><br>
<b>6</b>. Milk It - <a target="_blank" href="http://www.google.com/search?q=spartiti+Milk+It+Nirvana" title="Spartiti di Milk It">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Milk+It+Nirvana" title="Accordi di Milk It">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Milk+It+Nirvana" title="Testi di Milk It">testi</a><br>
<b>7</b>. Moist Vagina - <a target="_blank" href="http://www.google.com/search?q=spartiti+Moist+Vagina+Nirvana" title="Spartiti di Moist Vagina">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Moist+Vagina+Nirvana" title="Accordi di Moist Vagina">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Moist+Vagina+Nirvana" title="Testi di Moist Vagina">testi</a><br>
<b>8</b>. Gallons Of Rubbing Alcohol Flow Through The Strip - <a target="_blank" href="http://www.google.com/search?q=spartiti+Gallons+Of+Rubbing+Alcohol+Flow+Through+The+Strip+Nirvana" title="Spartiti di Gallons Of Rubbing Alcohol Flow Through The Strip">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Gallons+Of+Rubbing+Alcohol+Flow+Through+The+Strip+Nirvana" title="Accordi di Gallons Of Rubbing Alcohol Flow Through The Strip">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Gallons+Of+Rubbing+Alcohol+Flow+Through+The+Strip+Nirvana" title="Testi di Gallons Of Rubbing Alcohol Flow Through The Strip">testi</a><br>
<b>9</b>. The Other Improv - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+Other+Improv+Nirvana" title="Spartiti di The Other Improv">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+Other+Improv+Nirvana" title="Accordi di The Other Improv">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+Other+Improv+Nirvana" title="Testi di The Other Improv">testi</a><br>
<b>10</b>. Serve The Servants - <a target="_blank" href="http://www.google.com/search?q=spartiti+Serve+The+Servants+Nirvana" title="Spartiti di Serve The Servants">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Serve+The+Servants+Nirvana" title="Accordi di Serve The Servants">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Serve+The+Servants+Nirvana" title="Testi di Serve The Servants">testi</a><br>
<b>11</b>. Very Ape - <a target="_blank" href="http://www.google.com/search?q=spartiti+Very+Ape+Nirvana" title="Spartiti di Very Ape">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Very+Ape+Nirvana" title="Accordi di Very Ape">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Very+Ape+Nirvana" title="Testi di Very Ape">testi</a><br>
<b>12</b>. Pennyroyal Tea - <a target="_blank" href="http://www.google.com/search?q=spartiti+Pennyroyal+Tea+Nirvana" title="Spartiti di Pennyroyal Tea">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Pennyroyal+Tea+Nirvana" title="Accordi di Pennyroyal Tea">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Pennyroyal+Tea+Nirvana" title="Testi di Pennyroyal Tea">testi</a><br>
<b>13</b>. Marigold - <a target="_blank" href="http://www.google.com/search?q=spartiti+Marigold+Nirvana" title="Spartiti di Marigold">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Marigold+Nirvana" title="Accordi di Marigold">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Marigold+Nirvana" title="Testi di Marigold">testi</a><br>
<b>14</b>. Sappy - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sappy+Nirvana" title="Spartiti di Sappy">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sappy+Nirvana" title="Accordi di Sappy">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sappy+Nirvana" title="Testi di Sappy">testi</a><br>
<b>15</b>. Jesus Doesn't Want Me For A Sunbeam - <a target="_blank" href="http://www.google.com/search?q=spartiti+Jesus+Doesn%27t+Want+Me+For+A+Sunbeam+Nirvana" title="Spartiti di Jesus Doesn't Want Me For A Sunbeam">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Jesus+Doesn%27t+Want+Me+For+A+Sunbeam+Nirvana" title="Accordi di Jesus Doesn't Want Me For A Sunbeam">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Jesus+Doesn%27t+Want+Me+For+A+Sunbeam+Nirvana" title="Testi di Jesus Doesn't Want Me For A Sunbeam">testi</a><br>
<b>16</b>. Do Re Mi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Do+Re+Mi+Nirvana" title="Spartiti di Do Re Mi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Do+Re+Mi+Nirvana" title="Accordi di Do Re Mi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Do+Re+Mi+Nirvana" title="Testi di Do Re Mi">testi</a><br>
<b>17</b>. You Know You're Right - <a target="_blank" href="http://www.google.com/search?q=spartiti+You+Know+You%27re+Right+Nirvana" title="Spartiti di You Know You're Right">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+You+Know+You%27re+Right+Nirvana" title="Accordi di You Know You're Right">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+You+Know+You%27re+Right+Nirvana" title="Testi di You Know You're Right">testi</a><br>
<b>18</b>. All Apologies - <a target="_blank" href="http://www.google.com/search?q=spartiti+All+Apologies+Nirvana" title="Spartiti di All Apologies">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+All+Apologies+Nirvana" title="Accordi di All Apologies">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+All+Apologies+Nirvana" title="Testi di All Apologies">testi</a><br>
<h2>With The Lights Out - Cd 2 (2004) </h2>
<b>1</b>. Opinion - <a target="_blank" href="http://www.google.com/search?q=spartiti+Opinion+Nirvana" title="Spartiti di Opinion">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Opinion+Nirvana" title="Accordi di Opinion">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Opinion+Nirvana" title="Testi di Opinion">testi</a><br>
<b>2</b>. Lithium - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lithium+Nirvana" title="Spartiti di Lithium">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lithium+Nirvana" title="Accordi di Lithium">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lithium+Nirvana" title="Testi di Lithium">testi</a><br>
<b>3</b>. Been A Son - <a target="_blank" href="http://www.google.com/search?q=spartiti+Been+A+Son+Nirvana" title="Spartiti di Been A Son">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Been+A+Son+Nirvana" title="Accordi di Been A Son">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Been+A+Son+Nirvana" title="Testi di Been A Son">testi</a><br>
<b>4</b>. Sliver - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sliver+Nirvana" title="Spartiti di Sliver">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sliver+Nirvana" title="Accordi di Sliver">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sliver+Nirvana" title="Testi di Sliver">testi</a><br>
<b>5</b>. Where Did You Sleep Last Night? - <a target="_blank" href="http://www.google.com/search?q=spartiti+Where+Did+You+Sleep+Last+Night%3F+Nirvana" title="Spartiti di Where Did You Sleep Last Night?">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Where+Did+You+Sleep+Last+Night%3F+Nirvana" title="Accordi di Where Did You Sleep Last Night?">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Where+Did+You+Sleep+Last+Night%3F+Nirvana" title="Testi di Where Did You Sleep Last Night?">testi</a><br>
<b>6</b>. Pay To Play - <a target="_blank" href="http://www.google.com/search?q=spartiti+Pay+To+Play+Nirvana" title="Spartiti di Pay To Play">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Pay+To+Play+Nirvana" title="Accordi di Pay To Play">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Pay+To+Play+Nirvana" title="Testi di Pay To Play">testi</a><br>
<b>7</b>. Here She Comes Now - <a target="_blank" href="http://www.google.com/search?q=spartiti+Here+She+Comes+Now+Nirvana" title="Spartiti di Here She Comes Now">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Here+She+Comes+Now+Nirvana" title="Accordi di Here She Comes Now">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Here+She+Comes+Now+Nirvana" title="Testi di Here She Comes Now">testi</a><br>
<b>8</b>. Drain You - <a target="_blank" href="http://www.google.com/search?q=spartiti+Drain+You+Nirvana" title="Spartiti di Drain You">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Drain+You+Nirvana" title="Accordi di Drain You">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Drain+You+Nirvana" title="Testi di Drain You">testi</a><br>
<b>9</b>. Aneurysm - <a target="_blank" href="http://www.google.com/search?q=spartiti+Aneurysm+Nirvana" title="Spartiti di Aneurysm">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Aneurysm+Nirvana" title="Accordi di Aneurysm">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Aneurysm+Nirvana" title="Testi di Aneurysm">testi</a><br>
<b>10</b>. Smells Like Teen Spirit - <a target="_blank" href="http://www.google.com/search?q=spartiti+Smells+Like+Teen+Spirit+Nirvana" title="Spartiti di Smells Like Teen Spirit">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Smells+Like+Teen+Spirit+Nirvana" title="Accordi di Smells Like Teen Spirit">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Smells+Like+Teen+Spirit+Nirvana" title="Testi di Smells Like Teen Spirit">testi</a><br>
<b>11</b>. Breed - <a target="_blank" href="http://www.google.com/search?q=spartiti+Breed+Nirvana" title="Spartiti di Breed">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Breed+Nirvana" title="Accordi di Breed">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Breed+Nirvana" title="Testi di Breed">testi</a><br>
<b>12</b>. Verse Chorus Verse - <a target="_blank" href="http://www.google.com/search?q=spartiti+Verse+Chorus+Verse+Nirvana" title="Spartiti di Verse Chorus Verse">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Verse+Chorus+Verse+Nirvana" title="Accordi di Verse Chorus Verse">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Verse+Chorus+Verse+Nirvana" title="Testi di Verse Chorus Verse">testi</a><br>
<b>13</b>. Old Age - <a target="_blank" href="http://www.google.com/search?q=spartiti+Old+Age+Nirvana" title="Spartiti di Old Age">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Old+Age+Nirvana" title="Accordi di Old Age">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Old+Age+Nirvana" title="Testi di Old Age">testi</a><br>
<b>14</b>. Endless, Nameless - <a target="_blank" href="http://www.google.com/search?q=spartiti+Endless%2C+Nameless+Nirvana" title="Spartiti di Endless, Nameless">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Endless%2C+Nameless+Nirvana" title="Accordi di Endless, Nameless">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Endless%2C+Nameless+Nirvana" title="Testi di Endless, Nameless">testi</a><br>
<b>15</b>. Dumb - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dumb+Nirvana" title="Spartiti di Dumb">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dumb+Nirvana" title="Accordi di Dumb">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dumb+Nirvana" title="Testi di Dumb">testi</a><br>
<b>16</b>. D-7 - <a target="_blank" href="http://www.google.com/search?q=spartiti+D-7+Nirvana" title="Spartiti di D-7">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+D-7+Nirvana" title="Accordi di D-7">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+D-7+Nirvana" title="Testi di D-7">testi</a><br>
<b>17</b>. Oh, The Guilt - <a target="_blank" href="http://www.google.com/search?q=spartiti+Oh%2C+The+Guilt+Nirvana" title="Spartiti di Oh, The Guilt">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Oh%2C+The+Guilt+Nirvana" title="Accordi di Oh, The Guilt">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Oh%2C+The+Guilt+Nirvana" title="Testi di Oh, The Guilt">testi</a><br>
<b>18</b>. Curmudgeon - <a target="_blank" href="http://www.google.com/search?q=spartiti+Curmudgeon+Nirvana" title="Spartiti di Curmudgeon">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Curmudgeon+Nirvana" title="Accordi di Curmudgeon">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Curmudgeon+Nirvana" title="Testi di Curmudgeon">testi</a><br>
<b>19</b>. Return Of The Rat - <a target="_blank" href="http://www.google.com/search?q=spartiti+Return+Of+The+Rat+Nirvana" title="Spartiti di Return Of The Rat">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Return+Of+The+Rat+Nirvana" title="Accordi di Return Of The Rat">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Return+Of+The+Rat+Nirvana" title="Testi di Return Of The Rat">testi</a><br>
<b>20</b>. Smells Like Teen Spirit (Butch Vig Mix) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Smells+Like+Teen+Spirit+%28Butch+Vig+Mix%29+Nirvana" title="Spartiti di Smells Like Teen Spirit (Butch Vig Mix)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Smells+Like+Teen+Spirit+%28Butch+Vig+Mix%29+Nirvana" title="Accordi di Smells Like Teen Spirit (Butch Vig Mix)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Smells+Like+Teen+Spirit+%28Butch+Vig+Mix%29+Nirvana" title="Testi di Smells Like Teen Spirit (Butch Vig Mix)">testi</a><br>
<h2>With The Lights Out - Cd 1 (2004) </h2>
<b>1</b>. Heartbreaker - <a target="_blank" href="http://www.google.com/search?q=spartiti+Heartbreaker+Nirvana" title="Spartiti di Heartbreaker">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Heartbreaker+Nirvana" title="Accordi di Heartbreaker">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Heartbreaker+Nirvana" title="Testi di Heartbreaker">testi</a><br>
<b>2</b>. Anorexorcist - <a target="_blank" href="http://www.google.com/search?q=spartiti+Anorexorcist+Nirvana" title="Spartiti di Anorexorcist">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Anorexorcist+Nirvana" title="Accordi di Anorexorcist">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Anorexorcist+Nirvana" title="Testi di Anorexorcist">testi</a><br>
<b>3</b>. With Lace And Strange - <a target="_blank" href="http://www.google.com/search?q=spartiti+With+Lace+And+Strange+Nirvana" title="Spartiti di With Lace And Strange">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+With+Lace+And+Strange+Nirvana" title="Accordi di With Lace And Strange">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+With+Lace+And+Strange+Nirvana" title="Testi di With Lace And Strange">testi</a><br>
<b>4</b>. Help Me, I'm Hungry - <a target="_blank" href="http://www.google.com/search?q=spartiti+Help+Me%2C+I%27m+Hungry+Nirvana" title="Spartiti di Help Me, I'm Hungry">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Help+Me%2C+I%27m+Hungry+Nirvana" title="Accordi di Help Me, I'm Hungry">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Help+Me%2C+I%27m+Hungry+Nirvana" title="Testi di Help Me, I'm Hungry">testi</a><br>
<b>5</b>. Mrs. Butterworth - <a target="_blank" href="http://www.google.com/search?q=spartiti+Mrs.+Butterworth+Nirvana" title="Spartiti di Mrs. Butterworth">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Mrs.+Butterworth+Nirvana" title="Accordi di Mrs. Butterworth">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Mrs.+Butterworth+Nirvana" title="Testi di Mrs. Butterworth">testi</a><br>
<b>6</b>. If You Must - <a target="_blank" href="http://www.google.com/search?q=spartiti+If+You+Must+Nirvana" title="Spartiti di If You Must">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+If+You+Must+Nirvana" title="Accordi di If You Must">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+If+You+Must+Nirvana" title="Testi di If You Must">testi</a><br>
<b>7</b>. Pen Cap Chew - <a target="_blank" href="http://www.google.com/search?q=spartiti+Pen+Cap+Chew+Nirvana" title="Spartiti di Pen Cap Chew">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Pen+Cap+Chew+Nirvana" title="Accordi di Pen Cap Chew">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Pen+Cap+Chew+Nirvana" title="Testi di Pen Cap Chew">testi</a><br>
<b>8</b>. Downer - <a target="_blank" href="http://www.google.com/search?q=spartiti+Downer+Nirvana" title="Spartiti di Downer">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Downer+Nirvana" title="Accordi di Downer">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Downer+Nirvana" title="Testi di Downer">testi</a><br>
<b>9</b>. Floyd The Barber - <a target="_blank" href="http://www.google.com/search?q=spartiti+Floyd+The+Barber+Nirvana" title="Spartiti di Floyd The Barber">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Floyd+The+Barber+Nirvana" title="Accordi di Floyd The Barber">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Floyd+The+Barber+Nirvana" title="Testi di Floyd The Barber">testi</a><br>
<b>10</b>. Raunchola / Moby Dick - <a target="_blank" href="http://www.google.com/search?q=spartiti+Raunchola+%2F+Moby+Dick+Nirvana" title="Spartiti di Raunchola / Moby Dick">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Raunchola+%2F+Moby+Dick+Nirvana" title="Accordi di Raunchola / Moby Dick">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Raunchola+%2F+Moby+Dick+Nirvana" title="Testi di Raunchola / Moby Dick">testi</a><br>
<b>11</b>. Beans - <a target="_blank" href="http://www.google.com/search?q=spartiti+Beans+Nirvana" title="Spartiti di Beans">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Beans+Nirvana" title="Accordi di Beans">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Beans+Nirvana" title="Testi di Beans">testi</a><br>
<b>12</b>. Don't Want It All - <a target="_blank" href="http://www.google.com/search?q=spartiti+Don%27t+Want+It+All+Nirvana" title="Spartiti di Don't Want It All">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Don%27t+Want+It+All+Nirvana" title="Accordi di Don't Want It All">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Don%27t+Want+It+All+Nirvana" title="Testi di Don't Want It All">testi</a><br>
<b>13</b>. Clean Up Before She Comes - <a target="_blank" href="http://www.google.com/search?q=spartiti+Clean+Up+Before+She+Comes+Nirvana" title="Spartiti di Clean Up Before She Comes">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Clean+Up+Before+She+Comes+Nirvana" title="Accordi di Clean Up Before She Comes">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Clean+Up+Before+She+Comes+Nirvana" title="Testi di Clean Up Before She Comes">testi</a><br>
<b>14</b>. Polly (Solo) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Polly+%28Solo%29+Nirvana" title="Spartiti di Polly (Solo)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Polly+%28Solo%29+Nirvana" title="Accordi di Polly (Solo)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Polly+%28Solo%29+Nirvana" title="Testi di Polly (Solo)">testi</a><br>
<b>15</b>. About A Girl - <a target="_blank" href="http://www.google.com/search?q=spartiti+About+A+Girl+Nirvana" title="Spartiti di About A Girl">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+About+A+Girl+Nirvana" title="Accordi di About A Girl">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+About+A+Girl+Nirvana" title="Testi di About A Girl">testi</a><br>
<b>16</b>. Blandest - <a target="_blank" href="http://www.google.com/search?q=spartiti+Blandest+Nirvana" title="Spartiti di Blandest">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Blandest+Nirvana" title="Accordi di Blandest">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Blandest+Nirvana" title="Testi di Blandest">testi</a><br>
<b>17</b>. Dive - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dive+Nirvana" title="Spartiti di Dive">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dive+Nirvana" title="Accordi di Dive">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dive+Nirvana" title="Testi di Dive">testi</a><br>
<b>18</b>. They Hung Him On A Cross - <a target="_blank" href="http://www.google.com/search?q=spartiti+They+Hung+Him+On+A+Cross+Nirvana" title="Spartiti di They Hung Him On A Cross">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+They+Hung+Him+On+A+Cross+Nirvana" title="Accordi di They Hung Him On A Cross">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+They+Hung+Him+On+A+Cross+Nirvana" title="Testi di They Hung Him On A Cross">testi</a><br>
<b>19</b>. Grey Goose - <a target="_blank" href="http://www.google.com/search?q=spartiti+Grey+Goose+Nirvana" title="Spartiti di Grey Goose">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Grey+Goose+Nirvana" title="Accordi di Grey Goose">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Grey+Goose+Nirvana" title="Testi di Grey Goose">testi</a><br>
<b>20</b>. Ain't It A Shame - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ain%27t+It+A+Shame+Nirvana" title="Spartiti di Ain't It A Shame">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ain%27t+It+A+Shame+Nirvana" title="Accordi di Ain't It A Shame">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ain%27t+It+A+Shame+Nirvana" title="Testi di Ain't It A Shame">testi</a><br>
<b>21</b>. Token Eastern Song - <a target="_blank" href="http://www.google.com/search?q=spartiti+Token+Eastern+Song+Nirvana" title="Spartiti di Token Eastern Song">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Token+Eastern+Song+Nirvana" title="Accordi di Token Eastern Song">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Token+Eastern+Song+Nirvana" title="Testi di Token Eastern Song">testi</a><br>
<b>22</b>. Even In His Youth - <a target="_blank" href="http://www.google.com/search?q=spartiti+Even+In+His+Youth+Nirvana" title="Spartiti di Even In His Youth">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Even+In+His+Youth+Nirvana" title="Accordi di Even In His Youth">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Even+In+His+Youth+Nirvana" title="Testi di Even In His Youth">testi</a><br>
<b>23</b>. Polly - <a target="_blank" href="http://www.google.com/search?q=spartiti+Polly+Nirvana" title="Spartiti di Polly">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Polly+Nirvana" title="Accordi di Polly">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Polly+Nirvana" title="Testi di Polly">testi</a><br>
<h2>Nirvana (2002) </h2>
<b>1</b>. You Know You're Right - <a target="_blank" href="http://www.google.com/search?q=spartiti+You+Know+You%27re+Right+Nirvana" title="Spartiti di You Know You're Right">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+You+Know+You%27re+Right+Nirvana" title="Accordi di You Know You're Right">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+You+Know+You%27re+Right+Nirvana" title="Testi di You Know You're Right">testi</a><br>
<b>2</b>. About A Girl - <a target="_blank" href="http://www.google.com/search?q=spartiti+About+A+Girl+Nirvana" title="Spartiti di About A Girl">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+About+A+Girl+Nirvana" title="Accordi di About A Girl">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+About+A+Girl+Nirvana" title="Testi di About A Girl">testi</a><br>
<b>3</b>. Been A Son - <a target="_blank" href="http://www.google.com/search?q=spartiti+Been+A+Son+Nirvana" title="Spartiti di Been A Son">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Been+A+Son+Nirvana" title="Accordi di Been A Son">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Been+A+Son+Nirvana" title="Testi di Been A Son">testi</a><br>
<b>4</b>. Sliver - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sliver+Nirvana" title="Spartiti di Sliver">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sliver+Nirvana" title="Accordi di Sliver">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sliver+Nirvana" title="Testi di Sliver">testi</a><br>
<b>5</b>. Smells Like Teen Spirit - <a target="_blank" href="http://www.google.com/search?q=spartiti+Smells+Like+Teen+Spirit+Nirvana" title="Spartiti di Smells Like Teen Spirit">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Smells+Like+Teen+Spirit+Nirvana" title="Accordi di Smells Like Teen Spirit">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Smells+Like+Teen+Spirit+Nirvana" title="Testi di Smells Like Teen Spirit">testi</a><br>
<b>6</b>. Smells Like Teen Spirit - <a target="_blank" href="http://www.google.com/search?q=spartiti+Smells+Like+Teen+Spirit+Nirvana" title="Spartiti di Smells Like Teen Spirit">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Smells+Like+Teen+Spirit+Nirvana" title="Accordi di Smells Like Teen Spirit">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Smells+Like+Teen+Spirit+Nirvana" title="Testi di Smells Like Teen Spirit">testi</a><br>
<b>7</b>. Come As You Are - <a target="_blank" href="http://www.google.com/search?q=spartiti+Come+As+You+Are+Nirvana" title="Spartiti di Come As You Are">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Come+As+You+Are+Nirvana" title="Accordi di Come As You Are">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Come+As+You+Are+Nirvana" title="Testi di Come As You Are">testi</a><br>
<b>8</b>. Lithium - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lithium+Nirvana" title="Spartiti di Lithium">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lithium+Nirvana" title="Accordi di Lithium">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lithium+Nirvana" title="Testi di Lithium">testi</a><br>
<b>9</b>. In Bloom - <a target="_blank" href="http://www.google.com/search?q=spartiti+In+Bloom+Nirvana" title="Spartiti di In Bloom">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+In+Bloom+Nirvana" title="Accordi di In Bloom">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+In+Bloom+Nirvana" title="Testi di In Bloom">testi</a><br>
<b>10</b>. Heart - Shaped Box - <a target="_blank" href="http://www.google.com/search?q=spartiti+Heart+-+Shaped+Box+Nirvana" title="Spartiti di Heart - Shaped Box">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Heart+-+Shaped+Box+Nirvana" title="Accordi di Heart - Shaped Box">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Heart+-+Shaped+Box+Nirvana" title="Testi di Heart - Shaped Box">testi</a><br>
<b>11</b>. Pennyroyal Tea - <a target="_blank" href="http://www.google.com/search?q=spartiti+Pennyroyal+Tea+Nirvana" title="Spartiti di Pennyroyal Tea">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Pennyroyal+Tea+Nirvana" title="Accordi di Pennyroyal Tea">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Pennyroyal+Tea+Nirvana" title="Testi di Pennyroyal Tea">testi</a><br>
<b>12</b>. Rape Me - <a target="_blank" href="http://www.google.com/search?q=spartiti+Rape+Me+Nirvana" title="Spartiti di Rape Me">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Rape+Me+Nirvana" title="Accordi di Rape Me">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Rape+Me+Nirvana" title="Testi di Rape Me">testi</a><br>
<b>13</b>. Dumb - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dumb+Nirvana" title="Spartiti di Dumb">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dumb+Nirvana" title="Accordi di Dumb">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dumb+Nirvana" title="Testi di Dumb">testi</a><br>
<b>14</b>. All Apologies - <a target="_blank" href="http://www.google.com/search?q=spartiti+All+Apologies+Nirvana" title="Spartiti di All Apologies">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+All+Apologies+Nirvana" title="Accordi di All Apologies">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+All+Apologies+Nirvana" title="Testi di All Apologies">testi</a><br>
<b>15</b>. The Man Who Sold The World - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+Man+Who+Sold+The+World+Nirvana" title="Spartiti di The Man Who Sold The World">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+Man+Who+Sold+The+World+Nirvana" title="Accordi di The Man Who Sold The World">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+Man+Who+Sold+The+World+Nirvana" title="Testi di The Man Who Sold The World">testi</a><br>
<h2>From The Muddy Banks Of Wishkah (1996) </h2>
<b>1</b>. Aneurysm - <a target="_blank" href="http://www.google.com/search?q=spartiti+Aneurysm+Nirvana" title="Spartiti di Aneurysm">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Aneurysm+Nirvana" title="Accordi di Aneurysm">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Aneurysm+Nirvana" title="Testi di Aneurysm">testi</a><br>
<b>2</b>. Been A Son - <a target="_blank" href="http://www.google.com/search?q=spartiti+Been+A+Son+Nirvana" title="Spartiti di Been A Son">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Been+A+Son+Nirvana" title="Accordi di Been A Son">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Been+A+Son+Nirvana" title="Testi di Been A Son">testi</a><br>
<b>3</b>. Blew - <a target="_blank" href="http://www.google.com/search?q=spartiti+Blew+Nirvana" title="Spartiti di Blew">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Blew+Nirvana" title="Accordi di Blew">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Blew+Nirvana" title="Testi di Blew">testi</a><br>
<b>4</b>. Breed - <a target="_blank" href="http://www.google.com/search?q=spartiti+Breed+Nirvana" title="Spartiti di Breed">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Breed+Nirvana" title="Accordi di Breed">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Breed+Nirvana" title="Testi di Breed">testi</a><br>
<b>5</b>. Drain You - <a target="_blank" href="http://www.google.com/search?q=spartiti+Drain+You+Nirvana" title="Spartiti di Drain You">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Drain+You+Nirvana" title="Accordi di Drain You">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Drain+You+Nirvana" title="Testi di Drain You">testi</a><br>
<b>6</b>. Heart-Shaped Box - <a target="_blank" href="http://www.google.com/search?q=spartiti+Heart-Shaped+Box+Nirvana" title="Spartiti di Heart-Shaped Box">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Heart-Shaped+Box+Nirvana" title="Accordi di Heart-Shaped Box">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Heart-Shaped+Box+Nirvana" title="Testi di Heart-Shaped Box">testi</a><br>
<b>7</b>. Lithium - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lithium+Nirvana" title="Spartiti di Lithium">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lithium+Nirvana" title="Accordi di Lithium">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lithium+Nirvana" title="Testi di Lithium">testi</a><br>
<b>8</b>. Milk It - <a target="_blank" href="http://www.google.com/search?q=spartiti+Milk+It+Nirvana" title="Spartiti di Milk It">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Milk+It+Nirvana" title="Accordi di Milk It">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Milk+It+Nirvana" title="Testi di Milk It">testi</a><br>
<b>9</b>. Negative Creep - <a target="_blank" href="http://www.google.com/search?q=spartiti+Negative+Creep+Nirvana" title="Spartiti di Negative Creep">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Negative+Creep+Nirvana" title="Accordi di Negative Creep">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Negative+Creep+Nirvana" title="Testi di Negative Creep">testi</a><br>
<b>10</b>. Polly - <a target="_blank" href="http://www.google.com/search?q=spartiti+Polly+Nirvana" title="Spartiti di Polly">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Polly+Nirvana" title="Accordi di Polly">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Polly+Nirvana" title="Testi di Polly">testi</a><br>
<b>11</b>. Scentless Apprentice - <a target="_blank" href="http://www.google.com/search?q=spartiti+Scentless+Apprentice+Nirvana" title="Spartiti di Scentless Apprentice">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Scentless+Apprentice+Nirvana" title="Accordi di Scentless Apprentice">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Scentless+Apprentice+Nirvana" title="Testi di Scentless Apprentice">testi</a><br>
<b>12</b>. School - <a target="_blank" href="http://www.google.com/search?q=spartiti+School+Nirvana" title="Spartiti di School">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+School+Nirvana" title="Accordi di School">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+School+Nirvana" title="Testi di School">testi</a><br>
<b>13</b>. Sliver - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sliver+Nirvana" title="Spartiti di Sliver">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sliver+Nirvana" title="Accordi di Sliver">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sliver+Nirvana" title="Testi di Sliver">testi</a><br>
<b>14</b>. Smells Like Teen Spirit - <a target="_blank" href="http://www.google.com/search?q=spartiti+Smells+Like+Teen+Spirit+Nirvana" title="Spartiti di Smells Like Teen Spirit">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Smells+Like+Teen+Spirit+Nirvana" title="Accordi di Smells Like Teen Spirit">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Smells+Like+Teen+Spirit+Nirvana" title="Testi di Smells Like Teen Spirit">testi</a><br>
<b>15</b>. Spank Thru - <a target="_blank" href="http://www.google.com/search?q=spartiti+Spank+Thru+Nirvana" title="Spartiti di Spank Thru">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Spank+Thru+Nirvana" title="Accordi di Spank Thru">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Spank+Thru+Nirvana" title="Testi di Spank Thru">testi</a><br>
<b>16</b>. Tourette's - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tourette%27s+Nirvana" title="Spartiti di Tourette's">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tourette%27s+Nirvana" title="Accordi di Tourette's">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tourette%27s+Nirvana" title="Testi di Tourette's">testi</a><br>
<h2>Unplugged In New York (1994) </h2>
<b>1</b>. About A Girl - <a target="_blank" href="http://www.google.com/search?q=spartiti+About+A+Girl+Nirvana" title="Spartiti di About A Girl">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+About+A+Girl+Nirvana" title="Accordi di About A Girl">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+About+A+Girl+Nirvana" title="Testi di About A Girl">testi</a><br>
<b>2</b>. Come As You Are - <a target="_blank" href="http://www.google.com/search?q=spartiti+Come+As+You+Are+Nirvana" title="Spartiti di Come As You Are">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Come+As+You+Are+Nirvana" title="Accordi di Come As You Are">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Come+As+You+Are+Nirvana" title="Testi di Come As You Are">testi</a><br>
<b>3</b>. Jesus Doesn't Want Me For A Sunbeam - <a target="_blank" href="http://www.google.com/search?q=spartiti+Jesus+Doesn%27t+Want+Me+For+A+Sunbeam+Nirvana" title="Spartiti di Jesus Doesn't Want Me For A Sunbeam">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Jesus+Doesn%27t+Want+Me+For+A+Sunbeam+Nirvana" title="Accordi di Jesus Doesn't Want Me For A Sunbeam">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Jesus+Doesn%27t+Want+Me+For+A+Sunbeam+Nirvana" title="Testi di Jesus Doesn't Want Me For A Sunbeam">testi</a><br>
<b>4</b>. The Man Who Sold The World - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+Man+Who+Sold+The+World+Nirvana" title="Spartiti di The Man Who Sold The World">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+Man+Who+Sold+The+World+Nirvana" title="Accordi di The Man Who Sold The World">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+Man+Who+Sold+The+World+Nirvana" title="Testi di The Man Who Sold The World">testi</a><br>
<b>5</b>. The Man Who Sold The World (David Bowie Version) - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+Man+Who+Sold+The+World+%28David+Bowie+Version%29+Nirvana" title="Spartiti di The Man Who Sold The World (David Bowie Version)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+Man+Who+Sold+The+World+%28David+Bowie+Version%29+Nirvana" title="Accordi di The Man Who Sold The World (David Bowie Version)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+Man+Who+Sold+The+World+%28David+Bowie+Version%29+Nirvana" title="Testi di The Man Who Sold The World (David Bowie Version)">testi</a><br>
<b>6</b>. Pennyroyal Tea - <a target="_blank" href="http://www.google.com/search?q=spartiti+Pennyroyal+Tea+Nirvana" title="Spartiti di Pennyroyal Tea">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Pennyroyal+Tea+Nirvana" title="Accordi di Pennyroyal Tea">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Pennyroyal+Tea+Nirvana" title="Testi di Pennyroyal Tea">testi</a><br>
<b>7</b>. Dumb - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dumb+Nirvana" title="Spartiti di Dumb">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dumb+Nirvana" title="Accordi di Dumb">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dumb+Nirvana" title="Testi di Dumb">testi</a><br>
<b>8</b>. Polly - <a target="_blank" href="http://www.google.com/search?q=spartiti+Polly+Nirvana" title="Spartiti di Polly">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Polly+Nirvana" title="Accordi di Polly">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Polly+Nirvana" title="Testi di Polly">testi</a><br>
<b>9</b>. On A Plain - <a target="_blank" href="http://www.google.com/search?q=spartiti+On+A+Plain+Nirvana" title="Spartiti di On A Plain">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+On+A+Plain+Nirvana" title="Accordi di On A Plain">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+On+A+Plain+Nirvana" title="Testi di On A Plain">testi</a><br>
<b>10</b>. Something In The Way - <a target="_blank" href="http://www.google.com/search?q=spartiti+Something+In+The+Way+Nirvana" title="Spartiti di Something In The Way">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Something+In+The+Way+Nirvana" title="Accordi di Something In The Way">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Something+In+The+Way+Nirvana" title="Testi di Something In The Way">testi</a><br>
<b>11</b>. Plateau - <a target="_blank" href="http://www.google.com/search?q=spartiti+Plateau+Nirvana" title="Spartiti di Plateau">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Plateau+Nirvana" title="Accordi di Plateau">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Plateau+Nirvana" title="Testi di Plateau">testi</a><br>
<b>12</b>. Oh, Me - <a target="_blank" href="http://www.google.com/search?q=spartiti+Oh%2C+Me+Nirvana" title="Spartiti di Oh, Me">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Oh%2C+Me+Nirvana" title="Accordi di Oh, Me">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Oh%2C+Me+Nirvana" title="Testi di Oh, Me">testi</a><br>
<b>13</b>. Lake Of Fire - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lake+Of+Fire+Nirvana" title="Spartiti di Lake Of Fire">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lake+Of+Fire+Nirvana" title="Accordi di Lake Of Fire">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lake+Of+Fire+Nirvana" title="Testi di Lake Of Fire">testi</a><br>
<b>14</b>. All Apologies - <a target="_blank" href="http://www.google.com/search?q=spartiti+All+Apologies+Nirvana" title="Spartiti di All Apologies">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+All+Apologies+Nirvana" title="Accordi di All Apologies">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+All+Apologies+Nirvana" title="Testi di All Apologies">testi</a><br>
<b>15</b>. Where Did You Sleep Last Night? - <a target="_blank" href="http://www.google.com/search?q=spartiti+Where+Did+You+Sleep+Last+Night%3F+Nirvana" title="Spartiti di Where Did You Sleep Last Night?">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Where+Did+You+Sleep+Last+Night%3F+Nirvana" title="Accordi di Where Did You Sleep Last Night?">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Where+Did+You+Sleep+Last+Night%3F+Nirvana" title="Testi di Where Did You Sleep Last Night?">testi</a><br>
<h2>In Utero (1993) </h2>
<b>1</b>. Serve the Servants - <a target="_blank" href="http://www.google.com/search?q=spartiti+Serve+the+Servants+Nirvana" title="Spartiti di Serve the Servants">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Serve+the+Servants+Nirvana" title="Accordi di Serve the Servants">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Serve+the+Servants+Nirvana" title="Testi di Serve the Servants">testi</a><br>
<b>2</b>. Scentless Apprentice - <a target="_blank" href="http://www.google.com/search?q=spartiti+Scentless+Apprentice+Nirvana" title="Spartiti di Scentless Apprentice">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Scentless+Apprentice+Nirvana" title="Accordi di Scentless Apprentice">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Scentless+Apprentice+Nirvana" title="Testi di Scentless Apprentice">testi</a><br>
<b>3</b>. Heart-Shaped Box - <a target="_blank" href="http://www.google.com/search?q=spartiti+Heart-Shaped+Box+Nirvana" title="Spartiti di Heart-Shaped Box">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Heart-Shaped+Box+Nirvana" title="Accordi di Heart-Shaped Box">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Heart-Shaped+Box+Nirvana" title="Testi di Heart-Shaped Box">testi</a><br>
<b>4</b>. Rape Me - <a target="_blank" href="http://www.google.com/search?q=spartiti+Rape+Me+Nirvana" title="Spartiti di Rape Me">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Rape+Me+Nirvana" title="Accordi di Rape Me">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Rape+Me+Nirvana" title="Testi di Rape Me">testi</a><br>
<b>5</b>. Frances Farmer Will Have Her Revenge On Seattle - <a target="_blank" href="http://www.google.com/search?q=spartiti+Frances+Farmer+Will+Have+Her+Revenge+On+Seattle+Nirvana" title="Spartiti di Frances Farmer Will Have Her Revenge On Seattle">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Frances+Farmer+Will+Have+Her+Revenge+On+Seattle+Nirvana" title="Accordi di Frances Farmer Will Have Her Revenge On Seattle">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Frances+Farmer+Will+Have+Her+Revenge+On+Seattle+Nirvana" title="Testi di Frances Farmer Will Have Her Revenge On Seattle">testi</a><br>
<b>6</b>. Dumb - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dumb+Nirvana" title="Spartiti di Dumb">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dumb+Nirvana" title="Accordi di Dumb">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dumb+Nirvana" title="Testi di Dumb">testi</a><br>
<b>7</b>. Very Ape - <a target="_blank" href="http://www.google.com/search?q=spartiti+Very+Ape+Nirvana" title="Spartiti di Very Ape">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Very+Ape+Nirvana" title="Accordi di Very Ape">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Very+Ape+Nirvana" title="Testi di Very Ape">testi</a><br>
<b>8</b>. Milk It - <a target="_blank" href="http://www.google.com/search?q=spartiti+Milk+It+Nirvana" title="Spartiti di Milk It">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Milk+It+Nirvana" title="Accordi di Milk It">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Milk+It+Nirvana" title="Testi di Milk It">testi</a><br>
<b>9</b>. Pennyroyal Tea - <a target="_blank" href="http://www.google.com/search?q=spartiti+Pennyroyal+Tea+Nirvana" title="Spartiti di Pennyroyal Tea">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Pennyroyal+Tea+Nirvana" title="Accordi di Pennyroyal Tea">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Pennyroyal+Tea+Nirvana" title="Testi di Pennyroyal Tea">testi</a><br>
<b>10</b>. Radio Friendly Unit Shifter - <a target="_blank" href="http://www.google.com/search?q=spartiti+Radio+Friendly+Unit+Shifter+Nirvana" title="Spartiti di Radio Friendly Unit Shifter">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Radio+Friendly+Unit+Shifter+Nirvana" title="Accordi di Radio Friendly Unit Shifter">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Radio+Friendly+Unit+Shifter+Nirvana" title="Testi di Radio Friendly Unit Shifter">testi</a><br>
<b>11</b>. Tourette's - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tourette%27s+Nirvana" title="Spartiti di Tourette's">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tourette%27s+Nirvana" title="Accordi di Tourette's">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tourette%27s+Nirvana" title="Testi di Tourette's">testi</a><br>
<b>12</b>. All Apologies - <a target="_blank" href="http://www.google.com/search?q=spartiti+All+Apologies+Nirvana" title="Spartiti di All Apologies">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+All+Apologies+Nirvana" title="Accordi di All Apologies">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+All+Apologies+Nirvana" title="Testi di All Apologies">testi</a><br>
<b>13</b>. Gallons Of Rubbing Alcohol Flow Through The Strip - <a target="_blank" href="http://www.google.com/search?q=spartiti+Gallons+Of+Rubbing+Alcohol+Flow+Through+The+Strip+Nirvana" title="Spartiti di Gallons Of Rubbing Alcohol Flow Through The Strip">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Gallons+Of+Rubbing+Alcohol+Flow+Through+The+Strip+Nirvana" title="Accordi di Gallons Of Rubbing Alcohol Flow Through The Strip">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Gallons+Of+Rubbing+Alcohol+Flow+Through+The+Strip+Nirvana" title="Testi di Gallons Of Rubbing Alcohol Flow Through The Strip">testi</a><br>
<h2>Hormoaning (1992) </h2>
<b>1</b>. Turnaround - <a target="_blank" href="http://www.google.com/search?q=spartiti+Turnaround+Nirvana" title="Spartiti di Turnaround">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Turnaround+Nirvana" title="Accordi di Turnaround">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Turnaround+Nirvana" title="Testi di Turnaround">testi</a><br>
<b>2</b>. Aneurysm - <a target="_blank" href="http://www.google.com/search?q=spartiti+Aneurysm+Nirvana" title="Spartiti di Aneurysm">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Aneurysm+Nirvana" title="Accordi di Aneurysm">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Aneurysm+Nirvana" title="Testi di Aneurysm">testi</a><br>
<b>3</b>. D-7 - <a target="_blank" href="http://www.google.com/search?q=spartiti+D-7+Nirvana" title="Spartiti di D-7">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+D-7+Nirvana" title="Accordi di D-7">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+D-7+Nirvana" title="Testi di D-7">testi</a><br>
<b>4</b>. Son Of A Gun - <a target="_blank" href="http://www.google.com/search?q=spartiti+Son+Of+A+Gun+Nirvana" title="Spartiti di Son Of A Gun">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Son+Of+A+Gun+Nirvana" title="Accordi di Son Of A Gun">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Son+Of+A+Gun+Nirvana" title="Testi di Son Of A Gun">testi</a><br>
<b>5</b>. Even In His Youth - <a target="_blank" href="http://www.google.com/search?q=spartiti+Even+In+His+Youth+Nirvana" title="Spartiti di Even In His Youth">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Even+In+His+Youth+Nirvana" title="Accordi di Even In His Youth">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Even+In+His+Youth+Nirvana" title="Testi di Even In His Youth">testi</a><br>
<b>6</b>. Molly's Lips - <a target="_blank" href="http://www.google.com/search?q=spartiti+Molly%27s+Lips+Nirvana" title="Spartiti di Molly's Lips">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Molly%27s+Lips+Nirvana" title="Accordi di Molly's Lips">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Molly%27s+Lips+Nirvana" title="Testi di Molly's Lips">testi</a><br>
<h2>Incesticide (1992) </h2>
<b>1</b>. Dive - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dive+Nirvana" title="Spartiti di Dive">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dive+Nirvana" title="Accordi di Dive">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dive+Nirvana" title="Testi di Dive">testi</a><br>
<b>2</b>. Sliver - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sliver+Nirvana" title="Spartiti di Sliver">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sliver+Nirvana" title="Accordi di Sliver">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sliver+Nirvana" title="Testi di Sliver">testi</a><br>
<b>3</b>. Stain - <a target="_blank" href="http://www.google.com/search?q=spartiti+Stain+Nirvana" title="Spartiti di Stain">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Stain+Nirvana" title="Accordi di Stain">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Stain+Nirvana" title="Testi di Stain">testi</a><br>
<b>4</b>. Been a Son - <a target="_blank" href="http://www.google.com/search?q=spartiti+Been+a+Son+Nirvana" title="Spartiti di Been a Son">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Been+a+Son+Nirvana" title="Accordi di Been a Son">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Been+a+Son+Nirvana" title="Testi di Been a Son">testi</a><br>
<b>5</b>. Turnaround (Devo cover) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Turnaround+%28Devo+cover%29+Nirvana" title="Spartiti di Turnaround (Devo cover)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Turnaround+%28Devo+cover%29+Nirvana" title="Accordi di Turnaround (Devo cover)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Turnaround+%28Devo+cover%29+Nirvana" title="Testi di Turnaround (Devo cover)">testi</a><br>
<b>6</b>. Molly's Lips (Vaselines cover) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Molly%27s+Lips+%28Vaselines+cover%29+Nirvana" title="Spartiti di Molly's Lips (Vaselines cover)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Molly%27s+Lips+%28Vaselines+cover%29+Nirvana" title="Accordi di Molly's Lips (Vaselines cover)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Molly%27s+Lips+%28Vaselines+cover%29+Nirvana" title="Testi di Molly's Lips (Vaselines cover)">testi</a><br>
<b>7</b>. Son of a Gun (Vaselines cover) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Son+of+a+Gun+%28Vaselines+cover%29+Nirvana" title="Spartiti di Son of a Gun (Vaselines cover)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Son+of+a+Gun+%28Vaselines+cover%29+Nirvana" title="Accordi di Son of a Gun (Vaselines cover)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Son+of+a+Gun+%28Vaselines+cover%29+Nirvana" title="Testi di Son of a Gun (Vaselines cover)">testi</a><br>
<b>8</b>. New Wave Polly - <a target="_blank" href="http://www.google.com/search?q=spartiti+New+Wave+Polly+Nirvana" title="Spartiti di New Wave Polly">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+New+Wave+Polly+Nirvana" title="Accordi di New Wave Polly">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+New+Wave+Polly+Nirvana" title="Testi di New Wave Polly">testi</a><br>
<b>9</b>. Beeswax - <a target="_blank" href="http://www.google.com/search?q=spartiti+Beeswax+Nirvana" title="Spartiti di Beeswax">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Beeswax+Nirvana" title="Accordi di Beeswax">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Beeswax+Nirvana" title="Testi di Beeswax">testi</a><br>
<b>10</b>. Downer - <a target="_blank" href="http://www.google.com/search?q=spartiti+Downer+Nirvana" title="Spartiti di Downer">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Downer+Nirvana" title="Accordi di Downer">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Downer+Nirvana" title="Testi di Downer">testi</a><br>
<b>11</b>. Mexican Seafood - <a target="_blank" href="http://www.google.com/search?q=spartiti+Mexican+Seafood+Nirvana" title="Spartiti di Mexican Seafood">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Mexican+Seafood+Nirvana" title="Accordi di Mexican Seafood">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Mexican+Seafood+Nirvana" title="Testi di Mexican Seafood">testi</a><br>
<b>12</b>. Hairspray Queen - <a target="_blank" href="http://www.google.com/search?q=spartiti+Hairspray+Queen+Nirvana" title="Spartiti di Hairspray Queen">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Hairspray+Queen+Nirvana" title="Accordi di Hairspray Queen">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Hairspray+Queen+Nirvana" title="Testi di Hairspray Queen">testi</a><br>
<b>13</b>. Aero Zeppelin - <a target="_blank" href="http://www.google.com/search?q=spartiti+Aero+Zeppelin+Nirvana" title="Spartiti di Aero Zeppelin">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Aero+Zeppelin+Nirvana" title="Accordi di Aero Zeppelin">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Aero+Zeppelin+Nirvana" title="Testi di Aero Zeppelin">testi</a><br>
<b>14</b>. Big Long Now - <a target="_blank" href="http://www.google.com/search?q=spartiti+Big+Long+Now+Nirvana" title="Spartiti di Big Long Now">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Big+Long+Now+Nirvana" title="Accordi di Big Long Now">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Big+Long+Now+Nirvana" title="Testi di Big Long Now">testi</a><br>
<b>15</b>. Aneurysm - <a target="_blank" href="http://www.google.com/search?q=spartiti+Aneurysm+Nirvana" title="Spartiti di Aneurysm">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Aneurysm+Nirvana" title="Accordi di Aneurysm">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Aneurysm+Nirvana" title="Testi di Aneurysm">testi</a><br>
<h2>Nevermind (1991) </h2>
<b>1</b>. Smells Like Teen Spirit - <a target="_blank" href="http://www.google.com/search?q=spartiti+Smells+Like+Teen+Spirit+Nirvana" title="Spartiti di Smells Like Teen Spirit">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Smells+Like+Teen+Spirit+Nirvana" title="Accordi di Smells Like Teen Spirit">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Smells+Like+Teen+Spirit+Nirvana" title="Testi di Smells Like Teen Spirit">testi</a><br>
<b>2</b>. In Bloom - <a target="_blank" href="http://www.google.com/search?q=spartiti+In+Bloom+Nirvana" title="Spartiti di In Bloom">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+In+Bloom+Nirvana" title="Accordi di In Bloom">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+In+Bloom+Nirvana" title="Testi di In Bloom">testi</a><br>
<b>3</b>. Come As You Are - <a target="_blank" href="http://www.google.com/search?q=spartiti+Come+As+You+Are+Nirvana" title="Spartiti di Come As You Are">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Come+As+You+Are+Nirvana" title="Accordi di Come As You Are">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Come+As+You+Are+Nirvana" title="Testi di Come As You Are">testi</a><br>
<b>4</b>. Breed - <a target="_blank" href="http://www.google.com/search?q=spartiti+Breed+Nirvana" title="Spartiti di Breed">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Breed+Nirvana" title="Accordi di Breed">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Breed+Nirvana" title="Testi di Breed">testi</a><br>
<b>5</b>. Lithium - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lithium+Nirvana" title="Spartiti di Lithium">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lithium+Nirvana" title="Accordi di Lithium">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lithium+Nirvana" title="Testi di Lithium">testi</a><br>
<b>6</b>. Polly - <a target="_blank" href="http://www.google.com/search?q=spartiti+Polly+Nirvana" title="Spartiti di Polly">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Polly+Nirvana" title="Accordi di Polly">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Polly+Nirvana" title="Testi di Polly">testi</a><br>
<b>7</b>. Territorial Pissings - <a target="_blank" href="http://www.google.com/search?q=spartiti+Territorial+Pissings+Nirvana" title="Spartiti di Territorial Pissings">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Territorial+Pissings+Nirvana" title="Accordi di Territorial Pissings">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Territorial+Pissings+Nirvana" title="Testi di Territorial Pissings">testi</a><br>
<b>8</b>. Drain You - <a target="_blank" href="http://www.google.com/search?q=spartiti+Drain+You+Nirvana" title="Spartiti di Drain You">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Drain+You+Nirvana" title="Accordi di Drain You">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Drain+You+Nirvana" title="Testi di Drain You">testi</a><br>
<b>9</b>. Lounge Act - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lounge+Act+Nirvana" title="Spartiti di Lounge Act">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lounge+Act+Nirvana" title="Accordi di Lounge Act">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lounge+Act+Nirvana" title="Testi di Lounge Act">testi</a><br>
<b>10</b>. Stay Away - <a target="_blank" href="http://www.google.com/search?q=spartiti+Stay+Away+Nirvana" title="Spartiti di Stay Away">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Stay+Away+Nirvana" title="Accordi di Stay Away">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Stay+Away+Nirvana" title="Testi di Stay Away">testi</a><br>
<b>11</b>. On A Plain - <a target="_blank" href="http://www.google.com/search?q=spartiti+On+A+Plain+Nirvana" title="Spartiti di On A Plain">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+On+A+Plain+Nirvana" title="Accordi di On A Plain">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+On+A+Plain+Nirvana" title="Testi di On A Plain">testi</a><br>
<b>12</b>. Something In The Way - <a target="_blank" href="http://www.google.com/search?q=spartiti+Something+In+The+Way+Nirvana" title="Spartiti di Something In The Way">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Something+In+The+Way+Nirvana" title="Accordi di Something In The Way">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Something+In+The+Way+Nirvana" title="Testi di Something In The Way">testi</a><br>
<b>13</b>. Endless Nameless - <a target="_blank" href="http://www.google.com/search?q=spartiti+Endless+Nameless+Nirvana" title="Spartiti di Endless Nameless">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Endless+Nameless+Nirvana" title="Accordi di Endless Nameless">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Endless+Nameless+Nirvana" title="Testi di Endless Nameless">testi</a><br>
<h2>Bleach (1989) </h2>
<b>1</b>. Blew - <a target="_blank" href="http://www.google.com/search?q=spartiti+Blew+Nirvana" title="Spartiti di Blew">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Blew+Nirvana" title="Accordi di Blew">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Blew+Nirvana" title="Testi di Blew">testi</a><br>
<b>2</b>. Floyd the Barber - <a target="_blank" href="http://www.google.com/search?q=spartiti+Floyd+the+Barber+Nirvana" title="Spartiti di Floyd the Barber">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Floyd+the+Barber+Nirvana" title="Accordi di Floyd the Barber">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Floyd+the+Barber+Nirvana" title="Testi di Floyd the Barber">testi</a><br>
<b>3</b>. About a Girl - <a target="_blank" href="http://www.google.com/search?q=spartiti+About+a+Girl+Nirvana" title="Spartiti di About a Girl">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+About+a+Girl+Nirvana" title="Accordi di About a Girl">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+About+a+Girl+Nirvana" title="Testi di About a Girl">testi</a><br>
<b>4</b>. School - <a target="_blank" href="http://www.google.com/search?q=spartiti+School+Nirvana" title="Spartiti di School">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+School+Nirvana" title="Accordi di School">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+School+Nirvana" title="Testi di School">testi</a><br>
<b>5</b>. Love Buzz - <a target="_blank" href="http://www.google.com/search?q=spartiti+Love+Buzz+Nirvana" title="Spartiti di Love Buzz">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Love+Buzz+Nirvana" title="Accordi di Love Buzz">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Love+Buzz+Nirvana" title="Testi di Love Buzz">testi</a><br>
<b>6</b>. Paper Cuts - <a target="_blank" href="http://www.google.com/search?q=spartiti+Paper+Cuts+Nirvana" title="Spartiti di Paper Cuts">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Paper+Cuts+Nirvana" title="Accordi di Paper Cuts">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Paper+Cuts+Nirvana" title="Testi di Paper Cuts">testi</a><br>
<b>7</b>. Negative Creep - <a target="_blank" href="http://www.google.com/search?q=spartiti+Negative+Creep+Nirvana" title="Spartiti di Negative Creep">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Negative+Creep+Nirvana" title="Accordi di Negative Creep">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Negative+Creep+Nirvana" title="Testi di Negative Creep">testi</a><br>
<b>8</b>. Scoff - <a target="_blank" href="http://www.google.com/search?q=spartiti+Scoff+Nirvana" title="Spartiti di Scoff">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Scoff+Nirvana" title="Accordi di Scoff">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Scoff+Nirvana" title="Testi di Scoff">testi</a><br>
<b>9</b>. Swap Meet - <a target="_blank" href="http://www.google.com/search?q=spartiti+Swap+Meet+Nirvana" title="Spartiti di Swap Meet">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Swap+Meet+Nirvana" title="Accordi di Swap Meet">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Swap+Meet+Nirvana" title="Testi di Swap Meet">testi</a><br>
<b>10</b>. Mr. Moustache - <a target="_blank" href="http://www.google.com/search?q=spartiti+Mr.+Moustache+Nirvana" title="Spartiti di Mr. Moustache">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Mr.+Moustache+Nirvana" title="Accordi di Mr. Moustache">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Mr.+Moustache+Nirvana" title="Testi di Mr. Moustache">testi</a><br>
<b>11</b>. Sifting - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sifting+Nirvana" title="Spartiti di Sifting">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sifting+Nirvana" title="Accordi di Sifting">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sifting+Nirvana" title="Testi di Sifting">testi</a><br>
<b>12</b>. Big Cheese - <a target="_blank" href="http://www.google.com/search?q=spartiti+Big+Cheese+Nirvana" title="Spartiti di Big Cheese">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Big+Cheese+Nirvana" title="Accordi di Big Cheese">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Big+Cheese+Nirvana" title="Testi di Big Cheese">testi</a><br>
<b>13</b>. Downer - <a target="_blank" href="http://www.google.com/search?q=spartiti+Downer+Nirvana" title="Spartiti di Downer">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Downer+Nirvana" title="Accordi di Downer">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Downer+Nirvana" title="Testi di Downer">testi</a><br>
<h2>Altre Canzoni </h2>
<b>1</b>. Alcohol (Also called High On Hog) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Alcohol+%28Also+called+High+On+Hog%29+Nirvana" title="Spartiti di Alcohol (Also called High On Hog)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Alcohol+%28Also+called+High+On+Hog%29+Nirvana" title="Accordi di Alcohol (Also called High On Hog)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Alcohol+%28Also+called+High+On+Hog%29+Nirvana" title="Testi di Alcohol (Also called High On Hog)">testi</a><br>
<b>2</b>. Anorexorcist - <a target="_blank" href="http://www.google.com/search?q=spartiti+Anorexorcist+Nirvana" title="Spartiti di Anorexorcist">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Anorexorcist+Nirvana" title="Accordi di Anorexorcist">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Anorexorcist+Nirvana" title="Testi di Anorexorcist">testi</a><br>
<b>3</b>. Baba O' Riley - <a target="_blank" href="http://www.google.com/search?q=spartiti+Baba+O%27+Riley+Nirvana" title="Spartiti di Baba O' Riley">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Baba+O%27+Riley+Nirvana" title="Accordi di Baba O' Riley">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Baba+O%27+Riley+Nirvana" title="Testi di Baba O' Riley">testi</a><br>
<b>4</b>. Bad Moon Rising - <a target="_blank" href="http://www.google.com/search?q=spartiti+Bad+Moon+Rising+Nirvana" title="Spartiti di Bad Moon Rising">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Bad+Moon+Rising+Nirvana" title="Accordi di Bad Moon Rising">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Bad+Moon+Rising+Nirvana" title="Testi di Bad Moon Rising">testi</a><br>
<b>5</b>. Bambi Slaughter / Bambi Kill - <a target="_blank" href="http://www.google.com/search?q=spartiti+Bambi+Slaughter+%2F+Bambi+Kill+Nirvana" title="Spartiti di Bambi Slaughter / Bambi Kill">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Bambi+Slaughter+%2F+Bambi+Kill+Nirvana" title="Accordi di Bambi Slaughter / Bambi Kill">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Bambi+Slaughter+%2F+Bambi+Kill+Nirvana" title="Testi di Bambi Slaughter / Bambi Kill">testi</a><br>
<b>6</b>. Beans - <a target="_blank" href="http://www.google.com/search?q=spartiti+Beans+Nirvana" title="Spartiti di Beans">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Beans+Nirvana" title="Accordi di Beans">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Beans+Nirvana" title="Testi di Beans">testi</a><br>
<b>7</b>. Blandest - <a target="_blank" href="http://www.google.com/search?q=spartiti+Blandest+Nirvana" title="Spartiti di Blandest">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Blandest+Nirvana" title="Accordi di Blandest">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Blandest+Nirvana" title="Testi di Blandest">testi</a><br>
<b>8</b>. Clean Up Before She Comes - <a target="_blank" href="http://www.google.com/search?q=spartiti+Clean+Up+Before+She+Comes+Nirvana" title="Spartiti di Clean Up Before She Comes">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Clean+Up+Before+She+Comes+Nirvana" title="Accordi di Clean Up Before She Comes">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Clean+Up+Before+She+Comes+Nirvana" title="Testi di Clean Up Before She Comes">testi</a><br>
<b>9</b>. Come On Death - <a target="_blank" href="http://www.google.com/search?q=spartiti+Come+On+Death+Nirvana" title="Spartiti di Come On Death">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Come+On+Death+Nirvana" title="Accordi di Come On Death">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Come+On+Death+Nirvana" title="Testi di Come On Death">testi</a><br>
<b>10</b>. Curmudgeon - <a target="_blank" href="http://www.google.com/search?q=spartiti+Curmudgeon+Nirvana" title="Spartiti di Curmudgeon">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Curmudgeon+Nirvana" title="Accordi di Curmudgeon">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Curmudgeon+Nirvana" title="Testi di Curmudgeon">testi</a><br>
<b>11</b>. D7 - <a target="_blank" href="http://www.google.com/search?q=spartiti+D7+Nirvana" title="Spartiti di D7">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+D7+Nirvana" title="Accordi di D7">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+D7+Nirvana" title="Testi di D7">testi</a><br>
<b>12</b>. Dazed and Confused - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dazed+and+Confused+Nirvana" title="Spartiti di Dazed and Confused">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dazed+and+Confused+Nirvana" title="Accordi di Dazed and Confused">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dazed+and+Confused+Nirvana" title="Testi di Dazed and Confused">testi</a><br>
<b>13</b>. Do You Love Me? - <a target="_blank" href="http://www.google.com/search?q=spartiti+Do+You+Love+Me%3F+Nirvana" title="Spartiti di Do You Love Me?">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Do+You+Love+Me%3F+Nirvana" title="Accordi di Do You Love Me?">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Do+You+Love+Me%3F+Nirvana" title="Testi di Do You Love Me?">testi</a><br>
<b>14</b>. Down In The Dark - <a target="_blank" href="http://www.google.com/search?q=spartiti+Down+In+The+Dark+Nirvana" title="Spartiti di Down In The Dark">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Down+In+The+Dark+Nirvana" title="Accordi di Down In The Dark">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Down+In+The+Dark+Nirvana" title="Testi di Down In The Dark">testi</a><br>
<b>15</b>. Even In His Youth - <a target="_blank" href="http://www.google.com/search?q=spartiti+Even+In+His+Youth+Nirvana" title="Spartiti di Even In His Youth">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Even+In+His+Youth+Nirvana" title="Accordi di Even In His Youth">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Even+In+His+Youth+Nirvana" title="Testi di Even In His Youth">testi</a><br>
<b>16</b>. Gypsies, Tramps and Thieves - <a target="_blank" href="http://www.google.com/search?q=spartiti+Gypsies%2C+Tramps+and+Thieves+Nirvana" title="Spartiti di Gypsies, Tramps and Thieves">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Gypsies%2C+Tramps+and+Thieves+Nirvana" title="Accordi di Gypsies, Tramps and Thieves">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Gypsies%2C+Tramps+and+Thieves+Nirvana" title="Testi di Gypsies, Tramps and Thieves">testi</a><br>
<b>17</b>. Heartbreaker - <a target="_blank" href="http://www.google.com/search?q=spartiti+Heartbreaker+Nirvana" title="Spartiti di Heartbreaker">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Heartbreaker+Nirvana" title="Accordi di Heartbreaker">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Heartbreaker+Nirvana" title="Testi di Heartbreaker">testi</a><br>
<b>18</b>. Help Me, I'm Hungry - <a target="_blank" href="http://www.google.com/search?q=spartiti+Help+Me%2C+I%27m+Hungry+Nirvana" title="Spartiti di Help Me, I'm Hungry">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Help+Me%2C+I%27m+Hungry+Nirvana" title="Accordi di Help Me, I'm Hungry">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Help+Me%2C+I%27m+Hungry+Nirvana" title="Testi di Help Me, I'm Hungry">testi</a><br>
<b>19</b>. Here She Comes Now - <a target="_blank" href="http://www.google.com/search?q=spartiti+Here+She+Comes+Now+Nirvana" title="Spartiti di Here She Comes Now">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Here+She+Comes+Now+Nirvana" title="Accordi di Here She Comes Now">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Here+She+Comes+Now+Nirvana" title="Testi di Here She Comes Now">testi</a><br>
<b>20</b>. I Feel Fine - <a target="_blank" href="http://www.google.com/search?q=spartiti+I+Feel+Fine+Nirvana" title="Spartiti di I Feel Fine">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+I+Feel+Fine+Nirvana" title="Accordi di I Feel Fine">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+I+Feel+Fine+Nirvana" title="Testi di I Feel Fine">testi</a><br>
<b>21</b>. I Hate Myself and Want to Die - <a target="_blank" href="http://www.google.com/search?q=spartiti+I+Hate+Myself+and+Want+to+Die+Nirvana" title="Spartiti di I Hate Myself and Want to Die">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+I+Hate+Myself+and+Want+to+Die+Nirvana" title="Accordi di I Hate Myself and Want to Die">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+I+Hate+Myself+and+Want+to+Die+Nirvana" title="Testi di I Hate Myself and Want to Die">testi</a><br>
<b>22</b>. I Wanna Be Your Dog - <a target="_blank" href="http://www.google.com/search?q=spartiti+I+Wanna+Be+Your+Dog+Nirvana" title="Spartiti di I Wanna Be Your Dog">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+I+Wanna+Be+Your+Dog+Nirvana" title="Accordi di I Wanna Be Your Dog">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+I+Wanna+Be+Your+Dog+Nirvana" title="Testi di I Wanna Be Your Dog">testi</a><br>
<b>23</b>. If You Must / Happy Hour / The Extreme - <a target="_blank" href="http://www.google.com/search?q=spartiti+If+You+Must+%2F+Happy+Hour+%2F+The+Extreme+Nirvana" title="Spartiti di If You Must / Happy Hour / The Extreme">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+If+You+Must+%2F+Happy+Hour+%2F+The+Extreme+Nirvana" title="Accordi di If You Must / Happy Hour / The Extreme">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+If+You+Must+%2F+Happy+Hour+%2F+The+Extreme+Nirvana" title="Testi di If You Must / Happy Hour / The Extreme">testi</a><br>
<b>24</b>. Immigrant Song - <a target="_blank" href="http://www.google.com/search?q=spartiti+Immigrant+Song+Nirvana" title="Spartiti di Immigrant Song">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Immigrant+Song+Nirvana" title="Accordi di Immigrant Song">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Immigrant+Song+Nirvana" title="Testi di Immigrant Song">testi</a><br>
<b>25</b>. Immodium - <a target="_blank" href="http://www.google.com/search?q=spartiti+Immodium+Nirvana" title="Spartiti di Immodium">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Immodium+Nirvana" title="Accordi di Immodium">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Immodium+Nirvana" title="Testi di Immodium">testi</a><br>
<b>26</b>. In His Room - <a target="_blank" href="http://www.google.com/search?q=spartiti+In+His+Room+Nirvana" title="Spartiti di In His Room">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+In+His+Room+Nirvana" title="Accordi di In His Room">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+In+His+Room+Nirvana" title="Testi di In His Room">testi</a><br>
<b>27</b>. Junkyard - <a target="_blank" href="http://www.google.com/search?q=spartiti+Junkyard+Nirvana" title="Spartiti di Junkyard">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Junkyard+Nirvana" title="Accordi di Junkyard">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Junkyard+Nirvana" title="Testi di Junkyard">testi</a><br>
<b>28</b>. Love Gun - <a target="_blank" href="http://www.google.com/search?q=spartiti+Love+Gun+Nirvana" title="Spartiti di Love Gun">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Love+Gun+Nirvana" title="Accordi di Love Gun">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Love+Gun+Nirvana" title="Testi di Love Gun">testi</a><br>
<b>29</b>. Marigold - <a target="_blank" href="http://www.google.com/search?q=spartiti+Marigold+Nirvana" title="Spartiti di Marigold">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Marigold+Nirvana" title="Accordi di Marigold">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Marigold+Nirvana" title="Testi di Marigold">testi</a><br>
<b>30</b>. Moist Vagina - <a target="_blank" href="http://www.google.com/search?q=spartiti+Moist+Vagina+Nirvana" title="Spartiti di Moist Vagina">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Moist+Vagina+Nirvana" title="Accordi di Moist Vagina">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Moist+Vagina+Nirvana" title="Testi di Moist Vagina">testi</a><br>
<b>31</b>. My Best Friends Girl - <a target="_blank" href="http://www.google.com/search?q=spartiti+My+Best+Friends+Girl+Nirvana" title="Spartiti di My Best Friends Girl">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+My+Best+Friends+Girl+Nirvana" title="Accordi di My Best Friends Girl">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+My+Best+Friends+Girl+Nirvana" title="Testi di My Best Friends Girl">testi</a><br>
<b>32</b>. My Sharona - <a target="_blank" href="http://www.google.com/search?q=spartiti+My+Sharona+Nirvana" title="Spartiti di My Sharona">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+My+Sharona+Nirvana" title="Accordi di My Sharona">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+My+Sharona+Nirvana" title="Testi di My Sharona">testi</a><br>
<b>33</b>. No Quarter - <a target="_blank" href="http://www.google.com/search?q=spartiti+No+Quarter+Nirvana" title="Spartiti di No Quarter">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+No+Quarter+Nirvana" title="Accordi di No Quarter">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+No+Quarter+Nirvana" title="Testi di No Quarter">testi</a><br>
<b>34</b>. Oh, the Guilt - <a target="_blank" href="http://www.google.com/search?q=spartiti+Oh%2C+the+Guilt+Nirvana" title="Spartiti di Oh, the Guilt">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Oh%2C+the+Guilt+Nirvana" title="Accordi di Oh, the Guilt">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Oh%2C+the+Guilt+Nirvana" title="Testi di Oh, the Guilt">testi</a><br>
<b>35</b>. Old Age - <a target="_blank" href="http://www.google.com/search?q=spartiti+Old+Age+Nirvana" title="Spartiti di Old Age">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Old+Age+Nirvana" title="Accordi di Old Age">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Old+Age+Nirvana" title="Testi di Old Age">testi</a><br>
<b>36</b>. On the Mountain (a.k.a. You Got No Right) - <a target="_blank" href="http://www.google.com/search?q=spartiti+On+the+Mountain+%28a.k.a.+You+Got+No+Right%29+Nirvana" title="Spartiti di On the Mountain (a.k.a. You Got No Right)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+On+the+Mountain+%28a.k.a.+You+Got+No+Right%29+Nirvana" title="Accordi di On the Mountain (a.k.a. You Got No Right)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+On+the+Mountain+%28a.k.a.+You+Got+No+Right%29+Nirvana" title="Testi di On the Mountain (a.k.a. You Got No Right)">testi</a><br>
<b>37</b>. Opinion - <a target="_blank" href="http://www.google.com/search?q=spartiti+Opinion+Nirvana" title="Spartiti di Opinion">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Opinion+Nirvana" title="Accordi di Opinion">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Opinion+Nirvana" title="Testi di Opinion">testi</a><br>
<b>38</b>. Pay To Play - <a target="_blank" href="http://www.google.com/search?q=spartiti+Pay+To+Play+Nirvana" title="Spartiti di Pay To Play">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Pay+To+Play+Nirvana" title="Accordi di Pay To Play">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Pay+To+Play+Nirvana" title="Testi di Pay To Play">testi</a><br>
<b>39</b>. Pen Cap Chew - <a target="_blank" href="http://www.google.com/search?q=spartiti+Pen+Cap+Chew+Nirvana" title="Spartiti di Pen Cap Chew">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Pen+Cap+Chew+Nirvana" title="Accordi di Pen Cap Chew">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Pen+Cap+Chew+Nirvana" title="Testi di Pen Cap Chew">testi</a><br>
<b>40</b>. Raunchola - <a target="_blank" href="http://www.google.com/search?q=spartiti+Raunchola+Nirvana" title="Spartiti di Raunchola">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Raunchola+Nirvana" title="Accordi di Raunchola">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Raunchola+Nirvana" title="Testi di Raunchola">testi</a><br>
<b>41</b>. Return of the Rat - <a target="_blank" href="http://www.google.com/search?q=spartiti+Return+of+the+Rat+Nirvana" title="Spartiti di Return of the Rat">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Return+of+the+Rat+Nirvana" title="Accordi di Return of the Rat">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Return+of+the+Rat+Nirvana" title="Testi di Return of the Rat">testi</a><br>
<b>42</b>. Rio - <a target="_blank" href="http://www.google.com/search?q=spartiti+Rio+Nirvana" title="Spartiti di Rio">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Rio+Nirvana" title="Accordi di Rio">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Rio+Nirvana" title="Testi di Rio">testi</a><br>
<b>43</b>. Sappy - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sappy+Nirvana" title="Spartiti di Sappy">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sappy+Nirvana" title="Accordi di Sappy">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sappy+Nirvana" title="Testi di Sappy">testi</a><br>
<b>44</b>. Spectre - <a target="_blank" href="http://www.google.com/search?q=spartiti+Spectre+Nirvana" title="Spartiti di Spectre">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Spectre+Nirvana" title="Accordi di Spectre">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Spectre+Nirvana" title="Testi di Spectre">testi</a><br>
<b>45</b>. Talk To Me - <a target="_blank" href="http://www.google.com/search?q=spartiti+Talk+To+Me+Nirvana" title="Spartiti di Talk To Me">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Talk+To+Me+Nirvana" title="Accordi di Talk To Me">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Talk+To+Me+Nirvana" title="Testi di Talk To Me">testi</a><br>
<b>46</b>. The End - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+End+Nirvana" title="Spartiti di The End">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+End+Nirvana" title="Accordi di The End">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+End+Nirvana" title="Testi di The End">testi</a><br>
<b>47</b>. The Money Will Roll Right In - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+Money+Will+Roll+Right+In+Nirvana" title="Spartiti di The Money Will Roll Right In">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+Money+Will+Roll+Right+In+Nirvana" title="Accordi di The Money Will Roll Right In">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+Money+Will+Roll+Right+In+Nirvana" title="Testi di The Money Will Roll Right In">testi</a><br>
<b>48</b>. The Priest They Called Him - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+Priest+They+Called+Him+Nirvana" title="Spartiti di The Priest They Called Him">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+Priest+They+Called+Him+Nirvana" title="Accordi di The Priest They Called Him">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+Priest+They+Called+Him+Nirvana" title="Testi di The Priest They Called Him">testi</a><br>
<b>49</b>. Token Eastern Song (also known as Happy Hour) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Token+Eastern+Song+%28also+known+as+Happy+Hour%29+Nirvana" title="Spartiti di Token Eastern Song (also known as Happy Hour)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Token+Eastern+Song+%28also+known+as+Happy+Hour%29+Nirvana" title="Accordi di Token Eastern Song (also known as Happy Hour)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Token+Eastern+Song+%28also+known+as+Happy+Hour%29+Nirvana" title="Testi di Token Eastern Song (also known as Happy Hour)">testi</a><br>
<b>50</b>. Verse Chorus Verse (also called 'Everything And Nothing') - <a target="_blank" href="http://www.google.com/search?q=spartiti+Verse+Chorus+Verse+%28also+called+%27Everything+And+Nothing%27%29+Nirvana" title="Spartiti di Verse Chorus Verse (also called 'Everything And Nothing')">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Verse+Chorus+Verse+%28also+called+%27Everything+And+Nothing%27%29+Nirvana" title="Accordi di Verse Chorus Verse (also called 'Everything And Nothing')">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Verse+Chorus+Verse+%28also+called+%27Everything+And+Nothing%27%29+Nirvana" title="Testi di Verse Chorus Verse (also called 'Everything And Nothing')">testi</a><br>
<b>51</b>. Yes, She Is My Skinhead - <a target="_blank" href="http://www.google.com/search?q=spartiti+Yes%2C+She+Is+My+Skinhead+Nirvana" title="Spartiti di Yes, She Is My Skinhead">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Yes%2C+She+Is+My+Skinhead+Nirvana" title="Accordi di Yes, She Is My Skinhead">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Yes%2C+She+Is+My+Skinhead+Nirvana" title="Testi di Yes, She Is My Skinhead">testi</a><br>
<h2><a href="<?php echo "$base_website_address/$spartiti_dir" ?>/index.html" title="Trova accordi, spartiti, tablature e testi di tantissimi artisti">Torna all'indice degli artisti</a></h2>
