<!--
title: Trova spartiti per chitarra, accordi, testi e tablature di Lucio Dalla. Discografia Lucio Dalla.
description: Trova tutti gli spartiti, accordi, testi e tablature di Lucio Dalla. Discografia Lucio Dalla.
keywords: Discografia, Lucio Dalla, spartiti, accordi, testi, tablature
template: tablature
-->
<h1>Trova spartiti per chitarra, accordi, testi e tablature di Lucio Dalla</h1><h2>Leggere gli spartiti per chitarra, gli accordi e le tablature:</h2>
<?php require("tabdescription.php"); ?>

<h2>Discografia Lucio Dalla:</h2>
<h2>12000 Lune (2006) </h2>
<b>1</b>. Caruso - <a target="_blank" href="http://www.google.com/search?q=spartiti+Caruso+Lucio+Dalla" title="Spartiti di Caruso">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Caruso+Lucio+Dalla" title="Accordi di Caruso">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Caruso+Lucio+Dalla" title="Testi di Caruso">testi</a><br>
<b>2</b>. Attenti Al Lupo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Attenti+Al+Lupo+Lucio+Dalla" title="Spartiti di Attenti Al Lupo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Attenti+Al+Lupo+Lucio+Dalla" title="Accordi di Attenti Al Lupo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Attenti+Al+Lupo+Lucio+Dalla" title="Testi di Attenti Al Lupo">testi</a><br>
<b>3</b>. Canzone - <a target="_blank" href="http://www.google.com/search?q=spartiti+Canzone+Lucio+Dalla" title="Spartiti di Canzone">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Canzone+Lucio+Dalla" title="Accordi di Canzone">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Canzone+Lucio+Dalla" title="Testi di Canzone">testi</a><br>
<b>4</b>. Tu Non Mi Basti Mai - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tu+Non+Mi+Basti+Mai+Lucio+Dalla" title="Spartiti di Tu Non Mi Basti Mai">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tu+Non+Mi+Basti+Mai+Lucio+Dalla" title="Accordi di Tu Non Mi Basti Mai">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tu+Non+Mi+Basti+Mai+Lucio+Dalla" title="Testi di Tu Non Mi Basti Mai">testi</a><br>
<b>5</b>. Ciao - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ciao+Lucio+Dalla" title="Spartiti di Ciao">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ciao+Lucio+Dalla" title="Accordi di Ciao">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ciao+Lucio+Dalla" title="Testi di Ciao">testi</a><br>
<b>6</b>. Non Vergognarsi Mai - <a target="_blank" href="http://www.google.com/search?q=spartiti+Non+Vergognarsi+Mai+Lucio+Dalla" title="Spartiti di Non Vergognarsi Mai">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Non+Vergognarsi+Mai+Lucio+Dalla" title="Accordi di Non Vergognarsi Mai">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Non+Vergognarsi+Mai+Lucio+Dalla" title="Testi di Non Vergognarsi Mai">testi</a><br>
<b>7</b>. Apriti Cuore - <a target="_blank" href="http://www.google.com/search?q=spartiti+Apriti+Cuore+Lucio+Dalla" title="Spartiti di Apriti Cuore">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Apriti+Cuore+Lucio+Dalla" title="Accordi di Apriti Cuore">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Apriti+Cuore+Lucio+Dalla" title="Testi di Apriti Cuore">testi</a><br>
<b>8</b>. Liberi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Liberi+Lucio+Dalla" title="Spartiti di Liberi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Liberi+Lucio+Dalla" title="Accordi di Liberi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Liberi+Lucio+Dalla" title="Testi di Liberi">testi</a><br>
<b>9</b>. Là - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%E0+Lucio+Dalla" title="Spartiti di Là">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%E0+Lucio+Dalla" title="Accordi di Là">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%E0+Lucio+Dalla" title="Testi di Là">testi</a><br>
<b>10</b>. Don't Touch Me - <a target="_blank" href="http://www.google.com/search?q=spartiti+Don%27t+Touch+Me+Lucio+Dalla" title="Spartiti di Don't Touch Me">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Don%27t+Touch+Me+Lucio+Dalla" title="Accordi di Don't Touch Me">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Don%27t+Touch+Me+Lucio+Dalla" title="Testi di Don't Touch Me">testi</a><br>
<b>11</b>. Henna - <a target="_blank" href="http://www.google.com/search?q=spartiti+Henna+Lucio+Dalla" title="Spartiti di Henna">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Henna+Lucio+Dalla" title="Accordi di Henna">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Henna+Lucio+Dalla" title="Testi di Henna">testi</a><br>
<b>12</b>. Le Rondini - <a target="_blank" href="http://www.google.com/search?q=spartiti+Le+Rondini+Lucio+Dalla" title="Spartiti di Le Rondini">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Le+Rondini+Lucio+Dalla" title="Accordi di Le Rondini">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Le+Rondini+Lucio+Dalla" title="Testi di Le Rondini">testi</a><br>
<b>13</b>. Siciliano - <a target="_blank" href="http://www.google.com/search?q=spartiti+Siciliano+Lucio+Dalla" title="Spartiti di Siciliano">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Siciliano+Lucio+Dalla" title="Accordi di Siciliano">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Siciliano+Lucio+Dalla" title="Testi di Siciliano">testi</a><br>
<b>14</b>. Ayrton - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ayrton+Lucio+Dalla" title="Spartiti di Ayrton">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ayrton+Lucio+Dalla" title="Accordi di Ayrton">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ayrton+Lucio+Dalla" title="Testi di Ayrton">testi</a><br>
<b>15</b>. Stella - <a target="_blank" href="http://www.google.com/search?q=spartiti+Stella+Lucio+Dalla" title="Spartiti di Stella">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Stella+Lucio+Dalla" title="Accordi di Stella">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Stella+Lucio+Dalla" title="Testi di Stella">testi</a><br>
<b>16</b>. Sotto Casa - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sotto+Casa+Lucio+Dalla" title="Spartiti di Sotto Casa">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sotto+Casa+Lucio+Dalla" title="Accordi di Sotto Casa">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sotto+Casa+Lucio+Dalla" title="Testi di Sotto Casa">testi</a><br>
<b>17</b>. Dark Bologna - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dark+Bologna+Lucio+Dalla" title="Spartiti di Dark Bologna">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dark+Bologna+Lucio+Dalla" title="Accordi di Dark Bologna">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dark+Bologna+Lucio+Dalla" title="Testi di Dark Bologna">testi</a><br>
<b>18</b>. Balla Balla Ballerino - <a target="_blank" href="http://www.google.com/search?q=spartiti+Balla+Balla+Ballerino+Lucio+Dalla" title="Spartiti di Balla Balla Ballerino">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Balla+Balla+Ballerino+Lucio+Dalla" title="Accordi di Balla Balla Ballerino">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Balla+Balla+Ballerino+Lucio+Dalla" title="Testi di Balla Balla Ballerino">testi</a><br>
<b>19</b>. Futura - <a target="_blank" href="http://www.google.com/search?q=spartiti+Futura+Lucio+Dalla" title="Spartiti di Futura">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Futura+Lucio+Dalla" title="Accordi di Futura">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Futura+Lucio+Dalla" title="Testi di Futura">testi</a><br>
<b>20</b>. Anna E Marco - <a target="_blank" href="http://www.google.com/search?q=spartiti+Anna+E+Marco+Lucio+Dalla" title="Spartiti di Anna E Marco">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Anna+E+Marco+Lucio+Dalla" title="Accordi di Anna E Marco">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Anna+E+Marco+Lucio+Dalla" title="Testi di Anna E Marco">testi</a><br>
<b>21</b>. Stella Di Mare - <a target="_blank" href="http://www.google.com/search?q=spartiti+Stella+Di+Mare+Lucio+Dalla" title="Spartiti di Stella Di Mare">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Stella+Di+Mare+Lucio+Dalla" title="Accordi di Stella Di Mare">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Stella+Di+Mare+Lucio+Dalla" title="Testi di Stella Di Mare">testi</a><br>
<b>22</b>. L'anno Che Verrà - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%27anno+Che+Verr%E0+Lucio+Dalla" title="Spartiti di L'anno Che Verrà">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%27anno+Che+Verr%E0+Lucio+Dalla" title="Accordi di L'anno Che Verrà">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%27anno+Che+Verr%E0+Lucio+Dalla" title="Testi di L'anno Che Verrà">testi</a><br>
<b>23</b>. Il Parco Della Luna - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Parco+Della+Luna+Lucio+Dalla" title="Spartiti di Il Parco Della Luna">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Parco+Della+Luna+Lucio+Dalla" title="Accordi di Il Parco Della Luna">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Parco+Della+Luna+Lucio+Dalla" title="Testi di Il Parco Della Luna">testi</a><br>
<b>24</b>. Milano - <a target="_blank" href="http://www.google.com/search?q=spartiti+Milano+Lucio+Dalla" title="Spartiti di Milano">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Milano+Lucio+Dalla" title="Accordi di Milano">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Milano+Lucio+Dalla" title="Testi di Milano">testi</a><br>
<b>25</b>. Cara - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cara+Lucio+Dalla" title="Spartiti di Cara">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cara+Lucio+Dalla" title="Accordi di Cara">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cara+Lucio+Dalla" title="Testi di Cara">testi</a><br>
<b>26</b>. La Sera Dei Miracoli - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Sera+Dei+Miracoli+Lucio+Dalla" title="Spartiti di La Sera Dei Miracoli">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Sera+Dei+Miracoli+Lucio+Dalla" title="Accordi di La Sera Dei Miracoli">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Sera+Dei+Miracoli+Lucio+Dalla" title="Testi di La Sera Dei Miracoli">testi</a><br>
<b>27</b>. Mambo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Mambo+Lucio+Dalla" title="Spartiti di Mambo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Mambo+Lucio+Dalla" title="Accordi di Mambo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Mambo+Lucio+Dalla" title="Testi di Mambo">testi</a><br>
<b>28</b>. Tutta La Vita - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tutta+La+Vita+Lucio+Dalla" title="Spartiti di Tutta La Vita">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tutta+La+Vita+Lucio+Dalla" title="Accordi di Tutta La Vita">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tutta+La+Vita+Lucio+Dalla" title="Testi di Tutta La Vita">testi</a><br>
<b>29</b>. Se Io Fossi Un Angelo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Se+Io+Fossi+Un+Angelo+Lucio+Dalla" title="Spartiti di Se Io Fossi Un Angelo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Se+Io+Fossi+Un+Angelo+Lucio+Dalla" title="Accordi di Se Io Fossi Un Angelo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Se+Io+Fossi+Un+Angelo+Lucio+Dalla" title="Testi di Se Io Fossi Un Angelo">testi</a><br>
<b>30</b>. Washington - <a target="_blank" href="http://www.google.com/search?q=spartiti+Washington+Lucio+Dalla" title="Spartiti di Washington">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Washington+Lucio+Dalla" title="Accordi di Washington">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Washington+Lucio+Dalla" title="Testi di Washington">testi</a><br>
<b>31</b>. Chissà Se Lo Sai - <a target="_blank" href="http://www.google.com/search?q=spartiti+Chiss%E0+Se+Lo+Sai+Lucio+Dalla" title="Spartiti di Chissà Se Lo Sai">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Chiss%E0+Se+Lo+Sai+Lucio+Dalla" title="Accordi di Chissà Se Lo Sai">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Chiss%E0+Se+Lo+Sai+Lucio+Dalla" title="Testi di Chissà Se Lo Sai">testi</a><br>
<b>32</b>. Amen - <a target="_blank" href="http://www.google.com/search?q=spartiti+Amen+Lucio+Dalla" title="Spartiti di Amen">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Amen+Lucio+Dalla" title="Accordi di Amen">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Amen+Lucio+Dalla" title="Testi di Amen">testi</a><br>
<b>33</b>. Felicità - <a target="_blank" href="http://www.google.com/search?q=spartiti+Felicit%E0+Lucio+Dalla" title="Spartiti di Felicità">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Felicit%E0+Lucio+Dalla" title="Accordi di Felicità">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Felicit%E0+Lucio+Dalla" title="Testi di Felicità">testi</a><br>
<b>34</b>. Com'è Profondo Il Mare - <a target="_blank" href="http://www.google.com/search?q=spartiti+Com%27%E8+Profondo+Il+Mare+Lucio+Dalla" title="Spartiti di Com'è Profondo Il Mare">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Com%27%E8+Profondo+Il+Mare+Lucio+Dalla" title="Accordi di Com'è Profondo Il Mare">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Com%27%E8+Profondo+Il+Mare+Lucio+Dalla" title="Testi di Com'è Profondo Il Mare">testi</a><br>
<b>35</b>. L'ultima Luna - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%27ultima+Luna+Lucio+Dalla" title="Spartiti di L'ultima Luna">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%27ultima+Luna+Lucio+Dalla" title="Accordi di L'ultima Luna">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%27ultima+Luna+Lucio+Dalla" title="Testi di L'ultima Luna">testi</a><br>
<b>36</b>. Disperato Erotico Stomp - <a target="_blank" href="http://www.google.com/search?q=spartiti+Disperato+Erotico+Stomp+Lucio+Dalla" title="Spartiti di Disperato Erotico Stomp">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Disperato+Erotico+Stomp+Lucio+Dalla" title="Accordi di Disperato Erotico Stomp">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Disperato+Erotico+Stomp+Lucio+Dalla" title="Testi di Disperato Erotico Stomp">testi</a><br>
<b>37</b>. Lunedì Cinema - <a target="_blank" href="http://www.google.com/search?q=spartiti+Luned%EC+Cinema+Lucio+Dalla" title="Spartiti di Lunedì Cinema">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Luned%EC+Cinema+Lucio+Dalla" title="Accordi di Lunedì Cinema">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Luned%EC+Cinema+Lucio+Dalla" title="Testi di Lunedì Cinema">testi</a><br>
<b>38</b>. Telefonami Tra Vent'anni - <a target="_blank" href="http://www.google.com/search?q=spartiti+Telefonami+Tra+Vent%27anni+Lucio+Dalla" title="Spartiti di Telefonami Tra Vent'anni">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Telefonami+Tra+Vent%27anni+Lucio+Dalla" title="Accordi di Telefonami Tra Vent'anni">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Telefonami+Tra+Vent%27anni+Lucio+Dalla" title="Testi di Telefonami Tra Vent'anni">testi</a><br>
<b>39</b>. Quale Allegria - <a target="_blank" href="http://www.google.com/search?q=spartiti+Quale+Allegria+Lucio+Dalla" title="Spartiti di Quale Allegria">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Quale+Allegria+Lucio+Dalla" title="Accordi di Quale Allegria">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Quale+Allegria+Lucio+Dalla" title="Testi di Quale Allegria">testi</a><br>
<b>40</b>. Nuvolari - <a target="_blank" href="http://www.google.com/search?q=spartiti+Nuvolari+Lucio+Dalla" title="Spartiti di Nuvolari">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Nuvolari+Lucio+Dalla" title="Accordi di Nuvolari">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Nuvolari+Lucio+Dalla" title="Testi di Nuvolari">testi</a><br>
<b>41</b>. Piazza Grande - <a target="_blank" href="http://www.google.com/search?q=spartiti+Piazza+Grande+Lucio+Dalla" title="Spartiti di Piazza Grande">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Piazza+Grande+Lucio+Dalla" title="Accordi di Piazza Grande">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Piazza+Grande+Lucio+Dalla" title="Testi di Piazza Grande">testi</a><br>
<b>42</b>. Itaca - <a target="_blank" href="http://www.google.com/search?q=spartiti+Itaca+Lucio+Dalla" title="Spartiti di Itaca">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Itaca+Lucio+Dalla" title="Accordi di Itaca">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Itaca+Lucio+Dalla" title="Testi di Itaca">testi</a><br>
<b>43</b>. Il Gigante E La Bambina - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Gigante+E+La+Bambina+Lucio+Dalla" title="Spartiti di Il Gigante E La Bambina">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Gigante+E+La+Bambina+Lucio+Dalla" title="Accordi di Il Gigante E La Bambina">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Gigante+E+La+Bambina+Lucio+Dalla" title="Testi di Il Gigante E La Bambina">testi</a><br>
<b>44</b>. La Casa In Riva Al Mare - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Casa+In+Riva+Al+Mare+Lucio+Dalla" title="Spartiti di La Casa In Riva Al Mare">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Casa+In+Riva+Al+Mare+Lucio+Dalla" title="Accordi di La Casa In Riva Al Mare">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Casa+In+Riva+Al+Mare+Lucio+Dalla" title="Testi di La Casa In Riva Al Mare">testi</a><br>
<b>45</b>. Un Uomo Come Me - <a target="_blank" href="http://www.google.com/search?q=spartiti+Un+Uomo+Come+Me+Lucio+Dalla" title="Spartiti di Un Uomo Come Me">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Un+Uomo+Come+Me+Lucio+Dalla" title="Accordi di Un Uomo Come Me">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Un+Uomo+Come+Me+Lucio+Dalla" title="Testi di Un Uomo Come Me">testi</a><br>
<b>46</b>. 4/3/1943 - <a target="_blank" href="http://www.google.com/search?q=spartiti+4%2F3%2F1943+Lucio+Dalla" title="Spartiti di 4/3/1943">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+4%2F3%2F1943+Lucio+Dalla" title="Accordi di 4/3/1943">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+4%2F3%2F1943+Lucio+Dalla" title="Testi di 4/3/1943">testi</a><br>
<b>47</b>. Occhi Di Ragazza - <a target="_blank" href="http://www.google.com/search?q=spartiti+Occhi+Di+Ragazza+Lucio+Dalla" title="Spartiti di Occhi Di Ragazza">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Occhi+Di+Ragazza+Lucio+Dalla" title="Accordi di Occhi Di Ragazza">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Occhi+Di+Ragazza+Lucio+Dalla" title="Testi di Occhi Di Ragazza">testi</a><br>
<b>48</b>. Sylvie - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sylvie+Lucio+Dalla" title="Spartiti di Sylvie">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sylvie+Lucio+Dalla" title="Accordi di Sylvie">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sylvie+Lucio+Dalla" title="Testi di Sylvie">testi</a><br>
<b>49</b>. Il Cielo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Cielo+Lucio+Dalla" title="Spartiti di Il Cielo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Cielo+Lucio+Dalla" title="Accordi di Il Cielo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Cielo+Lucio+Dalla" title="Testi di Il Cielo">testi</a><br>
<b>50</b>. Anna Bellanna - <a target="_blank" href="http://www.google.com/search?q=spartiti+Anna+Bellanna+Lucio+Dalla" title="Spartiti di Anna Bellanna">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Anna+Bellanna+Lucio+Dalla" title="Accordi di Anna Bellanna">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Anna+Bellanna+Lucio+Dalla" title="Testi di Anna Bellanna">testi</a><br>
<b>51</b>. Pafff...bum! - <a target="_blank" href="http://www.google.com/search?q=spartiti+Pafff...bum%21+Lucio+Dalla" title="Spartiti di Pafff...bum!">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Pafff...bum%21+Lucio+Dalla" title="Accordi di Pafff...bum!">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Pafff...bum%21+Lucio+Dalla" title="Testi di Pafff...bum!">testi</a><br>
<b>52</b>. Bisogna Saper Perdere - <a target="_blank" href="http://www.google.com/search?q=spartiti+Bisogna+Saper+Perdere+Lucio+Dalla" title="Spartiti di Bisogna Saper Perdere">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Bisogna+Saper+Perdere+Lucio+Dalla" title="Accordi di Bisogna Saper Perdere">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Bisogna+Saper+Perdere+Lucio+Dalla" title="Testi di Bisogna Saper Perdere">testi</a><br>
<b>53</b>. Lei (Non è Per Me) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lei+%28Non+%E8+Per+Me%29+Lucio+Dalla" title="Spartiti di Lei (Non è Per Me)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lei+%28Non+%E8+Per+Me%29+Lucio+Dalla" title="Accordi di Lei (Non è Per Me)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lei+%28Non+%E8+Per+Me%29+Lucio+Dalla" title="Testi di Lei (Non è Per Me)">testi</a><br>
<h2>Lucio (2003) </h2>
<b>1</b>. Amore Disperato - <a target="_blank" href="http://www.google.com/search?q=spartiti+Amore+Disperato+Lucio+Dalla" title="Spartiti di Amore Disperato">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Amore+Disperato+Lucio+Dalla" title="Accordi di Amore Disperato">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Amore+Disperato+Lucio+Dalla" title="Testi di Amore Disperato">testi</a><br>
<b>2</b>. Le Stelle Nel Sacco - <a target="_blank" href="http://www.google.com/search?q=spartiti+Le+Stelle+Nel+Sacco+Lucio+Dalla" title="Spartiti di Le Stelle Nel Sacco">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Le+Stelle+Nel+Sacco+Lucio+Dalla" title="Accordi di Le Stelle Nel Sacco">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Le+Stelle+Nel+Sacco+Lucio+Dalla" title="Testi di Le Stelle Nel Sacco">testi</a><br>
<b>3</b>. Prima Dammi Un Bacio - <a target="_blank" href="http://www.google.com/search?q=spartiti+Prima+Dammi+Un+Bacio+Lucio+Dalla" title="Spartiti di Prima Dammi Un Bacio">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Prima+Dammi+Un+Bacio+Lucio+Dalla" title="Accordi di Prima Dammi Un Bacio">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Prima+Dammi+Un+Bacio+Lucio+Dalla" title="Testi di Prima Dammi Un Bacio">testi</a><br>
<b>4</b>. Ho Trovato Una Rosa - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ho+Trovato+Una+Rosa+Lucio+Dalla" title="Spartiti di Ho Trovato Una Rosa">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ho+Trovato+Una+Rosa+Lucio+Dalla" title="Accordi di Ho Trovato Una Rosa">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ho+Trovato+Una+Rosa+Lucio+Dalla" title="Testi di Ho Trovato Una Rosa">testi</a><br>
<b>5</b>. Per Sempre Presente - <a target="_blank" href="http://www.google.com/search?q=spartiti+Per+Sempre+Presente+Lucio+Dalla" title="Spartiti di Per Sempre Presente">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Per+Sempre+Presente+Lucio+Dalla" title="Accordi di Per Sempre Presente">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Per+Sempre+Presente+Lucio+Dalla" title="Testi di Per Sempre Presente">testi</a><br>
<b>6</b>. Per Te - <a target="_blank" href="http://www.google.com/search?q=spartiti+Per+Te+Lucio+Dalla" title="Spartiti di Per Te">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Per+Te+Lucio+Dalla" title="Accordi di Per Te">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Per+Te+Lucio+Dalla" title="Testi di Per Te">testi</a><br>
<b>7</b>. Tu Sa' Ch'I' So - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tu+Sa%27+Ch%27I%27+So+Lucio+Dalla" title="Spartiti di Tu Sa' Ch'I' So">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tu+Sa%27+Ch%27I%27+So+Lucio+Dalla" title="Accordi di Tu Sa' Ch'I' So">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tu+Sa%27+Ch%27I%27+So+Lucio+Dalla" title="Testi di Tu Sa' Ch'I' So">testi</a><br>
<b>8</b>. Ambarabà Ciccicocò - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ambarab%E0+Ciccicoc%F2+Lucio+Dalla" title="Spartiti di Ambarabà Ciccicocò">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ambarab%E0+Ciccicoc%F2+Lucio+Dalla" title="Accordi di Ambarabà Ciccicocò">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ambarab%E0+Ciccicoc%F2+Lucio+Dalla" title="Testi di Ambarabà Ciccicocò">testi</a><br>
<b>9</b>. Putipù - <a target="_blank" href="http://www.google.com/search?q=spartiti+Putip%F9+Lucio+Dalla" title="Spartiti di Putipù">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Putip%F9+Lucio+Dalla" title="Accordi di Putipù">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Putip%F9+Lucio+Dalla" title="Testi di Putipù">testi</a><br>
<b>10</b>. Yesterday O Lady Jane? - <a target="_blank" href="http://www.google.com/search?q=spartiti+Yesterday+O+Lady+Jane%3F+Lucio+Dalla" title="Spartiti di Yesterday O Lady Jane?">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Yesterday+O+Lady+Jane%3F+Lucio+Dalla" title="Accordi di Yesterday O Lady Jane?">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Yesterday+O+Lady+Jane%3F+Lucio+Dalla" title="Testi di Yesterday O Lady Jane?">testi</a><br>
<b>11</b>. Over The Rainbow - <a target="_blank" href="http://www.google.com/search?q=spartiti+Over+The+Rainbow+Lucio+Dalla" title="Spartiti di Over The Rainbow">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Over+The+Rainbow+Lucio+Dalla" title="Accordi di Over The Rainbow">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Over+The+Rainbow+Lucio+Dalla" title="Testi di Over The Rainbow">testi</a><br>
<b>12</b>. Amore Disperato - <a target="_blank" href="http://www.google.com/search?q=spartiti+Amore+Disperato+Lucio+Dalla" title="Spartiti di Amore Disperato">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Amore+Disperato+Lucio+Dalla" title="Accordi di Amore Disperato">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Amore+Disperato+Lucio+Dalla" title="Testi di Amore Disperato">testi</a><br>
<h2>Caro Amico Ti Scrivo (2002) </h2>
<b>1</b>. 4/3/1943 - <a target="_blank" href="http://www.google.com/search?q=spartiti+4%2F3%2F1943+Lucio+Dalla" title="Spartiti di 4/3/1943">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+4%2F3%2F1943+Lucio+Dalla" title="Accordi di 4/3/1943">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+4%2F3%2F1943+Lucio+Dalla" title="Testi di 4/3/1943">testi</a><br>
<b>2</b>. Piazza Grande - <a target="_blank" href="http://www.google.com/search?q=spartiti+Piazza+Grande+Lucio+Dalla" title="Spartiti di Piazza Grande">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Piazza+Grande+Lucio+Dalla" title="Accordi di Piazza Grande">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Piazza+Grande+Lucio+Dalla" title="Testi di Piazza Grande">testi</a><br>
<b>3</b>. Com'è Profondo Il Mare - <a target="_blank" href="http://www.google.com/search?q=spartiti+Com%27%E8+Profondo+Il+Mare+Lucio+Dalla" title="Spartiti di Com'è Profondo Il Mare">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Com%27%E8+Profondo+Il+Mare+Lucio+Dalla" title="Accordi di Com'è Profondo Il Mare">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Com%27%E8+Profondo+Il+Mare+Lucio+Dalla" title="Testi di Com'è Profondo Il Mare">testi</a><br>
<b>4</b>. Disperato Erotico Stomp - <a target="_blank" href="http://www.google.com/search?q=spartiti+Disperato+Erotico+Stomp+Lucio+Dalla" title="Spartiti di Disperato Erotico Stomp">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Disperato+Erotico+Stomp+Lucio+Dalla" title="Accordi di Disperato Erotico Stomp">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Disperato+Erotico+Stomp+Lucio+Dalla" title="Testi di Disperato Erotico Stomp">testi</a><br>
<b>5</b>. L'Anno Che Verrà - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%27Anno+Che+Verr%E0+Lucio+Dalla" title="Spartiti di L'Anno Che Verrà">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%27Anno+Che+Verr%E0+Lucio+Dalla" title="Accordi di L'Anno Che Verrà">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%27Anno+Che+Verr%E0+Lucio+Dalla" title="Testi di L'Anno Che Verrà">testi</a><br>
<b>6</b>. Futura - <a target="_blank" href="http://www.google.com/search?q=spartiti+Futura+Lucio+Dalla" title="Spartiti di Futura">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Futura+Lucio+Dalla" title="Accordi di Futura">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Futura+Lucio+Dalla" title="Testi di Futura">testi</a><br>
<b>7</b>. Washington - <a target="_blank" href="http://www.google.com/search?q=spartiti+Washington+Lucio+Dalla" title="Spartiti di Washington">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Washington+Lucio+Dalla" title="Accordi di Washington">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Washington+Lucio+Dalla" title="Testi di Washington">testi</a><br>
<b>8</b>. Caruso - <a target="_blank" href="http://www.google.com/search?q=spartiti+Caruso+Lucio+Dalla" title="Spartiti di Caruso">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Caruso+Lucio+Dalla" title="Accordi di Caruso">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Caruso+Lucio+Dalla" title="Testi di Caruso">testi</a><br>
<b>9</b>. Attenti Al Lupo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Attenti+Al+Lupo+Lucio+Dalla" title="Spartiti di Attenti Al Lupo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Attenti+Al+Lupo+Lucio+Dalla" title="Accordi di Attenti Al Lupo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Attenti+Al+Lupo+Lucio+Dalla" title="Testi di Attenti Al Lupo">testi</a><br>
<b>10</b>. Apriti Cuore - <a target="_blank" href="http://www.google.com/search?q=spartiti+Apriti+Cuore+Lucio+Dalla" title="Spartiti di Apriti Cuore">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Apriti+Cuore+Lucio+Dalla" title="Accordi di Apriti Cuore">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Apriti+Cuore+Lucio+Dalla" title="Testi di Apriti Cuore">testi</a><br>
<b>11</b>. Canzone - <a target="_blank" href="http://www.google.com/search?q=spartiti+Canzone+Lucio+Dalla" title="Spartiti di Canzone">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Canzone+Lucio+Dalla" title="Accordi di Canzone">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Canzone+Lucio+Dalla" title="Testi di Canzone">testi</a><br>
<b>12</b>. Tu Non Mi Basti Mai - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tu+Non+Mi+Basti+Mai+Lucio+Dalla" title="Spartiti di Tu Non Mi Basti Mai">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tu+Non+Mi+Basti+Mai+Lucio+Dalla" title="Accordi di Tu Non Mi Basti Mai">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tu+Non+Mi+Basti+Mai+Lucio+Dalla" title="Testi di Tu Non Mi Basti Mai">testi</a><br>
<b>13</b>. Ciao - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ciao+Lucio+Dalla" title="Spartiti di Ciao">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ciao+Lucio+Dalla" title="Accordi di Ciao">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ciao+Lucio+Dalla" title="Testi di Ciao">testi</a><br>
<b>14</b>. Là - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%E0+Lucio+Dalla" title="Spartiti di Là">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%E0+Lucio+Dalla" title="Accordi di Là">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%E0+Lucio+Dalla" title="Testi di Là">testi</a><br>
<b>15</b>. Kamikaze - <a target="_blank" href="http://www.google.com/search?q=spartiti+Kamikaze+Lucio+Dalla" title="Spartiti di Kamikaze">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Kamikaze+Lucio+Dalla" title="Accordi di Kamikaze">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Kamikaze+Lucio+Dalla" title="Testi di Kamikaze">testi</a><br>
<b>16</b>. Zingaro - <a target="_blank" href="http://www.google.com/search?q=spartiti+Zingaro+Lucio+Dalla" title="Spartiti di Zingaro">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Zingaro+Lucio+Dalla" title="Accordi di Zingaro">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Zingaro+Lucio+Dalla" title="Testi di Zingaro">testi</a><br>
<h2>Luna Matana (2001) </h2>
<b>1</b>. Chi Sarò Io - <a target="_blank" href="http://www.google.com/search?q=spartiti+Chi+Sar%F2+Io+Lucio+Dalla" title="Spartiti di Chi Sarò Io">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Chi+Sar%F2+Io+Lucio+Dalla" title="Accordi di Chi Sarò Io">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Chi+Sar%F2+Io+Lucio+Dalla" title="Testi di Chi Sarò Io">testi</a><br>
<b>2</b>. Siciliano - <a target="_blank" href="http://www.google.com/search?q=spartiti+Siciliano+Lucio+Dalla" title="Spartiti di Siciliano">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Siciliano+Lucio+Dalla" title="Accordi di Siciliano">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Siciliano+Lucio+Dalla" title="Testi di Siciliano">testi</a><br>
<b>3</b>. La Strada E La Stella - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Strada+E+La+Stella+Lucio+Dalla" title="Spartiti di La Strada E La Stella">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Strada+E+La+Stella+Lucio+Dalla" title="Accordi di La Strada E La Stella">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Strada+E+La+Stella+Lucio+Dalla" title="Testi di La Strada E La Stella">testi</a><br>
<b>4</b>. Zingaro - <a target="_blank" href="http://www.google.com/search?q=spartiti+Zingaro+Lucio+Dalla" title="Spartiti di Zingaro">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Zingaro+Lucio+Dalla" title="Accordi di Zingaro">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Zingaro+Lucio+Dalla" title="Testi di Zingaro">testi</a><br>
<b>5</b>. Kamikaze - <a target="_blank" href="http://www.google.com/search?q=spartiti+Kamikaze+Lucio+Dalla" title="Spartiti di Kamikaze">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Kamikaze+Lucio+Dalla" title="Accordi di Kamikaze">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Kamikaze+Lucio+Dalla" title="Testi di Kamikaze">testi</a><br>
<b>6</b>. Serial Killer - <a target="_blank" href="http://www.google.com/search?q=spartiti+Serial+Killer+Lucio+Dalla" title="Spartiti di Serial Killer">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Serial+Killer+Lucio+Dalla" title="Accordi di Serial Killer">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Serial+Killer+Lucio+Dalla" title="Testi di Serial Killer">testi</a><br>
<b>7</b>. Domenico Sputo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Domenico+Sputo+Lucio+Dalla" title="Spartiti di Domenico Sputo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Domenico+Sputo+Lucio+Dalla" title="Accordi di Domenico Sputo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Domenico+Sputo+Lucio+Dalla" title="Testi di Domenico Sputo">testi</a><br>
<b>8</b>. Baggio... Baggio - <a target="_blank" href="http://www.google.com/search?q=spartiti+Baggio...+Baggio+Lucio+Dalla" title="Spartiti di Baggio... Baggio">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Baggio...+Baggio+Lucio+Dalla" title="Accordi di Baggio... Baggio">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Baggio...+Baggio+Lucio+Dalla" title="Testi di Baggio... Baggio">testi</a><br>
<b>9</b>. Anni Luce - <a target="_blank" href="http://www.google.com/search?q=spartiti+Anni+Luce+Lucio+Dalla" title="Spartiti di Anni Luce">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Anni+Luce+Lucio+Dalla" title="Accordi di Anni Luce">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Anni+Luce+Lucio+Dalla" title="Testi di Anni Luce">testi</a><br>
<b>10</b>. Notte Americana - <a target="_blank" href="http://www.google.com/search?q=spartiti+Notte+Americana+Lucio+Dalla" title="Spartiti di Notte Americana">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Notte+Americana+Lucio+Dalla" title="Accordi di Notte Americana">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Notte+Americana+Lucio+Dalla" title="Testi di Notte Americana">testi</a><br>
<b>11</b>. Agnese Dellecocomere - <a target="_blank" href="http://www.google.com/search?q=spartiti+Agnese+Dellecocomere+Lucio+Dalla" title="Spartiti di Agnese Dellecocomere">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Agnese+Dellecocomere+Lucio+Dalla" title="Accordi di Agnese Dellecocomere">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Agnese+Dellecocomere+Lucio+Dalla" title="Testi di Agnese Dellecocomere">testi</a><br>
<h2>Ciao (1999) </h2>
<b>1</b>. Ciao - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ciao+Lucio+Dalla" title="Spartiti di Ciao">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ciao+Lucio+Dalla" title="Accordi di Ciao">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ciao+Lucio+Dalla" title="Testi di Ciao">testi</a><br>
<b>2</b>. Non Vergognarsi Mai - <a target="_blank" href="http://www.google.com/search?q=spartiti+Non+Vergognarsi+Mai+Lucio+Dalla" title="Spartiti di Non Vergognarsi Mai">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Non+Vergognarsi+Mai+Lucio+Dalla" title="Accordi di Non Vergognarsi Mai">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Non+Vergognarsi+Mai+Lucio+Dalla" title="Testi di Non Vergognarsi Mai">testi</a><br>
<b>3</b>. Io Tra Un'Ora Sono Lì - <a target="_blank" href="http://www.google.com/search?q=spartiti+Io+Tra+Un%27Ora+Sono+L%EC+Lucio+Dalla" title="Spartiti di Io Tra Un'Ora Sono Lì">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Io+Tra+Un%27Ora+Sono+L%EC+Lucio+Dalla" title="Accordi di Io Tra Un'Ora Sono Lì">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Io+Tra+Un%27Ora+Sono+L%EC+Lucio+Dalla" title="Testi di Io Tra Un'Ora Sono Lì">testi</a><br>
<b>4</b>. Là - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%E0+Lucio+Dalla" title="Spartiti di Là">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%E0+Lucio+Dalla" title="Accordi di Là">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%E0+Lucio+Dalla" title="Testi di Là">testi</a><br>
<b>5</b>. What A Beautiful Day - <a target="_blank" href="http://www.google.com/search?q=spartiti+What+A+Beautiful+Day+Lucio+Dalla" title="Spartiti di What A Beautiful Day">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+What+A+Beautiful+Day+Lucio+Dalla" title="Accordi di What A Beautiful Day">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+What+A+Beautiful+Day+Lucio+Dalla" title="Testi di What A Beautiful Day">testi</a><br>
<b>6</b>. Trapiantoperso - <a target="_blank" href="http://www.google.com/search?q=spartiti+Trapiantoperso+Lucio+Dalla" title="Spartiti di Trapiantoperso">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Trapiantoperso+Lucio+Dalla" title="Accordi di Trapiantoperso">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Trapiantoperso+Lucio+Dalla" title="Testi di Trapiantoperso">testi</a><br>
<b>7</b>. Hotel - <a target="_blank" href="http://www.google.com/search?q=spartiti+Hotel+Lucio+Dalla" title="Spartiti di Hotel">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Hotel+Lucio+Dalla" title="Accordi di Hotel">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Hotel+Lucio+Dalla" title="Testi di Hotel">testi</a><br>
<b>8</b>. Trash - <a target="_blank" href="http://www.google.com/search?q=spartiti+Trash+Lucio+Dalla" title="Spartiti di Trash">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Trash+Lucio+Dalla" title="Accordi di Trash">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Trash+Lucio+Dalla" title="Testi di Trash">testi</a><br>
<b>9</b>. Scusa - <a target="_blank" href="http://www.google.com/search?q=spartiti+Scusa+Lucio+Dalla" title="Spartiti di Scusa">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Scusa+Lucio+Dalla" title="Accordi di Scusa">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Scusa+Lucio+Dalla" title="Testi di Scusa">testi</a><br>
<b>10</b>. 1999 - <a target="_blank" href="http://www.google.com/search?q=spartiti+1999+Lucio+Dalla" title="Spartiti di 1999">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+1999+Lucio+Dalla" title="Accordi di 1999">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+1999+Lucio+Dalla" title="Testi di 1999">testi</a><br>
<b>11</b>. Born To Be Alone - <a target="_blank" href="http://www.google.com/search?q=spartiti+Born+To+Be+Alone+Lucio+Dalla" title="Spartiti di Born To Be Alone">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Born+To+Be+Alone+Lucio+Dalla" title="Accordi di Born To Be Alone">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Born+To+Be+Alone+Lucio+Dalla" title="Testi di Born To Be Alone">testi</a><br>
<h2>Canzoni (1996) </h2>
<b>1</b>. Ayrton - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ayrton+Lucio+Dalla" title="Spartiti di Ayrton">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ayrton+Lucio+Dalla" title="Accordi di Ayrton">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ayrton+Lucio+Dalla" title="Testi di Ayrton">testi</a><br>
<b>2</b>. Canzone - <a target="_blank" href="http://www.google.com/search?q=spartiti+Canzone+Lucio+Dalla" title="Spartiti di Canzone">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Canzone+Lucio+Dalla" title="Accordi di Canzone">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Canzone+Lucio+Dalla" title="Testi di Canzone">testi</a><br>
<b>3</b>. Tu Non Mi Basti Mai - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tu+Non+Mi+Basti+Mai+Lucio+Dalla" title="Spartiti di Tu Non Mi Basti Mai">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tu+Non+Mi+Basti+Mai+Lucio+Dalla" title="Accordi di Tu Non Mi Basti Mai">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tu+Non+Mi+Basti+Mai+Lucio+Dalla" title="Testi di Tu Non Mi Basti Mai">testi</a><br>
<b>4</b>. Domani - <a target="_blank" href="http://www.google.com/search?q=spartiti+Domani+Lucio+Dalla" title="Spartiti di Domani">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Domani+Lucio+Dalla" title="Accordi di Domani">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Domani+Lucio+Dalla" title="Testi di Domani">testi</a><br>
<b>5</b>. Ballando Ballando - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ballando+Ballando+Lucio+Dalla" title="Spartiti di Ballando Ballando">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ballando+Ballando+Lucio+Dalla" title="Accordi di Ballando Ballando">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ballando+Ballando+Lucio+Dalla" title="Testi di Ballando Ballando">testi</a><br>
<b>6</b>. Sul Mondo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sul+Mondo+Lucio+Dalla" title="Spartiti di Sul Mondo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sul+Mondo+Lucio+Dalla" title="Accordi di Sul Mondo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sul+Mondo+Lucio+Dalla" title="Testi di Sul Mondo">testi</a><br>
<b>7</b>. Amici - <a target="_blank" href="http://www.google.com/search?q=spartiti+Amici+Lucio+Dalla" title="Spartiti di Amici">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Amici+Lucio+Dalla" title="Accordi di Amici">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Amici+Lucio+Dalla" title="Testi di Amici">testi</a><br>
<b>8</b>. Prendimi Così - <a target="_blank" href="http://www.google.com/search?q=spartiti+Prendimi+Cos%EC+Lucio+Dalla" title="Spartiti di Prendimi Così">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Prendimi+Cos%EC+Lucio+Dalla" title="Accordi di Prendimi Così">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Prendimi+Cos%EC+Lucio+Dalla" title="Testi di Prendimi Così">testi</a><br>
<b>9</b>. Nun Parlà - <a target="_blank" href="http://www.google.com/search?q=spartiti+Nun+Parl%E0+Lucio+Dalla" title="Spartiti di Nun Parlà">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Nun+Parl%E0+Lucio+Dalla" title="Accordi di Nun Parlà">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Nun+Parl%E0+Lucio+Dalla" title="Testi di Nun Parlà">testi</a><br>
<b>10</b>. Cosa Vuol Dire Una Lacrima - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cosa+Vuol+Dire+Una+Lacrima+Lucio+Dalla" title="Spartiti di Cosa Vuol Dire Una Lacrima">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cosa+Vuol+Dire+Una+Lacrima+Lucio+Dalla" title="Accordi di Cosa Vuol Dire Una Lacrima">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cosa+Vuol+Dire+Una+Lacrima+Lucio+Dalla" title="Testi di Cosa Vuol Dire Una Lacrima">testi</a><br>
<b>11</b>. Goodbye - <a target="_blank" href="http://www.google.com/search?q=spartiti+Goodbye+Lucio+Dalla" title="Spartiti di Goodbye">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Goodbye+Lucio+Dalla" title="Accordi di Goodbye">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Goodbye+Lucio+Dalla" title="Testi di Goodbye">testi</a><br>
<h2>Henna (1994) </h2>
<b>1</b>. Henna - <a target="_blank" href="http://www.google.com/search?q=spartiti+Henna+Lucio+Dalla" title="Spartiti di Henna">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Henna+Lucio+Dalla" title="Accordi di Henna">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Henna+Lucio+Dalla" title="Testi di Henna">testi</a><br>
<b>2</b>. Liberi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Liberi+Lucio+Dalla" title="Spartiti di Liberi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Liberi+Lucio+Dalla" title="Accordi di Liberi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Liberi+Lucio+Dalla" title="Testi di Liberi">testi</a><br>
<b>3</b>. Rispondimi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Rispondimi+Lucio+Dalla" title="Spartiti di Rispondimi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Rispondimi+Lucio+Dalla" title="Accordi di Rispondimi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Rispondimi+Lucio+Dalla" title="Testi di Rispondimi">testi</a><br>
<b>4</b>. Cinema - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cinema+Lucio+Dalla" title="Spartiti di Cinema">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cinema+Lucio+Dalla" title="Accordi di Cinema">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cinema+Lucio+Dalla" title="Testi di Cinema">testi</a><br>
<b>5</b>. Domenica - <a target="_blank" href="http://www.google.com/search?q=spartiti+Domenica+Lucio+Dalla" title="Spartiti di Domenica">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Domenica+Lucio+Dalla" title="Accordi di Domenica">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Domenica+Lucio+Dalla" title="Testi di Domenica">testi</a><br>
<b>6</b>. Merdman - <a target="_blank" href="http://www.google.com/search?q=spartiti+Merdman+Lucio+Dalla" title="Spartiti di Merdman">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Merdman+Lucio+Dalla" title="Accordi di Merdman">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Merdman+Lucio+Dalla" title="Testi di Merdman">testi</a><br>
<b>7</b>. Latin Lover - <a target="_blank" href="http://www.google.com/search?q=spartiti+Latin+Lover+Lucio+Dalla" title="Spartiti di Latin Lover">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Latin+Lover+Lucio+Dalla" title="Accordi di Latin Lover">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Latin+Lover+Lucio+Dalla" title="Testi di Latin Lover">testi</a><br>
<b>8</b>. Erosip - <a target="_blank" href="http://www.google.com/search?q=spartiti+Erosip+Lucio+Dalla" title="Spartiti di Erosip">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Erosip+Lucio+Dalla" title="Accordi di Erosip">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Erosip+Lucio+Dalla" title="Testi di Erosip">testi</a><br>
<b>9</b>. Don't Touch Me - <a target="_blank" href="http://www.google.com/search?q=spartiti+Don%27t+Touch+Me+Lucio+Dalla" title="Spartiti di Don't Touch Me">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Don%27t+Touch+Me+Lucio+Dalla" title="Accordi di Don't Touch Me">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Don%27t+Touch+Me+Lucio+Dalla" title="Testi di Don't Touch Me">testi</a><br>
<b>10</b>. Treno - <a target="_blank" href="http://www.google.com/search?q=spartiti+Treno+Lucio+Dalla" title="Spartiti di Treno">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Treno+Lucio+Dalla" title="Accordi di Treno">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Treno+Lucio+Dalla" title="Testi di Treno">testi</a><br>
<h2>Amen (1992) </h2>
<b>1</b>. Amen - <a target="_blank" href="http://www.google.com/search?q=spartiti+Amen+Lucio+Dalla" title="Spartiti di Amen">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Amen+Lucio+Dalla" title="Accordi di Amen">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Amen+Lucio+Dalla" title="Testi di Amen">testi</a><br>
<b>2</b>. Quale Allegria - <a target="_blank" href="http://www.google.com/search?q=spartiti+Quale+Allegria+Lucio+Dalla" title="Spartiti di Quale Allegria">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Quale+Allegria+Lucio+Dalla" title="Accordi di Quale Allegria">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Quale+Allegria+Lucio+Dalla" title="Testi di Quale Allegria">testi</a><br>
<b>3</b>. Denis - <a target="_blank" href="http://www.google.com/search?q=spartiti+Denis+Lucio+Dalla" title="Spartiti di Denis">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Denis+Lucio+Dalla" title="Accordi di Denis">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Denis+Lucio+Dalla" title="Testi di Denis">testi</a><br>
<b>4</b>. Felicità - <a target="_blank" href="http://www.google.com/search?q=spartiti+Felicit%E0+Lucio+Dalla" title="Spartiti di Felicità">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Felicit%E0+Lucio+Dalla" title="Accordi di Felicità">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Felicit%E0+Lucio+Dalla" title="Testi di Felicità">testi</a><br>
<b>5</b>. Nuvolari - <a target="_blank" href="http://www.google.com/search?q=spartiti+Nuvolari+Lucio+Dalla" title="Spartiti di Nuvolari">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Nuvolari+Lucio+Dalla" title="Accordi di Nuvolari">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Nuvolari+Lucio+Dalla" title="Testi di Nuvolari">testi</a><br>
<b>6</b>. Il Mostro - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Mostro+Lucio+Dalla" title="Spartiti di Il Mostro">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Mostro+Lucio+Dalla" title="Accordi di Il Mostro">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Mostro+Lucio+Dalla" title="Testi di Il Mostro">testi</a><br>
<b>7</b>. Com'è Profondo Il Mare - <a target="_blank" href="http://www.google.com/search?q=spartiti+Com%27%E8+Profondo+Il+Mare+Lucio+Dalla" title="Spartiti di Com'è Profondo Il Mare">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Com%27%E8+Profondo+Il+Mare+Lucio+Dalla" title="Accordi di Com'è Profondo Il Mare">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Com%27%E8+Profondo+Il+Mare+Lucio+Dalla" title="Testi di Com'è Profondo Il Mare">testi</a><br>
<b>8</b>. Washington - <a target="_blank" href="http://www.google.com/search?q=spartiti+Washington+Lucio+Dalla" title="Spartiti di Washington">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Washington+Lucio+Dalla" title="Accordi di Washington">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Washington+Lucio+Dalla" title="Testi di Washington">testi</a><br>
<b>9</b>. C'era Un Ragazzo - <a target="_blank" href="http://www.google.com/search?q=spartiti+C%27era+Un+Ragazzo+Lucio+Dalla" title="Spartiti di C'era Un Ragazzo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+C%27era+Un+Ragazzo+Lucio+Dalla" title="Accordi di C'era Un Ragazzo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+C%27era+Un+Ragazzo+Lucio+Dalla" title="Testi di C'era Un Ragazzo">testi</a><br>
<b>10</b>. Attenti Al Lupo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Attenti+Al+Lupo+Lucio+Dalla" title="Spartiti di Attenti Al Lupo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Attenti+Al+Lupo+Lucio+Dalla" title="Accordi di Attenti Al Lupo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Attenti+Al+Lupo+Lucio+Dalla" title="Testi di Attenti Al Lupo">testi</a><br>
<b>11</b>. Apriti Cuore - <a target="_blank" href="http://www.google.com/search?q=spartiti+Apriti+Cuore+Lucio+Dalla" title="Spartiti di Apriti Cuore">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Apriti+Cuore+Lucio+Dalla" title="Accordi di Apriti Cuore">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Apriti+Cuore+Lucio+Dalla" title="Testi di Apriti Cuore">testi</a><br>
<h2>Cambio (1990) </h2>
<b>1</b>. Attenti Al Lupo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Attenti+Al+Lupo+Lucio+Dalla" title="Spartiti di Attenti Al Lupo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Attenti+Al+Lupo+Lucio+Dalla" title="Accordi di Attenti Al Lupo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Attenti+Al+Lupo+Lucio+Dalla" title="Testi di Attenti Al Lupo">testi</a><br>
<b>2</b>. 2009 (Le Cicale E Le Stelle) - <a target="_blank" href="http://www.google.com/search?q=spartiti+2009+%28Le+Cicale+E+Le+Stelle%29+Lucio+Dalla" title="Spartiti di 2009 (Le Cicale E Le Stelle)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+2009+%28Le+Cicale+E+Le+Stelle%29+Lucio+Dalla" title="Accordi di 2009 (Le Cicale E Le Stelle)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+2009+%28Le+Cicale+E+Le+Stelle%29+Lucio+Dalla" title="Testi di 2009 (Le Cicale E Le Stelle)">testi</a><br>
<b>3</b>. E L'Amore - <a target="_blank" href="http://www.google.com/search?q=spartiti+E+L%27Amore+Lucio+Dalla" title="Spartiti di E L'Amore">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+E+L%27Amore+Lucio+Dalla" title="Accordi di E L'Amore">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+E+L%27Amore+Lucio+Dalla" title="Testi di E L'Amore">testi</a><br>
<b>4</b>. Le Rondini - <a target="_blank" href="http://www.google.com/search?q=spartiti+Le+Rondini+Lucio+Dalla" title="Spartiti di Le Rondini">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Le+Rondini+Lucio+Dalla" title="Accordi di Le Rondini">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Le+Rondini+Lucio+Dalla" title="Testi di Le Rondini">testi</a><br>
<b>5</b>. Apriti Cuore - <a target="_blank" href="http://www.google.com/search?q=spartiti+Apriti+Cuore+Lucio+Dalla" title="Spartiti di Apriti Cuore">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Apriti+Cuore+Lucio+Dalla" title="Accordi di Apriti Cuore">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Apriti+Cuore+Lucio+Dalla" title="Testi di Apriti Cuore">testi</a><br>
<b>6</b>. Denis - <a target="_blank" href="http://www.google.com/search?q=spartiti+Denis+Lucio+Dalla" title="Spartiti di Denis">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Denis+Lucio+Dalla" title="Accordi di Denis">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Denis+Lucio+Dalla" title="Testi di Denis">testi</a><br>
<b>7</b>. Bella - <a target="_blank" href="http://www.google.com/search?q=spartiti+Bella+Lucio+Dalla" title="Spartiti di Bella">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Bella+Lucio+Dalla" title="Accordi di Bella">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Bella+Lucio+Dalla" title="Testi di Bella">testi</a><br>
<b>8</b>. Tempo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tempo+Lucio+Dalla" title="Spartiti di Tempo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tempo+Lucio+Dalla" title="Accordi di Tempo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tempo+Lucio+Dalla" title="Testi di Tempo">testi</a><br>
<b>9</b>. Comunista - <a target="_blank" href="http://www.google.com/search?q=spartiti+Comunista+Lucio+Dalla" title="Spartiti di Comunista">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Comunista+Lucio+Dalla" title="Accordi di Comunista">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Comunista+Lucio+Dalla" title="Testi di Comunista">testi</a><br>
<h2>Dalla Morandi (1988) </h2>
<b>1</b>. Vita - <a target="_blank" href="http://www.google.com/search?q=spartiti+Vita+Lucio+Dalla" title="Spartiti di Vita">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Vita+Lucio+Dalla" title="Accordi di Vita">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Vita+Lucio+Dalla" title="Testi di Vita">testi</a><br>
<b>2</b>. Cera Un Ragazzo Che Come Me Amava I Beatles E I Rolling Stones - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cera+Un+Ragazzo+Che+Come+Me+Amava+I+Beatles+E+I+Rolling+Stones+Lucio+Dalla" title="Spartiti di Cera Un Ragazzo Che Come Me Amava I Beatles E I Rolling Stones">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cera+Un+Ragazzo+Che+Come+Me+Amava+I+Beatles+E+I+Rolling+Stones+Lucio+Dalla" title="Accordi di Cera Un Ragazzo Che Come Me Amava I Beatles E I Rolling Stones">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cera+Un+Ragazzo+Che+Come+Me+Amava+I+Beatles+E+I+Rolling+Stones+Lucio+Dalla" title="Testi di Cera Un Ragazzo Che Come Me Amava I Beatles E I Rolling Stones">testi</a><br>
<b>3</b>. Dimmi Dimmi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dimmi+Dimmi+Lucio+Dalla" title="Spartiti di Dimmi Dimmi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dimmi+Dimmi+Lucio+Dalla" title="Accordi di Dimmi Dimmi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dimmi+Dimmi+Lucio+Dalla" title="Testi di Dimmi Dimmi">testi</a><br>
<b>4</b>. Chiedi Chi Erano I Beatles - <a target="_blank" href="http://www.google.com/search?q=spartiti+Chiedi+Chi+Erano+I+Beatles+Lucio+Dalla" title="Spartiti di Chiedi Chi Erano I Beatles">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Chiedi+Chi+Erano+I+Beatles+Lucio+Dalla" title="Accordi di Chiedi Chi Erano I Beatles">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Chiedi+Chi+Erano+I+Beatles+Lucio+Dalla" title="Testi di Chiedi Chi Erano I Beatles">testi</a><br>
<b>5</b>. Felicità - <a target="_blank" href="http://www.google.com/search?q=spartiti+Felicit%E0+Lucio+Dalla" title="Spartiti di Felicità">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Felicit%E0+Lucio+Dalla" title="Accordi di Felicità">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Felicit%E0+Lucio+Dalla" title="Testi di Felicità">testi</a><br>
<b>6</b>. Il Cielo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Cielo+Lucio+Dalla" title="Spartiti di Il Cielo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Cielo+Lucio+Dalla" title="Accordi di Il Cielo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Cielo+Lucio+Dalla" title="Testi di Il Cielo">testi</a><br>
<b>7</b>. Il Duemila, Un Gatto E Il Re - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Duemila%2C+Un+Gatto+E+Il+Re+Lucio+Dalla" title="Spartiti di Il Duemila, Un Gatto E Il Re">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Duemila%2C+Un+Gatto+E+Il+Re+Lucio+Dalla" title="Accordi di Il Duemila, Un Gatto E Il Re">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Duemila%2C+Un+Gatto+E+Il+Re+Lucio+Dalla" title="Testi di Il Duemila, Un Gatto E Il Re">testi</a><br>
<b>8</b>. Disperati Complici - <a target="_blank" href="http://www.google.com/search?q=spartiti+Disperati+Complici+Lucio+Dalla" title="Spartiti di Disperati Complici">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Disperati+Complici+Lucio+Dalla" title="Accordi di Disperati Complici">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Disperati+Complici+Lucio+Dalla" title="Testi di Disperati Complici">testi</a><br>
<b>9</b>. Emilia - <a target="_blank" href="http://www.google.com/search?q=spartiti+Emilia+Lucio+Dalla" title="Spartiti di Emilia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Emilia+Lucio+Dalla" title="Accordi di Emilia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Emilia+Lucio+Dalla" title="Testi di Emilia">testi</a><br>
<b>10</b>. Cuori Di Gesù - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cuori+Di+Ges%F9+Lucio+Dalla" title="Spartiti di Cuori Di Gesù">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cuori+Di+Ges%F9+Lucio+Dalla" title="Accordi di Cuori Di Gesù">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cuori+Di+Ges%F9+Lucio+Dalla" title="Testi di Cuori Di Gesù">testi</a><br>
<b>11</b>. Tu Mi Entri Dentro Il Cuore - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tu+Mi+Entri+Dentro+Il+Cuore+Lucio+Dalla" title="Spartiti di Tu Mi Entri Dentro Il Cuore">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tu+Mi+Entri+Dentro+Il+Cuore+Lucio+Dalla" title="Accordi di Tu Mi Entri Dentro Il Cuore">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tu+Mi+Entri+Dentro+Il+Cuore+Lucio+Dalla" title="Testi di Tu Mi Entri Dentro Il Cuore">testi</a><br>
<b>12</b>. Il Motore Del 2000 - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Motore+Del+2000+Lucio+Dalla" title="Spartiti di Il Motore Del 2000">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Motore+Del+2000+Lucio+Dalla" title="Accordi di Il Motore Del 2000">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Motore+Del+2000+Lucio+Dalla" title="Testi di Il Motore Del 2000">testi</a><br>
<b>13</b>. Misterioso - <a target="_blank" href="http://www.google.com/search?q=spartiti+Misterioso+Lucio+Dalla" title="Spartiti di Misterioso">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Misterioso+Lucio+Dalla" title="Accordi di Misterioso">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Misterioso+Lucio+Dalla" title="Testi di Misterioso">testi</a><br>
<b>14</b>. Che Cosa Resterà Di Me - <a target="_blank" href="http://www.google.com/search?q=spartiti+Che+Cosa+Rester%E0+Di+Me+Lucio+Dalla" title="Spartiti di Che Cosa Resterà Di Me">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Che+Cosa+Rester%E0+Di+Me+Lucio+Dalla" title="Accordi di Che Cosa Resterà Di Me">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Che+Cosa+Rester%E0+Di+Me+Lucio+Dalla" title="Testi di Che Cosa Resterà Di Me">testi</a><br>
<b>15</b>. Pomeriggio In Ufficio - <a target="_blank" href="http://www.google.com/search?q=spartiti+Pomeriggio+In+Ufficio+Lucio+Dalla" title="Spartiti di Pomeriggio In Ufficio">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Pomeriggio+In+Ufficio+Lucio+Dalla" title="Accordi di Pomeriggio In Ufficio">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Pomeriggio+In+Ufficio+Lucio+Dalla" title="Testi di Pomeriggio In Ufficio">testi</a><br>
<b>16</b>. Soli Ma Splendenti - <a target="_blank" href="http://www.google.com/search?q=spartiti+Soli+Ma+Splendenti+Lucio+Dalla" title="Spartiti di Soli Ma Splendenti">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Soli+Ma+Splendenti+Lucio+Dalla" title="Accordi di Soli Ma Splendenti">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Soli+Ma+Splendenti+Lucio+Dalla" title="Testi di Soli Ma Splendenti">testi</a><br>
<b>17</b>. Amore Piccolino - <a target="_blank" href="http://www.google.com/search?q=spartiti+Amore+Piccolino+Lucio+Dalla" title="Spartiti di Amore Piccolino">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Amore+Piccolino+Lucio+Dalla" title="Accordi di Amore Piccolino">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Amore+Piccolino+Lucio+Dalla" title="Testi di Amore Piccolino">testi</a><br>
<b>18</b>. Felicità (Finale) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Felicit%E0+%28Finale%29+Lucio+Dalla" title="Spartiti di Felicità (Finale)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Felicit%E0+%28Finale%29+Lucio+Dalla" title="Accordi di Felicità (Finale)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Felicit%E0+%28Finale%29+Lucio+Dalla" title="Testi di Felicità (Finale)">testi</a><br>
<h2>In Europa (1988) </h2>
<b>1</b>. Vita - <a target="_blank" href="http://www.google.com/search?q=spartiti+Vita+Lucio+Dalla" title="Spartiti di Vita">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Vita+Lucio+Dalla" title="Accordi di Vita">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Vita+Lucio+Dalla" title="Testi di Vita">testi</a><br>
<b>2</b>. Il Motore Del 2000 - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Motore+Del+2000+Lucio+Dalla" title="Spartiti di Il Motore Del 2000">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Motore+Del+2000+Lucio+Dalla" title="Accordi di Il Motore Del 2000">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Motore+Del+2000+Lucio+Dalla" title="Testi di Il Motore Del 2000">testi</a><br>
<b>3</b>. Amore Piccolino - <a target="_blank" href="http://www.google.com/search?q=spartiti+Amore+Piccolino+Lucio+Dalla" title="Spartiti di Amore Piccolino">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Amore+Piccolino+Lucio+Dalla" title="Accordi di Amore Piccolino">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Amore+Piccolino+Lucio+Dalla" title="Testi di Amore Piccolino">testi</a><br>
<b>4</b>. Pomeriggio In Ufficio - <a target="_blank" href="http://www.google.com/search?q=spartiti+Pomeriggio+In+Ufficio+Lucio+Dalla" title="Spartiti di Pomeriggio In Ufficio">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Pomeriggio+In+Ufficio+Lucio+Dalla" title="Accordi di Pomeriggio In Ufficio">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Pomeriggio+In+Ufficio+Lucio+Dalla" title="Testi di Pomeriggio In Ufficio">testi</a><br>
<b>5</b>. Che Cosa Resterà Di Me - <a target="_blank" href="http://www.google.com/search?q=spartiti+Che+Cosa+Rester%E0+Di+Me+Lucio+Dalla" title="Spartiti di Che Cosa Resterà Di Me">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Che+Cosa+Rester%E0+Di+Me+Lucio+Dalla" title="Accordi di Che Cosa Resterà Di Me">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Che+Cosa+Rester%E0+Di+Me+Lucio+Dalla" title="Testi di Che Cosa Resterà Di Me">testi</a><br>
<b>6</b>. Dimmi Dimmi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dimmi+Dimmi+Lucio+Dalla" title="Spartiti di Dimmi Dimmi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dimmi+Dimmi+Lucio+Dalla" title="Accordi di Dimmi Dimmi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dimmi+Dimmi+Lucio+Dalla" title="Testi di Dimmi Dimmi">testi</a><br>
<b>7</b>. Chiedi Chi Erano I Beatles - <a target="_blank" href="http://www.google.com/search?q=spartiti+Chiedi+Chi+Erano+I+Beatles+Lucio+Dalla" title="Spartiti di Chiedi Chi Erano I Beatles">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Chiedi+Chi+Erano+I+Beatles+Lucio+Dalla" title="Accordi di Chiedi Chi Erano I Beatles">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Chiedi+Chi+Erano+I+Beatles+Lucio+Dalla" title="Testi di Chiedi Chi Erano I Beatles">testi</a><br>
<b>8</b>. Cuori Di Gesù - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cuori+Di+Ges%F9+Lucio+Dalla" title="Spartiti di Cuori Di Gesù">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cuori+Di+Ges%F9+Lucio+Dalla" title="Accordi di Cuori Di Gesù">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cuori+Di+Ges%F9+Lucio+Dalla" title="Testi di Cuori Di Gesù">testi</a><br>
<b>9</b>. Il Cielo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Cielo+Lucio+Dalla" title="Spartiti di Il Cielo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Cielo+Lucio+Dalla" title="Accordi di Il Cielo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Cielo+Lucio+Dalla" title="Testi di Il Cielo">testi</a><br>
<b>10</b>. Felicità - <a target="_blank" href="http://www.google.com/search?q=spartiti+Felicit%E0+Lucio+Dalla" title="Spartiti di Felicità">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Felicit%E0+Lucio+Dalla" title="Accordi di Felicità">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Felicit%E0+Lucio+Dalla" title="Testi di Felicità">testi</a><br>
<h2>Dallamericaruso (1986) </h2>
<b>1</b>. Caruso - <a target="_blank" href="http://www.google.com/search?q=spartiti+Caruso+Lucio+Dalla" title="Spartiti di Caruso">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Caruso+Lucio+Dalla" title="Accordi di Caruso">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Caruso+Lucio+Dalla" title="Testi di Caruso">testi</a><br>
<b>2</b>. Balla Balla Ballerino - <a target="_blank" href="http://www.google.com/search?q=spartiti+Balla+Balla+Ballerino+Lucio+Dalla" title="Spartiti di Balla Balla Ballerino">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Balla+Balla+Ballerino+Lucio+Dalla" title="Accordi di Balla Balla Ballerino">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Balla+Balla+Ballerino+Lucio+Dalla" title="Testi di Balla Balla Ballerino">testi</a><br>
<b>3</b>. Viaggi Organizzati - <a target="_blank" href="http://www.google.com/search?q=spartiti+Viaggi+Organizzati+Lucio+Dalla" title="Spartiti di Viaggi Organizzati">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Viaggi+Organizzati+Lucio+Dalla" title="Accordi di Viaggi Organizzati">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Viaggi+Organizzati+Lucio+Dalla" title="Testi di Viaggi Organizzati">testi</a><br>
<b>4</b>. Anna E Marco - <a target="_blank" href="http://www.google.com/search?q=spartiti+Anna+E+Marco+Lucio+Dalla" title="Spartiti di Anna E Marco">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Anna+E+Marco+Lucio+Dalla" title="Accordi di Anna E Marco">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Anna+E+Marco+Lucio+Dalla" title="Testi di Anna E Marco">testi</a><br>
<b>5</b>. Tutta La Vita - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tutta+La+Vita+Lucio+Dalla" title="Spartiti di Tutta La Vita">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tutta+La+Vita+Lucio+Dalla" title="Accordi di Tutta La Vita">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tutta+La+Vita+Lucio+Dalla" title="Testi di Tutta La Vita">testi</a><br>
<b>6</b>. Se Io Fossi Un Angelo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Se+Io+Fossi+Un+Angelo+Lucio+Dalla" title="Spartiti di Se Io Fossi Un Angelo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Se+Io+Fossi+Un+Angelo+Lucio+Dalla" title="Accordi di Se Io Fossi Un Angelo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Se+Io+Fossi+Un+Angelo+Lucio+Dalla" title="Testi di Se Io Fossi Un Angelo">testi</a><br>
<b>7</b>. Cara - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cara+Lucio+Dalla" title="Spartiti di Cara">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cara+Lucio+Dalla" title="Accordi di Cara">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cara+Lucio+Dalla" title="Testi di Cara">testi</a><br>
<b>8</b>. Washington - <a target="_blank" href="http://www.google.com/search?q=spartiti+Washington+Lucio+Dalla" title="Spartiti di Washington">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Washington+Lucio+Dalla" title="Accordi di Washington">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Washington+Lucio+Dalla" title="Testi di Washington">testi</a><br>
<b>9</b>. 4/3/1943 - <a target="_blank" href="http://www.google.com/search?q=spartiti+4%2F3%2F1943+Lucio+Dalla" title="Spartiti di 4/3/1943">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+4%2F3%2F1943+Lucio+Dalla" title="Accordi di 4/3/1943">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+4%2F3%2F1943+Lucio+Dalla" title="Testi di 4/3/1943">testi</a><br>
<b>10</b>. Futura - <a target="_blank" href="http://www.google.com/search?q=spartiti+Futura+Lucio+Dalla" title="Spartiti di Futura">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Futura+Lucio+Dalla" title="Accordi di Futura">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Futura+Lucio+Dalla" title="Testi di Futura">testi</a><br>
<b>11</b>. Stella Di Mare - <a target="_blank" href="http://www.google.com/search?q=spartiti+Stella+Di+Mare+Lucio+Dalla" title="Spartiti di Stella Di Mare">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Stella+Di+Mare+Lucio+Dalla" title="Accordi di Stella Di Mare">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Stella+Di+Mare+Lucio+Dalla" title="Testi di Stella Di Mare">testi</a><br>
<b>12</b>. L'Anno Che Verrà - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%27Anno+Che+Verr%E0+Lucio+Dalla" title="Spartiti di L'Anno Che Verrà">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%27Anno+Che+Verr%E0+Lucio+Dalla" title="Accordi di L'Anno Che Verrà">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%27Anno+Che+Verr%E0+Lucio+Dalla" title="Testi di L'Anno Che Verrà">testi</a><br>
<h2>Bugie (1985) </h2>
<b>1</b>. Se Io Fossi Un Angelo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Se+Io+Fossi+Un+Angelo+Lucio+Dalla" title="Spartiti di Se Io Fossi Un Angelo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Se+Io+Fossi+Un+Angelo+Lucio+Dalla" title="Accordi di Se Io Fossi Un Angelo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Se+Io+Fossi+Un+Angelo+Lucio+Dalla" title="Testi di Se Io Fossi Un Angelo">testi</a><br>
<b>2</b>. Soli Io E Te - <a target="_blank" href="http://www.google.com/search?q=spartiti+Soli+Io+E+Te+Lucio+Dalla" title="Spartiti di Soli Io E Te">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Soli+Io+E+Te+Lucio+Dalla" title="Accordi di Soli Io E Te">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Soli+Io+E+Te+Lucio+Dalla" title="Testi di Soli Io E Te">testi</a><br>
<b>3</b>. Luk - <a target="_blank" href="http://www.google.com/search?q=spartiti+Luk+Lucio+Dalla" title="Spartiti di Luk">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Luk+Lucio+Dalla" title="Accordi di Luk">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Luk+Lucio+Dalla" title="Testi di Luk">testi</a><br>
<b>4</b>. Tania Delcirco - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tania+Delcirco+Lucio+Dalla" title="Spartiti di Tania Delcirco">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tania+Delcirco+Lucio+Dalla" title="Accordi di Tania Delcirco">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tania+Delcirco+Lucio+Dalla" title="Testi di Tania Delcirco">testi</a><br>
<b>5</b>. Scusami Tanto Ma Ho Solo Te - <a target="_blank" href="http://www.google.com/search?q=spartiti+Scusami+Tanto+Ma+Ho+Solo+Te+Lucio+Dalla" title="Spartiti di Scusami Tanto Ma Ho Solo Te">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Scusami+Tanto+Ma+Ho+Solo+Te+Lucio+Dalla" title="Accordi di Scusami Tanto Ma Ho Solo Te">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Scusami+Tanto+Ma+Ho+Solo+Te+Lucio+Dalla" title="Testi di Scusami Tanto Ma Ho Solo Te">testi</a><br>
<b>6</b>. Chissà Se Lo Sai - <a target="_blank" href="http://www.google.com/search?q=spartiti+Chiss%E0+Se+Lo+Sai+Lucio+Dalla" title="Spartiti di Chissà Se Lo Sai">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Chiss%E0+Se+Lo+Sai+Lucio+Dalla" title="Accordi di Chissà Se Lo Sai">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Chiss%E0+Se+Lo+Sai+Lucio+Dalla" title="Testi di Chissà Se Lo Sai">testi</a><br>
<b>7</b>. Ribot - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ribot+Lucio+Dalla" title="Spartiti di Ribot">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ribot+Lucio+Dalla" title="Accordi di Ribot">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ribot+Lucio+Dalla" title="Testi di Ribot">testi</a><br>
<b>8</b>. Navigando - <a target="_blank" href="http://www.google.com/search?q=spartiti+Navigando+Lucio+Dalla" title="Spartiti di Navigando">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Navigando+Lucio+Dalla" title="Accordi di Navigando">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Navigando+Lucio+Dalla" title="Testi di Navigando">testi</a><br>
<h2>Viaggi Organizzati (1984) </h2>
<b>1</b>. Tutta La Vita - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tutta+La+Vita+Lucio+Dalla" title="Spartiti di Tutta La Vita">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tutta+La+Vita+Lucio+Dalla" title="Accordi di Tutta La Vita">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tutta+La+Vita+Lucio+Dalla" title="Testi di Tutta La Vita">testi</a><br>
<b>2</b>. Toro - <a target="_blank" href="http://www.google.com/search?q=spartiti+Toro+Lucio+Dalla" title="Spartiti di Toro">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Toro+Lucio+Dalla" title="Accordi di Toro">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Toro+Lucio+Dalla" title="Testi di Toro">testi</a><br>
<b>3</b>. Aquila - <a target="_blank" href="http://www.google.com/search?q=spartiti+Aquila+Lucio+Dalla" title="Spartiti di Aquila">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Aquila+Lucio+Dalla" title="Accordi di Aquila">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Aquila+Lucio+Dalla" title="Testi di Aquila">testi</a><br>
<b>4</b>. 60.000.000 Di Anni Fa - <a target="_blank" href="http://www.google.com/search?q=spartiti+60.000.000+Di+Anni+Fa+Lucio+Dalla" title="Spartiti di 60.000.000 Di Anni Fa">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+60.000.000+Di+Anni+Fa+Lucio+Dalla" title="Accordi di 60.000.000 Di Anni Fa">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+60.000.000+Di+Anni+Fa+Lucio+Dalla" title="Testi di 60.000.000 Di Anni Fa">testi</a><br>
<b>5</b>. Stornello - <a target="_blank" href="http://www.google.com/search?q=spartiti+Stornello+Lucio+Dalla" title="Spartiti di Stornello">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Stornello+Lucio+Dalla" title="Accordi di Stornello">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Stornello+Lucio+Dalla" title="Testi di Stornello">testi</a><br>
<b>6</b>. Viaggi Organizzati - <a target="_blank" href="http://www.google.com/search?q=spartiti+Viaggi+Organizzati+Lucio+Dalla" title="Spartiti di Viaggi Organizzati">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Viaggi+Organizzati+Lucio+Dalla" title="Accordi di Viaggi Organizzati">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Viaggi+Organizzati+Lucio+Dalla" title="Testi di Viaggi Organizzati">testi</a><br>
<b>7</b>. Washington - <a target="_blank" href="http://www.google.com/search?q=spartiti+Washington+Lucio+Dalla" title="Spartiti di Washington">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Washington+Lucio+Dalla" title="Accordi di Washington">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Washington+Lucio+Dalla" title="Testi di Washington">testi</a><br>
<b>8</b>. Tu Come Eri - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tu+Come+Eri+Lucio+Dalla" title="Spartiti di Tu Come Eri">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tu+Come+Eri+Lucio+Dalla" title="Accordi di Tu Come Eri">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tu+Come+Eri+Lucio+Dalla" title="Testi di Tu Come Eri">testi</a><br>
<h2>1983 (1983) </h2>
<b>1</b>. 1983 - <a target="_blank" href="http://www.google.com/search?q=spartiti+1983+Lucio+Dalla" title="Spartiti di 1983">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+1983+Lucio+Dalla" title="Accordi di 1983">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+1983+Lucio+Dalla" title="Testi di 1983">testi</a><br>
<b>2</b>. Pecorella - <a target="_blank" href="http://www.google.com/search?q=spartiti+Pecorella+Lucio+Dalla" title="Spartiti di Pecorella">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Pecorella+Lucio+Dalla" title="Accordi di Pecorella">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Pecorella+Lucio+Dalla" title="Testi di Pecorella">testi</a><br>
<b>3</b>. L'altra Parte Del Mondo - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%27altra+Parte+Del+Mondo+Lucio+Dalla" title="Spartiti di L'altra Parte Del Mondo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%27altra+Parte+Del+Mondo+Lucio+Dalla" title="Accordi di L'altra Parte Del Mondo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%27altra+Parte+Del+Mondo+Lucio+Dalla" title="Testi di L'altra Parte Del Mondo">testi</a><br>
<b>4</b>. Camion - <a target="_blank" href="http://www.google.com/search?q=spartiti+Camion+Lucio+Dalla" title="Spartiti di Camion">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Camion+Lucio+Dalla" title="Accordi di Camion">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Camion+Lucio+Dalla" title="Testi di Camion">testi</a><br>
<b>5</b>. Noi Come Voi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Noi+Come+Voi+Lucio+Dalla" title="Spartiti di Noi Come Voi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Noi+Come+Voi+Lucio+Dalla" title="Accordi di Noi Come Voi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Noi+Come+Voi+Lucio+Dalla" title="Testi di Noi Come Voi">testi</a><br>
<b>6</b>. Stronzo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Stronzo+Lucio+Dalla" title="Spartiti di Stronzo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Stronzo+Lucio+Dalla" title="Accordi di Stronzo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Stronzo+Lucio+Dalla" title="Testi di Stronzo">testi</a><br>
<b>7</b>. Solo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Solo+Lucio+Dalla" title="Spartiti di Solo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Solo+Lucio+Dalla" title="Accordi di Solo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Solo+Lucio+Dalla" title="Testi di Solo">testi</a><br>
<h2>Lucio Dalla (1981) </h2>
<b>1</b>. Telefonami Tra Vent'Anni - <a target="_blank" href="http://www.google.com/search?q=spartiti+Telefonami+Tra+Vent%27Anni+Lucio+Dalla" title="Spartiti di Telefonami Tra Vent'Anni">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Telefonami+Tra+Vent%27Anni+Lucio+Dalla" title="Accordi di Telefonami Tra Vent'Anni">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Telefonami+Tra+Vent%27Anni+Lucio+Dalla" title="Testi di Telefonami Tra Vent'Anni">testi</a><br>
<b>2</b>. Madonna Disperazione - <a target="_blank" href="http://www.google.com/search?q=spartiti+Madonna+Disperazione+Lucio+Dalla" title="Spartiti di Madonna Disperazione">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Madonna+Disperazione+Lucio+Dalla" title="Accordi di Madonna Disperazione">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Madonna+Disperazione+Lucio+Dalla" title="Testi di Madonna Disperazione">testi</a><br>
<b>3</b>. Ciao A Te - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ciao+A+Te+Lucio+Dalla" title="Spartiti di Ciao A Te">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ciao+A+Te+Lucio+Dalla" title="Accordi di Ciao A Te">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ciao+A+Te+Lucio+Dalla" title="Testi di Ciao A Te">testi</a><br>
<b>4</b>. You've Got A Friend - <a target="_blank" href="http://www.google.com/search?q=spartiti+You%27ve+Got+A+Friend+Lucio+Dalla" title="Spartiti di You've Got A Friend">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+You%27ve+Got+A+Friend+Lucio+Dalla" title="Accordi di You've Got A Friend">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+You%27ve+Got+A+Friend+Lucio+Dalla" title="Testi di You've Got A Friend">testi</a><br>
<h2>Dalla (1980) </h2>
<b>1</b>. Balla Balla Ballerino - <a target="_blank" href="http://www.google.com/search?q=spartiti+Balla+Balla+Ballerino+Lucio+Dalla" title="Spartiti di Balla Balla Ballerino">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Balla+Balla+Ballerino+Lucio+Dalla" title="Accordi di Balla Balla Ballerino">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Balla+Balla+Ballerino+Lucio+Dalla" title="Testi di Balla Balla Ballerino">testi</a><br>
<b>2</b>. Il Parco Della Luna - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Parco+Della+Luna+Lucio+Dalla" title="Spartiti di Il Parco Della Luna">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Parco+Della+Luna+Lucio+Dalla" title="Accordi di Il Parco Della Luna">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Parco+Della+Luna+Lucio+Dalla" title="Testi di Il Parco Della Luna">testi</a><br>
<b>3</b>. La Sera Dei Miracoli - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Sera+Dei+Miracoli+Lucio+Dalla" title="Spartiti di La Sera Dei Miracoli">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Sera+Dei+Miracoli+Lucio+Dalla" title="Accordi di La Sera Dei Miracoli">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Sera+Dei+Miracoli+Lucio+Dalla" title="Testi di La Sera Dei Miracoli">testi</a><br>
<b>4</b>. Mambo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Mambo+Lucio+Dalla" title="Spartiti di Mambo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Mambo+Lucio+Dalla" title="Accordi di Mambo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Mambo+Lucio+Dalla" title="Testi di Mambo">testi</a><br>
<b>5</b>. Meri Luis - <a target="_blank" href="http://www.google.com/search?q=spartiti+Meri+Luis+Lucio+Dalla" title="Spartiti di Meri Luis">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Meri+Luis+Lucio+Dalla" title="Accordi di Meri Luis">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Meri+Luis+Lucio+Dalla" title="Testi di Meri Luis">testi</a><br>
<b>6</b>. Cara - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cara+Lucio+Dalla" title="Spartiti di Cara">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cara+Lucio+Dalla" title="Accordi di Cara">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cara+Lucio+Dalla" title="Testi di Cara">testi</a><br>
<b>7</b>. Siamo Dei - <a target="_blank" href="http://www.google.com/search?q=spartiti+Siamo+Dei+Lucio+Dalla" title="Spartiti di Siamo Dei">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Siamo+Dei+Lucio+Dalla" title="Accordi di Siamo Dei">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Siamo+Dei+Lucio+Dalla" title="Testi di Siamo Dei">testi</a><br>
<b>8</b>. Futura - <a target="_blank" href="http://www.google.com/search?q=spartiti+Futura+Lucio+Dalla" title="Spartiti di Futura">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Futura+Lucio+Dalla" title="Accordi di Futura">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Futura+Lucio+Dalla" title="Testi di Futura">testi</a><br>
<h2><a href="<?php echo "$base_website_address/$spartiti_dir" ?>/index.html" title="Trova accordi, spartiti, tablature e testi di tantissimi artisti">Torna all'indice degli artisti</a></h2>
