<!--
title: Trova spartiti per chitarra, accordi, testi e tablature di Irene Grandi. Discografia Irene Grandi.
description: Trova tutti gli spartiti, accordi, testi e tablature di Irene Grandi. Discografia Irene Grandi.
keywords: Discografia, Irene Grandi, spartiti, accordi, testi, tablature
template: tablature
-->
<h1>Trova spartiti per chitarra, accordi, testi e tablature di Irene Grandi</h1><h2>Leggere gli spartiti per chitarra, gli accordi e le tablature:</h2>
<?php require("tabdescription.php"); ?>
<?php require("adsense_leaderboard.php"); ?>
<h2>Discografia Irene Grandi:</h2>
<h2>Indelebile (2005) </h2>
<b>1</b>. Lasciala Andare - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lasciala+Andare+Irene+Grandi" title="Spartiti di Lasciala Andare">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lasciala+Andare+Irene+Grandi" title="Accordi di Lasciala Andare">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lasciala+Andare+Irene+Grandi" title="Testi di Lasciala Andare">testi</a><br>
<b>2</b>. La Mia Teoria - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Mia+Teoria+Irene+Grandi" title="Spartiti di La Mia Teoria">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Mia+Teoria+Irene+Grandi" title="Accordi di La Mia Teoria">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Mia+Teoria+Irene+Grandi" title="Testi di La Mia Teoria">testi</a><br>
<b>3</b>. La Danza Del Sole - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Danza+Del+Sole+Irene+Grandi" title="Spartiti di La Danza Del Sole">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Danza+Del+Sole+Irene+Grandi" title="Accordi di La Danza Del Sole">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Danza+Del+Sole+Irene+Grandi" title="Testi di La Danza Del Sole">testi</a><br>
<b>4</b>. Non Resisto - <a target="_blank" href="http://www.google.com/search?q=spartiti+Non+Resisto+Irene+Grandi" title="Spartiti di Non Resisto">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Non+Resisto+Irene+Grandi" title="Accordi di Non Resisto">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Non+Resisto+Irene+Grandi" title="Testi di Non Resisto">testi</a><br>
<b>5</b>. Mille Volte - <a target="_blank" href="http://www.google.com/search?q=spartiti+Mille+Volte+Irene+Grandi" title="Spartiti di Mille Volte">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Mille+Volte+Irene+Grandi" title="Accordi di Mille Volte">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Mille+Volte+Irene+Grandi" title="Testi di Mille Volte">testi</a><br>
<b>6</b>. È In Te - <a target="_blank" href="http://www.google.com/search?q=spartiti+%C8+In+Te+Irene+Grandi" title="Spartiti di È In Te">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+%C8+In+Te+Irene+Grandi" title="Accordi di È In Te">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+%C8+In+Te+Irene+Grandi" title="Testi di È In Te">testi</a><br>
<b>7</b>. Buongiorno Blu - <a target="_blank" href="http://www.google.com/search?q=spartiti+Buongiorno+Blu+Irene+Grandi" title="Spartiti di Buongiorno Blu">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Buongiorno+Blu+Irene+Grandi" title="Accordi di Buongiorno Blu">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Buongiorno+Blu+Irene+Grandi" title="Testi di Buongiorno Blu">testi</a><br>
<b>8</b>. Lady Picche - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lady+Picche+Irene+Grandi" title="Spartiti di Lady Picche">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lady+Picche+Irene+Grandi" title="Accordi di Lady Picche">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lady+Picche+Irene+Grandi" title="Testi di Lady Picche">testi</a><br>
<b>9</b>. Pensami - <a target="_blank" href="http://www.google.com/search?q=spartiti+Pensami+Irene+Grandi" title="Spartiti di Pensami">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Pensami+Irene+Grandi" title="Accordi di Pensami">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Pensami+Irene+Grandi" title="Testi di Pensami">testi</a><br>
<b>10</b>. Sciò - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sci%F2+Irene+Grandi" title="Spartiti di Sciò">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sci%F2+Irene+Grandi" title="Accordi di Sciò">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sci%F2+Irene+Grandi" title="Testi di Sciò">testi</a><br>
<b>11</b>. Santissima Janis - <a target="_blank" href="http://www.google.com/search?q=spartiti+Santissima+Janis+Irene+Grandi" title="Spartiti di Santissima Janis">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Santissima+Janis+Irene+Grandi" title="Accordi di Santissima Janis">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Santissima+Janis+Irene+Grandi" title="Testi di Santissima Janis">testi</a><br>
<b>12</b>. Resist You - <a target="_blank" href="http://www.google.com/search?q=spartiti+Resist+You+Irene+Grandi" title="Spartiti di Resist You">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Resist+You+Irene+Grandi" title="Accordi di Resist You">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Resist+You+Irene+Grandi" title="Testi di Resist You">testi</a><br>
<b>13</b>. È In Te (Ghost Track) - <a target="_blank" href="http://www.google.com/search?q=spartiti+%C8+In+Te+%28Ghost+Track%29+Irene+Grandi" title="Spartiti di È In Te (Ghost Track)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+%C8+In+Te+%28Ghost+Track%29+Irene+Grandi" title="Accordi di È In Te (Ghost Track)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+%C8+In+Te+%28Ghost+Track%29+Irene+Grandi" title="Testi di È In Te (Ghost Track)">testi</a><br>
<h2>Prima Di Partire (2003) </h2>
<b>1</b>. Prima Di Partire Per Un Lungo Viaggio - <a target="_blank" href="http://www.google.com/search?q=spartiti+Prima+Di+Partire+Per+Un+Lungo+Viaggio+Irene+Grandi" title="Spartiti di Prima Di Partire Per Un Lungo Viaggio">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Prima+Di+Partire+Per+Un+Lungo+Viaggio+Irene+Grandi" title="Accordi di Prima Di Partire Per Un Lungo Viaggio">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Prima+Di+Partire+Per+Un+Lungo+Viaggio+Irene+Grandi" title="Testi di Prima Di Partire Per Un Lungo Viaggio">testi</a><br>
<b>2</b>. Oltre - <a target="_blank" href="http://www.google.com/search?q=spartiti+Oltre+Irene+Grandi" title="Spartiti di Oltre">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Oltre+Irene+Grandi" title="Accordi di Oltre">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Oltre+Irene+Grandi" title="Testi di Oltre">testi</a><br>
<b>3</b>. Il Tuo Cuore E' Il Mio Letto - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Tuo+Cuore+E%27+Il+Mio+Letto+Irene+Grandi" title="Spartiti di Il Tuo Cuore E' Il Mio Letto">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Tuo+Cuore+E%27+Il+Mio+Letto+Irene+Grandi" title="Accordi di Il Tuo Cuore E' Il Mio Letto">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Tuo+Cuore+E%27+Il+Mio+Letto+Irene+Grandi" title="Testi di Il Tuo Cuore E' Il Mio Letto">testi</a><br>
<b>4</b>. Ninna Nanna - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ninna+Nanna+Irene+Grandi" title="Spartiti di Ninna Nanna">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ninna+Nanna+Irene+Grandi" title="Accordi di Ninna Nanna">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ninna+Nanna+Irene+Grandi" title="Testi di Ninna Nanna">testi</a><br>
<b>5</b>. Buon Compleanno - <a target="_blank" href="http://www.google.com/search?q=spartiti+Buon+Compleanno+Irene+Grandi" title="Spartiti di Buon Compleanno">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Buon+Compleanno+Irene+Grandi" title="Accordi di Buon Compleanno">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Buon+Compleanno+Irene+Grandi" title="Testi di Buon Compleanno">testi</a><br>
<b>6</b>. La Domenica 69 - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Domenica+69+Irene+Grandi" title="Spartiti di La Domenica 69">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Domenica+69+Irene+Grandi" title="Accordi di La Domenica 69">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Domenica+69+Irene+Grandi" title="Testi di La Domenica 69">testi</a><br>
<b>7</b>. E' Solo Un Sogno - <a target="_blank" href="http://www.google.com/search?q=spartiti+E%27+Solo+Un+Sogno+Irene+Grandi" title="Spartiti di E' Solo Un Sogno">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+E%27+Solo+Un+Sogno+Irene+Grandi" title="Accordi di E' Solo Un Sogno">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+E%27+Solo+Un+Sogno+Irene+Grandi" title="Testi di E' Solo Un Sogno">testi</a><br>
<b>8</b>. Io Bucolico - <a target="_blank" href="http://www.google.com/search?q=spartiti+Io+Bucolico+Irene+Grandi" title="Spartiti di Io Bucolico">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Io+Bucolico+Irene+Grandi" title="Accordi di Io Bucolico">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Io+Bucolico+Irene+Grandi" title="Testi di Io Bucolico">testi</a><br>
<b>9</b>. Matra Simca Rosa - <a target="_blank" href="http://www.google.com/search?q=spartiti+Matra+Simca+Rosa+Irene+Grandi" title="Spartiti di Matra Simca Rosa">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Matra+Simca+Rosa+Irene+Grandi" title="Accordi di Matra Simca Rosa">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Matra+Simca+Rosa+Irene+Grandi" title="Testi di Matra Simca Rosa">testi</a><br>
<b>10</b>. Nuvola Bianca - <a target="_blank" href="http://www.google.com/search?q=spartiti+Nuvola+Bianca+Irene+Grandi" title="Spartiti di Nuvola Bianca">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Nuvola+Bianca+Irene+Grandi" title="Accordi di Nuvola Bianca">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Nuvola+Bianca+Irene+Grandi" title="Testi di Nuvola Bianca">testi</a><br>
<h2>Irek (2001) </h2>
<b>1</b>. Per Fare L'Amore - <a target="_blank" href="http://www.google.com/search?q=spartiti+Per+Fare+L%27Amore+Irene+Grandi" title="Spartiti di Per Fare L'Amore">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Per+Fare+L%27Amore+Irene+Grandi" title="Accordi di Per Fare L'Amore">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Per+Fare+L%27Amore+Irene+Grandi" title="Testi di Per Fare L'Amore">testi</a><br>
<b>2</b>. Tutta Diversa (Come Mi Vuoi) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tutta+Diversa+%28Come+Mi+Vuoi%29+Irene+Grandi" title="Spartiti di Tutta Diversa (Come Mi Vuoi)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tutta+Diversa+%28Come+Mi+Vuoi%29+Irene+Grandi" title="Accordi di Tutta Diversa (Come Mi Vuoi)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tutta+Diversa+%28Come+Mi+Vuoi%29+Irene+Grandi" title="Testi di Tutta Diversa (Come Mi Vuoi)">testi</a><br>
<b>3</b>. Sconvolto Così - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sconvolto+Cos%EC+Irene+Grandi" title="Spartiti di Sconvolto Così">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sconvolto+Cos%EC+Irene+Grandi" title="Accordi di Sconvolto Così">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sconvolto+Cos%EC+Irene+Grandi" title="Testi di Sconvolto Così">testi</a><br>
<b>4</b>. La Tua Ragazza Sempre - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Tua+Ragazza+Sempre+Irene+Grandi" title="Spartiti di La Tua Ragazza Sempre">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Tua+Ragazza+Sempre+Irene+Grandi" title="Accordi di La Tua Ragazza Sempre">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Tua+Ragazza+Sempre+Irene+Grandi" title="Testi di La Tua Ragazza Sempre">testi</a><br>
<b>5</b>. Dolcissimo Amore - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dolcissimo+Amore+Irene+Grandi" title="Spartiti di Dolcissimo Amore">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dolcissimo+Amore+Irene+Grandi" title="Accordi di Dolcissimo Amore">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dolcissimo+Amore+Irene+Grandi" title="Testi di Dolcissimo Amore">testi</a><br>
<b>6</b>. Fuori - <a target="_blank" href="http://www.google.com/search?q=spartiti+Fuori+Irene+Grandi" title="Spartiti di Fuori">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Fuori+Irene+Grandi" title="Accordi di Fuori">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Fuori+Irene+Grandi" title="Testi di Fuori">testi</a><br>
<b>7</b>. Che Vita E' - <a target="_blank" href="http://www.google.com/search?q=spartiti+Che+Vita+E%27+Irene+Grandi" title="Spartiti di Che Vita E'">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Che+Vita+E%27+Irene+Grandi" title="Accordi di Che Vita E'">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Che+Vita+E%27+Irene+Grandi" title="Testi di Che Vita E'">testi</a><br>
<b>8</b>. 8 E 1/2 - <a target="_blank" href="http://www.google.com/search?q=spartiti+8+E+1%2F2+Irene+Grandi" title="Spartiti di 8 E 1/2">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+8+E+1%2F2+Irene+Grandi" title="Accordi di 8 E 1/2">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+8+E+1%2F2+Irene+Grandi" title="Testi di 8 E 1/2">testi</a><br>
<b>9</b>. Un Motivo Maledetto - <a target="_blank" href="http://www.google.com/search?q=spartiti+Un+Motivo+Maledetto+Irene+Grandi" title="Spartiti di Un Motivo Maledetto">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Un+Motivo+Maledetto+Irene+Grandi" title="Accordi di Un Motivo Maledetto">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Un+Motivo+Maledetto+Irene+Grandi" title="Testi di Un Motivo Maledetto">testi</a><br>
<b>10</b>. T.V.B. - <a target="_blank" href="http://www.google.com/search?q=spartiti+T.V.B.+Irene+Grandi" title="Spartiti di T.V.B.">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+T.V.B.+Irene+Grandi" title="Accordi di T.V.B.">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+T.V.B.+Irene+Grandi" title="Testi di T.V.B.">testi</a><br>
<b>11</b>. Bum Bum - <a target="_blank" href="http://www.google.com/search?q=spartiti+Bum+Bum+Irene+Grandi" title="Spartiti di Bum Bum">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Bum+Bum+Irene+Grandi" title="Accordi di Bum Bum">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Bum+Bum+Irene+Grandi" title="Testi di Bum Bum">testi</a><br>
<b>12</b>. Vai Vai Vai - <a target="_blank" href="http://www.google.com/search?q=spartiti+Vai+Vai+Vai+Irene+Grandi" title="Spartiti di Vai Vai Vai">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Vai+Vai+Vai+Irene+Grandi" title="Accordi di Vai Vai Vai">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Vai+Vai+Vai+Irene+Grandi" title="Testi di Vai Vai Vai">testi</a><br>
<b>13</b>. Eccezionale - <a target="_blank" href="http://www.google.com/search?q=spartiti+Eccezionale+Irene+Grandi" title="Spartiti di Eccezionale">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Eccezionale+Irene+Grandi" title="Accordi di Eccezionale">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Eccezionale+Irene+Grandi" title="Testi di Eccezionale">testi</a><br>
<b>14</b>. In Vacanza Da Una Vita - <a target="_blank" href="http://www.google.com/search?q=spartiti+In+Vacanza+Da+Una+Vita+Irene+Grandi" title="Spartiti di In Vacanza Da Una Vita">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+In+Vacanza+Da+Una+Vita+Irene+Grandi" title="Accordi di In Vacanza Da Una Vita">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+In+Vacanza+Da+Una+Vita+Irene+Grandi" title="Testi di In Vacanza Da Una Vita">testi</a><br>
<b>15</b>. Cose Da Grandi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cose+Da+Grandi+Irene+Grandi" title="Spartiti di Cose Da Grandi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cose+Da+Grandi+Irene+Grandi" title="Accordi di Cose Da Grandi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cose+Da+Grandi+Irene+Grandi" title="Testi di Cose Da Grandi">testi</a><br>
<h2>Verde Rosso E Blu (1999) </h2>
<b>1</b>. Eccezionale - <a target="_blank" href="http://www.google.com/search?q=spartiti+Eccezionale+Irene+Grandi" title="Spartiti di Eccezionale">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Eccezionale+Irene+Grandi" title="Accordi di Eccezionale">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Eccezionale+Irene+Grandi" title="Testi di Eccezionale">testi</a><br>
<b>2</b>. Verde Rosso E Blu - <a target="_blank" href="http://www.google.com/search?q=spartiti+Verde+Rosso+E+Blu+Irene+Grandi" title="Spartiti di Verde Rosso E Blu">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Verde+Rosso+E+Blu+Irene+Grandi" title="Accordi di Verde Rosso E Blu">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Verde+Rosso+E+Blu+Irene+Grandi" title="Testi di Verde Rosso E Blu">testi</a><br>
<b>3</b>. Tutta Diversa (Come Mi Vuoi) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tutta+Diversa+%28Come+Mi+Vuoi%29+Irene+Grandi" title="Spartiti di Tutta Diversa (Come Mi Vuoi)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tutta+Diversa+%28Come+Mi+Vuoi%29+Irene+Grandi" title="Accordi di Tutta Diversa (Come Mi Vuoi)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tutta+Diversa+%28Come+Mi+Vuoi%29+Irene+Grandi" title="Testi di Tutta Diversa (Come Mi Vuoi)">testi</a><br>
<b>4</b>. Sto Peggiorando - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sto+Peggiorando+Irene+Grandi" title="Spartiti di Sto Peggiorando">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sto+Peggiorando+Irene+Grandi" title="Accordi di Sto Peggiorando">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sto+Peggiorando+Irene+Grandi" title="Testi di Sto Peggiorando">testi</a><br>
<b>5</b>. Francesco - <a target="_blank" href="http://www.google.com/search?q=spartiti+Francesco+Irene+Grandi" title="Spartiti di Francesco">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Francesco+Irene+Grandi" title="Accordi di Francesco">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Francesco+Irene+Grandi" title="Testi di Francesco">testi</a><br>
<b>6</b>. Limbo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Limbo+Irene+Grandi" title="Spartiti di Limbo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Limbo+Irene+Grandi" title="Accordi di Limbo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Limbo+Irene+Grandi" title="Testi di Limbo">testi</a><br>
<b>7</b>. Pettine E Spazzola - <a target="_blank" href="http://www.google.com/search?q=spartiti+Pettine+E+Spazzola+Irene+Grandi" title="Spartiti di Pettine E Spazzola">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Pettine+E+Spazzola+Irene+Grandi" title="Accordi di Pettine E Spazzola">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Pettine+E+Spazzola+Irene+Grandi" title="Testi di Pettine E Spazzola">testi</a><br>
<b>8</b>. Contatto - <a target="_blank" href="http://www.google.com/search?q=spartiti+Contatto+Irene+Grandi" title="Spartiti di Contatto">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Contatto+Irene+Grandi" title="Accordi di Contatto">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Contatto+Irene+Grandi" title="Testi di Contatto">testi</a><br>
<b>9</b>. Che Fatica Si Fa A Cambiare Vita - <a target="_blank" href="http://www.google.com/search?q=spartiti+Che+Fatica+Si+Fa+A+Cambiare+Vita+Irene+Grandi" title="Spartiti di Che Fatica Si Fa A Cambiare Vita">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Che+Fatica+Si+Fa+A+Cambiare+Vita+Irene+Grandi" title="Accordi di Che Fatica Si Fa A Cambiare Vita">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Che+Fatica+Si+Fa+A+Cambiare+Vita+Irene+Grandi" title="Testi di Che Fatica Si Fa A Cambiare Vita">testi</a><br>
<b>10</b>. Rido Senz'Anima - <a target="_blank" href="http://www.google.com/search?q=spartiti+Rido+Senz%27Anima+Irene+Grandi" title="Spartiti di Rido Senz'Anima">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Rido+Senz%27Anima+Irene+Grandi" title="Accordi di Rido Senz'Anima">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Rido+Senz%27Anima+Irene+Grandi" title="Testi di Rido Senz'Anima">testi</a><br>
<h2>Irene Grandi (Spanish Version) (1998) </h2>
<b>1</b>. Que Vida Es - <a target="_blank" href="http://www.google.com/search?q=spartiti+Que+Vida+Es+Irene+Grandi" title="Spartiti di Que Vida Es">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Que+Vida+Es+Irene+Grandi" title="Accordi di Que Vida Es">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Que+Vida+Es+Irene+Grandi" title="Testi di Que Vida Es">testi</a><br>
<b>2</b>. Bum Bum (Spanish) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Bum+Bum+%28Spanish%29+Irene+Grandi" title="Spartiti di Bum Bum (Spanish)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Bum+Bum+%28Spanish%29+Irene+Grandi" title="Accordi di Bum Bum (Spanish)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Bum+Bum+%28Spanish%29+Irene+Grandi" title="Testi di Bum Bum (Spanish)">testi</a><br>
<b>3</b>. Ven Ven Ven - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ven+Ven+Ven+Irene+Grandi" title="Spartiti di Ven Ven Ven">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ven+Ven+Ven+Irene+Grandi" title="Accordi di Ven Ven Ven">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ven+Ven+Ven+Irene+Grandi" title="Testi di Ven Ven Ven">testi</a><br>
<b>4</b>. Un Tema Maledito - <a target="_blank" href="http://www.google.com/search?q=spartiti+Un+Tema+Maledito+Irene+Grandi" title="Spartiti di Un Tema Maledito">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Un+Tema+Maledito+Irene+Grandi" title="Accordi di Un Tema Maledito">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Un+Tema+Maledito+Irene+Grandi" title="Testi di Un Tema Maledito">testi</a><br>
<b>5</b>. Primitiva - <a target="_blank" href="http://www.google.com/search?q=spartiti+Primitiva+Irene+Grandi" title="Spartiti di Primitiva">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Primitiva+Irene+Grandi" title="Accordi di Primitiva">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Primitiva+Irene+Grandi" title="Testi di Primitiva">testi</a><br>
<b>6</b>. Dulcisimo Amante - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dulcisimo+Amante+Irene+Grandi" title="Spartiti di Dulcisimo Amante">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dulcisimo+Amante+Irene+Grandi" title="Accordi di Dulcisimo Amante">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dulcisimo+Amante+Irene+Grandi" title="Testi di Dulcisimo Amante">testi</a><br>
<b>7</b>. Fuera - <a target="_blank" href="http://www.google.com/search?q=spartiti+Fuera+Irene+Grandi" title="Spartiti di Fuera">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Fuera+Irene+Grandi" title="Accordi di Fuera">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Fuera+Irene+Grandi" title="Testi di Fuera">testi</a><br>
<b>8</b>. Es Posible Que Tu Y Yo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Es+Posible+Que+Tu+Y+Yo+Irene+Grandi" title="Spartiti di Es Posible Que Tu Y Yo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Es+Posible+Que+Tu+Y+Yo+Irene+Grandi" title="Accordi di Es Posible Que Tu Y Yo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Es+Posible+Que+Tu+Y+Yo+Irene+Grandi" title="Testi di Es Posible Que Tu Y Yo">testi</a><br>
<b>9</b>. T.Q.M. - <a target="_blank" href="http://www.google.com/search?q=spartiti+T.Q.M.+Irene+Grandi" title="Spartiti di T.Q.M.">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+T.Q.M.+Irene+Grandi" title="Accordi di T.Q.M.">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+T.Q.M.+Irene+Grandi" title="Testi di T.Q.M.">testi</a><br>
<b>10</b>. Cosas De Grandes - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cosas+De+Grandes+Irene+Grandi" title="Spartiti di Cosas De Grandes">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cosas+De+Grandes+Irene+Grandi" title="Accordi di Cosas De Grandes">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cosas+De+Grandes+Irene+Grandi" title="Testi di Cosas De Grandes">testi</a><br>
<h2>Per Fortuna Purtroppo (1997) </h2>
<b>1</b>. Per Fortuna Purtroppo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Per+Fortuna+Purtroppo+Irene+Grandi" title="Spartiti di Per Fortuna Purtroppo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Per+Fortuna+Purtroppo+Irene+Grandi" title="Accordi di Per Fortuna Purtroppo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Per+Fortuna+Purtroppo+Irene+Grandi" title="Testi di Per Fortuna Purtroppo">testi</a><br>
<b>2</b>. Nuova Posizione - <a target="_blank" href="http://www.google.com/search?q=spartiti+Nuova+Posizione+Irene+Grandi" title="Spartiti di Nuova Posizione">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Nuova+Posizione+Irene+Grandi" title="Accordi di Nuova Posizione">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Nuova+Posizione+Irene+Grandi" title="Testi di Nuova Posizione">testi</a><br>
<b>3</b>. Che Vita E' - <a target="_blank" href="http://www.google.com/search?q=spartiti+Che+Vita+E%27+Irene+Grandi" title="Spartiti di Che Vita E'">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Che+Vita+E%27+Irene+Grandi" title="Accordi di Che Vita E'">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Che+Vita+E%27+Irene+Grandi" title="Testi di Che Vita E'">testi</a><br>
<b>4</b>. Primitiva - <a target="_blank" href="http://www.google.com/search?q=spartiti+Primitiva+Irene+Grandi" title="Spartiti di Primitiva">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Primitiva+Irene+Grandi" title="Accordi di Primitiva">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Primitiva+Irene+Grandi" title="Testi di Primitiva">testi</a><br>
<b>5</b>. E' Possibile Che Noi - <a target="_blank" href="http://www.google.com/search?q=spartiti+E%27+Possibile+Che+Noi+Irene+Grandi" title="Spartiti di E' Possibile Che Noi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+E%27+Possibile+Che+Noi+Irene+Grandi" title="Accordi di E' Possibile Che Noi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+E%27+Possibile+Che+Noi+Irene+Grandi" title="Testi di E' Possibile Che Noi">testi</a><br>
<b>6</b>. Otto E Mezzo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Otto+E+Mezzo+Irene+Grandi" title="Spartiti di Otto E Mezzo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Otto+E+Mezzo+Irene+Grandi" title="Accordi di Otto E Mezzo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Otto+E+Mezzo+Irene+Grandi" title="Testi di Otto E Mezzo">testi</a><br>
<b>7</b>. Fai Come Me - <a target="_blank" href="http://www.google.com/search?q=spartiti+Fai+Come+Me+Irene+Grandi" title="Spartiti di Fai Come Me">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Fai+Come+Me+Irene+Grandi" title="Accordi di Fai Come Me">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Fai+Come+Me+Irene+Grandi" title="Testi di Fai Come Me">testi</a><br>
<b>8</b>. Non Ti Scriverò - <a target="_blank" href="http://www.google.com/search?q=spartiti+Non+Ti+Scriver%F2+Irene+Grandi" title="Spartiti di Non Ti Scriverò">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Non+Ti+Scriver%F2+Irene+Grandi" title="Accordi di Non Ti Scriverò">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Non+Ti+Scriver%F2+Irene+Grandi" title="Testi di Non Ti Scriverò">testi</a><br>
<b>9</b>. Sotto Le Stelle - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sotto+Le+Stelle+Irene+Grandi" title="Spartiti di Sotto Le Stelle">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sotto+Le+Stelle+Irene+Grandi" title="Accordi di Sotto Le Stelle">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sotto+Le+Stelle+Irene+Grandi" title="Testi di Sotto Le Stelle">testi</a><br>
<b>10</b>. Un Bagno In Mare - <a target="_blank" href="http://www.google.com/search?q=spartiti+Un+Bagno+In+Mare+Irene+Grandi" title="Spartiti di Un Bagno In Mare">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Un+Bagno+In+Mare+Irene+Grandi" title="Accordi di Un Bagno In Mare">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Un+Bagno+In+Mare+Irene+Grandi" title="Testi di Un Bagno In Mare">testi</a><br>
<h2>In Vacanza Da Una Vita (1995) </h2>
<b>1</b>. L'Amore Vola - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%27Amore+Vola+Irene+Grandi" title="Spartiti di L'Amore Vola">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%27Amore+Vola+Irene+Grandi" title="Accordi di L'Amore Vola">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%27Amore+Vola+Irene+Grandi" title="Testi di L'Amore Vola">testi</a><br>
<b>2</b>. Colpa Del Lupo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Colpa+Del+Lupo+Irene+Grandi" title="Spartiti di Colpa Del Lupo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Colpa+Del+Lupo+Irene+Grandi" title="Accordi di Colpa Del Lupo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Colpa+Del+Lupo+Irene+Grandi" title="Testi di Colpa Del Lupo">testi</a><br>
<b>3</b>. Dolcissimo Amore - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dolcissimo+Amore+Irene+Grandi" title="Spartiti di Dolcissimo Amore">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dolcissimo+Amore+Irene+Grandi" title="Accordi di Dolcissimo Amore">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dolcissimo+Amore+Irene+Grandi" title="Testi di Dolcissimo Amore">testi</a><br>
<b>4</b>. Il Gatto E Il Topo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Gatto+E+Il+Topo+Irene+Grandi" title="Spartiti di Il Gatto E Il Topo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Gatto+E+Il+Topo+Irene+Grandi" title="Accordi di Il Gatto E Il Topo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Gatto+E+Il+Topo+Irene+Grandi" title="Testi di Il Gatto E Il Topo">testi</a><br>
<b>5</b>. In Vacanza Da Una Vita - <a target="_blank" href="http://www.google.com/search?q=spartiti+In+Vacanza+Da+Una+Vita+Irene+Grandi" title="Spartiti di In Vacanza Da Una Vita">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+In+Vacanza+Da+Una+Vita+Irene+Grandi" title="Accordi di In Vacanza Da Una Vita">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+In+Vacanza+Da+Una+Vita+Irene+Grandi" title="Testi di In Vacanza Da Una Vita">testi</a><br>
<b>6</b>. Bum Bum - <a target="_blank" href="http://www.google.com/search?q=spartiti+Bum+Bum+Irene+Grandi" title="Spartiti di Bum Bum">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Bum+Bum+Irene+Grandi" title="Accordi di Bum Bum">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Bum+Bum+Irene+Grandi" title="Testi di Bum Bum">testi</a><br>
<b>7</b>. Bambine Cattive - <a target="_blank" href="http://www.google.com/search?q=spartiti+Bambine+Cattive+Irene+Grandi" title="Spartiti di Bambine Cattive">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Bambine+Cattive+Irene+Grandi" title="Accordi di Bambine Cattive">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Bambine+Cattive+Irene+Grandi" title="Testi di Bambine Cattive">testi</a><br>
<b>8</b>. Terra - <a target="_blank" href="http://www.google.com/search?q=spartiti+Terra+Irene+Grandi" title="Spartiti di Terra">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Terra+Irene+Grandi" title="Accordi di Terra">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Terra+Irene+Grandi" title="Testi di Terra">testi</a><br>
<b>9</b>. Ieri - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ieri+Irene+Grandi" title="Spartiti di Ieri">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ieri+Irene+Grandi" title="Accordi di Ieri">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ieri+Irene+Grandi" title="Testi di Ieri">testi</a><br>
<h2>Irene Grandi (1994) </h2>
<b>1</b>. Sposati! Subito! - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sposati%21+Subito%21+Irene+Grandi" title="Spartiti di Sposati! Subito!">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sposati%21+Subito%21+Irene+Grandi" title="Accordi di Sposati! Subito!">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sposati%21+Subito%21+Irene+Grandi" title="Testi di Sposati! Subito!">testi</a><br>
<b>2</b>. Mille - <a target="_blank" href="http://www.google.com/search?q=spartiti+Mille+Irene+Grandi" title="Spartiti di Mille">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Mille+Irene+Grandi" title="Accordi di Mille">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Mille+Irene+Grandi" title="Testi di Mille">testi</a><br>
<b>3</b>. Vai Vai Vai - <a target="_blank" href="http://www.google.com/search?q=spartiti+Vai+Vai+Vai+Irene+Grandi" title="Spartiti di Vai Vai Vai">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Vai+Vai+Vai+Irene+Grandi" title="Accordi di Vai Vai Vai">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Vai+Vai+Vai+Irene+Grandi" title="Testi di Vai Vai Vai">testi</a><br>
<b>4</b>. Fuori - <a target="_blank" href="http://www.google.com/search?q=spartiti+Fuori+Irene+Grandi" title="Spartiti di Fuori">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Fuori+Irene+Grandi" title="Accordi di Fuori">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Fuori+Irene+Grandi" title="Testi di Fuori">testi</a><br>
<b>5</b>. Un Motivo Maledetto - <a target="_blank" href="http://www.google.com/search?q=spartiti+Un+Motivo+Maledetto+Irene+Grandi" title="Spartiti di Un Motivo Maledetto">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Un+Motivo+Maledetto+Irene+Grandi" title="Accordi di Un Motivo Maledetto">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Un+Motivo+Maledetto+Irene+Grandi" title="Testi di Un Motivo Maledetto">testi</a><br>
<b>6</b>. T.V.B. - <a target="_blank" href="http://www.google.com/search?q=spartiti+T.V.B.+Irene+Grandi" title="Spartiti di T.V.B.">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+T.V.B.+Irene+Grandi" title="Accordi di T.V.B.">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+T.V.B.+Irene+Grandi" title="Testi di T.V.B.">testi</a><br>
<b>7</b>. A Natural Woman - <a target="_blank" href="http://www.google.com/search?q=spartiti+A+Natural+Woman+Irene+Grandi" title="Spartiti di A Natural Woman">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+A+Natural+Woman+Irene+Grandi" title="Accordi di A Natural Woman">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+A+Natural+Woman+Irene+Grandi" title="Testi di A Natural Woman">testi</a><br>
<b>8</b>. La Cucina - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Cucina+Irene+Grandi" title="Spartiti di La Cucina">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Cucina+Irene+Grandi" title="Accordi di La Cucina">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Cucina+Irene+Grandi" title="Testi di La Cucina">testi</a><br>
<b>9</b>. Cose Da Grandi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cose+Da+Grandi+Irene+Grandi" title="Spartiti di Cose Da Grandi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cose+Da+Grandi+Irene+Grandi" title="Accordi di Cose Da Grandi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cose+Da+Grandi+Irene+Grandi" title="Testi di Cose Da Grandi">testi</a><br>
<h2>Altre Canzoni </h2>
<b>1</b>. Lasciala Andare - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lasciala+Andare+Irene+Grandi" title="Spartiti di Lasciala Andare">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lasciala+Andare+Irene+Grandi" title="Accordi di Lasciala Andare">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lasciala+Andare+Irene+Grandi" title="Testi di Lasciala Andare">testi</a><br>
<b>2</b>. Olimpiade Invernale - <a target="_blank" href="http://www.google.com/search?q=spartiti+Olimpiade+Invernale+Irene+Grandi" title="Spartiti di Olimpiade Invernale">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Olimpiade+Invernale+Irene+Grandi" title="Accordi di Olimpiade Invernale">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Olimpiade+Invernale+Irene+Grandi" title="Testi di Olimpiade Invernale">testi</a><br>
<b>3</b>. Se Mi Vuoi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Se+Mi+Vuoi+Irene+Grandi" title="Spartiti di Se Mi Vuoi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Se+Mi+Vuoi+Irene+Grandi" title="Accordi di Se Mi Vuoi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Se+Mi+Vuoi+Irene+Grandi" title="Testi di Se Mi Vuoi">testi</a><br>
<h2><a href="<?php echo "$base_website_address/$spartiti_dir" ?>/index.html" title="Trova accordi, spartiti, tablature e testi di tantissimi artisti">Torna all'indice degli artisti</a></h2>
