<!--
title: Trova spartiti per chitarra, accordi, testi e tablature di Ligabue. Discografia Ligabue.
description: Trova tutti gli spartiti, accordi, testi e tablature di Ligabue. Discografia Ligabue.
keywords: Discografia, Ligabue, spartiti, accordi, testi, tablature
template: tablature
-->
<h1>Trova spartiti per chitarra, accordi, testi e tablature di Ligabue</h1><h2>Leggere gli spartiti per chitarra, gli accordi e le tablature:</h2>
<?php require("tabdescription.php"); ?>

<h2>Discografia Ligabue:</h2>
<h2>Nome e Cognome (2005) </h2>
<b>1</b>. Intro - <a target="_blank" href="http://www.google.com/search?q=spartiti+Intro+Ligabue" title="Spartiti di Intro">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Intro+Ligabue" title="Accordi di Intro">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Intro+Ligabue" title="Testi di Intro">testi</a><br>
<b>2</b>. Il Giorno Dei Giorni - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Giorno+Dei+Giorni+Ligabue" title="Spartiti di Il Giorno Dei Giorni">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Giorno+Dei+Giorni+Ligabue" title="Accordi di Il Giorno Dei Giorni">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Giorno+Dei+Giorni+Ligabue" title="Testi di Il Giorno Dei Giorni">testi</a><br>
<b>3</b>. Happy Hour - <a target="_blank" href="http://www.google.com/search?q=spartiti+Happy+Hour+Ligabue" title="Spartiti di Happy Hour">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Happy+Hour+Ligabue" title="Accordi di Happy Hour">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Happy+Hour+Ligabue" title="Testi di Happy Hour">testi</a><br>
<b>4</b>. L'amore Conta - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%27amore+Conta+Ligabue" title="Spartiti di L'amore Conta">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%27amore+Conta+Ligabue" title="Accordi di L'amore Conta">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%27amore+Conta+Ligabue" title="Testi di L'amore Conta">testi</a><br>
<b>5</b>. Cosa Vuoi Che Sia - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cosa+Vuoi+Che+Sia+Ligabue" title="Spartiti di Cosa Vuoi Che Sia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cosa+Vuoi+Che+Sia+Ligabue" title="Accordi di Cosa Vuoi Che Sia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cosa+Vuoi+Che+Sia+Ligabue" title="Testi di Cosa Vuoi Che Sia">testi</a><br>
<b>6</b>. Le Donne Lo Sanno - <a target="_blank" href="http://www.google.com/search?q=spartiti+Le+Donne+Lo+Sanno+Ligabue" title="Spartiti di Le Donne Lo Sanno">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Le+Donne+Lo+Sanno+Ligabue" title="Accordi di Le Donne Lo Sanno">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Le+Donne+Lo+Sanno+Ligabue" title="Testi di Le Donne Lo Sanno">testi</a><br>
<b>7</b>. Lettera A G. - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lettera+A+G.+Ligabue" title="Spartiti di Lettera A G.">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lettera+A+G.+Ligabue" title="Accordi di Lettera A G.">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lettera+A+G.+Ligabue" title="Testi di Lettera A G.">testi</a><br>
<b>8</b>. Vivere A Orecchio - <a target="_blank" href="http://www.google.com/search?q=spartiti+Vivere+A+Orecchio+Ligabue" title="Spartiti di Vivere A Orecchio">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Vivere+A+Orecchio+Ligabue" title="Accordi di Vivere A Orecchio">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Vivere+A+Orecchio+Ligabue" title="Testi di Vivere A Orecchio">testi</a><br>
<b>9</b>. Giorno Per Giorno - <a target="_blank" href="http://www.google.com/search?q=spartiti+Giorno+Per+Giorno+Ligabue" title="Spartiti di Giorno Per Giorno">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Giorno+Per+Giorno+Ligabue" title="Accordi di Giorno Per Giorno">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Giorno+Per+Giorno+Ligabue" title="Testi di Giorno Per Giorno">testi</a><br>
<b>10</b>. E' Piu' Forte Di Me - <a target="_blank" href="http://www.google.com/search?q=spartiti+E%27+Piu%27+Forte+Di+Me+Ligabue" title="Spartiti di E' Piu' Forte Di Me">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+E%27+Piu%27+Forte+Di+Me+Ligabue" title="Accordi di E' Piu' Forte Di Me">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+E%27+Piu%27+Forte+Di+Me+Ligabue" title="Testi di E' Piu' Forte Di Me">testi</a><br>
<b>11</b>. Sono Qui Per L'amore - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sono+Qui+Per+L%27amore+Ligabue" title="Spartiti di Sono Qui Per L'amore">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sono+Qui+Per+L%27amore+Ligabue" title="Accordi di Sono Qui Per L'amore">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sono+Qui+Per+L%27amore+Ligabue" title="Testi di Sono Qui Per L'amore">testi</a><br>
<h2>Giro D'Italia (Disc 3) (2003) </h2>
<b>1</b>. Chissà Se In Cielo Passano Gli Who - <a target="_blank" href="http://www.google.com/search?q=spartiti+Chiss%E0+Se+In+Cielo+Passano+Gli+Who+Ligabue" title="Spartiti di Chissà Se In Cielo Passano Gli Who">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Chiss%E0+Se+In+Cielo+Passano+Gli+Who+Ligabue" title="Accordi di Chissà Se In Cielo Passano Gli Who">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Chiss%E0+Se+In+Cielo+Passano+Gli+Who+Ligabue" title="Testi di Chissà Se In Cielo Passano Gli Who">testi</a><br>
<b>2</b>. Ti Sento - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ti+Sento+Ligabue" title="Spartiti di Ti Sento">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ti+Sento+Ligabue" title="Accordi di Ti Sento">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ti+Sento+Ligabue" title="Testi di Ti Sento">testi</a><br>
<b>3</b>. Voglia Di Caffé (Parlato) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Voglia+Di+Caff%E9+%28Parlato%29+Ligabue" title="Spartiti di Voglia Di Caffé (Parlato)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Voglia+Di+Caff%E9+%28Parlato%29+Ligabue" title="Accordi di Voglia Di Caffé (Parlato)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Voglia+Di+Caff%E9+%28Parlato%29+Ligabue" title="Testi di Voglia Di Caffé (Parlato)">testi</a><br>
<b>4</b>. Sulla Mia Strada - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sulla+Mia+Strada+Ligabue" title="Spartiti di Sulla Mia Strada">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sulla+Mia+Strada+Ligabue" title="Accordi di Sulla Mia Strada">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sulla+Mia+Strada+Ligabue" title="Testi di Sulla Mia Strada">testi</a><br>
<b>5</b>. Almeno Credo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Almeno+Credo+Ligabue" title="Spartiti di Almeno Credo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Almeno+Credo+Ligabue" title="Accordi di Almeno Credo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Almeno+Credo+Ligabue" title="Testi di Almeno Credo">testi</a><br>
<b>6</b>. Nato Per Me - <a target="_blank" href="http://www.google.com/search?q=spartiti+Nato+Per+Me+Ligabue" title="Spartiti di Nato Per Me">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Nato+Per+Me+Ligabue" title="Accordi di Nato Per Me">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Nato+Per+Me+Ligabue" title="Testi di Nato Per Me">testi</a><br>
<b>7</b>. Baby Talkin' Blues (Parlato) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Baby+Talkin%27+Blues+%28Parlato%29+Ligabue" title="Spartiti di Baby Talkin' Blues (Parlato)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Baby+Talkin%27+Blues+%28Parlato%29+Ligabue" title="Accordi di Baby Talkin' Blues (Parlato)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Baby+Talkin%27+Blues+%28Parlato%29+Ligabue" title="Testi di Baby Talkin' Blues (Parlato)">testi</a><br>
<b>8</b>. Il Mio Nome E' Mai Più - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Mio+Nome+E%27+Mai+Pi%F9+Ligabue" title="Spartiti di Il Mio Nome E' Mai Più">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Mio+Nome+E%27+Mai+Pi%F9+Ligabue" title="Accordi di Il Mio Nome E' Mai Più">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Mio+Nome+E%27+Mai+Pi%F9+Ligabue" title="Testi di Il Mio Nome E' Mai Più">testi</a><br>
<b>9</b>. Dove Fermano I Treni - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dove+Fermano+I+Treni+Ligabue" title="Spartiti di Dove Fermano I Treni">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dove+Fermano+I+Treni+Ligabue" title="Accordi di Dove Fermano I Treni">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dove+Fermano+I+Treni+Ligabue" title="Testi di Dove Fermano I Treni">testi</a><br>
<b>10</b>. Reading Bukowski (Parlato) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Reading+Bukowski+%28Parlato%29+Ligabue" title="Spartiti di Reading Bukowski (Parlato)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Reading+Bukowski+%28Parlato%29+Ligabue" title="Accordi di Reading Bukowski (Parlato)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Reading+Bukowski+%28Parlato%29+Ligabue" title="Testi di Reading Bukowski (Parlato)">testi</a><br>
<b>11</b>. Kay E' Stata Qui - <a target="_blank" href="http://www.google.com/search?q=spartiti+Kay+E%27+Stata+Qui+Ligabue" title="Spartiti di Kay E' Stata Qui">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Kay+E%27+Stata+Qui+Ligabue" title="Accordi di Kay E' Stata Qui">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Kay+E%27+Stata+Qui+Ligabue" title="Testi di Kay E' Stata Qui">testi</a><br>
<h2>Giro D'Italia (Disc 2) (2003) </h2>
<b>1</b>. Voglio Volere - <a target="_blank" href="http://www.google.com/search?q=spartiti+Voglio+Volere+Ligabue" title="Spartiti di Voglio Volere">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Voglio+Volere+Ligabue" title="Accordi di Voglio Volere">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Voglio+Volere+Ligabue" title="Testi di Voglio Volere">testi</a><br>
<b>2</b>. Sarà Un Bel Souvenir - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sar%E0+Un+Bel+Souvenir+Ligabue" title="Spartiti di Sarà Un Bel Souvenir">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sar%E0+Un+Bel+Souvenir+Ligabue" title="Accordi di Sarà Un Bel Souvenir">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sar%E0+Un+Bel+Souvenir+Ligabue" title="Testi di Sarà Un Bel Souvenir">testi</a><br>
<b>3</b>. Una Vita Da Mediano - <a target="_blank" href="http://www.google.com/search?q=spartiti+Una+Vita+Da+Mediano+Ligabue" title="Spartiti di Una Vita Da Mediano">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Una+Vita+Da+Mediano+Ligabue" title="Accordi di Una Vita Da Mediano">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Una+Vita+Da+Mediano+Ligabue" title="Testi di Una Vita Da Mediano">testi</a><br>
<b>4</b>. Angelo Della Nebbia - <a target="_blank" href="http://www.google.com/search?q=spartiti+Angelo+Della+Nebbia+Ligabue" title="Spartiti di Angelo Della Nebbia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Angelo+Della+Nebbia+Ligabue" title="Accordi di Angelo Della Nebbia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Angelo+Della+Nebbia+Ligabue" title="Testi di Angelo Della Nebbia">testi</a><br>
<b>5</b>. Ho Messo Via - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ho+Messo+Via+Ligabue" title="Spartiti di Ho Messo Via">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ho+Messo+Via+Ligabue" title="Accordi di Ho Messo Via">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ho+Messo+Via+Ligabue" title="Testi di Ho Messo Via">testi</a><br>
<b>6</b>. Baby, E' Un Mondo Super - <a target="_blank" href="http://www.google.com/search?q=spartiti+Baby%2C+E%27+Un+Mondo+Super+Ligabue" title="Spartiti di Baby, E' Un Mondo Super">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Baby%2C+E%27+Un+Mondo+Super+Ligabue" title="Accordi di Baby, E' Un Mondo Super">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Baby%2C+E%27+Un+Mondo+Super+Ligabue" title="Testi di Baby, E' Un Mondo Super">testi</a><br>
<b>7</b>. Tu Che Conosci Il Cielo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tu+Che+Conosci+Il+Cielo+Ligabue" title="Spartiti di Tu Che Conosci Il Cielo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tu+Che+Conosci+Il+Cielo+Ligabue" title="Accordi di Tu Che Conosci Il Cielo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tu+Che+Conosci+Il+Cielo+Ligabue" title="Testi di Tu Che Conosci Il Cielo">testi</a><br>
<b>8</b>. Eri Bellissima - <a target="_blank" href="http://www.google.com/search?q=spartiti+Eri+Bellissima+Ligabue" title="Spartiti di Eri Bellissima">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Eri+Bellissima+Ligabue" title="Accordi di Eri Bellissima">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Eri+Bellissima+Ligabue" title="Testi di Eri Bellissima">testi</a><br>
<b>9</b>. Metti In Circolo Il Tuo Amore - <a target="_blank" href="http://www.google.com/search?q=spartiti+Metti+In+Circolo+Il+Tuo+Amore+Ligabue" title="Spartiti di Metti In Circolo Il Tuo Amore">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Metti+In+Circolo+Il+Tuo+Amore+Ligabue" title="Accordi di Metti In Circolo Il Tuo Amore">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Metti+In+Circolo+Il+Tuo+Amore+Ligabue" title="Testi di Metti In Circolo Il Tuo Amore">testi</a><br>
<b>10</b>. Tutti Vogliono Viaggiare In Prima - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tutti+Vogliono+Viaggiare+In+Prima+Ligabue" title="Spartiti di Tutti Vogliono Viaggiare In Prima">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tutti+Vogliono+Viaggiare+In+Prima+Ligabue" title="Accordi di Tutti Vogliono Viaggiare In Prima">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tutti+Vogliono+Viaggiare+In+Prima+Ligabue" title="Testi di Tutti Vogliono Viaggiare In Prima">testi</a><br>
<b>11</b>. Tra Palco e Realtà - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tra+Palco+e+Realt%E0+Ligabue" title="Spartiti di Tra Palco e Realtà">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tra+Palco+e+Realt%E0+Ligabue" title="Accordi di Tra Palco e Realtà">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tra+Palco+e+Realt%E0+Ligabue" title="Testi di Tra Palco e Realtà">testi</a><br>
<h2>Giro D'Italia (Disc 1) (2003) </h2>
<b>1</b>. Piccola Stella Senza Cielo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Piccola+Stella+Senza+Cielo+Ligabue" title="Spartiti di Piccola Stella Senza Cielo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Piccola+Stella+Senza+Cielo+Ligabue" title="Accordi di Piccola Stella Senza Cielo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Piccola+Stella+Senza+Cielo+Ligabue" title="Testi di Piccola Stella Senza Cielo">testi</a><br>
<b>2</b>. Si Viene e Si Va - <a target="_blank" href="http://www.google.com/search?q=spartiti+Si+Viene+e+Si+Va+Ligabue" title="Spartiti di Si Viene e Si Va">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Si+Viene+e+Si+Va+Ligabue" title="Accordi di Si Viene e Si Va">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Si+Viene+e+Si+Va+Ligabue" title="Testi di Si Viene e Si Va">testi</a><br>
<b>3</b>. Il Giorno Di Dolore Che Uno Ha - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Giorno+Di+Dolore+Che+Uno+Ha+Ligabue" title="Spartiti di Il Giorno Di Dolore Che Uno Ha">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Giorno+Di+Dolore+Che+Uno+Ha+Ligabue" title="Accordi di Il Giorno Di Dolore Che Uno Ha">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Giorno+Di+Dolore+Che+Uno+Ha+Ligabue" title="Testi di Il Giorno Di Dolore Che Uno Ha">testi</a><br>
<b>4</b>. Sogni Di Rock'N'Roll - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sogni+Di+Rock%27N%27Roll+Ligabue" title="Spartiti di Sogni Di Rock'N'Roll">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sogni+Di+Rock%27N%27Roll+Ligabue" title="Accordi di Sogni Di Rock'N'Roll">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sogni+Di+Rock%27N%27Roll+Ligabue" title="Testi di Sogni Di Rock'N'Roll">testi</a><br>
<b>5</b>. Walter Il Mago - <a target="_blank" href="http://www.google.com/search?q=spartiti+Walter+Il+Mago+Ligabue" title="Spartiti di Walter Il Mago">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Walter+Il+Mago+Ligabue" title="Accordi di Walter Il Mago">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Walter+Il+Mago+Ligabue" title="Testi di Walter Il Mago">testi</a><br>
<b>6</b>. Vivo Morto o X - <a target="_blank" href="http://www.google.com/search?q=spartiti+Vivo+Morto+o+X+Ligabue" title="Spartiti di Vivo Morto o X">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Vivo+Morto+o+X+Ligabue" title="Accordi di Vivo Morto o X">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Vivo+Morto+o+X+Ligabue" title="Testi di Vivo Morto o X">testi</a><br>
<b>7</b>. Camera Con Vista Sul Deserto - <a target="_blank" href="http://www.google.com/search?q=spartiti+Camera+Con+Vista+Sul+Deserto+Ligabue" title="Spartiti di Camera Con Vista Sul Deserto">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Camera+Con+Vista+Sul+Deserto+Ligabue" title="Accordi di Camera Con Vista Sul Deserto">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Camera+Con+Vista+Sul+Deserto+Ligabue" title="Testi di Camera Con Vista Sul Deserto">testi</a><br>
<b>8</b>. Miss Mondo '99 - <a target="_blank" href="http://www.google.com/search?q=spartiti+Miss+Mondo+%2799+Ligabue" title="Spartiti di Miss Mondo '99">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Miss+Mondo+%2799+Ligabue" title="Accordi di Miss Mondo '99">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Miss+Mondo+%2799+Ligabue" title="Testi di Miss Mondo '99">testi</a><br>
<b>9</b>. Tutte Le Strade Portano A Te - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tutte+Le+Strade+Portano+A+Te+Ligabue" title="Spartiti di Tutte Le Strade Portano A Te">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tutte+Le+Strade+Portano+A+Te+Ligabue" title="Accordi di Tutte Le Strade Portano A Te">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tutte+Le+Strade+Portano+A+Te+Ligabue" title="Testi di Tutte Le Strade Portano A Te">testi</a><br>
<b>10</b>. Questa E' La Mia Vita - <a target="_blank" href="http://www.google.com/search?q=spartiti+Questa+E%27+La+Mia+Vita+Ligabue" title="Spartiti di Questa E' La Mia Vita">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Questa+E%27+La+Mia+Vita+Ligabue" title="Accordi di Questa E' La Mia Vita">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Questa+E%27+La+Mia+Vita+Ligabue" title="Testi di Questa E' La Mia Vita">testi</a><br>
<h2>Fuori Come Va? (2002) </h2>
<b>1</b>. Nato Per Me - <a target="_blank" href="http://www.google.com/search?q=spartiti+Nato+Per+Me+Ligabue" title="Spartiti di Nato Per Me">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Nato+Per+Me+Ligabue" title="Accordi di Nato Per Me">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Nato+Per+Me+Ligabue" title="Testi di Nato Per Me">testi</a><br>
<b>2</b>. Tutti Vogliono Viaggiare In Prima - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tutti+Vogliono+Viaggiare+In+Prima+Ligabue" title="Spartiti di Tutti Vogliono Viaggiare In Prima">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tutti+Vogliono+Viaggiare+In+Prima+Ligabue" title="Accordi di Tutti Vogliono Viaggiare In Prima">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tutti+Vogliono+Viaggiare+In+Prima+Ligabue" title="Testi di Tutti Vogliono Viaggiare In Prima">testi</a><br>
<b>3</b>. Ti Sento - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ti+Sento+Ligabue" title="Spartiti di Ti Sento">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ti+Sento+Ligabue" title="Accordi di Ti Sento">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ti+Sento+Ligabue" title="Testi di Ti Sento">testi</a><br>
<b>4</b>. Questa E' La Mia Vita - <a target="_blank" href="http://www.google.com/search?q=spartiti+Questa+E%27+La+Mia+Vita+Ligabue" title="Spartiti di Questa E' La Mia Vita">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Questa+E%27+La+Mia+Vita+Ligabue" title="Accordi di Questa E' La Mia Vita">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Questa+E%27+La+Mia+Vita+Ligabue" title="Testi di Questa E' La Mia Vita">testi</a><br>
<b>5</b>. Tu Che Conosci Il Cielo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tu+Che+Conosci+Il+Cielo+Ligabue" title="Spartiti di Tu Che Conosci Il Cielo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tu+Che+Conosci+Il+Cielo+Ligabue" title="Accordi di Tu Che Conosci Il Cielo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tu+Che+Conosci+Il+Cielo+Ligabue" title="Testi di Tu Che Conosci Il Cielo">testi</a><br>
<b>6</b>. Il Campo Delle Lucciole - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Campo+Delle+Lucciole+Ligabue" title="Spartiti di Il Campo Delle Lucciole">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Campo+Delle+Lucciole+Ligabue" title="Accordi di Il Campo Delle Lucciole">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Campo+Delle+Lucciole+Ligabue" title="Testi di Il Campo Delle Lucciole">testi</a><br>
<b>7</b>. Voglio Volere - <a target="_blank" href="http://www.google.com/search?q=spartiti+Voglio+Volere+Ligabue" title="Spartiti di Voglio Volere">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Voglio+Volere+Ligabue" title="Accordi di Voglio Volere">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Voglio+Volere+Ligabue" title="Testi di Voglio Volere">testi</a><br>
<b>8</b>. Eri Bellissima - <a target="_blank" href="http://www.google.com/search?q=spartiti+Eri+Bellissima+Ligabue" title="Spartiti di Eri Bellissima">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Eri+Bellissima+Ligabue" title="Accordi di Eri Bellissima">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Eri+Bellissima+Ligabue" title="Testi di Eri Bellissima">testi</a><br>
<b>9</b>. Libera Uscita - <a target="_blank" href="http://www.google.com/search?q=spartiti+Libera+Uscita+Ligabue" title="Spartiti di Libera Uscita">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Libera+Uscita+Ligabue" title="Accordi di Libera Uscita">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Libera+Uscita+Ligabue" title="Testi di Libera Uscita">testi</a><br>
<b>10</b>. Tutte Le Strade Portano A Te - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tutte+Le+Strade+Portano+A+Te+Ligabue" title="Spartiti di Tutte Le Strade Portano A Te">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tutte+Le+Strade+Portano+A+Te+Ligabue" title="Accordi di Tutte Le Strade Portano A Te">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tutte+Le+Strade+Portano+A+Te+Ligabue" title="Testi di Tutte Le Strade Portano A Te">testi</a><br>
<b>11</b>. In Pieno Rock '&' RollIn Pieno Rock '&' Roll - <a target="_blank" href="http://www.google.com/search?q=spartiti+In+Pieno+Rock+%27%26%27+RollIn+Pieno+Rock+%27%26%27+Roll+Ligabue" title="Spartiti di In Pieno Rock '&' RollIn Pieno Rock '&' Roll">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+In+Pieno+Rock+%27%26%27+RollIn+Pieno+Rock+%27%26%27+Roll+Ligabue" title="Accordi di In Pieno Rock '&' RollIn Pieno Rock '&' Roll">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+In+Pieno+Rock+%27%26%27+RollIn+Pieno+Rock+%27%26%27+Roll+Ligabue" title="Testi di In Pieno Rock '&' RollIn Pieno Rock '&' Roll">testi</a><br>
<b>12</b>. Chissà Se In Cielo Passano Gli Who - <a target="_blank" href="http://www.google.com/search?q=spartiti+Chiss%E0+Se+In+Cielo+Passano+Gli+Who+Ligabue" title="Spartiti di Chissà Se In Cielo Passano Gli Who">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Chiss%E0+Se+In+Cielo+Passano+Gli+Who+Ligabue" title="Accordi di Chissà Se In Cielo Passano Gli Who">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Chiss%E0+Se+In+Cielo+Passano+Gli+Who+Ligabue" title="Testi di Chissà Se In Cielo Passano Gli Who">testi</a><br>
<h2>Miss Mondo (1999) </h2>
<b>1</b>. Si Viene E Si Va - <a target="_blank" href="http://www.google.com/search?q=spartiti+Si+Viene+E+Si+Va+Ligabue" title="Spartiti di Si Viene E Si Va">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Si+Viene+E+Si+Va+Ligabue" title="Accordi di Si Viene E Si Va">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Si+Viene+E+Si+Va+Ligabue" title="Testi di Si Viene E Si Va">testi</a><br>
<b>2</b>. Uno Dei Tanti - <a target="_blank" href="http://www.google.com/search?q=spartiti+Uno+Dei+Tanti+Ligabue" title="Spartiti di Uno Dei Tanti">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Uno+Dei+Tanti+Ligabue" title="Accordi di Uno Dei Tanti">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Uno+Dei+Tanti+Ligabue" title="Testi di Uno Dei Tanti">testi</a><br>
<b>3</b>. Almeno Credo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Almeno+Credo+Ligabue" title="Spartiti di Almeno Credo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Almeno+Credo+Ligabue" title="Accordi di Almeno Credo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Almeno+Credo+Ligabue" title="Testi di Almeno Credo">testi</a><br>
<b>4</b>. E - <a target="_blank" href="http://www.google.com/search?q=spartiti+E+Ligabue" title="Spartiti di E">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+E+Ligabue" title="Accordi di E">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+E+Ligabue" title="Testi di E">testi</a><br>
<b>5</b>. Baby, E' Un Mondo Super - <a target="_blank" href="http://www.google.com/search?q=spartiti+Baby%2C+E%27+Un+Mondo+Super+Ligabue" title="Spartiti di Baby, E' Un Mondo Super">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Baby%2C+E%27+Un+Mondo+Super+Ligabue" title="Accordi di Baby, E' Un Mondo Super">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Baby%2C+E%27+Un+Mondo+Super+Ligabue" title="Testi di Baby, E' Un Mondo Super">testi</a><br>
<b>6</b>. Una Vita Da Mediano - <a target="_blank" href="http://www.google.com/search?q=spartiti+Una+Vita+Da+Mediano+Ligabue" title="Spartiti di Una Vita Da Mediano">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Una+Vita+Da+Mediano+Ligabue" title="Accordi di Una Vita Da Mediano">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Una+Vita+Da+Mediano+Ligabue" title="Testi di Una Vita Da Mediano">testi</a><br>
<b>7</b>. Da Adesso In Poi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Da+Adesso+In+Poi+Ligabue" title="Spartiti di Da Adesso In Poi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Da+Adesso+In+Poi+Ligabue" title="Accordi di Da Adesso In Poi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Da+Adesso+In+Poi+Ligabue" title="Testi di Da Adesso In Poi">testi</a><br>
<b>8</b>. L'odore Del Sesso - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%27odore+Del+Sesso+Ligabue" title="Spartiti di L'odore Del Sesso">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%27odore+Del+Sesso+Ligabue" title="Accordi di L'odore Del Sesso">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%27odore+Del+Sesso+Ligabue" title="Testi di L'odore Del Sesso">testi</a><br>
<b>9</b>. Kay E' Stata Qui - <a target="_blank" href="http://www.google.com/search?q=spartiti+Kay+E%27+Stata+Qui+Ligabue" title="Spartiti di Kay E' Stata Qui">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Kay+E%27+Stata+Qui+Ligabue" title="Accordi di Kay E' Stata Qui">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Kay+E%27+Stata+Qui+Ligabue" title="Testi di Kay E' Stata Qui">testi</a><br>
<b>10</b>. Qualcuno Ha Visto, Per Caso, Il Mio Cane Blu Elettrico Monofase? - <a target="_blank" href="http://www.google.com/search?q=spartiti+Qualcuno+Ha+Visto%2C+Per+Caso%2C+Il+Mio+Cane+Blu+Elettrico+Monofase%3F+Ligabue" title="Spartiti di Qualcuno Ha Visto, Per Caso, Il Mio Cane Blu Elettrico Monofase?">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Qualcuno+Ha+Visto%2C+Per+Caso%2C+Il+Mio+Cane+Blu+Elettrico+Monofase%3F+Ligabue" title="Accordi di Qualcuno Ha Visto, Per Caso, Il Mio Cane Blu Elettrico Monofase?">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Qualcuno+Ha+Visto%2C+Per+Caso%2C+Il+Mio+Cane+Blu+Elettrico+Monofase%3F+Ligabue" title="Testi di Qualcuno Ha Visto, Per Caso, Il Mio Cane Blu Elettrico Monofase?">testi</a><br>
<b>11</b>. Sulla Mia Strada - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sulla+Mia+Strada+Ligabue" title="Spartiti di Sulla Mia Strada">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sulla+Mia+Strada+Ligabue" title="Accordi di Sulla Mia Strada">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sulla+Mia+Strada+Ligabue" title="Testi di Sulla Mia Strada">testi</a><br>
<b>12</b>. Forse Mi Trovo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Forse+Mi+Trovo+Ligabue" title="Spartiti di Forse Mi Trovo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Forse+Mi+Trovo+Ligabue" title="Accordi di Forse Mi Trovo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Forse+Mi+Trovo+Ligabue" title="Testi di Forse Mi Trovo">testi</a><br>
<b>13</b>. Miss Mondo '99 - <a target="_blank" href="http://www.google.com/search?q=spartiti+Miss+Mondo+%2799+Ligabue" title="Spartiti di Miss Mondo '99">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Miss+Mondo+%2799+Ligabue" title="Accordi di Miss Mondo '99">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Miss+Mondo+%2799+Ligabue" title="Testi di Miss Mondo '99">testi</a><br>
<b>14</b>. La Porta Dei Sogni - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Porta+Dei+Sogni+Ligabue" title="Spartiti di La Porta Dei Sogni">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Porta+Dei+Sogni+Ligabue" title="Accordi di La Porta Dei Sogni">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Porta+Dei+Sogni+Ligabue" title="Testi di La Porta Dei Sogni">testi</a><br>
<h2>Il Mio Nome E' Mai Più (1999) </h2>
<b>1</b>. Il Mio Nome E' Mai Più - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Mio+Nome+E%27+Mai+Pi%F9+Ligabue" title="Spartiti di Il Mio Nome E' Mai Più">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Mio+Nome+E%27+Mai+Pi%F9+Ligabue" title="Accordi di Il Mio Nome E' Mai Più">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Mio+Nome+E%27+Mai+Pi%F9+Ligabue" title="Testi di Il Mio Nome E' Mai Più">testi</a><br>
<h2>Radiofreccia: Le Canzoni (Cd 2) (1998) </h2>
<b>1</b>. Rebel Rebel - <a target="_blank" href="http://www.google.com/search?q=spartiti+Rebel+Rebel+Ligabue" title="Spartiti di Rebel Rebel">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Rebel+Rebel+Ligabue" title="Accordi di Rebel Rebel">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Rebel+Rebel+Ligabue" title="Testi di Rebel Rebel">testi</a><br>
<b>2</b>. Werewolves of London - <a target="_blank" href="http://www.google.com/search?q=spartiti+Werewolves+of+London+Ligabue" title="Spartiti di Werewolves of London">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Werewolves+of+London+Ligabue" title="Accordi di Werewolves of London">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Werewolves+of+London+Ligabue" title="Testi di Werewolves of London">testi</a><br>
<b>3</b>. The Passenger - <a target="_blank" href="http://www.google.com/search?q=spartiti+The+Passenger+Ligabue" title="Spartiti di The Passenger">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+The+Passenger+Ligabue" title="Accordi di The Passenger">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+The+Passenger+Ligabue" title="Testi di The Passenger">testi</a><br>
<b>4</b>. Lord Of The Starfields - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lord+Of+The+Starfields+Ligabue" title="Spartiti di Lord Of The Starfields">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lord+Of+The+Starfields+Ligabue" title="Accordi di Lord Of The Starfields">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lord+Of+The+Starfields+Ligabue" title="Testi di Lord Of The Starfields">testi</a><br>
<b>5</b>. You Ain't Seen Nothing Yet - <a target="_blank" href="http://www.google.com/search?q=spartiti+You+Ain%27t+Seen+Nothing+Yet+Ligabue" title="Spartiti di You Ain't Seen Nothing Yet">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+You+Ain%27t+Seen+Nothing+Yet+Ligabue" title="Accordi di You Ain't Seen Nothing Yet">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+You+Ain%27t+Seen+Nothing+Yet+Ligabue" title="Testi di You Ain't Seen Nothing Yet">testi</a><br>
<b>6</b>. Love Is The Drug - <a target="_blank" href="http://www.google.com/search?q=spartiti+Love+Is+The+Drug+Ligabue" title="Spartiti di Love Is The Drug">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Love+Is+The+Drug+Ligabue" title="Accordi di Love Is The Drug">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Love+Is+The+Drug+Ligabue" title="Testi di Love Is The Drug">testi</a><br>
<b>7</b>. Long Train Running - <a target="_blank" href="http://www.google.com/search?q=spartiti+Long+Train+Running+Ligabue" title="Spartiti di Long Train Running">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Long+Train+Running+Ligabue" title="Accordi di Long Train Running">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Long+Train+Running+Ligabue" title="Testi di Long Train Running">testi</a><br>
<b>8</b>. Jessica - <a target="_blank" href="http://www.google.com/search?q=spartiti+Jessica+Ligabue" title="Spartiti di Jessica">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Jessica+Ligabue" title="Accordi di Jessica">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Jessica+Ligabue" title="Testi di Jessica">testi</a><br>
<b>9</b>. Vicious - <a target="_blank" href="http://www.google.com/search?q=spartiti+Vicious+Ligabue" title="Spartiti di Vicious">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Vicious+Ligabue" title="Accordi di Vicious">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Vicious+Ligabue" title="Testi di Vicious">testi</a><br>
<b>10</b>. Sweet Home Alabama - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sweet+Home+Alabama+Ligabue" title="Spartiti di Sweet Home Alabama">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sweet+Home+Alabama+Ligabue" title="Accordi di Sweet Home Alabama">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sweet+Home+Alabama+Ligabue" title="Testi di Sweet Home Alabama">testi</a><br>
<b>11</b>. Willin' - <a target="_blank" href="http://www.google.com/search?q=spartiti+Willin%27+Ligabue" title="Spartiti di Willin'">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Willin%27+Ligabue" title="Accordi di Willin'">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Willin%27+Ligabue" title="Testi di Willin'">testi</a><br>
<b>12</b>. Run Through The Jungle - <a target="_blank" href="http://www.google.com/search?q=spartiti+Run+Through+The+Jungle+Ligabue" title="Spartiti di Run Through The Jungle">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Run+Through+The+Jungle+Ligabue" title="Accordi di Run Through The Jungle">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Run+Through+The+Jungle+Ligabue" title="Testi di Run Through The Jungle">testi</a><br>
<b>13</b>. Year of The Cat - <a target="_blank" href="http://www.google.com/search?q=spartiti+Year+of+The+Cat+Ligabue" title="Spartiti di Year of The Cat">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Year+of+The+Cat+Ligabue" title="Accordi di Year of The Cat">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Year+of+The+Cat+Ligabue" title="Testi di Year of The Cat">testi</a><br>
<b>14</b>. Sing A Song - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sing+A+Song+Ligabue" title="Spartiti di Sing A Song">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sing+A+Song+Ligabue" title="Accordi di Sing A Song">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sing+A+Song+Ligabue" title="Testi di Sing A Song">testi</a><br>
<b>15</b>. Incontro - <a target="_blank" href="http://www.google.com/search?q=spartiti+Incontro+Ligabue" title="Spartiti di Incontro">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Incontro+Ligabue" title="Accordi di Incontro">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Incontro+Ligabue" title="Testi di Incontro">testi</a><br>
<b>16</b>. Black Market - <a target="_blank" href="http://www.google.com/search?q=spartiti+Black+Market+Ligabue" title="Spartiti di Black Market">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Black+Market+Ligabue" title="Accordi di Black Market">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Black+Market+Ligabue" title="Testi di Black Market">testi</a><br>
<h2>Radiofreccia: Le Canzoni (Cd 1) (1998) </h2>
<b>1</b>. Radiofreccia - <a target="_blank" href="http://www.google.com/search?q=spartiti+Radiofreccia+Ligabue" title="Spartiti di Radiofreccia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Radiofreccia+Ligabue" title="Accordi di Radiofreccia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Radiofreccia+Ligabue" title="Testi di Radiofreccia">testi</a><br>
<b>2</b>. Ho Perso Le Parole - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ho+Perso+Le+Parole+Ligabue" title="Spartiti di Ho Perso Le Parole">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ho+Perso+Le+Parole+Ligabue" title="Accordi di Ho Perso Le Parole">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ho+Perso+Le+Parole+Ligabue" title="Testi di Ho Perso Le Parole">testi</a><br>
<b>3</b>. Welcome Home, Freccia - <a target="_blank" href="http://www.google.com/search?q=spartiti+Welcome+Home%2C+Freccia+Ligabue" title="Spartiti di Welcome Home, Freccia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Welcome+Home%2C+Freccia+Ligabue" title="Accordi di Welcome Home, Freccia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Welcome+Home%2C+Freccia+Ligabue" title="Testi di Welcome Home, Freccia">testi</a><br>
<b>4</b>. Bordocampo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Bordocampo+Ligabue" title="Spartiti di Bordocampo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Bordocampo+Ligabue" title="Accordi di Bordocampo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Bordocampo+Ligabue" title="Testi di Bordocampo">testi</a><br>
<b>5</b>. Freccia - <a target="_blank" href="http://www.google.com/search?q=spartiti+Freccia+Ligabue" title="Spartiti di Freccia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Freccia+Ligabue" title="Accordi di Freccia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Freccia+Ligabue" title="Testi di Freccia">testi</a><br>
<b>6</b>. Metti In Circolo Il Tuo Amore - <a target="_blank" href="http://www.google.com/search?q=spartiti+Metti+In+Circolo+Il+Tuo+Amore+Ligabue" title="Spartiti di Metti In Circolo Il Tuo Amore">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Metti+In+Circolo+Il+Tuo+Amore+Ligabue" title="Accordi di Metti In Circolo Il Tuo Amore">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Metti+In+Circolo+Il+Tuo+Amore+Ligabue" title="Testi di Metti In Circolo Il Tuo Amore">testi</a><br>
<b>7</b>. Da Marzia - <a target="_blank" href="http://www.google.com/search?q=spartiti+Da+Marzia+Ligabue" title="Spartiti di Da Marzia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Da+Marzia+Ligabue" title="Accordi di Da Marzia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Da+Marzia+Ligabue" title="Testi di Da Marzia">testi</a><br>
<b>8</b>. Prima Pagina Del Libro D'oro - <a target="_blank" href="http://www.google.com/search?q=spartiti+Prima+Pagina+Del+Libro+D%27oro+Ligabue" title="Spartiti di Prima Pagina Del Libro D'oro">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Prima+Pagina+Del+Libro+D%27oro+Ligabue" title="Accordi di Prima Pagina Del Libro D'oro">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Prima+Pagina+Del+Libro+D%27oro+Ligabue" title="Testi di Prima Pagina Del Libro D'oro">testi</a><br>
<b>9</b>. Mezzanotte di Fuoco - <a target="_blank" href="http://www.google.com/search?q=spartiti+Mezzanotte+di+Fuoco+Ligabue" title="Spartiti di Mezzanotte di Fuoco">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Mezzanotte+di+Fuoco+Ligabue" title="Accordi di Mezzanotte di Fuoco">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Mezzanotte+di+Fuoco+Ligabue" title="Testi di Mezzanotte di Fuoco">testi</a><br>
<b>10</b>. Boris Segna Il Territorio - <a target="_blank" href="http://www.google.com/search?q=spartiti+Boris+Segna+Il+Territorio+Ligabue" title="Spartiti di Boris Segna Il Territorio">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Boris+Segna+Il+Territorio+Ligabue" title="Accordi di Boris Segna Il Territorio">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Boris+Segna+Il+Territorio+Ligabue" title="Testi di Boris Segna Il Territorio">testi</a><br>
<b>11</b>. Pesce-siluro - <a target="_blank" href="http://www.google.com/search?q=spartiti+Pesce-siluro+Ligabue" title="Spartiti di Pesce-siluro">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Pesce-siluro+Ligabue" title="Accordi di Pesce-siluro">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Pesce-siluro+Ligabue" title="Testi di Pesce-siluro">testi</a><br>
<b>12</b>. Siamo In Onda - <a target="_blank" href="http://www.google.com/search?q=spartiti+Siamo+In+Onda+Ligabue" title="Spartiti di Siamo In Onda">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Siamo+In+Onda+Ligabue" title="Accordi di Siamo In Onda">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Siamo+In+Onda+Ligabue" title="Testi di Siamo In Onda">testi</a><br>
<b>13</b>. Can't Help Falling In Love - <a target="_blank" href="http://www.google.com/search?q=spartiti+Can%27t+Help+Falling+In+Love+Ligabue" title="Spartiti di Can't Help Falling In Love">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Can%27t+Help+Falling+In+Love+Ligabue" title="Accordi di Can't Help Falling In Love">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Can%27t+Help+Falling+In+Love+Ligabue" title="Testi di Can't Help Falling In Love">testi</a><br>
<h2>Su E Giù Da Un Palco (Cd 2) (1997) </h2>
<b>1</b>. Tra Palco E Realtà - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tra+Palco+E+Realt%E0+Ligabue" title="Spartiti di Tra Palco E Realtà">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tra+Palco+E+Realt%E0+Ligabue" title="Accordi di Tra Palco E Realtà">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tra+Palco+E+Realt%E0+Ligabue" title="Testi di Tra Palco E Realtà">testi</a><br>
<b>2</b>. Sogni Di Rock'n'Roll - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sogni+Di+Rock%27n%27Roll+Ligabue" title="Spartiti di Sogni Di Rock'n'Roll">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sogni+Di+Rock%27n%27Roll+Ligabue" title="Accordi di Sogni Di Rock'n'Roll">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sogni+Di+Rock%27n%27Roll+Ligabue" title="Testi di Sogni Di Rock'n'Roll">testi</a><br>
<b>3</b>. Buon Compleanno, Elvis! - <a target="_blank" href="http://www.google.com/search?q=spartiti+Buon+Compleanno%2C+Elvis%21+Ligabue" title="Spartiti di Buon Compleanno, Elvis!">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Buon+Compleanno%2C+Elvis%21+Ligabue" title="Accordi di Buon Compleanno, Elvis!">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Buon+Compleanno%2C+Elvis%21+Ligabue" title="Testi di Buon Compleanno, Elvis!">testi</a><br>
<b>4</b>. Lambrusco E Pop Corn - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lambrusco+E+Pop+Corn+Ligabue" title="Spartiti di Lambrusco E Pop Corn">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lambrusco+E+Pop+Corn+Ligabue" title="Accordi di Lambrusco E Pop Corn">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lambrusco+E+Pop+Corn+Ligabue" title="Testi di Lambrusco E Pop Corn">testi</a><br>
<b>5</b>. Il Cielo E' Vuoto O Il Cielo E' Pieno - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Cielo+E%27+Vuoto+O+Il+Cielo+E%27+Pieno+Ligabue" title="Spartiti di Il Cielo E' Vuoto O Il Cielo E' Pieno">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Cielo+E%27+Vuoto+O+Il+Cielo+E%27+Pieno+Ligabue" title="Accordi di Il Cielo E' Vuoto O Il Cielo E' Pieno">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Cielo+E%27+Vuoto+O+Il+Cielo+E%27+Pieno+Ligabue" title="Testi di Il Cielo E' Vuoto O Il Cielo E' Pieno">testi</a><br>
<b>6</b>. Bambolina E Barracuda - <a target="_blank" href="http://www.google.com/search?q=spartiti+Bambolina+E+Barracuda+Ligabue" title="Spartiti di Bambolina E Barracuda">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Bambolina+E+Barracuda+Ligabue" title="Accordi di Bambolina E Barracuda">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Bambolina+E+Barracuda+Ligabue" title="Testi di Bambolina E Barracuda">testi</a><br>
<b>7</b>. Lo Zoo E' Qui - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lo+Zoo+E%27+Qui+Ligabue" title="Spartiti di Lo Zoo E' Qui">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lo+Zoo+E%27+Qui+Ligabue" title="Accordi di Lo Zoo E' Qui">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lo+Zoo+E%27+Qui+Ligabue" title="Testi di Lo Zoo E' Qui">testi</a><br>
<b>8</b>. Piccola Stella Senza Cielo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Piccola+Stella+Senza+Cielo+Ligabue" title="Spartiti di Piccola Stella Senza Cielo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Piccola+Stella+Senza+Cielo+Ligabue" title="Accordi di Piccola Stella Senza Cielo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Piccola+Stella+Senza+Cielo+Ligabue" title="Testi di Piccola Stella Senza Cielo">testi</a><br>
<b>9</b>. Vivo Morto o X - <a target="_blank" href="http://www.google.com/search?q=spartiti+Vivo+Morto+o+X+Ligabue" title="Spartiti di Vivo Morto o X">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Vivo+Morto+o+X+Ligabue" title="Accordi di Vivo Morto o X">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Vivo+Morto+o+X+Ligabue" title="Testi di Vivo Morto o X">testi</a><br>
<b>10</b>. Certe Notti - <a target="_blank" href="http://www.google.com/search?q=spartiti+Certe+Notti+Ligabue" title="Spartiti di Certe Notti">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Certe+Notti+Ligabue" title="Accordi di Certe Notti">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Certe+Notti+Ligabue" title="Testi di Certe Notti">testi</a><br>
<b>11</b>. Non E' Tempo Per Noi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Non+E%27+Tempo+Per+Noi+Ligabue" title="Spartiti di Non E' Tempo Per Noi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Non+E%27+Tempo+Per+Noi+Ligabue" title="Accordi di Non E' Tempo Per Noi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Non+E%27+Tempo+Per+Noi+Ligabue" title="Testi di Non E' Tempo Per Noi">testi</a><br>
<b>12</b>. Libera Nos A Malo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Libera+Nos+A+Malo+Ligabue" title="Spartiti di Libera Nos A Malo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Libera+Nos+A+Malo+Ligabue" title="Accordi di Libera Nos A Malo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Libera+Nos+A+Malo+Ligabue" title="Testi di Libera Nos A Malo">testi</a><br>
<b>13</b>. Balliamo Sul Mondo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Balliamo+Sul+Mondo+Ligabue" title="Spartiti di Balliamo Sul Mondo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Balliamo+Sul+Mondo+Ligabue" title="Accordi di Balliamo Sul Mondo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Balliamo+Sul+Mondo+Ligabue" title="Testi di Balliamo Sul Mondo">testi</a><br>
<b>14</b>. Leggero - <a target="_blank" href="http://www.google.com/search?q=spartiti+Leggero+Ligabue" title="Spartiti di Leggero">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Leggero+Ligabue" title="Accordi di Leggero">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Leggero+Ligabue" title="Testi di Leggero">testi</a><br>
<b>15</b>. Ultimo Tango A Memphis - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ultimo+Tango+A+Memphis+Ligabue" title="Spartiti di Ultimo Tango A Memphis">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ultimo+Tango+A+Memphis+Ligabue" title="Accordi di Ultimo Tango A Memphis">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ultimo+Tango+A+Memphis+Ligabue" title="Testi di Ultimo Tango A Memphis">testi</a><br>
<h2>Su E Giù Da Un Palco (Cd 1) (1997) </h2>
<b>1</b>. Il Giorno Del Dolore Che Uno Ha - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Giorno+Del+Dolore+Che+Uno+Ha+Ligabue" title="Spartiti di Il Giorno Del Dolore Che Uno Ha">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Giorno+Del+Dolore+Che+Uno+Ha+Ligabue" title="Accordi di Il Giorno Del Dolore Che Uno Ha">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Giorno+Del+Dolore+Che+Uno+Ha+Ligabue" title="Testi di Il Giorno Del Dolore Che Uno Ha">testi</a><br>
<b>2</b>. I Ragazzi Sono In Giro - <a target="_blank" href="http://www.google.com/search?q=spartiti+I+Ragazzi+Sono+In+Giro+Ligabue" title="Spartiti di I Ragazzi Sono In Giro">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+I+Ragazzi+Sono+In+Giro+Ligabue" title="Accordi di I Ragazzi Sono In Giro">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+I+Ragazzi+Sono+In+Giro+Ligabue" title="Testi di I Ragazzi Sono In Giro">testi</a><br>
<b>3</b>. Quella Che Non Sei - <a target="_blank" href="http://www.google.com/search?q=spartiti+Quella+Che+Non+Sei+Ligabue" title="Spartiti di Quella Che Non Sei">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Quella+Che+Non+Sei+Ligabue" title="Accordi di Quella Che Non Sei">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Quella+Che+Non+Sei+Ligabue" title="Testi di Quella Che Non Sei">testi</a><br>
<b>4</b>. Hai Un Momento, Dio? - <a target="_blank" href="http://www.google.com/search?q=spartiti+Hai+Un+Momento%2C+Dio%3F+Ligabue" title="Spartiti di Hai Un Momento, Dio?">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Hai+Un+Momento%2C+Dio%3F+Ligabue" title="Accordi di Hai Un Momento, Dio?">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Hai+Un+Momento%2C+Dio%3F+Ligabue" title="Testi di Hai Un Momento, Dio?">testi</a><br>
<b>5</b>. Un Figlio Di Nome Elvis - <a target="_blank" href="http://www.google.com/search?q=spartiti+Un+Figlio+Di+Nome+Elvis+Ligabue" title="Spartiti di Un Figlio Di Nome Elvis">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Un+Figlio+Di+Nome+Elvis+Ligabue" title="Accordi di Un Figlio Di Nome Elvis">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Un+Figlio+Di+Nome+Elvis+Ligabue" title="Testi di Un Figlio Di Nome Elvis">testi</a><br>
<b>6</b>. Ho Messo Via - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ho+Messo+Via+Ligabue" title="Spartiti di Ho Messo Via">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ho+Messo+Via+Ligabue" title="Accordi di Ho Messo Via">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ho+Messo+Via+Ligabue" title="Testi di Ho Messo Via">testi</a><br>
<b>7</b>. Bar Mario - <a target="_blank" href="http://www.google.com/search?q=spartiti+Bar+Mario+Ligabue" title="Spartiti di Bar Mario">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Bar+Mario+Ligabue" title="Accordi di Bar Mario">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Bar+Mario+Ligabue" title="Testi di Bar Mario">testi</a><br>
<b>8</b>. Salviamoci La Pelle - <a target="_blank" href="http://www.google.com/search?q=spartiti+Salviamoci+La+Pelle+Ligabue" title="Spartiti di Salviamoci La Pelle">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Salviamoci+La+Pelle+Ligabue" title="Accordi di Salviamoci La Pelle">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Salviamoci+La+Pelle+Ligabue" title="Testi di Salviamoci La Pelle">testi</a><br>
<b>9</b>. Figlio Di Un Cane - <a target="_blank" href="http://www.google.com/search?q=spartiti+Figlio+Di+Un+Cane+Ligabue" title="Spartiti di Figlio Di Un Cane">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Figlio+Di+Un+Cane+Ligabue" title="Accordi di Figlio Di Un Cane">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Figlio+Di+Un+Cane+Ligabue" title="Testi di Figlio Di Un Cane">testi</a><br>
<b>10</b>. Marlon Brando E' Sempre Lui - <a target="_blank" href="http://www.google.com/search?q=spartiti+Marlon+Brando+E%27+Sempre+Lui+Ligabue" title="Spartiti di Marlon Brando E' Sempre Lui">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Marlon+Brando+E%27+Sempre+Lui+Ligabue" title="Accordi di Marlon Brando E' Sempre Lui">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Marlon+Brando+E%27+Sempre+Lui+Ligabue" title="Testi di Marlon Brando E' Sempre Lui">testi</a><br>
<b>11</b>. Seduto In Riva Al Fosso - <a target="_blank" href="http://www.google.com/search?q=spartiti+Seduto+In+Riva+Al+Fosso+Ligabue" title="Spartiti di Seduto In Riva Al Fosso">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Seduto+In+Riva+Al+Fosso+Ligabue" title="Accordi di Seduto In Riva Al Fosso">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Seduto+In+Riva+Al+Fosso+Ligabue" title="Testi di Seduto In Riva Al Fosso">testi</a><br>
<b>12</b>. Viva! - <a target="_blank" href="http://www.google.com/search?q=spartiti+Viva%21+Ligabue" title="Spartiti di Viva!">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Viva%21+Ligabue" title="Accordi di Viva!">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Viva%21+Ligabue" title="Testi di Viva!">testi</a><br>
<b>13</b>. Urlando Contro Il Cielo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Urlando+Contro+Il+Cielo+Ligabue" title="Spartiti di Urlando Contro Il Cielo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Urlando+Contro+Il+Cielo+Ligabue" title="Accordi di Urlando Contro Il Cielo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Urlando+Contro+Il+Cielo+Ligabue" title="Testi di Urlando Contro Il Cielo">testi</a><br>
<b>14</b>. A Che Ora E' La Fine Del Mondo - <a target="_blank" href="http://www.google.com/search?q=spartiti+A+Che+Ora+E%27+La+Fine+Del+Mondo+Ligabue" title="Spartiti di A Che Ora E' La Fine Del Mondo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+A+Che+Ora+E%27+La+Fine+Del+Mondo+Ligabue" title="Accordi di A Che Ora E' La Fine Del Mondo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+A+Che+Ora+E%27+La+Fine+Del+Mondo+Ligabue" title="Testi di A Che Ora E' La Fine Del Mondo">testi</a><br>
<h2>Buon Compleanno, Elvis! (1995) </h2>
<b>1</b>. Vivo Morto o X - <a target="_blank" href="http://www.google.com/search?q=spartiti+Vivo+Morto+o+X+Ligabue" title="Spartiti di Vivo Morto o X">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Vivo+Morto+o+X+Ligabue" title="Accordi di Vivo Morto o X">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Vivo+Morto+o+X+Ligabue" title="Testi di Vivo Morto o X">testi</a><br>
<b>2</b>. Seduto In Riva Al Fosso - <a target="_blank" href="http://www.google.com/search?q=spartiti+Seduto+In+Riva+Al+Fosso+Ligabue" title="Spartiti di Seduto In Riva Al Fosso">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Seduto+In+Riva+Al+Fosso+Ligabue" title="Accordi di Seduto In Riva Al Fosso">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Seduto+In+Riva+Al+Fosso+Ligabue" title="Testi di Seduto In Riva Al Fosso">testi</a><br>
<b>3</b>. Buon Compleanno, Elvis! - <a target="_blank" href="http://www.google.com/search?q=spartiti+Buon+Compleanno%2C+Elvis%21+Ligabue" title="Spartiti di Buon Compleanno, Elvis!">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Buon+Compleanno%2C+Elvis%21+Ligabue" title="Accordi di Buon Compleanno, Elvis!">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Buon+Compleanno%2C+Elvis%21+Ligabue" title="Testi di Buon Compleanno, Elvis!">testi</a><br>
<b>4</b>. La Forza Della Banda - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Forza+Della+Banda+Ligabue" title="Spartiti di La Forza Della Banda">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Forza+Della+Banda+Ligabue" title="Accordi di La Forza Della Banda">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Forza+Della+Banda+Ligabue" title="Testi di La Forza Della Banda">testi</a><br>
<b>5</b>. Hai Un Momento, Dio? - <a target="_blank" href="http://www.google.com/search?q=spartiti+Hai+Un+Momento%2C+Dio%3F+Ligabue" title="Spartiti di Hai Un Momento, Dio?">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Hai+Un+Momento%2C+Dio%3F+Ligabue" title="Accordi di Hai Un Momento, Dio?">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Hai+Un+Momento%2C+Dio%3F+Ligabue" title="Testi di Hai Un Momento, Dio?">testi</a><br>
<b>6</b>. Rane a Rubiera Blues - <a target="_blank" href="http://www.google.com/search?q=spartiti+Rane+a+Rubiera+Blues+Ligabue" title="Spartiti di Rane a Rubiera Blues">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Rane+a+Rubiera+Blues+Ligabue" title="Accordi di Rane a Rubiera Blues">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Rane+a+Rubiera+Blues+Ligabue" title="Testi di Rane a Rubiera Blues">testi</a><br>
<b>7</b>. Certe Notti - <a target="_blank" href="http://www.google.com/search?q=spartiti+Certe+Notti+Ligabue" title="Spartiti di Certe Notti">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Certe+Notti+Ligabue" title="Accordi di Certe Notti">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Certe+Notti+Ligabue" title="Testi di Certe Notti">testi</a><br>
<b>8</b>. Viva! - <a target="_blank" href="http://www.google.com/search?q=spartiti+Viva%21+Ligabue" title="Spartiti di Viva!">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Viva%21+Ligabue" title="Accordi di Viva!">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Viva%21+Ligabue" title="Testi di Viva!">testi</a><br>
<b>9</b>. I Ragazzi Sono In Giro - <a target="_blank" href="http://www.google.com/search?q=spartiti+I+Ragazzi+Sono+In+Giro+Ligabue" title="Spartiti di I Ragazzi Sono In Giro">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+I+Ragazzi+Sono+In+Giro+Ligabue" title="Accordi di I Ragazzi Sono In Giro">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+I+Ragazzi+Sono+In+Giro+Ligabue" title="Testi di I Ragazzi Sono In Giro">testi</a><br>
<b>10</b>. Quella Che Non Sei - <a target="_blank" href="http://www.google.com/search?q=spartiti+Quella+Che+Non+Sei+Ligabue" title="Spartiti di Quella Che Non Sei">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Quella+Che+Non+Sei+Ligabue" title="Accordi di Quella Che Non Sei">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Quella+Che+Non+Sei+Ligabue" title="Testi di Quella Che Non Sei">testi</a><br>
<b>11</b>. Non Dovete Badare Al Cantante - <a target="_blank" href="http://www.google.com/search?q=spartiti+Non+Dovete+Badare+Al+Cantante+Ligabue" title="Spartiti di Non Dovete Badare Al Cantante">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Non+Dovete+Badare+Al+Cantante+Ligabue" title="Accordi di Non Dovete Badare Al Cantante">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Non+Dovete+Badare+Al+Cantante+Ligabue" title="Testi di Non Dovete Badare Al Cantante">testi</a><br>
<b>12</b>. Un Figlio Di Nome Elvis - <a target="_blank" href="http://www.google.com/search?q=spartiti+Un+Figlio+Di+Nome+Elvis+Ligabue" title="Spartiti di Un Figlio Di Nome Elvis">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Un+Figlio+Di+Nome+Elvis+Ligabue" title="Accordi di Un Figlio Di Nome Elvis">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Un+Figlio+Di+Nome+Elvis+Ligabue" title="Testi di Un Figlio Di Nome Elvis">testi</a><br>
<b>13</b>. Il Cielo E' Vuoto O Il Cielo E' Pieno - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Cielo+E%27+Vuoto+O+Il+Cielo+E%27+Pieno+Ligabue" title="Spartiti di Il Cielo E' Vuoto O Il Cielo E' Pieno">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Cielo+E%27+Vuoto+O+Il+Cielo+E%27+Pieno+Ligabue" title="Accordi di Il Cielo E' Vuoto O Il Cielo E' Pieno">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Cielo+E%27+Vuoto+O+Il+Cielo+E%27+Pieno+Ligabue" title="Testi di Il Cielo E' Vuoto O Il Cielo E' Pieno">testi</a><br>
<b>14</b>. Leggero - <a target="_blank" href="http://www.google.com/search?q=spartiti+Leggero+Ligabue" title="Spartiti di Leggero">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Leggero+Ligabue" title="Accordi di Leggero">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Leggero+Ligabue" title="Testi di Leggero">testi</a><br>
<h2>A Che Ora E' La Fine Del Mondo? (1994) </h2>
<b>1</b>. A Che Ora E' La Fine Del Mondo? - <a target="_blank" href="http://www.google.com/search?q=spartiti+A+Che+Ora+E%27+La+Fine+Del+Mondo%3F+Ligabue" title="Spartiti di A Che Ora E' La Fine Del Mondo?">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+A+Che+Ora+E%27+La+Fine+Del+Mondo%3F+Ligabue" title="Accordi di A Che Ora E' La Fine Del Mondo?">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+A+Che+Ora+E%27+La+Fine+Del+Mondo%3F+Ligabue" title="Testi di A Che Ora E' La Fine Del Mondo?">testi</a><br>
<b>2</b>. Male Non Farà - <a target="_blank" href="http://www.google.com/search?q=spartiti+Male+Non+Far%E0+Ligabue" title="Spartiti di Male Non Farà">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Male+Non+Far%E0+Ligabue" title="Accordi di Male Non Farà">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Male+Non+Far%E0+Ligabue" title="Testi di Male Non Farà">testi</a><br>
<b>3</b>. Cerca Nel Cuore - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cerca+Nel+Cuore+Ligabue" title="Spartiti di Cerca Nel Cuore">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cerca+Nel+Cuore+Ligabue" title="Accordi di Cerca Nel Cuore">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cerca+Nel+Cuore+Ligabue" title="Testi di Cerca Nel Cuore">testi</a><br>
<b>4</b>. Fuoritempo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Fuoritempo+Ligabue" title="Spartiti di Fuoritempo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Fuoritempo+Ligabue" title="Accordi di Fuoritempo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Fuoritempo+Ligabue" title="Testi di Fuoritempo">testi</a><br>
<b>5</b>. Il Gringo '94 - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Gringo+%2794+Ligabue" title="Spartiti di Il Gringo '94">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Gringo+%2794+Ligabue" title="Accordi di Il Gringo '94">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Gringo+%2794+Ligabue" title="Testi di Il Gringo '94">testi</a><br>
<b>6</b>. Il Gringo '91 - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Gringo+%2791+Ligabue" title="Spartiti di Il Gringo '91">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Gringo+%2791+Ligabue" title="Accordi di Il Gringo '91">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Gringo+%2791+Ligabue" title="Testi di Il Gringo '91">testi</a><br>
<b>7</b>. L'han Detto Anche Gli Stones - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%27han+Detto+Anche+Gli+Stones+Ligabue" title="Spartiti di L'han Detto Anche Gli Stones">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%27han+Detto+Anche+Gli+Stones+Ligabue" title="Accordi di L'han Detto Anche Gli Stones">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%27han+Detto+Anche+Gli+Stones+Ligabue" title="Testi di L'han Detto Anche Gli Stones">testi</a><br>
<b>8</b>. Urlando Contro Il Cielo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Urlando+Contro+Il+Cielo+Ligabue" title="Spartiti di Urlando Contro Il Cielo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Urlando+Contro+Il+Cielo+Ligabue" title="Accordi di Urlando Contro Il Cielo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Urlando+Contro+Il+Cielo+Ligabue" title="Testi di Urlando Contro Il Cielo">testi</a><br>
<h2>Sopravvissuti e Sopravviventi (1993) </h2>
<b>1</b>. Ancora In Piedi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ancora+In+Piedi+Ligabue" title="Spartiti di Ancora In Piedi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ancora+In+Piedi+Ligabue" title="Accordi di Ancora In Piedi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ancora+In+Piedi+Ligabue" title="Testi di Ancora In Piedi">testi</a><br>
<b>2</b>. A.A.A. Qualcuno Cercasi - <a target="_blank" href="http://www.google.com/search?q=spartiti+A.A.A.+Qualcuno+Cercasi+Ligabue" title="Spartiti di A.A.A. Qualcuno Cercasi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+A.A.A.+Qualcuno+Cercasi+Ligabue" title="Accordi di A.A.A. Qualcuno Cercasi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+A.A.A.+Qualcuno+Cercasi+Ligabue" title="Testi di A.A.A. Qualcuno Cercasi">testi</a><br>
<b>3</b>. Ho Messo Via - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ho+Messo+Via+Ligabue" title="Spartiti di Ho Messo Via">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ho+Messo+Via+Ligabue" title="Accordi di Ho Messo Via">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ho+Messo+Via+Ligabue" title="Testi di Ho Messo Via">testi</a><br>
<b>4</b>. Dove Fermano I Treni - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dove+Fermano+I+Treni+Ligabue" title="Spartiti di Dove Fermano I Treni">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dove+Fermano+I+Treni+Ligabue" title="Accordi di Dove Fermano I Treni">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dove+Fermano+I+Treni+Ligabue" title="Testi di Dove Fermano I Treni">testi</a><br>
<b>5</b>. I Duri Che Hanno Due Cuori - <a target="_blank" href="http://www.google.com/search?q=spartiti+I+Duri+Che+Hanno+Due+Cuori+Ligabue" title="Spartiti di I Duri Che Hanno Due Cuori">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+I+Duri+Che+Hanno+Due+Cuori+Ligabue" title="Accordi di I Duri Che Hanno Due Cuori">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+I+Duri+Che+Hanno+Due+Cuori+Ligabue" title="Testi di I Duri Che Hanno Due Cuori">testi</a><br>
<b>6</b>. La Ballerina Del Carillon - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Ballerina+Del+Carillon+Ligabue" title="Spartiti di La Ballerina Del Carillon">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Ballerina+Del+Carillon+Ligabue" title="Accordi di La Ballerina Del Carillon">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Ballerina+Del+Carillon+Ligabue" title="Testi di La Ballerina Del Carillon">testi</a><br>
<b>7</b>. Prezoo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Prezoo+Ligabue" title="Spartiti di Prezoo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Prezoo+Ligabue" title="Accordi di Prezoo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Prezoo+Ligabue" title="Testi di Prezoo">testi</a><br>
<b>8</b>. Lo Zoo E' Qui - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lo+Zoo+E%27+Qui+Ligabue" title="Spartiti di Lo Zoo E' Qui">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lo+Zoo+E%27+Qui+Ligabue" title="Accordi di Lo Zoo E' Qui">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lo+Zoo+E%27+Qui+Ligabue" title="Testi di Lo Zoo E' Qui">testi</a><br>
<b>9</b>. Piccola Città Eterna - <a target="_blank" href="http://www.google.com/search?q=spartiti+Piccola+Citt%E0+Eterna+Ligabue" title="Spartiti di Piccola Città Eterna">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Piccola+Citt%E0+Eterna+Ligabue" title="Accordi di Piccola Città Eterna">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Piccola+Citt%E0+Eterna+Ligabue" title="Testi di Piccola Città Eterna">testi</a><br>
<b>10</b>. Walter Il Mago - <a target="_blank" href="http://www.google.com/search?q=spartiti+Walter+Il+Mago+Ligabue" title="Spartiti di Walter Il Mago">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Walter+Il+Mago+Ligabue" title="Accordi di Walter Il Mago">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Walter+Il+Mago+Ligabue" title="Testi di Walter Il Mago">testi</a><br>
<b>11</b>. Pane Al Pane - <a target="_blank" href="http://www.google.com/search?q=spartiti+Pane+Al+Pane+Ligabue" title="Spartiti di Pane Al Pane">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Pane+Al+Pane+Ligabue" title="Accordi di Pane Al Pane">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Pane+Al+Pane+Ligabue" title="Testi di Pane Al Pane">testi</a><br>
<b>12</b>. Quando Tocca A Te - <a target="_blank" href="http://www.google.com/search?q=spartiti+Quando+Tocca+A+Te+Ligabue" title="Spartiti di Quando Tocca A Te">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Quando+Tocca+A+Te+Ligabue" title="Accordi di Quando Tocca A Te">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Quando+Tocca+A+Te+Ligabue" title="Testi di Quando Tocca A Te">testi</a><br>
<b>13</b>. Tema - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tema+Ligabue" title="Spartiti di Tema">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tema+Ligabue" title="Accordi di Tema">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tema+Ligabue" title="Testi di Tema">testi</a><br>
<h2>Lambrusco, Coltelli, Rose E Pop-corn (1991) </h2>
<b>1</b>. Salviamoci La Pelle - <a target="_blank" href="http://www.google.com/search?q=spartiti+Salviamoci+La+Pelle+Ligabue" title="Spartiti di Salviamoci La Pelle">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Salviamoci+La+Pelle+Ligabue" title="Accordi di Salviamoci La Pelle">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Salviamoci+La+Pelle+Ligabue" title="Testi di Salviamoci La Pelle">testi</a><br>
<b>2</b>. Lambrusco E Popcorn - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lambrusco+E+Popcorn+Ligabue" title="Spartiti di Lambrusco E Popcorn">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lambrusco+E+Popcorn+Ligabue" title="Accordi di Lambrusco E Popcorn">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lambrusco+E+Popcorn+Ligabue" title="Testi di Lambrusco E Popcorn">testi</a><br>
<b>3</b>. Camera Con Vista Sul Deserto - <a target="_blank" href="http://www.google.com/search?q=spartiti+Camera+Con+Vista+Sul+Deserto+Ligabue" title="Spartiti di Camera Con Vista Sul Deserto">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Camera+Con+Vista+Sul+Deserto+Ligabue" title="Accordi di Camera Con Vista Sul Deserto">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Camera+Con+Vista+Sul+Deserto+Ligabue" title="Testi di Camera Con Vista Sul Deserto">testi</a><br>
<b>4</b>. Anime In Plexiglass - <a target="_blank" href="http://www.google.com/search?q=spartiti+Anime+In+Plexiglass+Ligabue" title="Spartiti di Anime In Plexiglass">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Anime+In+Plexiglass+Ligabue" title="Accordi di Anime In Plexiglass">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Anime+In+Plexiglass+Ligabue" title="Testi di Anime In Plexiglass">testi</a><br>
<b>5</b>. Con Queste Facce Qui - <a target="_blank" href="http://www.google.com/search?q=spartiti+Con+Queste+Facce+Qui+Ligabue" title="Spartiti di Con Queste Facce Qui">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Con+Queste+Facce+Qui+Ligabue" title="Accordi di Con Queste Facce Qui">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Con+Queste+Facce+Qui+Ligabue" title="Testi di Con Queste Facce Qui">testi</a><br>
<b>6</b>. Sarà Un Bel Souvenir - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sar%E0+Un+Bel+Souvenir+Ligabue" title="Spartiti di Sarà Un Bel Souvenir">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sar%E0+Un+Bel+Souvenir+Ligabue" title="Accordi di Sarà Un Bel Souvenir">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sar%E0+Un+Bel+Souvenir+Ligabue" title="Testi di Sarà Un Bel Souvenir">testi</a><br>
<b>7</b>. Intro - <a target="_blank" href="http://www.google.com/search?q=spartiti+Intro+Ligabue" title="Spartiti di Intro">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Intro+Ligabue" title="Accordi di Intro">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Intro+Ligabue" title="Testi di Intro">testi</a><br>
<b>8</b>. Libera Nos A Malo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Libera+Nos+A+Malo+Ligabue" title="Spartiti di Libera Nos A Malo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Libera+Nos+A+Malo+Ligabue" title="Accordi di Libera Nos A Malo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Libera+Nos+A+Malo+Ligabue" title="Testi di Libera Nos A Malo">testi</a><br>
<b>9</b>. Ti Chiamerò Sam (Se Suoni Bene) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ti+Chiamer%F2+Sam+%28Se+Suoni+Bene%29+Ligabue" title="Spartiti di Ti Chiamerò Sam (Se Suoni Bene)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ti+Chiamer%F2+Sam+%28Se+Suoni+Bene%29+Ligabue" title="Accordi di Ti Chiamerò Sam (Se Suoni Bene)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ti+Chiamer%F2+Sam+%28Se+Suoni+Bene%29+Ligabue" title="Testi di Ti Chiamerò Sam (Se Suoni Bene)">testi</a><br>
<b>10</b>. Urlando Contro Il Cielo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Urlando+Contro+Il+Cielo+Ligabue" title="Spartiti di Urlando Contro Il Cielo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Urlando+Contro+Il+Cielo+Ligabue" title="Accordi di Urlando Contro Il Cielo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Urlando+Contro+Il+Cielo+Ligabue" title="Testi di Urlando Contro Il Cielo">testi</a><br>
<b>11</b>. Regalami Il Tuo Sogno - <a target="_blank" href="http://www.google.com/search?q=spartiti+Regalami+Il+Tuo+Sogno+Ligabue" title="Spartiti di Regalami Il Tuo Sogno">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Regalami+Il+Tuo+Sogno+Ligabue" title="Accordi di Regalami Il Tuo Sogno">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Regalami+Il+Tuo+Sogno+Ligabue" title="Testi di Regalami Il Tuo Sogno">testi</a><br>
<h2>Ligabue (1990) </h2>
<b>1</b>. Balliamo Sul Mondo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Balliamo+Sul+Mondo+Ligabue" title="Spartiti di Balliamo Sul Mondo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Balliamo+Sul+Mondo+Ligabue" title="Accordi di Balliamo Sul Mondo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Balliamo+Sul+Mondo+Ligabue" title="Testi di Balliamo Sul Mondo">testi</a><br>
<b>2</b>. Bambolina E Barracuda - <a target="_blank" href="http://www.google.com/search?q=spartiti+Bambolina+E+Barracuda+Ligabue" title="Spartiti di Bambolina E Barracuda">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Bambolina+E+Barracuda+Ligabue" title="Accordi di Bambolina E Barracuda">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Bambolina+E+Barracuda+Ligabue" title="Testi di Bambolina E Barracuda">testi</a><br>
<b>3</b>. Piccola Stella Senza Cielo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Piccola+Stella+Senza+Cielo+Ligabue" title="Spartiti di Piccola Stella Senza Cielo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Piccola+Stella+Senza+Cielo+Ligabue" title="Accordi di Piccola Stella Senza Cielo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Piccola+Stella+Senza+Cielo+Ligabue" title="Testi di Piccola Stella Senza Cielo">testi</a><br>
<b>4</b>. Non E' Tempo Per Noi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Non+E%27+Tempo+Per+Noi+Ligabue" title="Spartiti di Non E' Tempo Per Noi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Non+E%27+Tempo+Per+Noi+Ligabue" title="Accordi di Non E' Tempo Per Noi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Non+E%27+Tempo+Per+Noi+Ligabue" title="Testi di Non E' Tempo Per Noi">testi</a><br>
<b>5</b>. Bar Mario - <a target="_blank" href="http://www.google.com/search?q=spartiti+Bar+Mario+Ligabue" title="Spartiti di Bar Mario">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Bar+Mario+Ligabue" title="Accordi di Bar Mario">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Bar+Mario+Ligabue" title="Testi di Bar Mario">testi</a><br>
<b>6</b>. Marlon Brando E' Sempre Lui - <a target="_blank" href="http://www.google.com/search?q=spartiti+Marlon+Brando+E%27+Sempre+Lui+Ligabue" title="Spartiti di Marlon Brando E' Sempre Lui">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Marlon+Brando+E%27+Sempre+Lui+Ligabue" title="Accordi di Marlon Brando E' Sempre Lui">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Marlon+Brando+E%27+Sempre+Lui+Ligabue" title="Testi di Marlon Brando E' Sempre Lui">testi</a><br>
<b>7</b>. Sogni Di Rock n' Roll - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sogni+Di+Rock+n%27+Roll+Ligabue" title="Spartiti di Sogni Di Rock n' Roll">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sogni+Di+Rock+n%27+Roll+Ligabue" title="Accordi di Sogni Di Rock n' Roll">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sogni+Di+Rock+n%27+Roll+Ligabue" title="Testi di Sogni Di Rock n' Roll">testi</a><br>
<b>8</b>. Radio Radianti - <a target="_blank" href="http://www.google.com/search?q=spartiti+Radio+Radianti+Ligabue" title="Spartiti di Radio Radianti">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Radio+Radianti+Ligabue" title="Accordi di Radio Radianti">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Radio+Radianti+Ligabue" title="Testi di Radio Radianti">testi</a><br>
<b>9</b>. Freddo Cane In Questa Palude - <a target="_blank" href="http://www.google.com/search?q=spartiti+Freddo+Cane+In+Questa+Palude+Ligabue" title="Spartiti di Freddo Cane In Questa Palude">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Freddo+Cane+In+Questa+Palude+Ligabue" title="Accordi di Freddo Cane In Questa Palude">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Freddo+Cane+In+Questa+Palude+Ligabue" title="Testi di Freddo Cane In Questa Palude">testi</a><br>
<b>10</b>. Angelo Della Nebbia - <a target="_blank" href="http://www.google.com/search?q=spartiti+Angelo+Della+Nebbia+Ligabue" title="Spartiti di Angelo Della Nebbia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Angelo+Della+Nebbia+Ligabue" title="Accordi di Angelo Della Nebbia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Angelo+Della+Nebbia+Ligabue" title="Testi di Angelo Della Nebbia">testi</a><br>
<b>11</b>. Figlio Di Un Cane - <a target="_blank" href="http://www.google.com/search?q=spartiti+Figlio+Di+Un+Cane+Ligabue" title="Spartiti di Figlio Di Un Cane">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Figlio+Di+Un+Cane+Ligabue" title="Accordi di Figlio Di Un Cane">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Figlio+Di+Un+Cane+Ligabue" title="Testi di Figlio Di Un Cane">testi</a><br>
<h2>Anime In Plexiglass (1989) </h2>
<b>1</b>. Anime In Plexiglass - <a target="_blank" href="http://www.google.com/search?q=spartiti+Anime+In+Plexiglass+Ligabue" title="Spartiti di Anime In Plexiglass">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Anime+In+Plexiglass+Ligabue" title="Accordi di Anime In Plexiglass">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Anime+In+Plexiglass+Ligabue" title="Testi di Anime In Plexiglass">testi</a><br>
<b>2</b>. Bar Mario - <a target="_blank" href="http://www.google.com/search?q=spartiti+Bar+Mario+Ligabue" title="Spartiti di Bar Mario">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Bar+Mario+Ligabue" title="Accordi di Bar Mario">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Bar+Mario+Ligabue" title="Testi di Bar Mario">testi</a><br>
<h2><a href="<?php echo "$base_website_address/$spartiti_dir" ?>/index.html" title="Trova accordi, spartiti, tablature e testi di tantissimi artisti">Torna all'indice degli artisti</a></h2>
