<!--
title: Trova spartiti per chitarra, accordi, testi e tablature di Raf. Discografia Raf.
description: Trova tutti gli spartiti, accordi, testi e tablature di Raf. Discografia Raf.
keywords: Discografia, Raf, spartiti, accordi, testi, tablature
template: tablature
-->
<h1>Trova spartiti per chitarra, accordi, testi e tablature di Raf</h1><h2>Leggere gli spartiti per chitarra, gli accordi e le tablature:</h2>
<?php require("tabdescription.php"); ?>
<?php require("adsense_leaderboard.php"); ?>
<h2>Discografia Raf:</h2>
<h2>Passeggeri Distratti (2006) </h2>
<b>1</b>. Salta Più In Alto - <a target="_blank" href="http://www.google.com/search?q=spartiti+Salta+Pi%F9+In+Alto+Raf" title="Spartiti di Salta Più In Alto">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Salta+Pi%F9+In+Alto+Raf" title="Accordi di Salta Più In Alto">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Salta+Pi%F9+In+Alto+Raf" title="Testi di Salta Più In Alto">testi</a><br>
<b>2</b>. Dimentica - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dimentica+Raf" title="Spartiti di Dimentica">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dimentica+Raf" title="Accordi di Dimentica">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dimentica+Raf" title="Testi di Dimentica">testi</a><br>
<b>3</b>. Passeggeri Distratti - <a target="_blank" href="http://www.google.com/search?q=spartiti+Passeggeri+Distratti+Raf" title="Spartiti di Passeggeri Distratti">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Passeggeri+Distratti+Raf" title="Accordi di Passeggeri Distratti">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Passeggeri+Distratti+Raf" title="Testi di Passeggeri Distratti">testi</a><br>
<b>4</b>. Il Nodo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Nodo+Raf" title="Spartiti di Il Nodo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Nodo+Raf" title="Accordi di Il Nodo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Nodo+Raf" title="Testi di Il Nodo">testi</a><br>
<b>5</b>. Onde - <a target="_blank" href="http://www.google.com/search?q=spartiti+Onde+Raf" title="Spartiti di Onde">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Onde+Raf" title="Accordi di Onde">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Onde+Raf" title="Testi di Onde">testi</a><br>
<b>6</b>. Nati Ieri - <a target="_blank" href="http://www.google.com/search?q=spartiti+Nati+Ieri+Raf" title="Spartiti di Nati Ieri">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Nati+Ieri+Raf" title="Accordi di Nati Ieri">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Nati+Ieri+Raf" title="Testi di Nati Ieri">testi</a><br>
<b>7</b>. Acqua - <a target="_blank" href="http://www.google.com/search?q=spartiti+Acqua+Raf" title="Spartiti di Acqua">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Acqua+Raf" title="Accordi di Acqua">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Acqua+Raf" title="Testi di Acqua">testi</a><br>
<b>8</b>. Se Passerai Di Qui - <a target="_blank" href="http://www.google.com/search?q=spartiti+Se+Passerai+Di+Qui+Raf" title="Spartiti di Se Passerai Di Qui">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Se+Passerai+Di+Qui+Raf" title="Accordi di Se Passerai Di Qui">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Se+Passerai+Di+Qui+Raf" title="Testi di Se Passerai Di Qui">testi</a><br>
<b>9</b>. Mondi Paralleli - <a target="_blank" href="http://www.google.com/search?q=spartiti+Mondi+Paralleli+Raf" title="Spartiti di Mondi Paralleli">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Mondi+Paralleli+Raf" title="Accordi di Mondi Paralleli">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Mondi+Paralleli+Raf" title="Testi di Mondi Paralleli">testi</a><br>
<h2>Tutto Raf (2005) </h2>
<b>1</b>. Self Control - <a target="_blank" href="http://www.google.com/search?q=spartiti+Self+Control+Raf" title="Spartiti di Self Control">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Self+Control+Raf" title="Accordi di Self Control">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Self+Control+Raf" title="Testi di Self Control">testi</a><br>
<b>2</b>. Gente Di Mare - <a target="_blank" href="http://www.google.com/search?q=spartiti+Gente+Di+Mare+Raf" title="Spartiti di Gente Di Mare">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Gente+Di+Mare+Raf" title="Accordi di Gente Di Mare">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Gente+Di+Mare+Raf" title="Testi di Gente Di Mare">testi</a><br>
<b>3</b>. Inevitabile Follia - <a target="_blank" href="http://www.google.com/search?q=spartiti+Inevitabile+Follia+Raf" title="Spartiti di Inevitabile Follia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Inevitabile+Follia+Raf" title="Accordi di Inevitabile Follia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Inevitabile+Follia+Raf" title="Testi di Inevitabile Follia">testi</a><br>
<b>4</b>. Ti Pretendo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ti+Pretendo+Raf" title="Spartiti di Ti Pretendo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ti+Pretendo+Raf" title="Accordi di Ti Pretendo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ti+Pretendo+Raf" title="Testi di Ti Pretendo">testi</a><br>
<b>5</b>. La Battaglia Del Sesso - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Battaglia+Del+Sesso+Raf" title="Spartiti di La Battaglia Del Sesso">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Battaglia+Del+Sesso+Raf" title="Accordi di La Battaglia Del Sesso">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Battaglia+Del+Sesso+Raf" title="Testi di La Battaglia Del Sesso">testi</a><br>
<b>6</b>. Cosa Resterà Degli Anni '80 - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cosa+Rester%E0+Degli+Anni+%2780+Raf" title="Spartiti di Cosa Resterà Degli Anni '80">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cosa+Rester%E0+Degli+Anni+%2780+Raf" title="Accordi di Cosa Resterà Degli Anni '80">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cosa+Rester%E0+Degli+Anni+%2780+Raf" title="Testi di Cosa Resterà Degli Anni '80">testi</a><br>
<b>7</b>. Interminatamente - <a target="_blank" href="http://www.google.com/search?q=spartiti+Interminatamente+Raf" title="Spartiti di Interminatamente">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Interminatamente+Raf" title="Accordi di Interminatamente">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Interminatamente+Raf" title="Testi di Interminatamente">testi</a><br>
<b>8</b>. Siamo Soli Nell'immenso Vuoto Che C'è - <a target="_blank" href="http://www.google.com/search?q=spartiti+Siamo+Soli+Nell%27immenso+Vuoto+Che+C%27%E8+Raf" title="Spartiti di Siamo Soli Nell'immenso Vuoto Che C'è">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Siamo+Soli+Nell%27immenso+Vuoto+Che+C%27%E8+Raf" title="Accordi di Siamo Soli Nell'immenso Vuoto Che C'è">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Siamo+Soli+Nell%27immenso+Vuoto+Che+C%27%E8+Raf" title="Testi di Siamo Soli Nell'immenso Vuoto Che C'è">testi</a><br>
<b>9</b>. Oggi Un Dio Non Ho - <a target="_blank" href="http://www.google.com/search?q=spartiti+Oggi+Un+Dio+Non+Ho+Raf" title="Spartiti di Oggi Un Dio Non Ho">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Oggi+Un+Dio+Non+Ho+Raf" title="Accordi di Oggi Un Dio Non Ho">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Oggi+Un+Dio+Non+Ho+Raf" title="Testi di Oggi Un Dio Non Ho">testi</a><br>
<b>10</b>. Anche Tu - <a target="_blank" href="http://www.google.com/search?q=spartiti+Anche+Tu+Raf" title="Spartiti di Anche Tu">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Anche+Tu+Raf" title="Accordi di Anche Tu">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Anche+Tu+Raf" title="Testi di Anche Tu">testi</a><br>
<b>11</b>. Malinverno - <a target="_blank" href="http://www.google.com/search?q=spartiti+Malinverno+Raf" title="Spartiti di Malinverno">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Malinverno+Raf" title="Accordi di Malinverno">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Malinverno+Raf" title="Testi di Malinverno">testi</a><br>
<b>12</b>. Sogni - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sogni+Raf" title="Spartiti di Sogni">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sogni+Raf" title="Accordi di Sogni">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sogni+Raf" title="Testi di Sogni">testi</a><br>
<b>13</b>. Il Battito Animale - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Battito+Animale+Raf" title="Spartiti di Il Battito Animale">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Battito+Animale+Raf" title="Accordi di Il Battito Animale">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Battito+Animale+Raf" title="Testi di Il Battito Animale">testi</a><br>
<b>14</b>. Stai Con Me - <a target="_blank" href="http://www.google.com/search?q=spartiti+Stai+Con+Me+Raf" title="Spartiti di Stai Con Me">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Stai+Con+Me+Raf" title="Accordi di Stai Con Me">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Stai+Con+Me+Raf" title="Testi di Stai Con Me">testi</a><br>
<b>15</b>. Due (Due) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Due+%28Due%29+Raf" title="Spartiti di Due (Due)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Due+%28Due%29+Raf" title="Accordi di Due (Due)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Due+%28Due%29+Raf" title="Testi di Due (Due)">testi</a><br>
<b>16</b>. Dentro Ai Tuoi Occhi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dentro+Ai+Tuoi+Occhi+Raf" title="Spartiti di Dentro Ai Tuoi Occhi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dentro+Ai+Tuoi+Occhi+Raf" title="Accordi di Dentro Ai Tuoi Occhi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dentro+Ai+Tuoi+Occhi+Raf" title="Testi di Dentro Ai Tuoi Occhi">testi</a><br>
<b>17</b>. Sei La Più Bella Del Mondo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sei+La+Pi%F9+Bella+Del+Mondo+Raf" title="Spartiti di Sei La Più Bella Del Mondo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sei+La+Pi%F9+Bella+Del+Mondo+Raf" title="Accordi di Sei La Più Bella Del Mondo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sei+La+Pi%F9+Bella+Del+Mondo+Raf" title="Testi di Sei La Più Bella Del Mondo">testi</a><br>
<b>18</b>. E' Quasi L'alba - <a target="_blank" href="http://www.google.com/search?q=spartiti+E%27+Quasi+L%27alba+Raf" title="Spartiti di E' Quasi L'alba">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+E%27+Quasi+L%27alba+Raf" title="Accordi di E' Quasi L'alba">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+E%27+Quasi+L%27alba+Raf" title="Testi di E' Quasi L'alba">testi</a><br>
<b>19</b>. Il Suono C'è - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Suono+C%27%E8+Raf" title="Spartiti di Il Suono C'è">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Suono+C%27%E8+Raf" title="Accordi di Il Suono C'è">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Suono+C%27%E8+Raf" title="Testi di Il Suono C'è">testi</a><br>
<b>20</b>. Un Grande Salto - <a target="_blank" href="http://www.google.com/search?q=spartiti+Un+Grande+Salto+Raf" title="Spartiti di Un Grande Salto">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Un+Grande+Salto+Raf" title="Accordi di Un Grande Salto">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Un+Grande+Salto+Raf" title="Testi di Un Grande Salto">testi</a><br>
<b>21</b>. Svegliarsi Un Anno Fa - <a target="_blank" href="http://www.google.com/search?q=spartiti+Svegliarsi+Un+Anno+Fa+Raf" title="Spartiti di Svegliarsi Un Anno Fa">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Svegliarsi+Un+Anno+Fa+Raf" title="Accordi di Svegliarsi Un Anno Fa">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Svegliarsi+Un+Anno+Fa+Raf" title="Testi di Svegliarsi Un Anno Fa">testi</a><br>
<b>22</b>. Vita, Storie E Pensieri Di Un Alieno - <a target="_blank" href="http://www.google.com/search?q=spartiti+Vita%2C+Storie+E+Pensieri+Di+Un+Alieno+Raf" title="Spartiti di Vita, Storie E Pensieri Di Un Alieno">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Vita%2C+Storie+E+Pensieri+Di+Un+Alieno+Raf" title="Accordi di Vita, Storie E Pensieri Di Un Alieno">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Vita%2C+Storie+E+Pensieri+Di+Un+Alieno+Raf" title="Testi di Vita, Storie E Pensieri Di Un Alieno">testi</a><br>
<b>23</b>. La Danza Della Pioggia - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Danza+Della+Pioggia+Raf" title="Spartiti di La Danza Della Pioggia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Danza+Della+Pioggia+Raf" title="Accordi di La Danza Della Pioggia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Danza+Della+Pioggia+Raf" title="Testi di La Danza Della Pioggia">testi</a><br>
<b>24</b>. Infinito - <a target="_blank" href="http://www.google.com/search?q=spartiti+Infinito+Raf" title="Spartiti di Infinito">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Infinito+Raf" title="Accordi di Infinito">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Infinito+Raf" title="Testi di Infinito">testi</a><br>
<b>25</b>. Via - <a target="_blank" href="http://www.google.com/search?q=spartiti+Via+Raf" title="Spartiti di Via">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Via+Raf" title="Accordi di Via">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Via+Raf" title="Testi di Via">testi</a><br>
<b>26</b>. Nei Silenzi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Nei+Silenzi+Raf" title="Spartiti di Nei Silenzi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Nei+Silenzi+Raf" title="Accordi di Nei Silenzi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Nei+Silenzi+Raf" title="Testi di Nei Silenzi">testi</a><br>
<b>27</b>. Oasi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Oasi+Raf" title="Spartiti di Oasi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Oasi+Raf" title="Accordi di Oasi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Oasi+Raf" title="Testi di Oasi">testi</a><br>
<b>28</b>. In Tutti I Miei Giorni - <a target="_blank" href="http://www.google.com/search?q=spartiti+In+Tutti+I+Miei+Giorni+Raf" title="Spartiti di In Tutti I Miei Giorni">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+In+Tutti+I+Miei+Giorni+Raf" title="Accordi di In Tutti I Miei Giorni">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+In+Tutti+I+Miei+Giorni+Raf" title="Testi di In Tutti I Miei Giorni">testi</a><br>
<b>29</b>. Superstiti - <a target="_blank" href="http://www.google.com/search?q=spartiti+Superstiti+Raf" title="Spartiti di Superstiti">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Superstiti+Raf" title="Accordi di Superstiti">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Superstiti+Raf" title="Testi di Superstiti">testi</a><br>
<b>30</b>. Aria Da Niente - <a target="_blank" href="http://www.google.com/search?q=spartiti+Aria+Da+Niente+Raf" title="Spartiti di Aria Da Niente">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Aria+Da+Niente+Raf" title="Accordi di Aria Da Niente">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Aria+Da+Niente+Raf" title="Testi di Aria Da Niente">testi</a><br>
<b>31</b>. E Penso A Te (Bonus Track) - <a target="_blank" href="http://www.google.com/search?q=spartiti+E+Penso+A+Te+%28Bonus+Track%29+Raf" title="Spartiti di E Penso A Te (Bonus Track)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+E+Penso+A+Te+%28Bonus+Track%29+Raf" title="Accordi di E Penso A Te (Bonus Track)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+E+Penso+A+Te+%28Bonus+Track%29+Raf" title="Testi di E Penso A Te (Bonus Track)">testi</a><br>
<b>32</b>. Amarse O No Amarse (Bonus Track) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Amarse+O+No+Amarse+%28Bonus+Track%29+Raf" title="Spartiti di Amarse O No Amarse (Bonus Track)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Amarse+O+No+Amarse+%28Bonus+Track%29+Raf" title="Accordi di Amarse O No Amarse (Bonus Track)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Amarse+O+No+Amarse+%28Bonus+Track%29+Raf" title="Testi di Amarse O No Amarse (Bonus Track)">testi</a><br>
<h2>Ouch (2004) </h2>
<b>1</b>. In Tutti I Miei Giorni - <a target="_blank" href="http://www.google.com/search?q=spartiti+In+Tutti+I+Miei+Giorni+Raf" title="Spartiti di In Tutti I Miei Giorni">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+In+Tutti+I+Miei+Giorni+Raf" title="Accordi di In Tutti I Miei Giorni">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+In+Tutti+I+Miei+Giorni+Raf" title="Testi di In Tutti I Miei Giorni">testi</a><br>
<b>2</b>. Superstiti - <a target="_blank" href="http://www.google.com/search?q=spartiti+Superstiti+Raf" title="Spartiti di Superstiti">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Superstiti+Raf" title="Accordi di Superstiti">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Superstiti+Raf" title="Testi di Superstiti">testi</a><br>
<b>3</b>. Milioni Di Cose Che Non Ti Ho Detto - <a target="_blank" href="http://www.google.com/search?q=spartiti+Milioni+Di+Cose+Che+Non+Ti+Ho+Detto+Raf" title="Spartiti di Milioni Di Cose Che Non Ti Ho Detto">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Milioni+Di+Cose+Che+Non+Ti+Ho+Detto+Raf" title="Accordi di Milioni Di Cose Che Non Ti Ho Detto">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Milioni+Di+Cose+Che+Non+Ti+Ho+Detto+Raf" title="Testi di Milioni Di Cose Che Non Ti Ho Detto">testi</a><br>
<b>4</b>. Il Senso Delle Cose - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Senso+Delle+Cose+Raf" title="Spartiti di Il Senso Delle Cose">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Senso+Delle+Cose+Raf" title="Accordi di Il Senso Delle Cose">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Senso+Delle+Cose+Raf" title="Testi di Il Senso Delle Cose">testi</a><br>
<b>5</b>. Estate In Città - <a target="_blank" href="http://www.google.com/search?q=spartiti+Estate+In+Citt%E0+Raf" title="Spartiti di Estate In Città">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Estate+In+Citt%E0+Raf" title="Accordi di Estate In Città">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Estate+In+Citt%E0+Raf" title="Testi di Estate In Città">testi</a><br>
<b>6</b>. Il Prestigiatore - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Prestigiatore+Raf" title="Spartiti di Il Prestigiatore">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Prestigiatore+Raf" title="Accordi di Il Prestigiatore">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Prestigiatore+Raf" title="Testi di Il Prestigiatore">testi</a><br>
<b>7</b>. Aria Di Niente - <a target="_blank" href="http://www.google.com/search?q=spartiti+Aria+Di+Niente+Raf" title="Spartiti di Aria Di Niente">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Aria+Di+Niente+Raf" title="Accordi di Aria Di Niente">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Aria+Di+Niente+Raf" title="Testi di Aria Di Niente">testi</a><br>
<b>8</b>. Nessuno - <a target="_blank" href="http://www.google.com/search?q=spartiti+Nessuno+Raf" title="Spartiti di Nessuno">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Nessuno+Raf" title="Accordi di Nessuno">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Nessuno+Raf" title="Testi di Nessuno">testi</a><br>
<b>9</b>. Ouch! - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ouch%21+Raf" title="Spartiti di Ouch!">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ouch%21+Raf" title="Accordi di Ouch!">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ouch%21+Raf" title="Testi di Ouch!">testi</a><br>
<b>10</b>. Mi Fermo Qui - <a target="_blank" href="http://www.google.com/search?q=spartiti+Mi+Fermo+Qui+Raf" title="Spartiti di Mi Fermo Qui">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Mi+Fermo+Qui+Raf" title="Accordi di Mi Fermo Qui">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Mi+Fermo+Qui+Raf" title="Testi di Mi Fermo Qui">testi</a><br>
<h2>Iperbole (2001) </h2>
<b>1</b>. Infinito - <a target="_blank" href="http://www.google.com/search?q=spartiti+Infinito+Raf" title="Spartiti di Infinito">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Infinito+Raf" title="Accordi di Infinito">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Infinito+Raf" title="Testi di Infinito">testi</a><br>
<b>2</b>. R4 - <a target="_blank" href="http://www.google.com/search?q=spartiti+R4+Raf" title="Spartiti di R4">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+R4+Raf" title="Accordi di R4">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+R4+Raf" title="Testi di R4">testi</a><br>
<b>3</b>. Via - <a target="_blank" href="http://www.google.com/search?q=spartiti+Via+Raf" title="Spartiti di Via">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Via+Raf" title="Accordi di Via">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Via+Raf" title="Testi di Via">testi</a><br>
<b>4</b>. Nei Silenzi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Nei+Silenzi+Raf" title="Spartiti di Nei Silenzi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Nei+Silenzi+Raf" title="Accordi di Nei Silenzi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Nei+Silenzi+Raf" title="Testi di Nei Silenzi">testi</a><br>
<b>5</b>. Oasi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Oasi+Raf" title="Spartiti di Oasi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Oasi+Raf" title="Accordi di Oasi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Oasi+Raf" title="Testi di Oasi">testi</a><br>
<b>6</b>. Assolti - <a target="_blank" href="http://www.google.com/search?q=spartiti+Assolti+Raf" title="Spartiti di Assolti">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Assolti+Raf" title="Accordi di Assolti">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Assolti+Raf" title="Testi di Assolti">testi</a><br>
<b>7</b>. Troppo Sensibile - <a target="_blank" href="http://www.google.com/search?q=spartiti+Troppo+Sensibile+Raf" title="Spartiti di Troppo Sensibile">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Troppo+Sensibile+Raf" title="Accordi di Troppo Sensibile">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Troppo+Sensibile+Raf" title="Testi di Troppo Sensibile">testi</a><br>
<b>8</b>. Allegro Tormentone - <a target="_blank" href="http://www.google.com/search?q=spartiti+Allegro+Tormentone+Raf" title="Spartiti di Allegro Tormentone">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Allegro+Tormentone+Raf" title="Accordi di Allegro Tormentone">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Allegro+Tormentone+Raf" title="Testi di Allegro Tormentone">testi</a><br>
<b>9</b>. Iperbole - <a target="_blank" href="http://www.google.com/search?q=spartiti+Iperbole+Raf" title="Spartiti di Iperbole">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Iperbole+Raf" title="Accordi di Iperbole">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Iperbole+Raf" title="Testi di Iperbole">testi</a><br>
<b>10</b>. Infinito RMX - <a target="_blank" href="http://www.google.com/search?q=spartiti+Infinito+RMX+Raf" title="Spartiti di Infinito RMX">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Infinito+RMX+Raf" title="Accordi di Infinito RMX">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Infinito+RMX+Raf" title="Testi di Infinito RMX">testi</a><br>
<h2>La Prova (1998) </h2>
<b>1</b>. Vita, Storie E Pensieri Di Un Alieno - <a target="_blank" href="http://www.google.com/search?q=spartiti+Vita%2C+Storie+E+Pensieri+Di+Un+Alieno+Raf" title="Spartiti di Vita, Storie E Pensieri Di Un Alieno">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Vita%2C+Storie+E+Pensieri+Di+Un+Alieno+Raf" title="Accordi di Vita, Storie E Pensieri Di Un Alieno">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Vita%2C+Storie+E+Pensieri+Di+Un+Alieno+Raf" title="Testi di Vita, Storie E Pensieri Di Un Alieno">testi</a><br>
<b>2</b>. Lava - <a target="_blank" href="http://www.google.com/search?q=spartiti+Lava+Raf" title="Spartiti di Lava">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Lava+Raf" title="Accordi di Lava">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Lava+Raf" title="Testi di Lava">testi</a><br>
<b>3</b>. Little Girl - <a target="_blank" href="http://www.google.com/search?q=spartiti+Little+Girl+Raf" title="Spartiti di Little Girl">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Little+Girl+Raf" title="Accordi di Little Girl">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Little+Girl+Raf" title="Testi di Little Girl">testi</a><br>
<b>4</b>. Che Giorno E' - <a target="_blank" href="http://www.google.com/search?q=spartiti+Che+Giorno+E%27+Raf" title="Spartiti di Che Giorno E'">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Che+Giorno+E%27+Raf" title="Accordi di Che Giorno E'">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Che+Giorno+E%27+Raf" title="Testi di Che Giorno E'">testi</a><br>
<b>5</b>. Jamas - <a target="_blank" href="http://www.google.com/search?q=spartiti+Jamas+Raf" title="Spartiti di Jamas">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Jamas+Raf" title="Accordi di Jamas">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Jamas+Raf" title="Testi di Jamas">testi</a><br>
<b>6</b>. La Danza Della Pioggia - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Danza+Della+Pioggia+Raf" title="Spartiti di La Danza Della Pioggia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Danza+Della+Pioggia+Raf" title="Accordi di La Danza Della Pioggia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Danza+Della+Pioggia+Raf" title="Testi di La Danza Della Pioggia">testi</a><br>
<b>7</b>. Il Primo Uomo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Primo+Uomo+Raf" title="Spartiti di Il Primo Uomo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Primo+Uomo+Raf" title="Accordi di Il Primo Uomo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Primo+Uomo+Raf" title="Testi di Il Primo Uomo">testi</a><br>
<b>8</b>. Tra Le Mie Domande E Il Mare - <a target="_blank" href="http://www.google.com/search?q=spartiti+Tra+Le+Mie+Domande+E+Il+Mare+Raf" title="Spartiti di Tra Le Mie Domande E Il Mare">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Tra+Le+Mie+Domande+E+Il+Mare+Raf" title="Accordi di Tra Le Mie Domande E Il Mare">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Tra+Le+Mie+Domande+E+Il+Mare+Raf" title="Testi di Tra Le Mie Domande E Il Mare">testi</a><br>
<b>9</b>. La Prova - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Prova+Raf" title="Spartiti di La Prova">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Prova+Raf" title="Accordi di La Prova">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Prova+Raf" title="Testi di La Prova">testi</a><br>
<h2>Collezione Temporanea (1996) </h2>
<b>1</b>. Un Grande Salto - <a target="_blank" href="http://www.google.com/search?q=spartiti+Un+Grande+Salto+Raf" title="Spartiti di Un Grande Salto">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Un+Grande+Salto+Raf" title="Accordi di Un Grande Salto">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Un+Grande+Salto+Raf" title="Testi di Un Grande Salto">testi</a><br>
<b>2</b>. Il Battito Animale - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Battito+Animale+Raf" title="Spartiti di Il Battito Animale">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Battito+Animale+Raf" title="Accordi di Il Battito Animale">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Battito+Animale+Raf" title="Testi di Il Battito Animale">testi</a><br>
<b>3</b>. Interminatamente - <a target="_blank" href="http://www.google.com/search?q=spartiti+Interminatamente+Raf" title="Spartiti di Interminatamente">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Interminatamente+Raf" title="Accordi di Interminatamente">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Interminatamente+Raf" title="Testi di Interminatamente">testi</a><br>
<b>4</b>. Cosa Resterà Degli Anni '80 - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cosa+Rester%E0+Degli+Anni+%2780+Raf" title="Spartiti di Cosa Resterà Degli Anni '80">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cosa+Rester%E0+Degli+Anni+%2780+Raf" title="Accordi di Cosa Resterà Degli Anni '80">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cosa+Rester%E0+Degli+Anni+%2780+Raf" title="Testi di Cosa Resterà Degli Anni '80">testi</a><br>
<b>5</b>. Sei La Più Bella Del Mondo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sei+La+Pi%F9+Bella+Del+Mondo+Raf" title="Spartiti di Sei La Più Bella Del Mondo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sei+La+Pi%F9+Bella+Del+Mondo+Raf" title="Accordi di Sei La Più Bella Del Mondo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sei+La+Pi%F9+Bella+Del+Mondo+Raf" title="Testi di Sei La Più Bella Del Mondo">testi</a><br>
<b>6</b>. Ti Pretendo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ti+Pretendo+Raf" title="Spartiti di Ti Pretendo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ti+Pretendo+Raf" title="Accordi di Ti Pretendo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ti+Pretendo+Raf" title="Testi di Ti Pretendo">testi</a><br>
<b>7</b>. Gente Di Mare - <a target="_blank" href="http://www.google.com/search?q=spartiti+Gente+Di+Mare+Raf" title="Spartiti di Gente Di Mare">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Gente+Di+Mare+Raf" title="Accordi di Gente Di Mare">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Gente+Di+Mare+Raf" title="Testi di Gente Di Mare">testi</a><br>
<b>8</b>. Svegliarsi Un Anno Fa - <a target="_blank" href="http://www.google.com/search?q=spartiti+Svegliarsi+Un+Anno+Fa+Raf" title="Spartiti di Svegliarsi Un Anno Fa">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Svegliarsi+Un+Anno+Fa+Raf" title="Accordi di Svegliarsi Un Anno Fa">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Svegliarsi+Un+Anno+Fa+Raf" title="Testi di Svegliarsi Un Anno Fa">testi</a><br>
<b>9</b>. Inevitabile Follia - <a target="_blank" href="http://www.google.com/search?q=spartiti+Inevitabile+Follia+Raf" title="Spartiti di Inevitabile Follia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Inevitabile+Follia+Raf" title="Accordi di Inevitabile Follia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Inevitabile+Follia+Raf" title="Testi di Inevitabile Follia">testi</a><br>
<b>10</b>. Malinverno - <a target="_blank" href="http://www.google.com/search?q=spartiti+Malinverno+Raf" title="Spartiti di Malinverno">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Malinverno+Raf" title="Accordi di Malinverno">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Malinverno+Raf" title="Testi di Malinverno">testi</a><br>
<b>11</b>. Due - <a target="_blank" href="http://www.google.com/search?q=spartiti+Due+Raf" title="Spartiti di Due">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Due+Raf" title="Accordi di Due">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Due+Raf" title="Testi di Due">testi</a><br>
<b>12</b>. E' Quasi L'Alba - <a target="_blank" href="http://www.google.com/search?q=spartiti+E%27+Quasi+L%27Alba+Raf" title="Spartiti di E' Quasi L'Alba">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+E%27+Quasi+L%27Alba+Raf" title="Accordi di E' Quasi L'Alba">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+E%27+Quasi+L%27Alba+Raf" title="Testi di E' Quasi L'Alba">testi</a><br>
<b>13</b>. Oggi Un Dio Non Ho - <a target="_blank" href="http://www.google.com/search?q=spartiti+Oggi+Un+Dio+Non+Ho+Raf" title="Spartiti di Oggi Un Dio Non Ho">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Oggi+Un+Dio+Non+Ho+Raf" title="Accordi di Oggi Un Dio Non Ho">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Oggi+Un+Dio+Non+Ho+Raf" title="Testi di Oggi Un Dio Non Ho">testi</a><br>
<b>14</b>. Il Suono C'è - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Suono+C%27%E8+Raf" title="Spartiti di Il Suono C'è">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Suono+C%27%E8+Raf" title="Accordi di Il Suono C'è">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Suono+C%27%E8+Raf" title="Testi di Il Suono C'è">testi</a><br>
<b>15</b>. Stai Con Me - <a target="_blank" href="http://www.google.com/search?q=spartiti+Stai+Con+Me+Raf" title="Spartiti di Stai Con Me">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Stai+Con+Me+Raf" title="Accordi di Stai Con Me">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Stai+Con+Me+Raf" title="Testi di Stai Con Me">testi</a><br>
<b>16</b>. Dentro Ai Tuoi Occhi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dentro+Ai+Tuoi+Occhi+Raf" title="Spartiti di Dentro Ai Tuoi Occhi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dentro+Ai+Tuoi+Occhi+Raf" title="Accordi di Dentro Ai Tuoi Occhi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dentro+Ai+Tuoi+Occhi+Raf" title="Testi di Dentro Ai Tuoi Occhi">testi</a><br>
<b>17</b>. Siamo Soli Nell'Immenso Vuoto Che C'è - <a target="_blank" href="http://www.google.com/search?q=spartiti+Siamo+Soli+Nell%27Immenso+Vuoto+Che+C%27%E8+Raf" title="Spartiti di Siamo Soli Nell'Immenso Vuoto Che C'è">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Siamo+Soli+Nell%27Immenso+Vuoto+Che+C%27%E8+Raf" title="Accordi di Siamo Soli Nell'Immenso Vuoto Che C'è">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Siamo+Soli+Nell%27Immenso+Vuoto+Che+C%27%E8+Raf" title="Testi di Siamo Soli Nell'Immenso Vuoto Che C'è">testi</a><br>
<h2>Manifesto (1995) </h2>
<b>1</b>. Sei La Più Bella Del Mondo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sei+La+Pi%F9+Bella+Del+Mondo+Raf" title="Spartiti di Sei La Più Bella Del Mondo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sei+La+Pi%F9+Bella+Del+Mondo+Raf" title="Accordi di Sei La Più Bella Del Mondo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sei+La+Pi%F9+Bella+Del+Mondo+Raf" title="Testi di Sei La Più Bella Del Mondo">testi</a><br>
<b>2</b>. Dentro Ai Tuoi Occhi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dentro+Ai+Tuoi+Occhi+Raf" title="Spartiti di Dentro Ai Tuoi Occhi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dentro+Ai+Tuoi+Occhi+Raf" title="Accordi di Dentro Ai Tuoi Occhi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dentro+Ai+Tuoi+Occhi+Raf" title="Testi di Dentro Ai Tuoi Occhi">testi</a><br>
<b>3</b>. Io E Te - <a target="_blank" href="http://www.google.com/search?q=spartiti+Io+E+Te+Raf" title="Spartiti di Io E Te">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Io+E+Te+Raf" title="Accordi di Io E Te">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Io+E+Te+Raf" title="Testi di Io E Te">testi</a><br>
<b>4</b>. Manifesto - <a target="_blank" href="http://www.google.com/search?q=spartiti+Manifesto+Raf" title="Spartiti di Manifesto">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Manifesto+Raf" title="Accordi di Manifesto">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Manifesto+Raf" title="Testi di Manifesto">testi</a><br>
<b>5</b>. E' Quasi L'Alba - <a target="_blank" href="http://www.google.com/search?q=spartiti+E%27+Quasi+L%27Alba+Raf" title="Spartiti di E' Quasi L'Alba">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+E%27+Quasi+L%27Alba+Raf" title="Accordi di E' Quasi L'Alba">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+E%27+Quasi+L%27Alba+Raf" title="Testi di E' Quasi L'Alba">testi</a><br>
<b>6</b>. Il Suono C'è - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Suono+C%27%E8+Raf" title="Spartiti di Il Suono C'è">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Suono+C%27%E8+Raf" title="Accordi di Il Suono C'è">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Suono+C%27%E8+Raf" title="Testi di Il Suono C'è">testi</a><br>
<b>7</b>. Meteo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Meteo+Raf" title="Spartiti di Meteo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Meteo+Raf" title="Accordi di Meteo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Meteo+Raf" title="Testi di Meteo">testi</a><br>
<b>8</b>. Prima Che Sia Giorno - <a target="_blank" href="http://www.google.com/search?q=spartiti+Prima+Che+Sia+Giorno+Raf" title="Spartiti di Prima Che Sia Giorno">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Prima+Che+Sia+Giorno+Raf" title="Accordi di Prima Che Sia Giorno">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Prima+Che+Sia+Giorno+Raf" title="Testi di Prima Che Sia Giorno">testi</a><br>
<b>9</b>. Interagendo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Interagendo+Raf" title="Spartiti di Interagendo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Interagendo+Raf" title="Accordi di Interagendo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Interagendo+Raf" title="Testi di Interagendo">testi</a><br>
<h2>Cannibali (1993) </h2>
<b>1</b>. Il Battito Animale - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Battito+Animale+Raf" title="Spartiti di Il Battito Animale">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Battito+Animale+Raf" title="Accordi di Il Battito Animale">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Battito+Animale+Raf" title="Testi di Il Battito Animale">testi</a><br>
<b>2</b>. Stai Con Me - <a target="_blank" href="http://www.google.com/search?q=spartiti+Stai+Con+Me+Raf" title="Spartiti di Stai Con Me">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Stai+Con+Me+Raf" title="Accordi di Stai Con Me">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Stai+Con+Me+Raf" title="Testi di Stai Con Me">testi</a><br>
<b>3</b>. Il Re - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Re+Raf" title="Spartiti di Il Re">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Re+Raf" title="Accordi di Il Re">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Re+Raf" title="Testi di Il Re">testi</a><br>
<b>4</b>. Cannibali - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cannibali+Raf" title="Spartiti di Cannibali">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cannibali+Raf" title="Accordi di Cannibali">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cannibali+Raf" title="Testi di Cannibali">testi</a><br>
<b>5</b>. La Folle Corsa - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Folle+Corsa+Raf" title="Spartiti di La Folle Corsa">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Folle+Corsa+Raf" title="Accordi di La Folle Corsa">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Folle+Corsa+Raf" title="Testi di La Folle Corsa">testi</a><br>
<b>6</b>. Due - <a target="_blank" href="http://www.google.com/search?q=spartiti+Due+Raf" title="Spartiti di Due">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Due+Raf" title="Accordi di Due">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Due+Raf" title="Testi di Due">testi</a><br>
<b>7</b>. Il Canto - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Canto+Raf" title="Spartiti di Il Canto">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Canto+Raf" title="Accordi di Il Canto">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Canto+Raf" title="Testi di Il Canto">testi</a><br>
<b>8</b>. Blu - <a target="_blank" href="http://www.google.com/search?q=spartiti+Blu+Raf" title="Spartiti di Blu">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Blu+Raf" title="Accordi di Blu">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Blu+Raf" title="Testi di Blu">testi</a><br>
<b>9</b>. Mai - <a target="_blank" href="http://www.google.com/search?q=spartiti+Mai+Raf" title="Spartiti di Mai">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Mai+Raf" title="Accordi di Mai">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Mai+Raf" title="Testi di Mai">testi</a><br>
<b>10</b>. Due (Due) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Due+%28Due%29+Raf" title="Spartiti di Due (Due)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Due+%28Due%29+Raf" title="Accordi di Due (Due)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Due+%28Due%29+Raf" title="Testi di Due (Due)">testi</a><br>
<h2>RAF (Spanish Edition) (1992) </h2>
<b>1</b>. Interminablemente - <a target="_blank" href="http://www.google.com/search?q=spartiti+Interminablemente+Raf" title="Spartiti di Interminablemente">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Interminablemente+Raf" title="Accordi di Interminablemente">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Interminablemente+Raf" title="Testi di Interminablemente">testi</a><br>
<b>2</b>. Solos En El Universo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Solos+En+El+Universo+Raf" title="Spartiti di Solos En El Universo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Solos+En+El+Universo+Raf" title="Accordi di Solos En El Universo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Solos+En+El+Universo+Raf" title="Testi di Solos En El Universo">testi</a><br>
<b>3</b>. Dormirse Y Despertar - <a target="_blank" href="http://www.google.com/search?q=spartiti+Dormirse+Y+Despertar+Raf" title="Spartiti di Dormirse Y Despertar">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Dormirse+Y+Despertar+Raf" title="Accordi di Dormirse Y Despertar">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Dormirse+Y+Despertar+Raf" title="Testi di Dormirse Y Despertar">testi</a><br>
<b>4</b>. Que Quedara De Los '80 - <a target="_blank" href="http://www.google.com/search?q=spartiti+Que+Quedara+De+Los+%2780+Raf" title="Spartiti di Que Quedara De Los '80">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Que+Quedara+De+Los+%2780+Raf" title="Accordi di Que Quedara De Los '80">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Que+Quedara+De+Los+%2780+Raf" title="Testi di Que Quedara De Los '80">testi</a><br>
<b>5</b>. Te Pretendo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Te+Pretendo+Raf" title="Spartiti di Te Pretendo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Te+Pretendo+Raf" title="Accordi di Te Pretendo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Te+Pretendo+Raf" title="Testi di Te Pretendo">testi</a><br>
<b>6</b>. Hoy No Tengo Un Dios - <a target="_blank" href="http://www.google.com/search?q=spartiti+Hoy+No+Tengo+Un+Dios+Raf" title="Spartiti di Hoy No Tengo Un Dios">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Hoy+No+Tengo+Un+Dios+Raf" title="Accordi di Hoy No Tengo Un Dios">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Hoy+No+Tengo+Un+Dios+Raf" title="Testi di Hoy No Tengo Un Dios">testi</a><br>
<b>7</b>. Amarse O No Amarse - <a target="_blank" href="http://www.google.com/search?q=spartiti+Amarse+O+No+Amarse+Raf" title="Spartiti di Amarse O No Amarse">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Amarse+O+No+Amarse+Raf" title="Accordi di Amarse O No Amarse">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Amarse+O+No+Amarse+Raf" title="Testi di Amarse O No Amarse">testi</a><br>
<b>8</b>. Inevitable Tonteria - <a target="_blank" href="http://www.google.com/search?q=spartiti+Inevitable+Tonteria+Raf" title="Spartiti di Inevitable Tonteria">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Inevitable+Tonteria+Raf" title="Accordi di Inevitable Tonteria">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Inevitable+Tonteria+Raf" title="Testi di Inevitable Tonteria">testi</a><br>
<b>9</b>. Santos De Ciudad - <a target="_blank" href="http://www.google.com/search?q=spartiti+Santos+De+Ciudad+Raf" title="Spartiti di Santos De Ciudad">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Santos+De+Ciudad+Raf" title="Accordi di Santos De Ciudad">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Santos+De+Ciudad+Raf" title="Testi di Santos De Ciudad">testi</a><br>
<h2>Sogni... E' Tutto Quello Che C'è (1991) </h2>
<b>1</b>. Sogni (Prelude) - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sogni+%28Prelude%29+Raf" title="Spartiti di Sogni (Prelude)">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sogni+%28Prelude%29+Raf" title="Accordi di Sogni (Prelude)">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sogni+%28Prelude%29+Raf" title="Testi di Sogni (Prelude)">testi</a><br>
<b>2</b>. Interminatamente - <a target="_blank" href="http://www.google.com/search?q=spartiti+Interminatamente+Raf" title="Spartiti di Interminatamente">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Interminatamente+Raf" title="Accordi di Interminatamente">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Interminatamente+Raf" title="Testi di Interminatamente">testi</a><br>
<b>3</b>. Siamo Soli Nell'Immenso Vuoto Che C'è - <a target="_blank" href="http://www.google.com/search?q=spartiti+Siamo+Soli+Nell%27Immenso+Vuoto+Che+C%27%E8+Raf" title="Spartiti di Siamo Soli Nell'Immenso Vuoto Che C'è">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Siamo+Soli+Nell%27Immenso+Vuoto+Che+C%27%E8+Raf" title="Accordi di Siamo Soli Nell'Immenso Vuoto Che C'è">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Siamo+Soli+Nell%27Immenso+Vuoto+Che+C%27%E8+Raf" title="Testi di Siamo Soli Nell'Immenso Vuoto Che C'è">testi</a><br>
<b>4</b>. Oggi Un Dio Non Ho - <a target="_blank" href="http://www.google.com/search?q=spartiti+Oggi+Un+Dio+Non+Ho+Raf" title="Spartiti di Oggi Un Dio Non Ho">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Oggi+Un+Dio+Non+Ho+Raf" title="Accordi di Oggi Un Dio Non Ho">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Oggi+Un+Dio+Non+Ho+Raf" title="Testi di Oggi Un Dio Non Ho">testi</a><br>
<b>5</b>. Se Ti Senti Sola - <a target="_blank" href="http://www.google.com/search?q=spartiti+Se+Ti+Senti+Sola+Raf" title="Spartiti di Se Ti Senti Sola">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Se+Ti+Senti+Sola+Raf" title="Accordi di Se Ti Senti Sola">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Se+Ti+Senti+Sola+Raf" title="Testi di Se Ti Senti Sola">testi</a><br>
<b>6</b>. Anche Tu - <a target="_blank" href="http://www.google.com/search?q=spartiti+Anche+Tu+Raf" title="Spartiti di Anche Tu">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Anche+Tu+Raf" title="Accordi di Anche Tu">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Anche+Tu+Raf" title="Testi di Anche Tu">testi</a><br>
<b>7</b>. Amarsi O Non Amarsi - <a target="_blank" href="http://www.google.com/search?q=spartiti+Amarsi+O+Non+Amarsi+Raf" title="Spartiti di Amarsi O Non Amarsi">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Amarsi+O+Non+Amarsi+Raf" title="Accordi di Amarsi O Non Amarsi">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Amarsi+O+Non+Amarsi+Raf" title="Testi di Amarsi O Non Amarsi">testi</a><br>
<b>8</b>. Senza Respiro - <a target="_blank" href="http://www.google.com/search?q=spartiti+Senza+Respiro+Raf" title="Spartiti di Senza Respiro">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Senza+Respiro+Raf" title="Accordi di Senza Respiro">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Senza+Respiro+Raf" title="Testi di Senza Respiro">testi</a><br>
<b>9</b>. E' Meglio Così - <a target="_blank" href="http://www.google.com/search?q=spartiti+E%27+Meglio+Cos%EC+Raf" title="Spartiti di E' Meglio Così">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+E%27+Meglio+Cos%EC+Raf" title="Accordi di E' Meglio Così">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+E%27+Meglio+Cos%EC+Raf" title="Testi di E' Meglio Così">testi</a><br>
<b>10</b>. Malinverno - <a target="_blank" href="http://www.google.com/search?q=spartiti+Malinverno+Raf" title="Spartiti di Malinverno">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Malinverno+Raf" title="Accordi di Malinverno">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Malinverno+Raf" title="Testi di Malinverno">testi</a><br>
<b>11</b>. Sogni - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sogni+Raf" title="Spartiti di Sogni">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sogni+Raf" title="Accordi di Sogni">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sogni+Raf" title="Testi di Sogni">testi</a><br>
<h2>Cosa Resterà (1989) </h2>
<b>1</b>. Ti Pretendo - <a target="_blank" href="http://www.google.com/search?q=spartiti+Ti+Pretendo+Raf" title="Spartiti di Ti Pretendo">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Ti+Pretendo+Raf" title="Accordi di Ti Pretendo">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Ti+Pretendo+Raf" title="Testi di Ti Pretendo">testi</a><br>
<b>2</b>. Santi Nel Viavai - <a target="_blank" href="http://www.google.com/search?q=spartiti+Santi+Nel+Viavai+Raf" title="Spartiti di Santi Nel Viavai">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Santi+Nel+Viavai+Raf" title="Accordi di Santi Nel Viavai">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Santi+Nel+Viavai+Raf" title="Testi di Santi Nel Viavai">testi</a><br>
<b>3</b>. La Battaglia Del Sesso - <a target="_blank" href="http://www.google.com/search?q=spartiti+La+Battaglia+Del+Sesso+Raf" title="Spartiti di La Battaglia Del Sesso">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+La+Battaglia+Del+Sesso+Raf" title="Accordi di La Battaglia Del Sesso">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+La+Battaglia+Del+Sesso+Raf" title="Testi di La Battaglia Del Sesso">testi</a><br>
<b>4</b>. E Gli Altri Dormono - <a target="_blank" href="http://www.google.com/search?q=spartiti+E+Gli+Altri+Dormono+Raf" title="Spartiti di E Gli Altri Dormono">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+E+Gli+Altri+Dormono+Raf" title="Accordi di E Gli Altri Dormono">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+E+Gli+Altri+Dormono+Raf" title="Testi di E Gli Altri Dormono">testi</a><br>
<b>5</b>. Cosa Resterà Degli Anni '80 - <a target="_blank" href="http://www.google.com/search?q=spartiti+Cosa+Rester%E0+Degli+Anni+%2780+Raf" title="Spartiti di Cosa Resterà Degli Anni '80">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Cosa+Rester%E0+Degli+Anni+%2780+Raf" title="Accordi di Cosa Resterà Degli Anni '80">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Cosa+Rester%E0+Degli+Anni+%2780+Raf" title="Testi di Cosa Resterà Degli Anni '80">testi</a><br>
<b>6</b>. Do I Need Your Love - <a target="_blank" href="http://www.google.com/search?q=spartiti+Do+I+Need+Your+Love+Raf" title="Spartiti di Do I Need Your Love">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Do+I+Need+Your+Love+Raf" title="Accordi di Do I Need Your Love">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Do+I+Need+Your+Love+Raf" title="Testi di Do I Need Your Love">testi</a><br>
<b>7</b>. Fai - <a target="_blank" href="http://www.google.com/search?q=spartiti+Fai+Raf" title="Spartiti di Fai">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Fai+Raf" title="Accordi di Fai">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Fai+Raf" title="Testi di Fai">testi</a><br>
<b>8</b>. E Sia Così - <a target="_blank" href="http://www.google.com/search?q=spartiti+E+Sia+Cos%EC+Raf" title="Spartiti di E Sia Così">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+E+Sia+Cos%EC+Raf" title="Accordi di E Sia Così">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+E+Sia+Cos%EC+Raf" title="Testi di E Sia Così">testi</a><br>
<h2>Svegliarsi Un Anno Fa (1988) </h2>
<b>1</b>. Svegliarsi Un Anno Fa - <a target="_blank" href="http://www.google.com/search?q=spartiti+Svegliarsi+Un+Anno+Fa+Raf" title="Spartiti di Svegliarsi Un Anno Fa">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Svegliarsi+Un+Anno+Fa+Raf" title="Accordi di Svegliarsi Un Anno Fa">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Svegliarsi+Un+Anno+Fa+Raf" title="Testi di Svegliarsi Un Anno Fa">testi</a><br>
<b>2</b>. Il Sapore Di Un Bacio - <a target="_blank" href="http://www.google.com/search?q=spartiti+Il+Sapore+Di+Un+Bacio+Raf" title="Spartiti di Il Sapore Di Un Bacio">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Il+Sapore+Di+Un+Bacio+Raf" title="Accordi di Il Sapore Di Un Bacio">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Il+Sapore+Di+Un+Bacio+Raf" title="Testi di Il Sapore Di Un Bacio">testi</a><br>
<b>3</b>. L'Aereoplano - <a target="_blank" href="http://www.google.com/search?q=spartiti+L%27Aereoplano+Raf" title="Spartiti di L'Aereoplano">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+L%27Aereoplano+Raf" title="Accordi di L'Aereoplano">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+L%27Aereoplano+Raf" title="Testi di L'Aereoplano">testi</a><br>
<b>4</b>. Inevitabile Follia - <a target="_blank" href="http://www.google.com/search?q=spartiti+Inevitabile+Follia+Raf" title="Spartiti di Inevitabile Follia">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Inevitabile+Follia+Raf" title="Accordi di Inevitabile Follia">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Inevitabile+Follia+Raf" title="Testi di Inevitabile Follia">testi</a><br>
<b>5</b>. Guai - <a target="_blank" href="http://www.google.com/search?q=spartiti+Guai+Raf" title="Spartiti di Guai">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Guai+Raf" title="Accordi di Guai">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Guai+Raf" title="Testi di Guai">testi</a><br>
<b>6</b>. Non Sei Tu - <a target="_blank" href="http://www.google.com/search?q=spartiti+Non+Sei+Tu+Raf" title="Spartiti di Non Sei Tu">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Non+Sei+Tu+Raf" title="Accordi di Non Sei Tu">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Non+Sei+Tu+Raf" title="Testi di Non Sei Tu">testi</a><br>
<b>7</b>. Sabbia Nei Bar - <a target="_blank" href="http://www.google.com/search?q=spartiti+Sabbia+Nei+Bar+Raf" title="Spartiti di Sabbia Nei Bar">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Sabbia+Nei+Bar+Raf" title="Accordi di Sabbia Nei Bar">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Sabbia+Nei+Bar+Raf" title="Testi di Sabbia Nei Bar">testi</a><br>
<b>8</b>. Due Occhi Deserti - <a target="_blank" href="http://www.google.com/search?q=spartiti+Due+Occhi+Deserti+Raf" title="Spartiti di Due Occhi Deserti">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Due+Occhi+Deserti+Raf" title="Accordi di Due Occhi Deserti">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Due+Occhi+Deserti+Raf" title="Testi di Due Occhi Deserti">testi</a><br>
<h2>Self Control (1983) </h2>
<b>1</b>. Self Control - <a target="_blank" href="http://www.google.com/search?q=spartiti+Self+Control+Raf" title="Spartiti di Self Control">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Self+Control+Raf" title="Accordi di Self Control">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Self+Control+Raf" title="Testi di Self Control">testi</a><br>
<b>2</b>. Black And Blue - <a target="_blank" href="http://www.google.com/search?q=spartiti+Black+And+Blue+Raf" title="Spartiti di Black And Blue">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Black+And+Blue+Raf" title="Accordi di Black And Blue">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Black+And+Blue+Raf" title="Testi di Black And Blue">testi</a><br>
<b>3</b>. I Don't Want To Lose You - <a target="_blank" href="http://www.google.com/search?q=spartiti+I+Don%27t+Want+To+Lose+You+Raf" title="Spartiti di I Don't Want To Lose You">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+I+Don%27t+Want+To+Lose+You+Raf" title="Accordi di I Don't Want To Lose You">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+I+Don%27t+Want+To+Lose+You+Raf" title="Testi di I Don't Want To Lose You">testi</a><br>
<b>4</b>. Madeleine - <a target="_blank" href="http://www.google.com/search?q=spartiti+Madeleine+Raf" title="Spartiti di Madeleine">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Madeleine+Raf" title="Accordi di Madeleine">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Madeleine+Raf" title="Testi di Madeleine">testi</a><br>
<b>5</b>. London Town - <a target="_blank" href="http://www.google.com/search?q=spartiti+London+Town+Raf" title="Spartiti di London Town">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+London+Town+Raf" title="Accordi di London Town">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+London+Town+Raf" title="Testi di London Town">testi</a><br>
<b>6</b>. Hard - <a target="_blank" href="http://www.google.com/search?q=spartiti+Hard+Raf" title="Spartiti di Hard">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Hard+Raf" title="Accordi di Hard">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Hard+Raf" title="Testi di Hard">testi</a><br>
<b>7</b>. Change Your Mind - <a target="_blank" href="http://www.google.com/search?q=spartiti+Change+Your+Mind+Raf" title="Spartiti di Change Your Mind">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Change+Your+Mind+Raf" title="Accordi di Change Your Mind">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Change+Your+Mind+Raf" title="Testi di Change Your Mind">testi</a><br>
<b>8</b>. Why In The World - <a target="_blank" href="http://www.google.com/search?q=spartiti+Why+In+The+World+Raf" title="Spartiti di Why In The World">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Why+In+The+World+Raf" title="Accordi di Why In The World">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Why+In+The+World+Raf" title="Testi di Why In The World">testi</a><br>
<b>9</b>. She's A Criminal - <a target="_blank" href="http://www.google.com/search?q=spartiti+She%27s+A+Criminal+Raf" title="Spartiti di She's A Criminal">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+She%27s+A+Criminal+Raf" title="Accordi di She's A Criminal">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+She%27s+A+Criminal+Raf" title="Testi di She's A Criminal">testi</a><br>
<b>10</b>. Imagination Lover - <a target="_blank" href="http://www.google.com/search?q=spartiti+Imagination+Lover+Raf" title="Spartiti di Imagination Lover">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Imagination+Lover+Raf" title="Accordi di Imagination Lover">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Imagination+Lover+Raf" title="Testi di Imagination Lover">testi</a><br>
<b>11</b>. Frontiers - <a target="_blank" href="http://www.google.com/search?q=spartiti+Frontiers+Raf" title="Spartiti di Frontiers">spartiti</a>, <a target="_blank" href="http://www.google.com/search?q=accordi+Frontiers+Raf" title="Accordi di Frontiers">accordi</a>, <a target="_blank" href="http://www.google.com/search?q=testi+Frontiers+Raf" title="Testi di Frontiers">testi</a><br>
<h2><a href="http://<?php echo "$base_website_address/$spartiti_dir" ?>/index.html" title="Trova accordi, spartiti, tablature e testi di tantissimi artisti">Torna all'indice degli artisti</a></h2>
